SilphCo_4F_Text_CantYouSeeImHiding::
	.string "Ssh!\n"
	.string "Non vedi che mi sto nascondendo?$"

SilphCo_4F_Text_TeamRocketIsGone::
	.string "Cosa?\n"
	.string "TEAM ROCKET se n'è andato?$"

SilphCo_4F_Text_Grunt1Intro::
	.string "TEAM ROCKET si è impadronito della\n"
	.string "SILPH SpA!!!$"

SilphCo_4F_Text_Grunt1Defeat::
	.string "Grrr!$"

SilphCo_4F_Text_Grunt1PostBattle::
	.string "Ihahah!!! Il mio CAPO aspettava\n"
	.string "questo momento!$"

SilphCo_4F_Text_RodneyIntro::
	.string "I miei POKéMON sono i miei fedeli\n"
	.string "guerrieri!$"

SilphCo_4F_Text_RodneyDefeat::
	.string "Accidenti!\n"
	.string "Metti i POKéMON KO!$"

SilphCo_4F_Text_RodneyPostBattle::
	.string "Le porte si chiudono\n"
	.string "elettronicamente!\p"
	.string "Si aprono solo con l'APRIPORTA!$"

SilphCo_4F_Text_Grunt2Intro::
	.string "Si segnala un'intrusione!$"

SilphCo_4F_Text_Grunt2Defeat::
	.string "Chi sei?$"

SilphCo_4F_Text_Grunt2PostBattle::
	.string "Lo dirò al CAPO al 10º piano!$"

SilphCo_4F_Text_FloorSign::
	.string "DIREZIONE della SILPH SpA\n"
	.string "3ºP$"

