PokemonMansion_1F_Text_TedIntro::
	.string "Chi sei?\n"
	.string "Nessuno può stare qui!$"

PokemonMansion_1F_Text_TedDefeat::
	.string "Ahi!$"

PokemonMansion_1F_Text_TedPostBattle::
	.string "Una chiave?\n"
	.string "Non so di cosa stai parlando!$"

PokemonMansion_1F_Text_JohnsonIntro::
	.string "Mi hai messo paura!\n"
	.string "Credevo che fossi un fantasma!$"

PokemonMansion_1F_Text_JohnsonDefeat::
	.string "Non riesco proprio a vincere!$"

PokemonMansion_1F_Text_JohnsonPostBattle::
	.string "Sono venuto a farmi un giro, ma\n"
	.string "mi è presa una paura…\p"
	.string "Forse è meglio che me ne vada…$"

