SixIsland_GreenPath_Text_JaclynIntro::
	.string "Ma come?\p"
	.string "Volevo TELESTRASPORTarmi a casa,\n"
	.string "e sono finita qui?!$"

SixIsland_GreenPath_Text_JaclynDefeat::
	.string "Buuu!!!$"

SixIsland_GreenPath_Text_JaclynPostBattle::
	.string "Devo concentrarmi!\p"
	.string "Altrimenti non riuscirò mai a\n"
	.string "TELETRASPORTarmi a casa!$"

SixIsland_GreenPath_Text_LeftRouteSign::
	.string "VIA VERDE\n"
	.string "Per il BOSCO DISEGNATO$"

SixIsland_GreenPath_Text_RightRouteSign::
	.string "VIA VERDE\n"
	.string "Ambiente pulito, futuro garantito!$"

