FuchsiaCity_WardensHouse_Text_HifFuffHefifoo::
	.string "GUARDIANO: Fii fuf fefifu!\p"
	.string "A fof a fif ee afahi fo.\n"
	.string "Eeff fi fui!$"

FuchsiaCity_WardensHouse_Text_AhHowheeHoHoo::
	.string "Ah fafee oo foo!\n"
	.string "Eef ee afafi fo!$"

FuchsiaCity_WardensHouse_Text_HeOhayHeHaHoo::
	.string "Ah?\n"
	.string "Fai fou fee fa foo if afee!$"

FuchsiaCity_WardensHouse_Text_GaveGoldTeethToWarden::
	.string "{PLAYER} dà i DENTI D'ORO al\n"
	.string "GUARDIANO!$"

FuchsiaCity_WardensHouse_Text_WardenPoppedInHisTeeth::
	.string "Il GUARDIANO si mette i denti!$"

FuchsiaCity_WardensHouse_Text_ThanksSonGiveYouSomething::
	.string "GUARDIANO: Grazie!\n"
	.string "Nessuno capiva niente di quello che\l"
	.string "dicevo.\p"
	.string "In quello stato non potevo\n"
	.string "lavorare.\p"
	.string "Ti darò qualcosa per ricompensarti!$"

FuchsiaCity_WardensHouse_Text_ThanksLassieGiveYouSomething::
	.string "GUARDIANO: Grazie!\n"
	.string "Nessuno capiva niente di quello che\l"
	.string "dicevo.\p"
	.string "In quello stato non potevo\n"
	.string "lavorare.\p"
	.string "Ti darò qualcosa per ricompensarti!$"

FuchsiaCity_WardensHouse_Text_ReceivedHM04FromWarden::
	.string "{PLAYER} riceve\n"
	.string "la MN04!$"

FuchsiaCity_WardensHouse_Text_ExplainStrength::
	.string "GUARDIANO: La MN04 insegna la\n"
	.string "FORZA!\p"
	.string "I tuoi POKéMON potranno muovere\n"
	.string "i massi fuori dalla lotta.\p"
	.string "Hai trovato la CASA SEGRETA in\n"
	.string "ZONA SAFARI?$"

FuchsiaCity_WardensHouse_Text_YouHaveTooMuchStuff::
	.string "ß+ô àóÚ\n"
	.string "ÁっぱÁô+Ì!$"

FuchsiaCity_WardensHouse_Text_MonPhotosFossilsOnDisplay::
	.string "Foto e fossili di POKéMON.$"

FuchsiaCity_WardensHouse_Text_OldMonMerchandiseOnDisplay::
	.string "Vecchi oggetti POKéMON!$"

