SaffronCity_MrPsychicsHouse_Text_YouWantedThis::
	.string "…Alt! Non dire una parola!\p"
	.string "Volevi questo!$"

SaffronCity_MrPsychicsHouse_Text_ReceivedTM29FromMrPsychic::
	.string "{PLAYER} riceve\n"
	.string "la MT29!$"

SaffronCity_MrPsychicsHouse_Text_ExplainTM29::
	.string "MT29 è PSICHICO.\p"
	.string "Riduce le statistiche SPECIALI\n"
	.string "dell'avversario!$"

SaffronCity_MrPsychicsHouse_Text_YouveNoRoom::
	.string "Non vedi che non hai spazio?$"

