RockTunnel_B1F_Text_SofiaIntro::
	.string "Sai come si fa a non perdersi in\n"
	.string "montagna? Basta segnare il\l"
	.string "percorso con dei rametti!$"

RockTunnel_B1F_Text_SofiaDefeat::
	.string "Oho!\n"
	.string "Ho fatto del mio meglio!$"

RockTunnel_B1F_Text_SofiaPostBattle::
	.string "Voglio andare a casa mia!$"

RockTunnel_B1F_Text_DudleyIntro::
	.string "Ahahah!\n"
	.string "Credi di potermi battere?$"

RockTunnel_B1F_Text_DudleyDefeat::
	.string "Ups!\n"
	.string "Livello muscolare: zero!$"

RockTunnel_B1F_Text_DudleyPostBattle::
	.string "Uso i muscoli perché odio pensare!$"

RockTunnel_B1F_Text_CooperIntro::
	.string "Hai un POKéDEX?\n"
	.string "Ne voglio uno anch'io!$"

RockTunnel_B1F_Text_CooperDefeat::
	.string "Grr!\n"
	.string "Crepo d'invidia!$"

RockTunnel_B1F_Text_CooperPostBattle::
	.string "Quando hai completato il tuo\n"
	.string "POKéDEX, me lo daresti?$"

RockTunnel_B1F_Text_SteveIntro::
	.string "Mai sentito dei giocatori in\n"
	.string "costume?$"

RockTunnel_B1F_Text_SteveDefeat::
	.string "Bene, questo è quanto.$"

RockTunnel_B1F_Text_StevePostBattle::
	.string "Ci sono persone che si travestono\n"
	.string "da POKéMON per divertimento.\p"
	.string "CLEFAIRY è la maschera preferita.$"

RockTunnel_B1F_Text_AllenIntro::
	.string "Le mie tecniche POKéMON ti\n"
	.string "distruggeranno!$"

RockTunnel_B1F_Text_AllenDefeat::
	.string "Mi arrendo!\n"
	.string "Le tue tecniche sono migliori!$"

RockTunnel_B1F_Text_AllenPostBattle::
	.string "In montagna si trovano spesso\n"
	.string "POKéMON di tipo ROCCIA.$"

RockTunnel_B1F_Text_MarthaIntro::
	.string "Non mi sento molto sicura, ma\n"
	.string "lotterò!$"

RockTunnel_B1F_Text_MarthaDefeat::
	.string "Oh!\n"
	.string "Ho perso!$"

RockTunnel_B1F_Text_MarthaPostBattle::
	.string "Mi piacciono i POKéMON piccoli,\n"
	.string "quelli grandi sono spaventosi!$"

RockTunnel_B1F_Text_EricIntro::
	.string "Sferra il tuo attacco migliore!$"

RockTunnel_B1F_Text_EricDefeat::
	.string "Bruciato in un soffio!$"

RockTunnel_B1F_Text_EricPostBattle::
	.string "Allenerò i miei POKéMON per\n"
	.string "battere i tuoi!$"

RockTunnel_B1F_Text_WinstonIntro::
	.string "Quando sono a casa disegno\n"
	.string "POKéMON.$"

RockTunnel_B1F_Text_WinstonDefeat::
	.string "Uff!\n"
	.string "Che stanchezza!$"

RockTunnel_B1F_Text_WinstonPostBattle::
	.string "Sono un artista, non un lottatore.$"

