CeladonCity_PokemonCenter_1F_Text_PokeFluteAwakensSleepingMons::
	.string "Il POKé FLAUTO sveglia i POKéMON\n"
	.string "con un suono che possono sentire\l"
	.string "solo loro!$"

CeladonCity_PokemonCenter_1F_Text_RodeHereFromFuchsia::
	.string "Sono venuta da FUCSIAPOLI per la\n"
	.string "PISTA CICLABILE, che salita!$"

CeladonCity_PokemonCenter_1F_Text_GoToCyclingRoadIfIHadBike::
	.string "Se avessi una BICICLETTA\n"
	.string "andrei sulla PISTA CICLABILE!$"

