ThreeIsland_Text_IslandSign::
	.string "TERZISOLA\n"
	.string "L'isola degli affetti familiari$"

ThreeIsland_Text_IslandBelongsToUs::
	.string "Wow!\p"
	.string "Da questo momento, l'isola è\n"
	.string "nostra!$"

ThreeIsland_Text_GoBackToKanto::
	.string "Senti, voglio dirtelo chiaro:\n"
	.string "tornatevene a KANTO.\p"
	.string "Non abbiamo bisogno della\n"
	.string "vostra confusione su quest'isola!$"

ThreeIsland_Text_BossIsOnHisWay::
	.string "Vai a piagnucolare da un'altra\n"
	.string "parte!\p"
	.string "Sta arrivando il nostro capo, e ti\n"
	.string "darà una lezione di motociclismo\l"
	.string "che non dimenticherai!$"

ThreeIsland_Text_GetOffIslandNow::
	.string "Come?! Tornate da dove siete\n"
	.string "venuti, o ve ne pentirete!$"

ThreeIsland_Text_WhosGonnaMakeMe::
	.string "Chi vuole sfidarmi?$"

ThreeIsland_Text_AreYouBossGoBackToKanto::
	.string "Sei tu il capo?\n"
	.string "Torna immediatamente a KANTO!$"

ThreeIsland_Text_JustGotHerePal::
	.string "Ehi, cos'è quell'aria ostile?\n"
	.string "Sono appena arrivato!\p"
	.string "Che bella accoglienza!$"

ThreeIsland_Text_FollowersRaisingHavoc::
	.string "La vostra banda sta creando\n"
	.string "scompiglio con quelle moto!\p"
	.string "Avete idea dei fastidi che ci\n"
	.string "avete procurato?$"

ThreeIsland_Text_OughtToBeThankingUs::
	.string "No, scusa ma non capisco.\p"
	.string "Guardati in giro: è un mortorio.\p"
	.string "Dovreste ringraziarci perché\n"
	.string "ravviviamo un po' questo posto!\p"
	.string "Ma se proprio ci tieni, prova a\n"
	.string "farci andare via! Ah ah ah!$"

ThreeIsland_Text_YouCowardsToughInPack::
	.string "Razza di codardi!\p"
	.string "Fate gli sbruffoni solo perché\n"
	.string "siete in gruppo!$"

ThreeIsland_Text_WannaMakeSomethingOfYourStaring::
	.string "Ehi, tu, la smetti di fissarci?\n"
	.string "Non lo sai che non è educato?\p"
	.string "Hai per caso intenzione di\n"
	.string "sfidarci?$"

ThreeIsland_Text_ThatsSmart::
	.string "Meglio per te.\n"
	.string "Vedi di non immischiarti!$"

ThreeIsland_Text_Biker1Intro::
	.string "Ehi, hai coraggio!\n"
	.string "Credo che perderai parecchi\l"
	.string "soldini, ma hai fegato…$"

ThreeIsland_Text_Biker1Defeat::
	.string "Ehi, ma chi sei?!$"

ThreeIsland_Text_Biker1PostBattle::
	.string "Non azzardarti a ridere!$"

ThreeIsland_Text_Biker2Intro::
	.string "Ma tu non sei di KANTO?\n"
	.string "Dovresti essere dalla nostra parte!$"

ThreeIsland_Text_Biker2Defeat::
	.string "Smetti di esaltarti!$"

ThreeIsland_Text_Biker2PostBattle::
	.string "Guarda come ti scaldi per una\n"
	.string "misera vittoria!\p"
	.string "Non hai proprio classe!$"

ThreeIsland_Text_Biker3Intro::
	.string "Abbiamo invitato qui il nostro\n"
	.string "capo…\p"
	.string "…e guarda che brutta figura\n"
	.string "ci fai fare!$"

ThreeIsland_Text_Biker3Defeat::
	.string "… … …   … … …$"

ThreeIsland_Text_Biker3PostBattle::
	.string "Capo, credo che dovrai sporcarti\n"
	.string "le mani con questa pulce!$"

ThreeIsland_Text_PaxtonIntro::
	.string "Ti ho osservato, e non sei male.\n"
	.string "Questo è il tuo capolinea, però!\p"
	.string "Ci tieni tanto alla gente di\n"
	.string "quest'isola?\p"
	.string "Vorrà dire che sfiderò te al posto\n"
	.string "loro!$"

ThreeIsland_Text_PaxtonDefeat::
	.string "E va bene.\p"
	.string "Ce ne andiamo, se è questo\n"
	.string "che vuoi.\p"
	.string "In fondo, questa è l'isola più\n"
	.string "noiosa che abbia mai visto.$"

ThreeIsland_Text_PaxtonPostBattle::
	.string "Cosa mai ci troverai in questi\n"
	.string "morti di sonno…$"

ThreeIsland_Text_ThankYouOhYourMonGotHurt::
	.string "Grazie per averci aiutato a\n"
	.string "sbarazzarci di quella gentaglia!\p"
	.string "Voglio farti un regalo!$"

ThreeIsland_Text_GivenFullRestore::
	.string "{PLAYER} riceve\n"
	.string "RICARICA TOT.$"

ThreeIsland_Text_OhYourBagIsFull::
	.string "Ehi, ma il tuo ZAINO è pieno!$"

ThreeIsland_Text_YouveGotImpressiveMons::
	.string "La tua squadra è davvero\n"
	.string "notevole!$"

ThreeIsland_Text_LostelleWentOffTowardsBondBridge::
	.string "Sarebbe fantastico avere con noi\n"
	.string "una persona forte come te!\p"
	.string "Ci auguriamo che tu possa\n"
	.string "restare ancora un po'.\p"
	.string "…Ah, stai cercando LISETTA?\p"
	.string "L'ho vista che non è molto: era\n"
	.string "diretta verso il PONTE ABBRACCIO.$"

ThreeIsland_Text_WouldntWantToSeeBikersHereAgain::
	.string "TERZISOLA è la più popolosa\n"
	.string "di tutto il SETTIPELAGO.\p"
	.string "È vero che non è molto vitale.\p"
	.string "Ma piuttosto che il fracasso di\n"
	.string "quei CENTAURI, preferisco\l"
	.string "questa quiete un po' noiosa.$"

ThreeIsland_Text_WhenDodouEvolvesGoingToPlayGame::
	.string "Vado ad allenare il mio DODUO\n"
	.string "nel BOSCO BACCOSO.\p"
	.string "E appena si evolve, lo porto a\n"
	.string "giocare a SECONDISOLA.$"

ThreeIsland_Text_Doduo::
	.string "DODUO: Dudo, dodu!$"

