CinnabarIsland_Gym_Text_PhotoOfBlaineAndFuji::
	.string "È una foto di BLAINE e MR. FUJI!\p"
	.string "Sorridono, affiancati.$"

CinnabarIsland_PokemonLab_Entrance_Text_StudyMonsExtensively::
	.string "Qui studiamo attentamente i\n"
	.string "POKéMON.\p"
	.string "Spesso ci portano dei POKéMON rari\n"
	.string "da esaminare.$"

CinnabarIsland_PokemonLab_Entrance_Text_PhotoOfLabFounderDrFuji::
	.string "Una foto del fondatore del\n"
	.string "LABORATORIO, il DR. FUJI!$"

CinnabarIsland_PokemonLab_Entrance_Text_MeetingRoomSign::
	.string "LABORATORIO POKéMON\n"
	.string "Sala riunioni$"

CinnabarIsland_PokemonLab_Entrance_Text_RAndDRoomSign::
	.string "LABORATORIO POKéMON\n"
	.string "Ricerca e sviluppo$"

CinnabarIsland_PokemonLab_Entrance_Text_TestingRoomSign::
	.string "LABORATORIO POKéMON\n"
	.string "Sala testing$"

