MtMoon_1F_Text_MarcosIntro::
	.string "WOW!\n"
	.string "Mi hai spaventato!$"

MtMoon_1F_Text_MarcosDefeat::
	.string "Wow!\n"
	.string "Mi hai spaventato di nuovo!$"

MtMoon_1F_Text_MarcosPostBattle::
	.string "Questo non è posto per bambini!$"

MtMoon_1F_Text_JoshIntro::
	.string "Anche tu qui per esplorare?$"

MtMoon_1F_Text_JoshDefeat::
	.string "Perdere fa male!$"

MtMoon_1F_Text_JoshPostBattle::
	.string "Sono qui per far colpo sulle\n"
	.string "ragazze!$"

MtMoon_1F_Text_MiriamIntro::
	.string "Wow! È molto più grande di quanto\n"
	.string "pensassi!$"

MtMoon_1F_Text_MiriamDefeat::
	.string "Oh no!\n"
	.string "Ho perso!$"

MtMoon_1F_Text_MiriamPostBattle::
	.string "Come si esce di qui?$"

MtMoon_1F_Text_JovanIntro::
	.string "Osi strisciarmi accanto?!$"

MtMoon_1F_Text_JovanDefeat::
	.string "I miei POKéMON non ce l'hanno\n"
	.string "fatta!$"

MtMoon_1F_Text_JovanPostBattle::
	.string "Devo catturare POKéMON più forti!$"

MtMoon_1F_Text_IrisIntro::
	.string "Che?\n"
	.string "Aspetto che arrivino i miei amici.$"

MtMoon_1F_Text_IrisDefeat::
	.string "Ho perso?$"

MtMoon_1F_Text_IrisPostBattle::
	.string "Si dice che qui ci siano dei fossili\n"
	.string "molto rari.$"

MtMoon_1F_Text_KentIntro::
	.string "Nella grotta ci sono tipi loschi.\n"
	.string "Tu, chi sei?$"

MtMoon_1F_Text_KentDefeat::
	.string "Ehi, mi hai beccato!$"

MtMoon_1F_Text_KentPostBattle::
	.string "Li ho visti!\n"
	.string "Sono quelli di TEAM ROCKET!\l"
	.string "È certo!$"

MtMoon_1F_Text_RobbyIntro::
	.string "Passa per questa grotta e sarai a\n"
	.string "CELESTOPOLI!$"

MtMoon_1F_Text_RobbyDefeat::
	.string "Ah!\n"
	.string "Ho perso!$"

MtMoon_1F_Text_RobbyPostBattle::
	.string "ZUBAT è tosto!\n"
	.string "Catturarne uno ti sarà molto utile!$"

MtMoon_1F_Text_ZubatIsABloodsucker::
	.string "Attento!\n"
	.string "ZUBAT è una sanguisuga!$"

MtMoon_1F_Text_BrockHelpsExcavateFossils::
	.string "Ciao, sono venuto sul MONTE LUNA\n"
	.string "per cercare fossili sottoterra.\p"
	.string "A volte viene ad aiutarmi BROCK \n"
	.string "da PLUMBEOPOLI.$"

