PokemonMansion_B1F_Text_LewisIntro::
	.string "Ohoh!\n"
	.string "E adesso, dove sono?$"

PokemonMansion_B1F_Text_LewisDefeat::
	.string "Ahi!$"

PokemonMansion_B1F_Text_LewisPostBattle::
	.string "Puoi trovare oggetti sparsi\n"
	.string "ovunque, lasciati da chi\l"
	.string "abitava in questa villa.$"

PokemonMansion_B1F_Text_IvanIntro::
	.string "Questo dev'essere stato\n"
	.string "un laboratorio.$"

PokemonMansion_B1F_Text_IvanDefeat::
	.string "A cosa serviva quello?$"

PokemonMansion_B1F_Text_IvanPostBattle::
	.string "Mi piace venire a studiare qui!\n"
	.string "Mi concentro meglio!$"

PokemonMansion_B1F_Text_MewtwoIsFarTooPowerful::
	.string "Diario: 1 settembre\n"
	.string "MEWTWO è davvero potente.\p"
	.string "Non riusciamo a contenere i suoi\n"
	.string "istinti feroci.$"

