SevenIsland_TrainerTower_Text_DarioIntro::
	.string "Ho presagito il tuo arrivo!$"

SevenIsland_TrainerTower_Text_DarioDefeat::
	.string "Mi arrendo…$"

SevenIsland_TrainerTower_Text_DarioPostBattle::
	.string "Incontrerai molte persone sul\n"
	.string "tuo cammino.\p"
	.string "E ti collegherai con loro grazie\n"
	.string "ad uno strano potere!$"

SevenIsland_TrainerTower_Text_RodetteIntro::
	.string "Ci sono POKéMON speciali che\n"
	.string "dormono su quest'isola.$"

SevenIsland_TrainerTower_Text_RodetteDefeat::
	.string "Che ALLENATORE eccezionale!$"

SevenIsland_TrainerTower_Text_RodettePostBattle::
	.string "Ci sono POKéMON speciali che\n"
	.string "dormono su quest'isola.\p"
	.string "Credi che ti stiano aspettando?$"

SevenIsland_TrainerTower_Text_TrainerTowerSign::
	.string "TORRE ALLENATORI\n"
	.string "Siete pronti per la sfida?$"

SevenIsland_TrainerTower_Text_TrainerTowerAhead::
	.string "Per la TORRE ALLENATORI$"

SevenIsland_TrainerTower_Text_LooksLikeTrainerTowerIsClosed::
	.string "トレ-ナ-タワ-àè\n"
	.string "Áまè èÁºßÁ îŒÁ…$"

SevenIsland_TrainerTower_Text_TrainerTowerIsOpenLetsGoIn::
	.string "トレ-ナ-タワ-が ÀÁÛñ!\n"
	.string "ÎっÔË èÁっÛîùÂ!$"

