FuchsiaCity_House1_Text_WardenIsOldHasFalseTeeth::
	.string "Il GUARDIANO della ZONA SAFARI è\n"
	.string "vecchio, ma ancora in gamba!\p"
	.string "Però porta la dentiera!$"

FuchsiaCity_House1_Text_BillIsMyGrandson::
	.string "Hmm?\n"
	.string "Conosci BILL?\p"
	.string "È mio nipote!\p"
	.string "Fin da piccolo, ha sempre \n"
	.string "avuto la passione per le\l"
	.string "collezioni.$"

FuchsiaCity_House1_Text_BillFilesHisOwnMonData::
	.string "BILL registra i dati dei suoi\n"
	.string "POKéMON nel suo PC!\p"
	.string "Te l'ha mostrato?$"

