PokemonTower_7F_Text_Grunt1Intro::
	.string "Cosa cerchi?\n"
	.string "Perché sei qui?$"

PokemonTower_7F_Text_Grunt1Defeat::
	.string "Mi arrendo!$"

PokemonTower_7F_Text_Grunt1PostBattle::
	.string "Non me lo dimenticherò!$"

PokemonTower_7F_Text_Grunt2Intro::
	.string "Questo vecchietto si è intrufolato\n"
	.string "nel nostro RIFUGIO.\p"
	.string "Poi, ha iniziato a lamentarsi,\n"
	.string "dicendo che TEAM ROCKET fa\l"
	.string "del male ai POKéMON.\p"
	.string "Ora stiamo cercando di farlo\n"
	.string "ragionare.$"

PokemonTower_7F_Text_Grunt2Defeat::
	.string "Basta, per favore!$"

PokemonTower_7F_Text_Grunt2PostBattle::
	.string "I POKéMON servono solo per far\n"
	.string "soldi!\p"
	.string "Non t'impicciare!$"

PokemonTower_7F_Text_Grunt3Intro::
	.string "Non salverai nessuno!$"

PokemonTower_7F_Text_Grunt3Defeat::
	.string "Non osare sfidare i ROCKET!$"

PokemonTower_7F_Text_Grunt3PostBattle::
	.string "Non te la caverai!$"

PokemonTower_7F_Text_MrFujiThankYouFollowMe::
	.string "MR. FUJI: Sei qui per salvarmi?\p"
	.string "Grazie, ma mi sono recato qui\n"
	.string "spontaneamente.\p"
	.string "Volevo calmare l'anima\n"
	.string "della madre di CUBONE.\p"
	.string "Credo che ormai lo spirito di\n"
	.string "MAROWAK sia già nell'aldilà.\p"
	.string "Grazie mille per l'interessamento!\p"
	.string "Seguimi fino alla CASA POKéMON, ai\n"
	.string "piedi di questa torre.$"

