SevenIsland_SevaultCanyon_House_Text_ChanseyDanceJoinIn::
	.string "Dance, dance!\n"
	.string "CHANSEY Dance!\p"
	.string "Ehi, balla con me!\n"
	.string "Dance, dance!$"

SevenIsland_SevaultCanyon_House_Text_WouldYouLikeToDance::
	.string "Ti va di ballare?$"

SevenIsland_SevaultCanyon_House_Text_ComeOnDance::
	.string "Dai, vieni a ballare!$"

SevenIsland_SevaultCanyon_House_Text_DancedChanseyDance::
	.string "{PLAYER} balla la CHANSEY Dance!$"

SevenIsland_SevaultCanyon_House_Text_YoureAllChipperNow::
	.string "Ahahahaha!\p"
	.string "Guarda come siete di buon umore\n"
	.string "adesso, tu e la tua squadra!$"

SevenIsland_SevaultCanyon_House_Text_Chansey::
	.string "CHANSEY: Chansi! Chansi!$"

