VermilionCity_House3_Text_PidgeyFlyLetterToSaffron::
	.string "Il mio PIDGEY volerà a nord, per\n"
	.string "portare una lettera a\l"
	.string "ZAFFERANOPOLI!$"

VermilionCity_House3_Text_Pidgey::
	.string "PIDGEY: pig pig!$"

VermilionCity_House3_Text_DearPippiLetter::
	.string "Caro PIPPI,\n"
	.string "spero di vederti presto.\p"
	.string "Ho saputo che ZAFFERANOPOLI ha\n"
	.string "problemi con TEAM ROCKET.\p"
	.string "ARANCIOPOLI sembra salva per ora.$"

VermilionCity_House3_Text_SendMyPidgeyToUnionRoom::
	.string "Voglio scambiare MESSAGGI con\n"
	.string "chiunque.\p"
	.string "Manderò il mio PIDGEY in una SALA\n"
	.string "CONTATTO a scambiare MESSAGGI\l"
	.string "per me!$"

