Route18_Text_WiltonIntro::
	.string "Cerco sempre nuovi POKéMON\n"
	.string "nell'erba alta.$"

Route18_Text_WiltonDefeat::
	.string "Ohi!$"

Route18_Text_WiltonPostBattle::
	.string "Mi piacerebbe avere una\n"
	.string "BICICLETTA!$"

Route18_Text_RamiroIntro::
	.string "Cu cu cu!\n"
	.string "Ti piace questo richiamo?$"

Route18_Text_RamiroDefeat::
	.string "Volevo darti fastidio!$"

Route18_Text_RamiroPostBattle::
	.string "Il fine settimana prendo anche\n"
	.string "POKéMON di mare!$"

Route18_Text_JacobIntro::
	.string "Questo è il mio territorio!\n"
	.string "Via!$"

Route18_Text_JacobDefeat::
	.string "Maledizione!$"

Route18_Text_JacobPostBattle::
	.string "Questa è la zona che preferisco\n"
	.string "per catturare i POKéMON!$"

Route18_Text_RouteSign::
	.string "PERCORSO 18\n"
	.string "AZZURROPOLI - FUCSIAPOLI$"

Route18_Text_CyclingRoadSign::
	.string "PISTA CICLABILE\n"
	.string "Vietata ai pedoni!$"

