Route19_Text_RichardIntro::
	.string "Prima di nuotare bisogna fare\n"
	.string "riscaldamento!$"

Route19_Text_RichardDefeat::
	.string "Ora sì che mi sono riscaldato!$"

Route19_Text_RichardPostBattle::
	.string "Grazie!\n"
	.string "Ora posso tuffarmi!$"

Route19_Text_ReeceIntro::
	.string "Aspetta!\n"
	.string "Ti verrà un accidente!$"

Route19_Text_ReeceDefeat::
	.string "Oooh!!\n"
	.string "Che doccia fredda!$"

Route19_Text_ReecePostBattle::
	.string "Attenzione a TENTACOOL!$"

Route19_Text_MatthewIntro::
	.string "Mi piace nuotare!\n"
	.string "E a te?$"

Route19_Text_MatthewDefeat::
	.string "Che spanciata!$"

Route19_Text_MatthewPostBattle::
	.string "Nuoto meglio dei POKéMON!$"

Route19_Text_DouglasIntro::
	.string "Che c'è oltre l'orizzonte?$"

Route19_Text_DouglasDefeat::
	.string "Glu! Glu!$"

Route19_Text_DouglasPostBattle::
	.string "Vedo un paio di isole!$"

Route19_Text_DavidIntro::
	.string "Mi sono tuffato per prendere dei\n"
	.string "POKéMON, ma zero!$"

Route19_Text_DavidDefeat::
	.string "Aiuto!$"

Route19_Text_DavidPostBattle::
	.string "Cerca di pescare POKéMON di mare!$"

Route19_Text_TonyIntro::
	.string "Guardo il mare per dimenticare!$"

Route19_Text_TonyDefeat::
	.string "Oh!\n"
	.string "Che trauma!$"

Route19_Text_TonyPostBattle::
	.string "Quando sono triste, guardo il mare!$"

Route19_Text_AnyaIntro::
	.string "Ah, usi un POKéMON per spostarti\n"
	.string "sull'acqua!\l"
	.string "Se vinco, me lo dai?$"

Route19_Text_AnyaDefeat::
	.string "Ho perso!\n"
	.string "Peccato!$"

Route19_Text_AnyaPostBattle::
	.string "La via per le ISOLE SPUMARINE è\n"
	.string "ancora lunga!$"

Route19_Text_AliceIntro::
	.string "Nuotare è bello!\n"
	.string "Scottarsi al sole invece no!$"

Route19_Text_AliceDefeat::
	.string "Che orrore!$"

Route19_Text_AlicePostBattle::
	.string "Il mio ragazzo voleva nuotare fino\n"
	.string "alle ISOLE SPUMARINE.$"

Route19_Text_AxleIntro::
	.string "Queste sono acque traditrici!$"

Route19_Text_AxleDefeat::
	.string "Oh!\n"
	.string "È pericoloso!$"

Route19_Text_AxlePostBattle::
	.string "Mi è venuto un crampo!\n"
	.string "Gulp!$"

Route19_Text_ConnieIntro::
	.string "Sono venuta a nuoto.\n"
	.string "Ma ora sono stanca!$"

Route19_Text_ConnieDefeat::
	.string "Sono sfinita!$"

Route19_Text_ConniePostBattle::
	.string "LAPRAS è enorme, su di lui non ti\n"
	.string "bagni di sicuro.$"

Route19_Text_RouteSign::
	.string "PERCORSO MARINO 19\n"
	.string "FUCSIAPOLI - ISOLE SPUMARINE$"

Route19_Text_LiaIntro::
	.string "KATE: Sto aiutando il mio\n"
	.string "fratellino a diventare un bravo\l"
	.string "ALLENATORE.$"

Route19_Text_LiaDefeat::
	.string "KATE: Vacci piano con mio fratello,\n"
	.string "è ancora inesperto.$"

Route19_Text_LiaPostBattle::
	.string "KATE: Anche tu hai un fratellino?\p"
	.string "Se è così, stagli vicino.\n"
	.string "Ha bisogno di te.$"

Route19_Text_LiaNotEnoughMons::
	.string "KATE: Io lotto solo al fianco di\n"
	.string "mio fratello.\p"
	.string "Se non hai almeno due POKéMON,\n"
	.string "non puoi sfidarci.$"

Route19_Text_LucIntro::
	.string "SAM: La mia sorellona mi ha\n"
	.string "insegnato ad allenare i POKéMON!$"

Route19_Text_LucDefeat::
	.string "SAM: Ehi! Tu sei più forte\n"
	.string "della mia sorellona!$"

Route19_Text_LucPostBattle::
	.string "SAM: La mia sorellona è bella e\n"
	.string "forte! È il mio idolo!$"

Route19_Text_LucNotEnoughMons::
	.string "SAM: Senza mia sorella, non\n"
	.string "mi diverto.\p"
	.string "Non hai un altro POKéMON per\n"
	.string "poterci sfidare entrambi?$"

