VictoryRoad_1F_Text_NaomiIntro::
	.string "Mi chiedo se sei all'altezza di\n"
	.string "lottare con me!$"

VictoryRoad_1F_Text_NaomiDefeat::
	.string "Ho perso tutto!$"

VictoryRoad_1F_Text_NaomiPostBattle::
	.string "Non sopporto le sconfitte!$"

VictoryRoad_1F_Text_RolandoIntro::
	.string "Mi sembri forte!\n"
	.string "Dimostramelo!$"

VictoryRoad_1F_Text_RolandoDefeat::
	.string "Ho avuto la mia possibilità!$"

VictoryRoad_1F_Text_RolandoPostBattle::
	.string "Lo ammetto!\n"
	.string "Sei più forte di me!$"

