Route2_ViridianForest_NorthEntrance_Text_ManyMonsOnlyInForests::
	.string "Molti POKéMON vivono solo in boschi\n"
	.string "e grotte.\p"
	.string "Devi guardare ovunque per\n"
	.string "catturarne diverse specie!$"

Route2_ViridianForest_NorthEntrance_Text_CanCutSkinnyTrees::
	.string "Hai visto gli alberelli a lato\n"
	.string "della strada?\p"
	.string "Con una mossa speciale i POKéMON\n"
	.string "possono tagliarli.$"

Route2_ViridianForest_NorthEntrance_Text_CanCancelEvolution::
	.string "Puoi interrompere l'evoluzione.\p"
	.string "Quando un POKéMON si evolve puoi\n"
	.string "bloccarlo e far sì che non muti.$"

