Route20_Text_BarryIntro::
	.string "Qui l'acqua non è profonda.$"

Route20_Text_BarryDefeat::
	.string "Splash!$"

Route20_Text_BarryPostBattle::
	.string "Vorrei potermi spostare sull'acqua\n"
	.string "sopra uno dei miei POKéMON!$"

Route20_Text_ShirleyIntro::
	.string "Le ISOLE SPUMARINE sono un\n"
	.string "posto tranquillo!$"

Route20_Text_ShirleyDefeat::
	.string "Finiscila!$"

Route20_Text_ShirleyPostBattle::
	.string "C'è un'enorme grotta sotto\n"
	.string "quest'isola.$"

Route20_Text_TiffanyIntro::
	.string "Nuotare con i pesci!\n"
	.string "Che bello!$"

Route20_Text_TiffanyDefeat::
	.string "Ahiahi!$"

Route20_Text_TiffanyPostBattle::
	.string "Vuoi nuotare con me?$"

Route20_Text_IreneIntro::
	.string "Anche tu in vacanza?$"

Route20_Text_IreneDefeat::
	.string "Nessuna pietà!$"

Route20_Text_IrenePostBattle::
	.string "Le ISOLE SPUMARINE una volta\n"
	.string "erano una sola isola!$"

Route20_Text_DeanIntro::
	.string "Guarda che fisico che ho!$"

Route20_Text_DeanDefeat::
	.string "Che imbranato!$"

Route20_Text_DeanPostBattle::
	.string "Avrei dovuto rafforzare i miei\n"
	.string "POKéMON, invece di pensare\l"
	.string "tanto a farmi il fisico!$"

Route20_Text_DarrinIntro::
	.string "Perché ti sposti su di un POKéMON?\n"
	.string "Non sai nuotare?$"

Route20_Text_DarrinDefeat::
	.string "Ahi!\n"
	.string "Silurato!$"

Route20_Text_DarrinPostBattle::
	.string "Spostarsi sull'acqua su di un\n"
	.string "POKéMON! Che trovata!$"

Route20_Text_RogerIntro::
	.string "Sono arrivato a dorso del mio\n"
	.string "POKéMON uccello!$"

Route20_Text_RogerDefeat::
	.string "Oh no!$"

Route20_Text_RogerPostBattle::
	.string "I miei POKéMON uccello sono\n"
	.string "esausti, ora!$"

Route20_Text_NoraIntro::
	.string "Il mio ragazzo mi ha dato delle\n"
	.string "perle giganti!$"

Route20_Text_NoraDefeat::
	.string "Non toccare le mie perle!$"

Route20_Text_NoraPostBattle::
	.string "Cresceranno le mie perle dentro a\n"
	.string "CLOYSTER?$"

Route20_Text_MissyIntro::
	.string "Sono venuta a nuoto dall'ISOLA\n"
	.string "CANNELLA!$"

Route20_Text_MissyDefeat::
	.string "Che delusione!$"

Route20_Text_MissyPostBattle::
	.string "I POKéMON hanno occupato una villa\n"
	.string "abbandonata sull'ISOLA CANNELLA!$"

Route20_Text_MelissaIntro::
	.string "C'è un LABORATORIO POKéMON a\n"
	.string "ovest, sull'ISOLA CANNELLA\p"
	.string "Mio papà lavora lì!$"

Route20_Text_MelissaDefeat::
	.string "Aspetta!$"

Route20_Text_MelissaPostBattle::
	.string "L'ISOLA CANNELLA è di origine\n"
	.string "vulcanica!$"

Route20_Text_SeafoamIslands::
	.string "ISOLE SPUMARINE$"

Route20_Text_MistyTrainsHere::
	.string "Questi posti sono frequentati da\n"
	.string "forti ALLENATORI e POKéMON di\l"
	.string "tipo ACQUA.\p"
	.string "Pare che MISTY di CELESTOPOLI\n"
	.string "si alleni da queste parti.$"

