SSAnne_Kitchen_Text_BusyOutOfTheWay::
	.string "Ehi tu! Abbiamo da fare!\n"
	.string "Fuori dai piedi!$"

SSAnne_Kitchen_Text_SawOddBerryInTrash::
	.string "Ho visto una strana BACCA nella\n"
	.string "spazzatura. Cosa sarà mai?$"

SSAnne_Kitchen_Text_SoBusyImDizzy::
	.string "Sono così occupato che mi gira la\n"
	.string "testa!$"

SSAnne_Kitchen_Text_PeelSpudsEveryDay::
	.string "Perché capitano tutte a me?\p"
	.string "Tutti i giorni qui a pelar patate!\n"
	.string "Che penitenza!$"

SSAnne_Kitchen_Text_HearAboutSnorlaxItsAGlutton::
	.string "Hai sentito parlare di SNORLAX?\p"
	.string "Non fa altro che mangiare e\n"
	.string "dormire!$"

SSAnne_Kitchen_Text_OnlyGetToPeelOnions::
	.string "Uffa!!! Uff!!!\p"
	.string "Sempre io a sbucciar cipolle!\n"
	.string "Uffa!!!$"

SSAnne_Kitchen_Text_IAmLeChefMainCourseIs::
	.string "Allora!\n"
	.string "Le CHEF c'est moi!\p"
	.string "Voilà le menu!$"

SSAnne_Kitchen_Text_SalmonDuSalad::
	.string "Salade de Saumon!\p"
	.string "Forse gli ospiti diranno\n"
	.string "“Uff, sempre pesce!”$"

SSAnne_Kitchen_Text_EelsAuBarbecue::
	.string "Anguille au Barbecue!\p"
	.string "Penso che ci sarà un\n"
	.string "ammutinamento!$"

SSAnne_Kitchen_Text_PrimeBeefsteak::
	.string "Bistecca ai ferri!\p"
	.string "Ma avrò abbastanza filetti di\n"
	.string "manzo?$"

