SilphCo_2F_Text_ConnorIntro::
	.string "Aiuto! Sono un dipendente della\n"
	.string "SILPH SpA!$"

SilphCo_2F_Text_ConnorDefeat::
	.string "Come sapevi che ero un ROCKET?$"

SilphCo_2F_Text_ConnorPostBattle::
	.string "Lavoro sia per la SILPH SpA che\n"
	.string "per TEAM ROCKET!$"

SilphCo_2F_Text_JerryIntro::
	.string "Qui è off limits!\n"
	.string "Aria, pulce!$"

SilphCo_2F_Text_JerryDefeat::
	.string "Però!\n"
	.string "Sei forte!$"

SilphCo_2F_Text_JerryPostBattle::
	.string "Riesci a uscire da questo\n"
	.string "labirinto?$"

SilphCo_2F_Text_Grunt1Intro::
	.string "Ehi, i bambini non possono entrare!$"

SilphCo_2F_Text_Grunt1Defeat::
	.string "È dura!$"

SilphCo_2F_Text_Grunt1PostBattle::
	.string "Le piastrelle a forma di diamante\n"
	.string "sono blocchi di teletrasporto!\p"
	.string "Teletrasporto ad alta tecnologia!$"

SilphCo_2F_Text_Grunt2Intro::
	.string "Ehi, mosca!\n"
	.string "Cosa fai qua?$"

SilphCo_2F_Text_Grunt2Defeat::
	.string "Ho fallito!$"

SilphCo_2F_Text_Grunt2PostBattle::
	.string "La SILPH SpA si fonderà con TEAM\n"
	.string "ROCKET!$"

Text_ThunderWaveTeach::
	.string "Aiuto!\n"
	.string "No! Fermati!\p"
	.string "Non stai con TEAM ROCKET!\n"
	.string "Pensavo… Scusa!\p"
	.string "Se ti insegno TUONONDA, mi\n"
	.string "perdoni?$"

Text_ThunderWaveDeclined::
	.string "Come vuoi. Comunque TUONONDA\n"
	.string "è un'ottima mossa.$"

Text_ThunderWaveWhichMon::
	.string "A quale POKéMON vuoi che insegni\n"
	.string "TUONONDA?$"

Text_ThunderWaveTaught::
	.string "Chi subisce TUONONDA può essere\n"
	.string "paralizzato.\p"
	.string "La paralisi può impedire ad un\n"
	.string "POKéMON di muoversi nella lotta.\p"
	.string "È una mossa di tipo ELETTRO, che\n"
	.string "non funziona su tutti i POKéMON.$"

SilphCo_2F_Text_FloorSign::
	.string "DIREZIONE della SILPH SpA\n"
	.string "1ºP$"

