Route21_South_Text_JackIntro::
	.string "Ho pescato tutti i miei POKéMON nel\n"
	.string "mare!$"

Route21_South_Text_JackDefeat::
	.string "Splash!$"

Route21_South_Text_JackPostBattle::
	.string "Dove hai preso i tuoi POKéMON?$"

Route21_South_Text_JeromeIntro::
	.string "Sto andando a fare una gara\n"
	.string "di triathlon!$"

Route21_South_Text_JeromeDefeat::
	.string "Sdonf… sdonf!$"

Route21_South_Text_JeromePostBattle::
	.string "Hai vinto! Ma mi rimangono il\n"
	.string "ciclismo e la maratona!$"

Route21_South_Text_RolandIntro::
	.string "Ah!\n"
	.string "Senti il sole e il vento!$"

Route21_South_Text_RolandDefeat::
	.string "Ahi ahi!\n"
	.string "Ho perso!$"

Route21_South_Text_RolandPostBattle::
	.string "Mi sono arrostito al sole!$"

Route21_South_Text_ClaudeIntro::
	.string "Ehi!\n"
	.string "Non spaventare i pesci!$"

Route21_South_Text_ClaudeDefeat::
	.string "Mi dispiace!\n"
	.string "Non volevo!$"

Route21_South_Text_ClaudePostBattle::
	.string "Mi sto scocciando perché non\n"
	.string "abbocca nulla!$"

Route21_South_Text_NolanIntro::
	.string "Fammi compagnia finché non prendo\n"
	.string "qualcosa!$"

Route21_South_Text_NolanDefeat::
	.string "Almeno così ho passato un po' di\n"
	.string "tempo.$"

Route21_South_Text_NolanPostBattle::
	.string "Aspetta…\n"
	.string "Sì! Ha abboccato!$"

Route21_North_Text_LilIntro::
	.string "LIL: Hai solo un POKéMON?\n"
	.string "IAN, non ce la fai da solo?$"

Route21_North_Text_LilDefeat::
	.string "LIL: Abbiamo perso. Sei felice,\n"
	.string "adesso?$"

Route21_North_Text_LilPostBattle::
	.string "LIL: Sono stanca. Non possiamo\n"
	.string "andare a casa?$"

Route21_North_Text_LilNotEnoughMons::
	.string "LIL: Eh? Una lotta?\n"
	.string "Da sola è troppo noioso. Porta due\l"
	.string "POKéMON, così ti sfidiamo insieme.$"

Route21_North_Text_IanIntro::
	.string "IAN: Mia sorella vuole perdere\n"
	.string "peso, così me la sono portata\l"
	.string "dietro.$"

Route21_North_Text_IanDefeat::
	.string "IAN: Sorella, abbiamo perso!$"

Route21_North_Text_IanPostBattle::
	.string "IAN: Sorellina, avanti di questo\n"
	.string "passo, non perderai mai i chili\l"
	.string "di troppo.$"

Route21_North_Text_IanNotEnoughMons::
	.string "IAN: Per una lotta 2 contro 2,\n"
	.string "devi avere due POKéMON!$"

