FiveIsland_WaterLabyrinth_Text_LetMeTakeLookAtMons::
	.string "Devi aver fatto molta strada.\p"
	.string "Tratti bene i tuoi POKéMON,\n"
	.string "vero?\p"
	.string "Fammi dare un'occhiata.\n"
	.string "… … …   … … …$"

FiveIsland_WaterLabyrinth_Text_HmmISeeIsee::
	.string "Ah…\n"
	.string "Capisco…$"

FiveIsland_WaterLabyrinth_Text_TreatMonRightHaveThis::
	.string "Vedo che tratti i tuoi POKéMON\n"
	.string "con grande amore.\p"
	.string "Tieni, meriti questo.$"

FiveIsland_WaterLabyrinth_Text_ReceivedEggFromMan::
	.string "{PLAYER} riceve l'UOVO.$"

FiveIsland_WaterLabyrinth_Text_DontHaveSpaceInYourParty::
	.string "…Purtroppo la tua squadra è\n"
	.string "già al completo.\p"
	.string "Torna a prendere il tuo regalo\n"
	.string "quando avrai fatto posto.$"

FiveIsland_WaterLabyrinth_Text_YouveComeBackForTheEgg::
	.string "ôÀ\n"
	.string "タíゴ& óúÁà\l"
	.string "ÊÛ ËºŒ+だね$"

FiveIsland_WaterLabyrinth_Text_GladIMetSomeoneLikeYou::
	.string "Ho ricevuto quell'UOVO durante uno\n"
	.string "dei miei viaggi.\p"
	.string "Mi fa piacere donarlo a una\n"
	.string "persona dolce come te.$"

FiveIsland_WaterLabyrinth_Text_CuteMonRemindsMeOfDaisy::
	.string "Ah, ciao. Questo è un\n"
	.string "bellissimo {STR_VAR_2}.\p"
	.string "Vederlo mi ricorda una cara\n"
	.string "ragazza che ho incontrato\l"
	.string "in viaggio.\p"
	.string "Si chiamava MARGI, se\n"
	.string "non sbaglio.\p"
	.string "Spazzolava i POKéMON con\n"
	.string "tanto amore!$"

FiveIsland_WaterLabyrinth_Text_AlizeIntro::
	.string "Questo posto è ideale per\n"
	.string "allevare i POKéMON.$"

FiveIsland_WaterLabyrinth_Text_AlizeDefeat::
	.string "I tuoi POKéMON crescono\n"
	.string "davvero bene!$"

FiveIsland_WaterLabyrinth_Text_AlizePostBattle::
	.string "Hai talento nell'allevare i\n"
	.string "POKéMON.$"

