FuchsiaCity_Gym_Text_KogaIntro::
	.byte 0xC5, 0xC9, 0xC1, 0xBB, 0xF0, 0x00, 0xC3, 0xDC, 0xD5, 0xDC, 0xD5, 0xDC
	.byte 0xD5, 0xDC, 0xD5, 0xAB, 0xFB, 0xCF, 0xE2, 0x00, 0xE1, 0xDD, 0xD7, 0xE6
	.byte 0xE3, 0xD6, 0xE3, 0x00, 0xD7, 0xE3, 0xE1, 0xD9, 0x00, 0xE8, 0xD9, 0x00
	.byte 0xE3, 0xE7, 0xD5, 0xFE, 0xE7, 0xDA, 0xDD, 0xD8, 0xD5, 0xE6, 0xE1, 0xDD
	.byte 0xAC, 0xFB, 0xBC, 0xD9, 0xE2, 0xD9, 0xAB, 0x00, 0xCE, 0xB4, 0xDD, 0xE2
	.byte 0xE7, 0xD9, 0xDB, 0xE2, 0xD9, 0xE6, 0x22, 0x00, 0xD7, 0xE3, 0xE7, 0xB4
	.byte 0x1A, 0x00, 0xE0, 0xD5, 0x00, 0xE4, 0xD5, 0xE9, 0xE6, 0xD5, 0xB8, 0xFE
	.byte 0xE7, 0xE3, 0xE2, 0xE3, 0x00, 0xE9, 0xE2, 0x00, 0xE1, 0xD5, 0xD9, 0xE7
	.byte 0xE8, 0xE6, 0xE3, 0x00, 0xE2, 0xDD, 0xE2, 0xDE, 0xD5, 0xAB, 0xFB, 0xCA
	.byte 0xE6, 0xE3, 0xEA, 0xD9, 0xE6, 0xD5, 0xDD, 0x00, 0xE0, 0xD5, 0x00, 0xDA
	.byte 0xE3, 0xE6, 0xEE, 0xD5, 0x00, 0xE8, 0xD9, 0xE6, 0xE6, 0xE3, 0xE6, 0xDD
	.byte 0xEE, 0xEE, 0xD5, 0xE2, 0xE8, 0xD9, 0x00, 0xD8, 0xD9, 0xDD, 0xFE, 0xCA
	.byte 0xC9, 0xC5, 0x1B, 0xC7, 0xC9, 0xC8, 0x00, 0xD8, 0xDD, 0x00, 0xE8, 0xDD
	.byte 0xE4, 0xE3, 0x00, 0xD0, 0xBF, 0xC6, 0xBF, 0xC8, 0xC9, 0xAB, 0xFC, 0x0B
	.byte 0x56, 0x01, 0xFF

FuchsiaCity_Gym_Text_KogaDefeat::
	.string "Hai provato quanto vali!\p"
	.string "Ti conferisco la MEDAGLIA ANIMA!$"

FuchsiaCity_Gym_Text_KogaPostBattle::
	.string "Se colpiti da TOSSINA, i POKéMON\n"
	.string "soffriranno sempre più durante la\l"
	.string "lotta!\p"
	.string "È lo spauracchio degli avversari!$"

FuchsiaCity_Gym_Text_KogaExplainSoulBadge::
	.string "Ora che hai la MEDAGLIA ANIMA, la\n"
	.string "DIFESA dei tuoi POKéMON aumenterà!\p"
	.string "Potrai anche usare SURF quando non\n"
	.string "stai lottando!\p"
	.string "Ah!\n"
	.string "Prendi anche questo!$"

FuchsiaCity_Gym_Text_ReceivedTM06FromKoga::
	.string "{PLAYER} riceve\n"
	.string "la MT06!$"

FuchsiaCity_Gym_Text_KogaExplainTM06::
	.string "La MT06 contiene la TOSSINA!\p"
	.string "È una tecnica segreta che risale a\n"
	.string "più di 400 anni fa!$"

FuchsiaCity_Gym_Text_MakeSpaceForThis::
	.string "Non hai abbastanza spazio!$"

FuchsiaCity_Gym_Text_KaydenIntro::
	.string "La forza non è tutto per i\n"
	.string "POKéMON!\p"
	.string "Ci vuole tattica!\p"
	.string "Ti insegnerò come la strategia può\n"
	.string "vincere sulla forza bruta!$"

FuchsiaCity_Gym_Text_KaydenDefeat::
	.string "Cosa?\n"
	.string "Straordinario!$"

FuchsiaCity_Gym_Text_KaydenPostBattle::
	.string "Unisci la forza all'intelligenza?\n"
	.string "Buona tattica!$"

FuchsiaCity_Gym_Text_KirkIntro::
	.string "Sono diventato membro di questa\n"
	.string "PALESTRA perché volevo\l"
	.string "diventare un ninja!$"

FuchsiaCity_Gym_Text_KirkDefeat::
	.string "Puah! Sono esausto!$"

FuchsiaCity_Gym_Text_KirkPostBattle::
	.string "Continuerò a seguire gli\n"
	.string "insegnamenti di KOGA,\l"
	.string "il mio maestro ninja!$"

FuchsiaCity_Gym_Text_NateIntro::
	.string "Vediamo se batti le mie tecniche\n"
	.string "speciali!$"

FuchsiaCity_Gym_Text_NateDefeat::
	.string "Mi hai ingannato!$"

FuchsiaCity_Gym_Text_NatePostBattle::
	.string "Mi piacciono le tecniche del sonno\n"
	.string "e del veleno perché durano oltre\l"
	.string "la lotta!$"

FuchsiaCity_Gym_Text_PhilIntro::
	.string "Fermati lì!\p"
	.string "Hai visto i nostri muri invisibili?\n"
	.string "Ops, scusa la contraddizione.$"

FuchsiaCity_Gym_Text_PhilDefeat::
	.string "Wow!\n"
	.string "Mica male!$"

FuchsiaCity_Gym_Text_PhilPostBattle::
	.string "Impressionante!\n"
	.string "Ti do un consiglio…\p"
	.string "Cerca le fessure nel muro\n"
	.string "invisibile!$"

FuchsiaCity_Gym_Text_EdgarIntro::
	.string "Studio le tecniche ninja con il\n"
	.string "maestro KOGA!\p"
	.string "I ninja usano da sempre gli\n"
	.string "animali!$"

FuchsiaCity_Gym_Text_EdgarDefeat::
	.string "Ahiaaa!$"

FuchsiaCity_Gym_Text_EdgarPostBattle::
	.string "Ho ancora molto da imparare!$"

FuchsiaCity_Gym_Text_ShawnIntro::
	.string "Il maestro KOGA discende da una\n"
	.string "grande famiglia di ninja!\p"
	.string "E tu da dove discendi?$"

FuchsiaCity_Gym_Text_ShawnDefeat::
	.string "Mi hai sconfitto.$"

FuchsiaCity_Gym_Text_ShawnPostBattle::
	.string "Dove c'è luce c'è anche ombra!\p"
	.string "Preferisci la luce o l'ombra?$"

FuchsiaCity_Gym_Text_GymGuyAdvice::
	.string "Ehi!\n"
	.string "Aspirante CAMPIONE!\p"
	.string "La PALESTRA di FUCSIAPOLI è piena\n"
	.string "di muri invisibili!\p"
	.string "KOGA può sembrare vicino, ma la\n"
	.string "via è sbarrata!\p"
	.string "Trova le fessure nel muro per\n"
	.string "raggiungerlo!$"

FuchsiaCity_Gym_Text_GymGuyPostVictory::
	.string "È incredibile quanto terribili\n"
	.string "possano essere i ninja!$"

FuchsiaCity_Gym_Text_GymStatue::
	.string "CAPOPALESTRA di FUCSIAPOLI:\n"
	.string "KOGA\p"
	.string "ALLENATORI VINCENTI:\n"
	.string "{RIVAL}$"

FuchsiaCity_Gym_Text_GymStatuePlayerWon::
	.string "CAPOPALESTRA di FUCSIAPOLI:\n"
	.string "KOGA\p"
	.string "ALLENATORI VINCENTI:\n"
	.string "{RIVAL}, {PLAYER}$"

