VermilionCity_House1_Text_ImFishingGuruDoYouLikeToFish::
	.string "Sono il GURU PESCATORE!\p"
	.string "Adoooro pescare!\p"
	.string "E a te piace la pesca?$"

VermilionCity_House1_Text_TakeThisAndFish::
	.string "Ottimo!\n"
	.string "Mi piace il tuo stile!\p"
	.string "Prendi questo e pesca, coraggio!$"

VermilionCity_House1_Text_ReceivedOldRodFromFishingGuru::
	.string "{PLAYER} riceve\n"
	.string "l'AMO VECCHIO!$"

VermilionCity_House1_Text_FishingIsAWayOfLife::
	.string "La pesca è uno stile di vita!\p"
	.string "Dai fiumi al mare, pesca il pesce\n"
	.string "più grosso!$"

VermilionCity_House1_Text_OhThatsSoDisappointing::
	.string "Oh!…\n"
	.string "Ma che delusione…$"

VermilionCity_House1_Text_HowAreTheFishBiting::
	.string "Salve, {PLAYER}!\p"
	.string "Come va?\n"
	.string "Abboccano i pesci?$"

VermilionCity_House1_Text_NoRoomForNiceGift::
	.string "Oh no!\p"
	.string "Avevo un regalo per te, ma tu non\n"
	.string "hai più spazio!$"

