SSAnne_1F_Room6_Text_TakeAShortRest::
	.string "Tu e la tua squadra avete\n"
	.string "l'aspetto stanco. Volete fare un\l"
	.string "riposino?$"

SSAnne_1F_Room6_Text_GladEveryoneIsRefreshed::
	.string "Vedo che tu e la tua squadra\n"
	.string "siete in piena forma, ora!$"

SSAnne_1F_Room6_Text_SorryYouLookLikeMyBrother::
	.string "OK, scusa se mi sono permessa…\n"
	.string "…È che mi ricordi mio fratello.$"

SSAnne_1F_Room6_Text_SorryYouLookLikeMySister::
	.string "OK, scusa se mi sono permessa…\n"
	.string "…È che mi ricordi mia sorella.$"

