Route4_PokemonCenter_1F_Text_CanHaveSixMonsWithYou::
	.string "Ho 6 POKé BALL nella cintura…\p"
	.string "Dovrebbero bastare: al massimo si\n"
	.string "possono avere 6 POKéMON in\l"
	.string "squadra!$"

Route4_PokemonCenter_1F_Text_TeamRocketAttacksCerulean::
	.string "TEAM ROCKET attacca i cittadini di\n"
	.string "CELESTOPOLI…\p"
	.string "TEAM ROCKET è sempre in prima\n"
	.string "pagina!$"

Route4_PokemonCenter_1F_Text_LaddieBuyMagikarpForJust500::
	.string "Ehilà, ciao ragazzino!\n"
	.string "Avrei un'offerta esclusiva per te!\p"
	.string "Ti do un MAGIKARP bello grasso per\n"
	.string "soli ¥500! Che ne dici?$"

Route4_PokemonCenter_1F_Text_SweetieBuyMagikarpForJust500::
	.string "Ehilà, ciao ragazzina!\n"
	.string "Avrei un'offerta esclusiva per te!\p"
	.string "Ti do un MAGIKARP bello grasso per\n"
	.string "soli ¥500! Che ne dici?$"

Route4_PokemonCenter_1F_Text_PaidOutrageouslyForMagikarp::
	.string "{PLAYER} ha acquistato MAGIKARP al\n"
	.string "prezzo esorbitante di ¥500!$"

Route4_PokemonCenter_1F_Text_OnlyDoingThisAsFavorToYou::
	.string "No? Stavo solo cercando di farti\n"
	.string "un favore!$"

Route4_PokemonCenter_1F_Text_NoRoomForMorePokemon::
	.string "Pare che non ci sia più spazio\n"
	.string "per nessun altro POKéMON.$"

Route4_PokemonCenter_1F_Text_YoullNeedMoreMoney::
	.string "Ti ci vogliono più soldi!$"

Route4_PokemonCenter_1F_Text_IDontGiveRefunds::
	.string "UOMO: La merce non si cambia!$"

Route4_PokemonCenter_1F_Text_ShouldStoreMonsUsingPC::
	.string "Se hai troppi POKéMON, riponili\n"
	.string "nel PC!$"

Route4_PokemonCenter_1F_Text_ItsANewspaper::
	.string "È un giornale!$"

