SSAnne_CaptainsOffice_Text_CaptainIFeelSeasick::
	.string "CAPITANO: Mi sento uno straccio!\n"
	.string "Oh!\l"
	.string "Il mal di mare!$"

SSAnne_CaptainsOffice_Text_RubbedCaptainsBack::
	.string "{PLAYER} massaggia la schiena al\n"
	.string "CAPITANO!\p"
	.string "Scratch…\n"
	.string "Scratch…$"

SSAnne_CaptainsOffice_Text_ThankYouHaveHMForCut::
	.string "CAPITANO: Ah!!! Grazie!\n"
	.string "Mi sento molto meglio!!!\p"
	.string "Vuoi vedere TAGLIO, la mia\n"
	.string "tecnica segreta?\p"
	.string "Te la potrei far vedere se non\n"
	.string "stessi così male!\p"
	.string "Ecco! Prendi questa!\p"
	.string "È una MACCHINA NASCOSTA.\p"
	.string "Insegna TAGLIO ai tuoi POKéMON:\n"
	.string "ti sarà molto utile, vedrai!$"

SSAnne_CaptainsOffice_Text_ObtainedHM01FromCaptain::
	.string "{PLAYER} riceve\n"
	.string "la MN01!$"

SSAnne_CaptainsOffice_Text_ExplainCut::
	.string "Con TAGLIO si possono abbattere\n"
	.string "piccoli alberi.\p"
	.string "Provalo su qualche pianta ad\n"
	.string "ARANCIOPOLI!$"

SSAnne_CaptainsOffice_Text_SSAnneWillSetSailSoon::
	.string "CAPITANO: Geniale!\p"
	.string "Non ho più il mal di mare!\n"
	.string "È ora di partire!\p"
	.string "La M/N ANNA salpa tra poco!\p"
	.string "Addio!\n"
	.string "Ci rivedremo ad ARANCIOPOLI!$"

SSAnne_CaptainsOffice_Text_YouHaveNoRoomForThis::
	.string "Non hai più spazio per questo!$"

SSAnne_CaptainsOffice_Text_YuckShouldntHaveLooked::
	.string "Puah!\n"
	.string "Non avrei dovuto guardare!$"

SSAnne_CaptainsOffice_Text_HowToConquerSeasickness::
	.string "Come combattere il mal di mare…\n"
	.string "Il CAPITANO sta leggendo questo!$"

