PalletTown_RivalsHouse_Text_HiBrothersAtLab::
	.string "MARGI: Ciao {PLAYER}!\p"
	.string "Mio fratello {RIVAL} è al\n"
	.string "LABORATORIO del nonno.$"

PalletTown_RivalsHouse_Text_HeardYouBattledRival::
	.string "MARGI: {PLAYER}, ho sentito che\n"
	.string "hai lottato contro {RIVAL}.\p"
	.string "Peccato che non vi ho visto\n"
	.string "combattere!$"

PalletTown_RivalsHouse_Text_ErrandForGrandpaThisWillHelp::
	.string "Il nonno ti ha chiesto di fargli un\n"
	.string "favore? Tieni, ti sarà d'aiuto!$"

PalletTown_RivalsHouse_Text_ReceivedTownMapFromDaisy::
	.string "{PLAYER} riceve la\n"
	.string "MAPPA CITTÀ.$"

PalletTown_RivalsHouse_Text_DontHaveSpaceForThis::
	.string "Ti porti troppe cose addosso!$"

PalletTown_RivalsHouse_Text_ExplainTownMap::
	.string "Usa la MAPPA CITTÀ per\n"
	.string "vedere dove sei.$"

PalletTown_RivalsHouse_Text_PleaseGiveMonsRest::
	.string "MARGI: I POKéMON, come gli uomini,\n"
	.string "sono esseri viventi.\p"
	.string "Quando sono stanchi, bisogna farli\n"
	.string "riposare.$"

PalletTown_RivalsHouse_Text_ItsBigMapOfKanto::
	.string "È una mappa enorme e utile!$"

PalletTown_RivalsHouse_Text_ShelvesCrammedFullOfBooks::
	.string "È pieno zeppo di libri POKéMON!$"

PalletTown_RivalsHouse_Text_LikeMeToGroomMon::
	.string "MARGI: Ciao, capiti a fagiolo: sto\n"
	.string "facendo il tè.\p"
	.string "Vuoi favorire?\p"
	.string "I tuoi POKéMON sono stanchi.\n"
	.string "Vuoi che te ne spazzoli uno?$"

PalletTown_RivalsHouse_Text_DontNeedAnyGrooming::
	.string "MARGI: Non vuoi che te ne spazzoli\n"
	.string "uno? OK, beviamo soltanto.$"

PalletTown_RivalsHouse_Text_GroomWhichOne::
	.string "MARGI: Quale vuoi far spazzolare?$"

PalletTown_RivalsHouse_Text_LookingNiceInNoTime::
	.string "MARGI: In un minuto diventerà\n"
	.string "splendido.$"

PalletTown_RivalsHouse_Text_ThereYouGoAllDone::
	.string "{FONT_NORMAL}{STR_VAR_1} ha un aspetto felice.\p"
	.string "{FONT_FEMALE}MARGI: Ecco qui, ho finito!\n"
	.string "È bello, non credi?\p"
	.string "È un POKéMON così carino!$"

PalletTown_RivalsHouse_Text_CantGroomAnEgg::
	.string "Mi spiace, ma non posso proprio\n"
	.string "spazzolare un UOVO!$"

PalletTown_RivalsHouse_Text_MayISeeFirstMon::
	.string "MARGI: Se allevi i tuoi POKéMON\n"
	.string "con amore, ti vorranno bene.\p"
	.string "Per esempio, {PLAYER}, posso vedere\n"
	.string "il tuo primo POKéMON?$"

PalletTown_RivalsHouse_Text_CouldntLoveYouMore::
	.string "Ti vuole un bene enorme!\p"
	.string "Non potrebbe esserti più\n"
	.string "affezionato di così!\p"
	.string "Il tuo POKéMON è al settimo\n"
	.string "cielo!$"

PalletTown_RivalsHouse_Text_ItLooksVeryHappy::
	.string "È molto felice!\p"
	.string "Vorrei che {RIVAL} lo vedesse,\n"
	.string "così imparerebbe qualcosa.$"

PalletTown_RivalsHouse_Text_ItsQuiteFriendly::
	.string "Questo POKéMON ti è amico.\n"
	.string "Continua a trattarlo bene!$"

PalletTown_RivalsHouse_Text_ItsWarmingUpToYou::
	.string "Questo POKéMON non si\n"
	.string "fida ancora molto di te.\p"
	.string "Il vostro rapporto deve\n"
	.string "ancora migliorare.$"

PalletTown_RivalsHouse_Text_NotFamiliarWithYouYet::
	.string "Questo POKéMON non si\n"
	.string "fida ancora di te.\p"
	.string "Appena li catturi, i POKéMON\n"
	.string "sono piuttosto diffidenti.$"

PalletTown_RivalsHouse_Text_DontLikeWayItGlaresAtYou::
	.string "{PLAYER}, non mi piace il modo\n"
	.string "in cui ti guarda.\p"
	.string "Cerca di trattarlo un po' meglio.$"

PalletTown_RivalsHouse_Text_WhyWouldMonHateYouSoMuch::
	.string "È un po' difficile… come dire…\p"
	.string "Questo POKéMON ti detesta proprio!\n"
	.string "Non è imbarazzante?$"

PalletTown_RivalsHouse_Text_LovelyAndSweetClefairy::
	.string "Il tenero e dolce\n"
	.string "CLEFAIRY.$"

