SilphCo_8F_Text_WonderIfSilphIsFinished::
	.string "Chissà se per la SILPH è finita.$"

SilphCo_8F_Text_ThanksForSavingUs::
	.string "Grazie per averci salvato!$"

SilphCo_8F_Text_Grunt1Intro::
	.string "Non potrai andare oltre!$"

SilphCo_8F_Text_Grunt1Defeat::
	.string "Non sono stato abbastanza\n"
	.string "grintoso!$"

SilphCo_8F_Text_Grunt1PostBattle::
	.string "Gira i tacchi o chiamo rinforzi!$"

SilphCo_8F_Text_ParkerIntro::
	.string "Ci stai dando un sacco di problemi!$"

SilphCo_8F_Text_ParkerDefeat::
	.string "Cosa?\n"
	.string "Ho perso?$"

SilphCo_8F_Text_ParkerPostBattle::
	.string "Cosa pensi della SILPH?\n"
	.string "Un vero labirinto, eh?$"

SilphCo_8F_Text_Grunt2Intro::
	.string "Sono uno dei 4 FRATELLI ROCKET!$"

SilphCo_8F_Text_Grunt2Defeat::
	.string "Che botta, fratelli miei!$"

SilphCo_8F_Text_Grunt2PostBattle::
	.string "Ti lascio nelle mani dei miei\n"
	.string "fratelli!$"

SilphCo_8F_Text_FloorSign::
	.string "DIREZIONE della SILPH SpA\n"
	.string "7ºP$"

SilphCo_8F_Text_ToRocketBossMonsAreTools::
	.string "Il CAPO di TEAM ROCKET\n"
	.string "è orribilmente crudele!\p"
	.string "Per lui, i POKéMON sono\n"
	.string "solo strumenti.\p"
	.string "Se quel furfante si impossessasse\n"
	.string "dell'azienda, sarebbe tremendo…$"

