SSAnne_2F_Room4_Text_LamarIntro::
	.string "Cosa preferisci?\n"
	.string "Un POKéMON forte o uno raro?$"

SSAnne_2F_Room4_Text_LamarDefeat::
	.string "Tanto di cappello!$"

SSAnne_2F_Room4_Text_LamarPostBattle::
	.string "Io preferisco quelli forti e rari!$"

SSAnne_2F_Room4_Text_DawnIntro::
	.string "Non mi pare di averti visto alla\n"
	.string "festa.$"

SSAnne_2F_Room4_Text_DawnDefeat::
	.string "Vacci piano!$"

SSAnne_2F_Room4_Text_DawnPostBattle::
	.string "Oh, i tuoi POKéMON sono fantastici!$"

