SafariZone_East_Text_KeepAnyItemFoundOnSafari::
	.string "Puoi tenere tutti gli strumenti che\n"
	.string "trovi per terra.\p"
	.string "Ma se ti soffermi troppo a\n"
	.string "cercarli, finirà il tempo!$"

SafariZone_East_Text_PrizeInDeepestPartOfSafariZone::
	.string "Addentrati nella parte più\n"
	.string "interna della ZONA SAFARI\l"
	.string "e vincerai un premio!$"

SafariZone_East_Text_MyEeveeEvolvedIntoFlareon::
	.string "Il mio EEVEE si è evoluto in\n"
	.string "FLAREON!\p"
	.string "Ma l'EEVEE di un amico si è\n"
	.string "evoluto in VAPOREON! Perché?$"

