OneIsland_KindleRoad_Text_MariaIntro::
	.string "Che bella giornata!\n"
	.string "Perfetta per una lotta!$"

OneIsland_KindleRoad_Text_MariaDefeat::
	.string "No, ti prego!$"

OneIsland_KindleRoad_Text_MariaPostBattle::
	.string "Non spruzzarmi l'acqua in faccia!$"

OneIsland_KindleRoad_Text_AbigailIntro::
	.string "Sento che sto per scottarmi!\n"
	.string "Userò la protezione solare!$"

OneIsland_KindleRoad_Text_AbigailDefeat::
	.string "Sei terribile!$"

OneIsland_KindleRoad_Text_AbigailPostBattle::
	.string "Mi piace il tuo berretto, dovrei\n"
	.string "comprarne uno così anch'io.$"

OneIsland_KindleRoad_Text_FinnIntro::
	.string "Visto com'è imperioso da qui\n"
	.string "il MONTE BRACE?$"

OneIsland_KindleRoad_Text_FinnDefeat::
	.string "Sai che sei proprio forte?$"

OneIsland_KindleRoad_Text_FinnPostBattle::
	.string "Il cielo è stupendo da queste\n"
	.string "parti.$"

OneIsland_KindleRoad_Text_GarrettIntro::
	.string "Non dirmi che ho interrotto la mia\n"
	.string "nuotata soltanto per sfidarti!$"

OneIsland_KindleRoad_Text_GarrettDefeat::
	.string "Ehi, non sei così male!$"

OneIsland_KindleRoad_Text_GarrettPostBattle::
	.string "SURF è comodo, ma preferisco\n"
	.string "nuotare.$"

OneIsland_KindleRoad_Text_TommyIntro::
	.string "Aspetta! Questa volta deve aver\n"
	.string "abboccato un pesce enorme!$"

OneIsland_KindleRoad_Text_TommyDefeat::
	.string "Oggi mi vanno tutte storte.$"

OneIsland_KindleRoad_Text_TommyPostBattle::
	.string "Ho perso sia la sfida che il\n"
	.string "pesce che aveva abboccato!$"

OneIsland_KindleRoad_Text_SharonIntro::
	.string "Ti alleni un po' con me?$"

OneIsland_KindleRoad_Text_SharonDefeat::
	.string "Sei più forte, non c'è dubbio.$"

OneIsland_KindleRoad_Text_SharonPostBattle::
	.string "Hai stoffa, si vede!$"

OneIsland_KindleRoad_Text_TanyaIntro::
	.string "Mi alleno tutti i giorni con i miei\n"
	.string "POKéMON!$"

OneIsland_KindleRoad_Text_TanyaDefeat::
	.string "L'allenamento non è bastato…$"

OneIsland_KindleRoad_Text_TanyaPostBattle::
	.string "È chiaro che devo allenarmi\n"
	.string "di più!$"

OneIsland_KindleRoad_Text_SheaIntro::
	.string "Ogni giorno, prima di colazione,\n"
	.string "nuoto intorno all'isola.$"

OneIsland_KindleRoad_Text_SheaDefeat::
	.string "Gasp…\n"
	.string "Gasp…$"

OneIsland_KindleRoad_Text_SheaPostBattle::
	.string "Forse ho perso perché mi alleno\n"
	.string "troppo.$"

OneIsland_KindleRoad_Text_HughIntro::
	.string "Ti sembra di avere un abbigliamento\n"
	.string "appropriato per lottare?$"

OneIsland_KindleRoad_Text_HughDefeat::
	.string "Perché?$"

OneIsland_KindleRoad_Text_HughPostBattle::
	.string "I cultori di arti marziali curano\n"
	.string "sempre di più il proprio aspetto.$"

OneIsland_KindleRoad_Text_BryceIntro::
	.string "Tutto sembra più saporito quando\n"
	.string "ti trovi a contatto con la natura!$"

OneIsland_KindleRoad_Text_BryceDefeat::
	.string "Che peccato!$"

OneIsland_KindleRoad_Text_BrycePostBattle::
	.string "Nelle aree vulcaniche l'acqua è\n"
	.string "ricca di minerali.$"

OneIsland_KindleRoad_Text_ClaireIntro::
	.string "Ora che ho mangiato, ho proprio\n"
	.string "voglia di una bella lotta!$"

OneIsland_KindleRoad_Text_ClaireDefeat::
	.string "Che sudata!$"

OneIsland_KindleRoad_Text_ClairePostBattle::
	.string "Dopo aver lottato mi è venuta\n"
	.string "di nuovo fame!$"

OneIsland_KindleRoad_Text_KiaIntro::
	.string "KIA: Io e il mio fratellone siamo\n"
	.string "una forza!$"

OneIsland_KindleRoad_Text_KiaDefeat::
	.string "KIA: Non ci posso credere!$"

OneIsland_KindleRoad_Text_KiaPostBattle::
	.string "KIA: Non posso credere che tu\n"
	.string "sia più in gamba di mio fratello!$"

OneIsland_KindleRoad_Text_KiaNotEnoughMons::
	.string "KIA: Per lottare con noi, devi\n"
	.string "avere con te almeno due\l"
	.string "POKéMON.$"

OneIsland_KindleRoad_Text_MikIntro::
	.string "MIK: Con KIA al mio fianco,\n"
	.string "niente mi fa paura!$"

OneIsland_KindleRoad_Text_MikDefeat::
	.string "MIK: Ehi, ma questo è\n"
	.string "davvero troppo!$"

OneIsland_KindleRoad_Text_MikPostBattle::
	.string "MIK: Credevo che io e KIA,\n"
	.string "insieme, fossimo imbattibili!$"

OneIsland_KindleRoad_Text_MikNotEnoughMons::
	.string "MIK: Ehi, vuoi lottare contro\n"
	.string "di noi?\p"
	.string "Allora ritorna con almeno due\n"
	.string "POKéMON in squadra.$"

OneIsland_KindleRoad_Text_RouteSign::
	.string "Questa è la VIA VULCANICA.\p"
	.string "Per di qui si arriva al\n"
	.string "MONTE BRACE.$"

OneIsland_KindleRoad_Text_EmberSpaSign::
	.string "TERME LAVICHE\n"
	.string "Ti riscaldano il cuore!$"

