PokemonTower_4F_Text_PaulaIntro::
	.string "Uno spettro!\n"
	.string "Nooo! Guaaah!$"

PokemonTower_4F_Text_PaulaDefeat::
	.string "Dov'è lo spettro?$"

PokemonTower_4F_Text_PaulaPostBattle::
	.string "Devo aver fatto un brutto sogno…$"

PokemonTower_4F_Text_LaurelIntro::
	.string "Ti maledico!\n"
	.string "Guaaah!$"

PokemonTower_4F_Text_LaurelDefeat::
	.string "Cosa?!$"

PokemonTower_4F_Text_LaurelPostBattle::
	.string "Non sappiamo dire l'identità degli\n"
	.string "spettri!$"

PokemonTower_4F_Text_JodyIntro::
	.string "Uu Uu Uu…\n"
	.string "Ti ho beccato!$"

PokemonTower_4F_Text_JodyDefeat::
	.string "Eh?\n"
	.string "Chi? Cosa?$"

PokemonTower_4F_Text_JodyPostBattle::
	.string "Che le anime dei POKéMON riposino\n"
	.string "in pace!$"

