LavenderTown_Mart_Text_SearchingForStatRaiseItems::
	.string "Cerco strumenti che aumentino le\n"
	.string "abilità dei POKéMON durante la\l"
	.string "lotta.\p"
	.string "Finita la lotta, il loro effetto\n"
	.string "svanisce.\p"
	.string "Mi riferisco a ATTACCO X, DIFESA\n"
	.string "X, VELOCITÀ X e SPECIAL X.\p"
	.string "Sai dove posso trovarli?$"

LavenderTown_Mart_Text_DidYouBuyRevives::
	.string "Lo sai che con il REVITALIZZANTE\n"
	.string "si ricaricano i POKéMON esausti?$"

LavenderTown_Mart_Text_TrainerDuosCanChallengeYou::
	.string "A volte incontri ALLENATORI che\n"
	.string "combattono in coppia, usando due\l"
	.string "POKéMON contemporaneamente.\p"
	.string "Per sfidarli, devi mandare in campo\n"
	.string "anche tu due POKéMON insieme.$"

LavenderTown_Mart_Text_SoldNuggetFromMountainsFor5000::
	.string "こç ÀÁだ ôまÈËで\n"
	.string "Ê+çŒま& éªÁ まÏÛね!\p"
	.string "ÚÉÇßÁ Ïßóç でÒが\n"
	.string "ÂっŒú ß+Ñ 5000¥でÏŒ$"

