SaffronCity_Dojo_Text_MasterKoichiIntro::
	.string "Grrr!\p"
	.string "Sono il MAESTRO di KARATE! Sono il\n"
	.string "CAPO qui!\p"
	.string "Vuoi sfidarci?\n"
	.string "Non avremo pietà!\p"
	.string "Fuaaa!$"

SaffronCity_Dojo_Text_MasterKoichiDefeat::
	.string "Hua!\n"
	.string "Mi hai battuto!$"

SaffronCity_Dojo_Text_ChoosePrizedFightingMon::
	.string "Ebbene sì, ho perso!\p"
	.string "Ma ti supplico di non prendere il\n"
	.string "nostro emblema come trofeo!\p"
	.string "In cambio ti darò un potente\n"
	.string "POKéMON di tipo LOTTA!\p"
	.string "Scegli quello che preferisci!$"

SaffronCity_Dojo_Text_StayAndTrainWithUs::
	.string "Ehi!\n"
	.string "Allenati a karate con noi!$"

SaffronCity_Dojo_Text_MikeIntro::
	.string "Urgg!\n"
	.string "Togliti le scarpe!$"

SaffronCity_Dojo_Text_MikeDefeat::
	.string "Mi arrendo!$"

SaffronCity_Dojo_Text_MikePostBattle::
	.string "Aspetta di vedere il Maestro!\n"
	.string "Non sono niente rispetto a lui!$"

SaffronCity_Dojo_Text_HidekiIntro::
	.string "Mi dicono che sei in gamba.\n"
	.string "Allora dimostralo!$"

SaffronCity_Dojo_Text_HidekiDefeat::
	.string "Ti darei 1 punto!$"

SaffronCity_Dojo_Text_HidekiPostBattle::
	.string "Il nostro Maestro è un lottatore\n"
	.string "professionista!$"

SaffronCity_Dojo_Text_AaronIntro::
	.string "Non mi spaventa proprio niente!\p"
	.string "Mi alleno spaccando rocce!$"

SaffronCity_Dojo_Text_AaronDefeat::
	.string "Ahi!\n"
	.string "Che male!$"

SaffronCity_Dojo_Text_AaronPostBattle::
	.string "L'unica cosa che temiamo è il\n"
	.string "potere psichico!$"

SaffronCity_Dojo_Text_HitoshiIntro::
	.string "Ehi!\p"
	.string "Stai varcando il nostro DOJO\n"
	.string "KARATE!$"

SaffronCity_Dojo_Text_HitoshiDefeat::
	.string "Uff!\n"
	.string "Mi arrendo!$"

SaffronCity_Dojo_Text_HitoshiPostBattle::
	.string "Qui si allenano i lottatori più\n"
	.string "bravi del mondo.$"

SaffronCity_Dojo_Text_YouWantHitmonlee::
	.string "Vuoi HITMONLEE, il tiracalci?$"

SaffronCity_Dojo_Text_ReceivedMonFromKarateMaster::
	.string "{PLAYER} riceve\n"
	.string "{STR_VAR_1}!$"

SaffronCity_Dojo_Text_YouWantHitmonchan::
	.string "Vuoi HITMONCHAN, pugno veloce?$"

SaffronCity_Dojo_Text_ReceivedMonFromKarateMaster2::
	.byte 0xFD, 0x01, 0x1A, 0x00, 0x56, 0x77, 0x63, 0x00, 0x41, 0x02, 0x05, 0x03
	.byte 0x00, 0x06, 0x27, 0xFE, 0xFD, 0x02, 0x2D, 0x00, 0x23, 0x27, 0x50, 0x10
	.byte 0xAB, 0xFF

SaffronCity_Dojo_Text_BetterNotGetGreedy::
	.string "Meglio non essere avidi!$"

SaffronCity_Dojo_Text_EnemiesOnEverySide::
	.string "I nemici! Siamo circondati!$"

SaffronCity_Dojo_Text_GoesAroundComesAround::
	.string "Chi semina, raccoglie!$"

SaffronCity_Dojo_Text_FightingDojo::
	.string "DOJO KARATE$"

