Aide_Text_HaventCaughtEnoughMonsForItem::
	.string "Vediamo…\n"
	.string "Oh! Hai raccolto dati solo su\l"
	.string "{STR_VAR_3} specie di POKéMON!\p"
	.string "Ti servono {STR_VAR_1} specie, se vuoi\n"
	.string "{STR_VAR_2}.$"
Aide_Text_GetEnoughMonsComeBackForItem::
	.string "Oh! Allora…\p"
	.string "Quando avrai {STR_VAR_1} specie di POKéMON\n"
	.string "torna qui e ti darò {STR_VAR_2}\l"
	.string "in regalo!$"
Aide_Text_DontHaveAnyRoomForItem::
	.string "Vedo che non hai più spazio per\n"
	.string "{STR_VAR_2}!$"
