Braille_Text_Up::
	.string "Éé Àßìç$"
Braille_Text_Down::
	.string "Éé ÈÀààç$"
Braille_Text_Right::
	.string "À ÎÌàìëÀ$"
Braille_Text_Left::
	.string "À àÉéÉàìëÀ$"
Braille_Text_Cut::
	.string "ìÀÔßÉç$"
Braille_Text_ABC::
	.string "ÀÈÂ$"
Braille_Text_GHI::
	.string "ÔÒÉ$"
Braille_Text_MNO::
	.string "Ûéç$"
Braille_Text_TUV::
	.string "ìぅ=$"
Braille_Text_DEF::
	.string "ÎÌÊ$"
Braille_Text_JKL::
	.string "ÓÙß$"
Braille_Text_PQRS::
	.string "áまëà$"
Braille_Text_WXYZ::
	.string "+ぉごぐ$"
Braille_Text_Period::
	.string "わ$"
Braille_Text_Comma::
	.string "Ë$"
Braille_Text_Everything::
	.string "ìぅììç$"
Braille_Text_HasMeaning1::
	.string "ÒÀ ぅé àÌéàç$"
Braille_Text_Existence::
	.string "ßÀ =ÉìÀ$"
Braille_Text_HasMeaning2::
	.string "ÒÀ ぅé àÌéàç$"
Braille_Text_BeingAlive::
	.string "ÌààÌëÌ =É=É$"
Braille_Text_HasMeaning3::
	.string "ÒÀ ぅé àÌéàç$"
Braille_Text_HaveDreams::
	.string "àçÔéÀ Ì ぅàÀ$"
Braille_Text_UsePower::
	.string "ßÀ ìぅÀ ÊçëぐÀ$"
Braille_Text_LetTheTwo::
	.string "ßÌ ÎぅÌ$"
Braille_Text_Glittering::
	.string "áÉÌìëÌ$"
Braille_Text_Stones::
	.string "àÂÉéìÉßßÀéìÉ$"
Braille_Text_OneInRed::
	.string "ぅéÀ ëçààÀ$"
Braille_Text_OneInBlue::
	.string "ぅéÀ Èßぅ$"
Braille_Text_ConnectThe::
	.string "ìÉ ÂçßßÌÔÀéç$"
Braille_Text_Past::
	.string "Àß áÀààÀìçわ$"
Braille_Text_TwoFriends::
	.string "ÎぅÌ ÀÛÉÂÉ$"
Braille_Text_Sharing::
	.string "ぅéÌéÎç ßÌ$"
Braille_Text_PowerOpen::
	.string "ÊçëぐÌ Àáëçéç$"
Braille_Text_AWindowTo::
	.string "ぅéÀ ÊÉéÌàìëÀ$"
Braille_Text_ANewWorld::
	.string "àぅ ぅé éぅç=ç$"
Braille_Text_ThatGlows::
	.string "ÛçéÎçわ$"
Braille_Text_TheNext::
	.string "Éß áëçààÉÛç$"
Braille_Text_WorldWaits::
	.string "ÛçéÎç$"
Braille_Text_ForYou::
	.string "ìÉ ÀììÌéÎÌわ$"
