CableClub_Text_WelcomeWhichCableClubService::
	.string "Ti do il benvenuto nel CLUB VIA\n"
	.string "CAVO POKéMON.\p"
	.string "A quale dei nostri servizi vuoi\n"
	.string "accedere?$"

CableClub_Text_WhichService::
	.string "A quale dei nostri servizi vuoi\n"
	.string "accedere?$"

CableClub_Text_TradeMonsUsingLinkCable::
	.string "Puoi scambiare POKéMON con il cavo\n"
	.string "Game Link per Game Boy Advance.$"

CableClub_Text_BattleUsingLinkCable::
	.string "Puoi sfidare un amico con il cavo\n"
	.string "Game Link per Game Boy Advance.$"

@ Unused, translated in Emerald
CableClub_Text_CloseThisMenu::
	.string "おわります$"

CableClub_Text_NeedTwoMonsForDoubleBattle::
	.string "Per la LOTTA in DOPPIO devi avere\n"
	.string "almeno due POKéMON.$"

CableClub_Text_NeedTwoMonsToTrade::
	.string "Per lo scambio devi avere con te\n"
	.string "almeno due POKéMON.$"

CableClub_Text_CantTradeEnigmaBerry::
	.string "Non si possono scambiare POKéMON\n"
	.string "che tengono una BACCA{STR_VAR_1}.$"

CableClub_Text_PleaseWaitBCancel::
	.string "Attendi. Premi il pulsante B\n"
	.string "per annullare…$"

CableClub_Text_WhenAllPlayersReadyAConfirmBCancel::
	.string "Se siete tutti pronti…\n"
	.string "Puls. A: Conferma  Puls. B: Annulla$"

CableClub_Text_StartLinkWithXPlayersAConfirmBCancel::
	.string "Inizio collegamento fra {STR_VAR_1}\n"
	.string "giocatori.\l"
	.string "Puls. A: Conferma  Puls. B: Annulla$"

CableClub_Text_AwaitingLinkupBCancel::
	.string "In attesa di collegamento…\n"
	.string "… … Pulsante B: Annulla$"

@ Unused, translated in Emerald
CableClub_Text_OkayToSaveProgress::
	.string "はじめる　まえに　レポートを\n"
	.string "かきますが　よろしいですか？$"

CableClub_Text_PleaseEnter::
	.string "Entra.$"

CableClub_Text_DirectYouToYourRoom::
	.string "Ora ti accompagno alla tua sala.$"

CableClub_Text_SomeoneIsNotReadyToLink::
	.string "Qualcuno non è pronto per\n"
	.string "collegarsi.\p"
	.string "Ritornate quando siete tutti pronti.$"

CableClub_Text_LinkErrorPleaseReset::
	.string "Errore di collegamento…\n"
	.string "Spegni, riaccendi e riprova.$"

CableClub_Text_PlayersMadeDifferentSelections::
	.string "Sono state fatte selezioni\n"
	.string "differenti dai diversi giocatori.$"

CableClub_Text_PleaseVisitAgain::
	.string "Torna a trovarci.$"

CableClub_Text_IncorrectNumberOfParticipants::
	.string "Il numero di giocatori non è\n"
	.string "corretto.$"

CableClub_Text_CantSingleBattleWithXPlayers::
	.string "Non possono partecipare {STR_VAR_1} giocatori\n"
	.string "in modalità LOTTA in SINGOLO.$"

CableClub_Text_CantDoubleBattleWithXPlayers::
	.string "Non possono partecipare {STR_VAR_1} giocatori\n"
	.string "in modalità LOTTA in DOPPIO.$"

CableClub_Text_NeedFourPlayers::
	.string "A questa modalità di lotta devono\n"
	.string "partecipare quattro giocatori.$"

CableClub_Text_PleaseConfirmNumberAndRestart::
	.string "Controlla il numero di giocatori\n"
	.string "e riprova.$"

Text_TerminateLinkIfYouLeaveRoom::
	.string "Il collegamento verrà interrotto se\n"
	.string "esci dalla sala. Vuoi uscire?$"

Text_TerminateLinkConfirmation::
	.string "Interruzione del collegamento…\n"
	.string "Uscirai dalla sala. Attendi.$"

Text_TrainerTooBusyToNotice::
	.string "L’ALLENATORE è troppo impegnato…$"

Text_LookedAtPlayersTrainerCard::
	.string "Bene! Puoi vedere la SCHEDA\n"
	.string "ALLENATORE di {STR_VAR_1}!$"

Text_LookedAtPlayersTrainerCardColored::
	.string "Bene! Puoi vedere la SCHEDA\n"
	.string "ALLENATORE di {STR_VAR_1}!\p"
	.string "È una scheda {STR_VAR_2}!$"

Text_TakeSeatStartBattle::
	.string "Accomodati e diamo il via alla\n"
	.string "lotta.$"

Text_TakeSeatStartTrade::
	.string "Accomodati e diamo il via allo\n"
	.string "scambio.$"

@ Unused, leftover from RS
RecordCorner_Text_ThanksForComing::
	.string "ごりよう　ありがとう　ございました$"

CableClub_Text_TrainerCardDataOverwritten::
	.string "I dati della SCHEDA ALLENATORE\n"
	.string "verranno sovrascritti.$"

CableClub_Text_HopeToSeeYouAgain::
	.string "Spero che ripasserai!$"

CableClub_Text_NotSetUpForFarAwayRegion::
	.string "Sono spiacente!\p"
	.string "Non siamo ancora attrezzati per\n"
	.string "gli scambi con ALLENATORI di\l"
	.string "un’altra regione.$"

CableClub_Text_OtherTrainerNotReady::
	.string "L’altro ALLENATORE non è pronto.$"

CableClub_Text_YouHaveAMonThatCantBeTaken::
	.string "Hai almeno un POKéMON che non può\n"
	.string "essere accettato.$"

CableClub_Text_AdapterNotConnected::
	.string "L’adattatore wireless per Game Boy\n"
	.string "Advance non risulta collegato.$"

CableClub_Text_ParticipantsStepUpToCounter::
	.string "I partecipanti devono presentarsi \n"
	.string "al banco di accettazione.$"

@ Unused, translated in Emerald
CableClub_Text_Hello::
	.string "こんにちは！$"

@ Unused, translated in Emerald
CableClub_Text_PleaseWait::
	.string "しょうしょう　おまちください$"

CableClub_Text_YouMayTradeHere::
	.string "Qui puoi scambiare i tuoi POKéMON\n"
	.string "con quelli di un amico.$"

CableClub_Text_YouMayBattleHere::
	.string "Qui puoi sfidare i tuoi amici.$"

CableClub_Text_CanMakeBerryPowder::
	.string "Da 2 a 5 ALLENATORI possono\n"
	.string "creare FARINA di BACCHE.$"

@ Unused, Record Mix nopped
CableClub_Text_CanMixRecords::
	.string "ワイヤレス　クラブでの\n"
	.string "あそびかたを　せつめいします$"

CableClub_Text_CancelSelectedItem::
	.string "Annulla la selezione nel MENU.$"

@ Unused, translated in Emerald
CableClub_Text_WhichBattleMode::
	.string "どちらの　しょうぶに　しますか？$"

@ Unused, translated in Emerald
CableClub_Text_ReturnsToPreviousStep::
	.string "ひとつ　まえに　もどります$"

CableClub_Text_NeedBerryForBerryCrush::
	.string "Per usare il MACINABACCHE\n"
	.string "devi avere almeno una BACCA.$"

CableClub_Text_NeedTwoMonsForUnionRoom::
	.string "Per accedere alla SALA CONTATTO\n"
	.string "devi avere almeno due POKéMON.$"

CableClub_Text_NoEnigmaBerryInUnionRoom::
	.string "Nella SALA CONTATTO non sono\n"
	.string "ammessi POKéMON che tengono\l"
	.string "una BACCA{STR_VAR_1}.$"

CableClub_Text_UnionRoomAdapterNotConnected::
	.string "Questa è la SALA CONTATTO del\n"
	.string "CLUB WIRELESS POKéMON.\p"
	.string "Purtroppo, l’adattatore wireless\n"
	.string "per GBA non risulta collegato.\p"
	.string "Torna più tardi.$"

@ Unused, translated in Emerald
CableClub_Text_OhExcuseMe::
	.string "あ‥‥\n"
	.string "おきゃくさま！$"

Text_PlayerIsPlayingRightNowGoForIt::
	.string "Sembra che {STR_VAR_1} voglia\n"
	.string "giocare.\l"
	.string "Dai, cosa aspetti!$"

Text_DescribeWhichGame::
	.string "Se vuoi posso spiegarti le\n"
	.string "regole.\p"
	.string "Quale gioco vuoi che ti\n"
	.string "descriva?$"

Text_PokemonJumpInfo::
	.string "POKéSALTI\p"
	.string "Fai saltare la corda al POKéMON\n"
	.string "premendo il pulsante A.\p"
	.string "Possono partecipare solo POKéMON\n"
	.string "non più alti di 70 cm (all’incirca).\p"
	.string "I POKéMON che sanno solo scavare,\n"
	.string "nuotare o volare non sono\p"
	.string "abili nel salto, quindi non possono\n"
	.string "partecipare.\p"
	.string "Se tutti saltano al momento \n"
	.string "giusto, succedono belle cose!$"

Text_DodrioBerryPickingInfo::
	.string "DODRIO PIGLIABACCHE\p"
	.string "Sposta le tre teste di DODRIO per\n"
	.string "raccogliere le BACCHE che cadono.\p"
	.string "Premi la pulsantiera di comando {PLUS}\n"
	.string "a destra, in alto e a sinistra.\p"
	.string "In questo modo, controlli le teste\n"
	.string "di DODRIO.\p"
	.string "Chiaramente, devi avere un DODRIO\n"
	.string "in squadra per partecipare.$"

Text_TalkToManToPlay::
	.string "Se vuoi cimentarti in uno dei\n"
	.string "giochi, parla con il signore qui\l"
	.string "di fianco.$"

Text_WelcomeCanYouWait::
	.string "Ciao!\n"
	.string "Con il Sistema di Comunicazione\l"
	.string "Wireless puoi giocare a minigiochi.\p"
	.string "Puoi attendere un attimo?$"

CableClub_Text_ComeAgain::
	.string "Va bene! Torna a trovarmi!$"

Text_AdapterNotConnectedMinigame::
	.string "L’adattatore wireless per GBA non è\n"
	.string "collegato.\p"
	.string "Torna dopo averlo connesso!$"

Text_PlayWhichGame::
	.string "Va bene. A quale minigioco\n"
	.string "vuoi giocare?$"

Text_EnterWhichPokemon::
	.string "Quale POKéMON vuoi iscrivere?$"

Text_AllGoodToGo::
	.string "Bene, è tutto pronto!\n"
	.string "Fatti valere, mi raccomando!$"

@ Unused, translated in Emerald
Text_LeavingDoComeAgain::
	.string "きょうは　けえるのか？\n"
	.string "またこいよ！$"

EventScript_ExplainPokemonJumpRequirements::
	.string "Non hai nessun POKéMON che\n"
	.string "possa partecipare.\p"
	.string "Vuoi che ti spieghi quali POKéMON\n"
	.string "si possono iscrivere?$"

Text_ShortJumpingPokemonAllowed::
	.string "Il gioco POKéSALTI è riservato a\n"
	.string "POKéMON di altezza non superiore\l"
	.string "a 70 cm (all’incirca).\p"
	.string "Non puoi iscrivere i POKéMON che\n"
	.string "non sanno saltare.\p"
	.string "Intendo dire, i POKéMON che sanno\n"
	.string "solo nuotare, scavare o volare.\p"
	.string "Tutto qui!$"

Text_OnlyDodrioAllowed::
	.string "DODRIO PIGLIABACCHE…\n"
	.string "Beh, già dal nome si capisce, no?\p"
	.string "Per partecipare devi avere un\n"
	.string "DODRIO.$"

@ Unused, translated in Emerald
Text_RetryFromStartPlease::
	.string "もういちど　はじめから\n"
	.string "やりなおして　みて　くれ$"

CableClub_Text_WelcomeWhichDirectCornerRoom::
	.string "Questa è la SALA DIRETTA del\n"
	.string "CLUB WIRELESS POKéMON.\p"
	.string "Qui puoi interagire direttamente\n"
	.string "con i tuoi amici.\p"
	.string "A quale servizio vuoi accedere?$"

CableClub_Text_TradePokemon::
	.string "Vuoi scambiare POKéMON?$"

CableClub_Text_PlayWhichBattleMode::
	.string "Quale modalità di lotta scegli?$"

CableClub_Text_UseBerryCrush::
	.string "Vuoi usare il MACINABACCHE?$"

CableClub_Text_ExplainBattleModes::
	.string "Esistono tre modalità di lotta.\p"
	.string "La LOTTA in SINGOLO è per due\n"
	.string "ALLENATORI con uno o più POKéMON\l"
	.string "ciascuno.\p"
	.string "Ogni ALLENATORE può mandare in\n"
	.string "campo un POKéMON alla volta.\p"
	.string "La LOTTA in DOPPIO è per due\n"
	.string "ALLENATORI con due o più POKéMON\l"
	.string "ciascuno.\p"
	.string "Ogni ALLENATORE può mandare in\n"
	.string "campo due POKéMON alla volta.\p"
	.string "La LOTTA MULTIPLA è per quattro\n"
	.string "ALLENATORI con uno o più POKéMON\l"
	.string "ciascuno.\p"
	.string "Ogni ALLENATORE può mandare in\n"
	.string "campo un POKéMON alla volta.$"

CableClub_Text_ChooseGroupLeaderOfTwo::
	.string "Decidete chi di voi due è il\n"
	.string "CAPOGRUPPO.\p"
	.string "Poi, l’altro giocatore selezionerà\n"
	.string "PARTECIPA.$"

CableClub_Text_ChooseGroupLeaderOfFour::
	.string "Decidete chi di voi quattro è il\n"
	.string "CAPOGRUPPO.\p"
	.string "Poi, gli altri giocatori\n"
	.string "selezioneranno PARTECIPA.$"

CableClub_Text_ChooseGroupLeader::
	.string "Decidete chi di voi è il\n"
	.string "CAPOGRUPPO.\p"
	.string "Poi, gli altri giocatori\n"
	.string "selezioneranno PARTECIPA.$"

CableClub_Text_WelcomeUnionRoomEnter::
	.string "Ti do il benvenuto alla SALA\n"
	.string "CONTATTO del CLUB WIRELESS\l"
	.string "POKéMON.\p"
	.string "Qui puoi interagire direttamente con\n"
	.string "altri ALLENATORI, che potresti\l"
	.string "persino non conoscere.\p"
	.string "Vuoi entrare nella SALA?$"

CableClub_Text_UnionRoomInfo::
	.string "Nella SALA CONTATTO incontrerai gli\n"
	.string "ALLENATORI nelle vicinanze che,\l"
	.string "come te, sono entrati nella SALA.\p"
	.string "Qui puoi fare molte cose.\p"
	.string "Puoi lottare, iscrivendo due\n"
	.string "POKéMON di livello non\l"
	.string "superiore al 30.\p"
	.string "Puoi partecipare ad una\n"
	.string "conversazione tra un minimo di due\l"
	.string "ed un massimo di cinque persone.\p"
	.string "Oppure, puoi registrare un POKéMON\n"
	.string "per lo scambio.\p"
	.string "Vuoi entrare nella SALA?$"

CableClub_Text_EnjoyUnionRoom::
	.string "Buon divertimento nella SALA\n"
	.string "CONTATTO!$"

CableClub_Text_FirstTimeRightThisWay::
	.string "Ciao, mi chiamo MILENA.\p"
	.string "È la prima volta che ti vedo qui.\p"
	.string "Ora ti spiego come funziona il\n"
	.string "Sistema di Comunicazione Wireless.\p"
	.string "Prima di tutto, voglio mostrarti il\n"
	.string "primo piano del CENTRO POKéMON.\p"
	.string "Da questa parte, prego.$"

CableClub_Text_ExplainWirelessClubFirstTime::
	.string "Al primo piano ci sono due stanze.\n"
	.string "A sinistra c’è la SALA CONTATTO.\p"
	.string "Lì puoi collegarti con gli\n"
	.string "ALLENATORI nelle vicinanze che,\l"
	.string "come te, sono entrati nella SALA.\p"
	.string "Potrai parlare con loro, oppure\n"
	.string "lottare o scambiare POKéMON.\p"
	.string "A destra, invece, c’è la SALA\n"
	.string "DIRETTA.\p"
	.string "Lì puoi lottare o scambiare i\n"
	.string "POKéMON con i tuoi amici.\p"
	.string "Se non è collegato l’adattatore\n"
	.string "wireless per GBA, puoi sempre\l"
	.string "usare il cavo Game Link per GBA.\p"
	.string "Il cavo Game Link per GBA può\n"
	.string "essere usato solo nella SALA\l"
	.string "DIRETTA, però.\p"
	.string "Buon divertimento con il Sistema\n"
	.string "di Comunicazione Wireless.$"

CableClub_Text_AskAboutLinking::
	.string "Ciao, {PLAYER}!\p"
	.string "Sono io, MILENA, l’addetta\n"
	.string "del primo piano.\p"
	.string "Volevi chiedermi qualcosa\n"
	.string "sul collegamento?$"

CableClub_Text_ExplainWirelessClub::
	.string "Ora ti spiego come funziona il\n"
	.string "CLUB WIRELESS POKéMON.\p"
	.string "Qui al primo piano si può\n"
	.string "accedere a due stanze.\p"
	.string "Quella a sinistra è la SALA\n"
	.string "CONTATTO.\p"
	.string "Da lì puoi collegarti con altri\n"
	.string "ALLENATORI che si trovano\l"
	.string "nella SALA.\p"
	.string "Con loro potrai chattare, lottare\n"
	.string "o scambiare POKéMON.\p"
	.string "A destra, invece, c’è la SALA\n"
	.string "DIRETTA.\p"
	.string "Lì puoi lottare o scambiare i\n"
	.string "POKéMON con i tuoi amici.\p"
	.string "Potrebbe capitarti di non trovare\n"
	.string "i tuoi amici in una sala, anche se\l"
	.string "sono collegati.\p"
	.string "In quel caso, le console\n"
	.string "potrebbero essere troppo\l"
	.string "distanti fra loro.\p"
	.string "Prova ad avvicinarle.\p"
	.string "Se non è collegato l’adattatore\n"
	.string "wireless per GBA, puoi sempre\l"
	.string "usare il cavo Game Link per GBA.\p"
	.string "Il cavo Game Link per GBA può\n"
	.string "essere usato solo nella SALA\l"
	.string "DIRETTA, però.\p"
	.string "Buon divertimento con il Sistema\n"
	.string "di Comunicazione Wireless.$"

CableClub_Text_HopeYouEnjoyWirelessSystem::
	.string "Buon divertimento con il Sistema\n"
	.string "di Comunicazione Wireless.$"
