DayCare_Text_ImDaycareManSpeakToMyWife::
	.string "Sono il PADRONE della PENSIONE\n"
	.string "POKéMON.\p"
	.string "Aiutiamo gli ALLENATORI a prendersi\n"
	.string "cura dei loro preziosi amici.\p"
	.string "Se vuoi che alleviamo anche i tuoi\n"
	.string "POKéMON, rivolgiti a mia moglie.$"
DayCare_Text_DoYouWantEgg::
	.string "Ah, sei tu!\p"
	.string "Stavamo allevando i tuoi POKéMON\n"
	.string "e, mamma mia, che sorpresa!!!\p"
	.string "Hanno avuto un UOVO!\p"
	.string "Non sappiamo come sia finito lì, ma\n"
	.string "sta di fatto che c'è!\p"
	.string "Vuoi ritirarlo, vero?$"
DayCare_Text_YourMonIsDoingFine::
	.string "Ah, sei tu! Hai fatto bene a\n"
	.string "passare. Il tuo {STR_VAR_1} sta\l"
	.string "crescendo bene.$"
DayCare_Text_IllKeepIt::
	.string "Va bene, allora lo tengo io.\n"
	.string "Grazie!$"
DayCare_Text_YouHaveNoRoomForIt::
	.string "La tua squadra è al completo…\n"
	.string "Torna quando hai un po' più di\l"
	.string "spazio.$"
DayCare_Text_ReceivedEgg::
	.string "{PLAYER} riceve l'UOVO dalla\n"
	.string "PENSIONE POKéMON.$"
DayCare_Text_TakeGoodCareOfIt::
	.string "Abbine cura!$"
DayCare_Text_SeeWifeIfYouWantToPickUpMon::
	.string "ポケモン& éÊÑûŒÁ ÑÊè\n"
	.string "ばÎ+à ÁっÛ ÈËº$"
DayCare_Text_YourMonsAreDoingFine::
	.string "Ah, sei tu! I tuoi {STR_VAR_1} e\n"
	.string "{STR_VAR_2} stanno crescendo bene.$"
DayCare_Text_IWillKeepDoYouWantIt::
	.string "Vorrei tenerlo io.\n"
	.string "Ma tu lo rivuoi indietro, vero?$"
DayCare_Text_WouldYouLikeUsToRaiseMon::
	.string "Sono la PADRONA della PENSIONE\n"
	.string "POKéMON.\p"
	.string "Possiamo allevare i tuoi POKéMON!\p"
	.string "Vuoi affidarcene uno?$"
DayCare_Text_WhichMonShouldWeRaise::
	.string "Che POKéMON vuoi che alleviamo?$"
DayCare_Text_WellRaiseYourMon::
	.string "Perfetto, alleveremo il tuo\n"
	.string "{STR_VAR_1} per un po'.\p"
	.string "Torna a prenderlo più tardi.$"
DayCare_Text_WeCanRaiseOneMore::
	.string "Possiamo allevare due dei tuoi\n"
	.string "POKéMON. Vuoi lasciarcene un\l"
	.string "altro?$"
DayCare_Text_HusbandWasLookingForYou::
	.string "Mio marito ti stava cercando.$"
DayCare_Text_FineThenComeAgain::
	.string "Oh, come vuoi.\n"
	.string "Torna a trovarci.$"
DayCare_Text_NotEnoughMoney::
	.string "Non hai abbastanza soldi…$"
DayCare_Text_TakeOtherOneBackToo::
	.string "Vuoi ritirare anche l'altro?$"
DayCare_Text_ComeAgain::
	.string "Va bene.\n"
	.string "Torna quando vuoi.$"
DayCare_Text_GoodToSeeYou::
	.string "Ah, sei tu! Hai fatto bene a\n"
	.string "passare. Stiamo ottenendo ottimi\l"
	.string "risultati!$"
DayCare_Text_YourMonHasGrownXLevels::
	.string "Il livello del tuo {STR_VAR_1} è\n"
	.string "cresciuto di {STR_VAR_2}!$"
DayCare_Text_YourPartyIsFull::
	.string "La tua squadra POKéMON è\n"
	.string "completa. Torna quando hai qualche\l"
	.string "posto libero.$"
DayCare_Text_TakeBackWhichMon::
	.string "どっÙç ポケモン& éÊÑñÉÁ?$"
DayCare_Text_ItWillCostX::
	.string "Per ritirare il tuo {STR_VAR_1},\n"
	.string "devi pagare ¥{STR_VAR_2}.$"
DayCare_Text_HeresYourMon::
	.string "Perfetto!\n"
	.string "Eccoti il POKéMON.$"
DayCare_Text_TookBackMon::
	.string "{PLAYER} ritira {STR_VAR_1} dalla\n"
	.string "PENSIONE POKéMON.$"
DayCare_Text_YouHaveJustOneMon::
	.string "Eh? Ma tu hai soltanto un POKéMON.\p"
	.string "Torna un'altra volta.$"
DayCare_Text_TakeYourMonBack::
	.string "Sei qui per ritirare un POKéMON?$"
DayCare_Text_WhatWillYouBattleWith::
	.string "Se mi affidi quel POKéMON,\n"
	.string "non potrai più lottare.\p"
	.string "Torna un'altra volta.$"
DayCare_Text_Huh::
	.string "Eh?$"
