Text_DadLetterArrivedForYouPlayer::
	.string "パパ“{PLAYER}! ùË ÊŒß!\n"
	.string "{PLAYER}ÀÛç Ûがîが ÑどÌúºŒぞ$"
Text_DadPassForShipNeverSeenBefore::
	.string "パパ“わŒÏó îŒこÑçßÁ\n"
	.string "êねç チケット だß……\l"
	.string "ミナモà ÁっÛîñÑ ÁÁだªÂ$"
Text_FerryToSlateportOhThatPass::
	.byte 0x56, 0x52, 0x65, 0x02, 0x07, 0x00, 0x2A, 0x2E, 0x27, 0x08, 0x0E, 0x2E
	.byte 0xB0, 0xB0, 0xFB, 0x01, 0x27, 0xAC, 0xFE, 0x0F, 0x19, 0x00, 0x61, 0x59
	.byte 0xA0, 0x64, 0x1A, 0xB0, 0xB0, 0xAB, 0xFF
Text_YoureOneWhoBroughtOddPass::
	.string "ヘンテÍß チケット&\n"
	.string "óっÛÊŒçè ÈまÇÎ+É?\p"
	.string "ÈまÇが ÁこÂÑ ÏÛÁñçè\n"
	.string "îßîç èÛç ÙっぽÌß Ïま……\p"
	.string "Ôこでè ßàが ÈこñçÉ\n"
	.string "だºó わÉúねÇ……\l"
	.string "ÂÂï êßçûç Ùが Îわぐぜ!\p"
	.string "ÎÀ çûß!$"
Text_NothingHereSailBackToLilycove::
	.string "ßàóねÇ Ù+Ìß Ïま だß……\n"
	.string "ミナモë ÉÇñÉ?$"
Text_SailHomeWeWill::
	.string "ùÏ! ÉÇñÑ ÒñÉ!$"
Text_AsYouLikeThen::
	.string "ÔÂÉÁ\n"
	.string "まÀ ÒÊàÒñが ÁÁÎ$"
SouthernIsland_Interior_Text_Sign::
	.string "ÒべÛç œòè óÂéÑÚç げ+じÚ\n"
	.string "Ôº& わÒºñべÉúず……$"
SouthernIsland_Exterior_Text_Sign::
	.string "ÊÈË ÉÒîÏ óçè\n"
	.string "ここªà ÊざîÚÌñ こÑ& çぞï……$"
