Text_WouldYouLikeToMixRecords::
	.string "Vuoi scambiare dati con altri\n"
	.string "ALLENATORI?$"

Text_WeHopeToSeeYouAgain2::
	.string "Torna a farci visita!$"

Text_BootedUpPC::
	.string "{PLAYER} accende il PC.$"

Text_AccessWhichPC::
	.string "A quale PC vuoi accedere?$"

Text_AccessedSomeonesPC::
	.string "Accesso al PC di ???.$"

Text_OpenedPkmnStorage::
	.string "Sistema Memoria POKéMON aperto.$"

Text_AccessedPlayersPC::
	.string "Accesso al PC di {PLAYER}.$"

Text_AccessedBillsPC::
	.string "Accesso al PC di BILL.$"

Text_WelcomeTradeCenter::
	.string "Ti do il benvenuto al CENTRO\n"
	.string "SCAMBI del CLUB VIA CAVO POKéMON.$"

Text_WelcomeColosseum::
	.string "Ti do il benvenuto al COLOSSEO del\n"
	.string "CLUB VIA CAVO POKéMON.$"

Text_WelcomeTimeCapsule::
	.string "Ti do il benvenuto alla\n"
	.string "TEMPOCAPSULA del CLUB VIA CAVO\l"
	.string "POKéMON.$"

Text_PleaseComeAgain::
	.string "Torna a trovarmi!$"

Text_HavingDiscountSaleToday::
	.string "Salve!\p"
	.string "Oggi ci sono le offerte speciali!$"

Text_PlayerWhatCanIDoForYou::
	.string "{PLAYER}{KUN}, salve!\p"
	.string "Che cosa posso fare per te?$"

Text_ObtainedTheX::
	.string "Hai ottenuto {STR_VAR_2}!$"

Text_BagIsFull::
	.string "Lo ZAINO è pieno…$"

Text_PutItemAway::
	.string "Strumento sistemato nello scomparto\n"
	.string "{STR_VAR_3} dello ZAINO.$"

Text_FoundOneItem::
	.byte 0xFD, 0x01, 0x00, 0xE8, 0xE6, 0xE3, 0xEA, 0xD5, 0x00, 0xFD, 0x03, 0xAB
	.byte 0xFC, 0x08, 0x40, 0xFF

Text_TooBadBagFull::
	.string "Che peccato!\n"
	.string "Hai lo ZAINO troppo pieno…$"

Text_FoundXCoins::
	.string "{PLAYER} trova\n"
	.string "{STR_VAR_1} {STR_VAR_2}!$"

Text_PutCoinsAwayInCoinCase::
	.string "{PLAYER} mette via i GETTONI\n"
	.string "nel SALVADANAIO.$"

Text_CoinCaseIsFull::
	.string "Che peccato!\n"
	.string "Il tuo SALVADANAIO è pieno!$"

Text_NothingToPutThemIn::
	.string "Che peccato!\n"
	.string "Non hai un contenitore in cui\l"
	.string "raccoglierli!$"

Text_FoundXItems::
	.string "{PLAYER} ha trovato {STR_VAR_1} unità\n"
	.string "di {STR_VAR_2}!$"

Text_ObtainedTheDecor::
	.string "Hai ottenuto {STR_VAR_2}!$"

Text_NoRoomForAnotherDecor::
	.string "Non hai spazio per {STR_VAR_2}? \n"
	.string "È un peccato…$"

Text_DecorTransferredToPC::
	.string "{STR_VAR_2} è nel tuo PC.$"

Text_MakingPreparations::
	.string "じ=+びÙ=ÂでÒ!$"

Text_WantWhichFloor::
	.string "A che piano vuoi andare?$"

Text_BagItemCanBeRegistered::
	.string "Puoi assegnare uno strumento dello\n"
	.string "ZAINO a SELECT.$"

Text_TrainerSchoolEmail::
	.string "パソÍンà\n"
	.string "ポケモン トレ-ナ- こÂざç\l"
	.string "メ-ルが ÊÛÁñ!\p"
	.string "…… …… ……\p"
	.string "ポケモンが ÈぼÇúºñ わざè 4Ú!\p"
	.string "ど+ß わざ& ÈぼÇÎÓñÉで\n"
	.string "トレ-ナ-ç じÚû;Ëが ÑわºまÒ!\p"
	.string "…… …… ……$"

Text_PlayerBootedUpPC::
	.string "{PLAYER} accende il PC.$"

Text_LinkWasCanceled::
	.byte 0x12, 0x03, 0x0C, 0x2E, 0x1A, 0x00, 0x57, 0x84, 0x7E, 0x5E, 0x79, 0x0B
	.byte 0x2A, 0x1F, 0x0C, 0x10, 0xFF

Text_GiveNicknameToReceivedMon::
	.string "Vuoi dare un soprannome a\n"
	.string "{STR_VAR_2}?$"

gText_PkmnFainted3::
	.string "{STR_VAR_1} è esausto…\p$"

Text_WelcomeWantToHealPkmn::
	.string "Sei in un CENTRO POKéMON.\p"
	.string "Rimettiamo in sesto i POKéMON\n"
	.string "stanchi.\p"
	.string "Vuoi far riposare la tua squadra?$"

Text_TakeYourPkmnForFewSeconds::
	.string "OK, mi prendo la tua squadra di\n"
	.string "POKéMON per qualche secondo.$"

Text_WeHopeToSeeYouAgain::
	.string "Arrivederci!$"

Text_RestoredPkmnToFullHealth::
	.string "Grazie per l'attesa.\n"
	.string "Ora la tua squadra di POKéMON è in\l"
	.string "perfetta forma.$"

Text_WantToSurf::
	.string "L'acqua ha un colore azzurro\n"
	.string "marino… Vuoi usare SURF?$"

Text_UsedSurf::
	.string "{STR_VAR_1} usa SURF!$"

Text_CurrentTooFast::
	.string "La corrente è troppo forte!\n"
	.string "Non puoi usare SURF qui.$"

Text_DoorOpenedFarAway::
	.string "どこÉ ÑÈËç Ñびúが\n"
	.string "éúÁŒùÂß ÈÑだ……$"

Text_BigHoleInTheWall::
	.string "Éべà\n"
	.string "ÈÈÊß Àßが ÀÁÛÁñ!$"

Text_WirelessClubUndergoingAdjustments::
	.string "Sono spiacente.\n"
	.string "Il CLUB WIRELESS POKéMON\l"
	.string "è chiuso per lavori.$"

Text_AppearsToBeUndergoingAdjustments::
	.string "Sembra che sia chiuso per lavori.$"

Text_HandedOverItem::
	.string "{PLAYER} cede\n"
	.string "{STR_VAR_1}.$"

Text_GiveNicknameToThisMon::
	.string "Vuoi dare un soprannome a\n"
	.string "{STR_VAR_1}?$"

Text_ItemfinderResponding::
	.byte 0x05, 0xA0, 0xAB, 0x00, 0x91, 0x53, 0x8D, 0x7E, 0x89, 0x6F, 0x5C, 0x7E
	.byte 0x37, 0xFE, 0x1A, 0x2E, 0x19, 0x03, 0x00, 0x0C, 0x13, 0x29, 0x40, 0xAB
	.byte 0xFB, 0x1F, 0x0C, 0x10, 0x16, 0x00, 0x45, 0x03, 0x39, 0x37, 0x00, 0x03
	.byte 0x1F, 0x50, 0x13, 0x29, 0xAB, 0xFE, 0xB0, 0xB0, 0xB0, 0xFF

Text_DugUpItemFromGround::
	.string "{PLAYER} trova un'unità\n"
	.string "di {STR_VAR_2} nel terreno.$"

Text_OnlySkilledTrainersAllowedThrough::
	.string "Solo i veri ALLENATORI possono\n"
	.string "passare.\p"
	.string "Non hai ancora la {STR_VAR_1}!$"

Text_CantLetYouPass::
	.string "Le regole sono regole.\n"
	.string "Non puoi passare!$"

Text_OhThatsBadgeGoRightAhead::
	.string "Oh! Ma questa è la {STR_VAR_1}!\n"
	.string "Passa pure!$"

Text_OnlyPassWithBadgeDontHaveYet::
	.string "Puoi passare solo se hai la\n"
	.string "{STR_VAR_1}!\p"
	.string "Non ce l'hai ancora!\p"
	.string "Per accedere alla LEGA POKéMON,\n"
	.string "devi procurartela!$"

Text_OnlyPassWithBadgeOhGoAhead::
	.byte 0xCA, 0xE9, 0xE3, 0xDD, 0x00, 0xE4, 0xD5, 0xE7, 0xE7, 0xD5, 0xE6, 0xD9
	.byte 0x00, 0xE7, 0xE3, 0xE0, 0xE3, 0x00, 0xE7, 0xD9, 0x00, 0xDC, 0xD5, 0xDD
	.byte 0x00, 0xE0, 0xD5, 0xFE, 0xFD, 0x02, 0xAB, 0xFB, 0xC9, 0xDC, 0xAB, 0x00
	.byte 0x05, 0x00, 0xE4, 0xE6, 0xE3, 0xE4, 0xE6, 0xDD, 0xE3, 0x00, 0xE0, 0xD5
	.byte 0x00, 0xFD, 0x02, 0xAB, 0xFC, 0x17, 0xFC, 0x0B, 0x01, 0x01, 0xFC, 0x08
	.byte 0x60, 0xFC, 0x18, 0xFB, 0xBC, 0xD9, 0xE2, 0xDD, 0xE7, 0xE7, 0xDD, 0xE1
	.byte 0xE3, 0xAB, 0xFE, 0xCA, 0xD5, 0xE7, 0xE7, 0xD5, 0x00, 0xE4, 0xE9, 0xE6
	.byte 0xD9, 0xAB, 0xFF

Aide_Text_HaventCaughtEnoughMonsForItem::
	.string "Vediamo…\n"
	.string "Oh! Hai raccolto dati solo su\l"
	.string "{STR_VAR_3} specie di POKéMON!\p"
	.string "Ti servono {STR_VAR_1} specie, se vuoi\n"
	.string "{STR_VAR_2}.$"

Aide_Text_GetEnoughMonsComeBackForItem::
	.string "Oh! Allora…\p"
	.string "Quando avrai {STR_VAR_1} specie di POKéMON\n"
	.string "torna qui e ti darò {STR_VAR_2}\l"
	.string "in regalo!$"

Aide_Text_DontHaveAnyRoomForItem::
	.string "Vedo che non hai più spazio per\n"
	.string "{STR_VAR_2}!$"

Trade_Text_LookingForMonWannaTradeForMon::
	.string "Cerco {STR_VAR_1}!\n"
	.string "Vuoi scambiarlo con {STR_VAR_2}?$"

Trade_Text_AwwOhWell::
	.string "Oh!\n"
	.string "Vabbè!$"

Trade_Text_WhatThatsNoMon::
	.string "Questo non è {STR_VAR_1}!$"

Trade_Text_HeyThanks::
	.string "Grazie mille!$"

Trade_Text_IsntMyOldMonGreat::
	.string "Visto com'è forte il mio vecchio\n"
	.string "{STR_VAR_2}?$"

Trade_Text_DoYouHaveMonWouldYouTradeForMon::
	.string "Ciao! Vuoi scambiare il tuo\n"
	.string "{STR_VAR_1} con {STR_VAR_2}?$"

Trade_Text_WellIfYouDontWantTo::
	.string "Vabbè! Se non vuoi…$"

Trade_Text_ThisIsntMon::
	.string "Questo non è {STR_VAR_1}.\p"
	.string "Quando ne hai uno torna a\n"
	.string "trovarmi!$"

Trade_Text_Thanks::
	.string "Grazie!$"

Trade_Text_HasTradedMonGrownStronger::
	.string "Come sta l'esemplare di\n"
	.string "{STR_VAR_2} che ti ho dato nello\l"
	.string "scambio? Si è rafforzato?$"

Trade_Text_DoYouHaveMonWantToTradeForMon::
	.string "Ciao!\n"
	.string "Hai {STR_VAR_1}?\p"
	.string "Vuoi scambiarlo con {STR_VAR_2}?$"

Trade_Text_ThatsTooBad::
	.string "Che sfortuna!$"

Trade_Text_ThisIsNoMon::
	.string "Questo non è {STR_VAR_1}.\p"
	.string "Quando ne hai uno, scambialo con\n"
	.string "me!$"

Trade_Text_ThanksYoureAPal::
	.string "Grazie mille!$"

Trade_Text_HowIsMyOldMon::
	.string "Come sta il mio vecchio\n"
	.string "{STR_VAR_2}?\p"
	.string "Il mio caro {STR_VAR_1} sta\n"
	.string "divinamente!$"

Text_CardKeyOpenedDoor::
	.string "Evviva!\n"
	.string "L'APRIPORTA ha funzionato!$"

Text_ItNeedsCardKey::
	.string "Oh, no!\n"
	.string "Ci vuole l'APRIPORTA!$"

Text_AccessedProfOaksPC::
	.string "Accesso al PC del PROF. OAK.\p"
	.string "Accesso al Sistema Valutazione\n"
	.string "POKéDEX.$"

Text_HavePokedexRated::
	.string "Vuoi far valutare il tuo POKéDEX?$"

Text_ClosedLinkToProfOaksPC::
	.string "Fine collegamento con il PC del\n"
	.string "PROF. OAK.$"

Text_VoiceRangOutDontRunAway::
	.string "Si sente una voce:\n"
	.string "“Non scappare!”.$"

Text_IdLikeToSeeRequest::
	.string "ÇっÑ-\n"
	.string "{STR_VAR_2}が îÛîŒÁß-\p"
	.string "Ôºó {STR_VAR_1}{STR_VAR_3}\n"
	.string "{STR_VAR_2}が îÛîŒÁß-$"

Text_ThankYouForShowingMe::
	.string "わぁ- ÒごÁ!\n"
	.string "{STR_VAR_1}{STR_VAR_3}{STR_VAR_2}だ-!\p"
	.string "ÀûがÑ-\n"
	.string "まŒ ùªÏËね-!$"

Text_ThatsNotRight::
	.string "Ôºっ ÙがÂù-!$"

Text_ISee::
	.string "ÔっÉ…$"

Text_TheDoorIsClosed::
	.string "ド¿è ÏまっÛÁñ…$"

Text_TheDoorIsOpen::
	.string "La porta è aperta…$"

Text_MonSentToBoxInSomeonesPC::
	.string "{STR_VAR_2} è stato trasferito\n"
	.string "al PC di ???.\p"
	.string "È nel BOX chiamato “{STR_VAR_1}”.$"

Text_MonSentToBoxInBillsPC::
	.string "{STR_VAR_2} è stato inviato al\n"
	.string "PC di BILL.\p"
	.string "È nel BOX chiamato “{STR_VAR_1}”.$"

Text_MonSentToBoxSomeonesBoxFull::
	.string "Il BOX chiamato “{STR_VAR_3}” nel\n"
	.string "PC di ??? è pieno.\p"
	.string "{STR_VAR_2} è stato inviato al\n"
	.string "BOX chiamato “{STR_VAR_1}”.$"

Text_MonSentToBoxBillsBoxFull::
	.string "Il BOX chiamato “{STR_VAR_3}” nel\n"
	.string "PC di BILL è pieno.\p"
	.string "{STR_VAR_2} è stato inviato al\n"
	.string "BOX chiamato “{STR_VAR_1}”.$"

Text_PlayerObtainedTheMon::
	.string "{PLAYER} riceve\n"
	.string "{STR_VAR_1}!$"

Text_MonSentToBoxInPC::
	.byte 0x9F, 0x59, 0x73, 0x7E, 0x2D, 0x00, 0x23, 0x11, 0x07, 0x2A, 0x15, 0x02
	.byte 0x19, 0x44, 0xFE, 0x9B, 0x5F, 0x5A, 0x7E, 0x19, 0x00, 0x9A, 0xA0, 0x58
	.byte 0x5D, 0xB1, 0xFD, 0x02, 0xB2, 0x00, 0x16, 0xFA, 0xFD, 0x03, 0x2D, 0x00
	.byte 0x13, 0x2E, 0x0F, 0x03, 0x0C, 0x10, 0xAB, 0xFF

Text_NoMoreRoomForPokemon::
	.string "Non c'è spazio per altri POKéMON!\n"
	.string "I BOX POKéMON sono pieni!$"

Text_FirstShouldRestoreMonsHealth::
	.string "Ora rimetterò in sesto la tua\n"
	.string "squadra di POKéMON.$"

Text_MonsHealedShouldBuyPotions::
	.string "Bene, ora la tua squadra di\n"
	.string "POKéMON è in perfetta forma.\p"
	.string "Se i tuoi POKéMON perdono PS,\n"
	.string "torna a trovarmi!\p"
	.string "Parti per un lungo viaggio? Allora,\n"
	.string "passa dal POKéMON-MARKET a\l"
	.string "comprare qualche POZIONE!$"

Text_MonsHealed::
	.string "Ora la tua squadra di POKéMON\n"
	.string "è in perfetta forma!\p"
	.string "In bocca al lupo!$"

Text_HadQuiteAnExperienceTakeRest::
	.string "MAMMA: {PLAYER}!\p"
	.string "Sembra proprio che tu stia\n"
	.string "vivendo una grande avventura!\p"
	.string "Ora, però, dovresti riposarti un\n"
	.string "po'.$"

Text_MomExplainHPGetPotions::
	.string "MAMMA: Perfetto!\n"
	.string "Ora tu e i tuoi POKéMON siete in\l"
	.string "gran forma!\p"
	.string "Ho appena sentito il PROF. OAK.\p"
	.string "Mi ha detto che l'energia dei\n"
	.string "POKéMON si misura in PS.\p"
	.string "Se i tuoi POKéMON perdono PS,\n"
	.string "possono recuperarli in un CENTRO\l"
	.string "POKéMON.\p"
	.string "Un buon ALLENATORE ha sempre con\n"
	.string "sé qualche POZIONE: si possono\l"
	.string "acquistare in un POKéMON-MARKET.\p"
	.string "Mi aspetto grandi cose da te!\p"
	.string "Fai attenzione!$"

Text_WhitedOutLostMoney::
	.string "{PLAYER} non ha più POKéMON utili!\p"
	.string "{PLAYER}, nel panico, ha perso\n"
	.string "¥{STR_VAR_1}…\p"
	.string "… … … …\p"
	.string "{PLAYER} è fuori combattimento!$"

Text_WhitedOut::
	.string "{PLAYER} non ha più POKéMON utili!\p"
	.string "{PLAYER} è fuori gioco!$"

Text_MayIHelpYou::
	.string "Salve!\n"
	.string "Posso essere d'aiuto?$"

Text_FillOutQuestionnaire::
	.string "C'è un questionario.\n"
	.string "Vuoi compilarlo?$"

Text_QuestionnaireThankYou::
	.string "Grazie per aver compilato\n"
	.string "il questionario.\p"
	.string "Le tue risposte saranno\n"
	.string "molto utili.$"

Text_YouKnowThoseWords::
	.string "Ciao!\n"
	.string "Ah, conosci le parole segrete?\p"
	.string "Quindi, sai anche cos'è\n"
	.string "il DONO SEGRETO!\p"
	.string "Da questo momento puoi\n"
	.string "ricevere DONI SEGRETI!$"

Text_YouCanAccessMysteryGift::
	.string "Dopo aver salvato il gioco, potrai\n"
	.string "accedere all'opzione DONO SEGRETO.$"

Text_ThankYouForAccessingMysteryGift::
	.string "Grazie per usufruire del servizio\n"
	.string "DONO SEGRETO!$"

Text_MonFlewAway::
	.string "{STR_VAR_1} è fuggito!$"

Text_TheresBedLetsRest::
	.string "ベッドが Àñ……\n"
	.string "ôÒ+でÁこÂ$"

Text_FoundTMHMContainsMove::
	.string "{PLAYER} trova {STR_VAR_2}.\n"
	.string "Contiene {STR_VAR_1}!$"

Text_WhereDoYouWantToGo::
	.string "ÈÚÉºÎ+!\n"
	.string "どこà ÁÊŒÁ+だ?$"

Text_AllAboardSeagallopNum::
	.string "Bene! Il POKéSCAFO {STR_VAR_1}\n"
	.string "è in partenza! Tutti a bordo!$"

Text_Gyaoo::
	.string "Ghiooo!$"

Text_MoveCanOnlyBeLearnedOnce::
	.string "Questa mossa può essere appresa\n"
	.string "soltanto una volta: vuoi\l"
	.string "continuare?$"

