Text_WouldYouLikeToMixRecords::
	.string "  ニヘフÂVuoi scambiare dati con altri\n"
	.string "ALLENATORI?$"

Text_WeHopeToSeeYouAgain2::
	.string "Torna a farci visita!$"

Text_WelcomeTradeCenter::
	.string "Ti do il benvenuto al CENTRO\n"
	.string "SCAMBI del CLUB VIA CAVO POKéMON.$"

Text_WelcomeColosseum::
	.string "Ti do il benvenuto al COLOSSEO del\n"
	.string "CLUB VIA CAVO POKéMON.$"

Text_WelcomeTimeCapsule::
	.string "Ti do il benvenuto alla\n"
	.string "TEMPOCAPSULA del CLUB VIA CAVO\l"
	.string "POKéMON.$"

Text_PleaseComeAgain::
	.string "Torna a trovarmi!$"

Text_HavingDiscountSaleToday::
	.string "Salve!\p"
	.string "Oggi ci sono le offerte speciali!$"

Text_PlayerWhatCanIDoForYou::
	.string "{PLAYER}{KUN}, salve!\p"
	.string "Che cosa posso fare per te?$"

Text_MakingPreparations::
	.string "じ=+びÙ=ÂでÒ!$"

Text_WantWhichFloor::
	.string "A che piano vuoi andare?$"

Text_BagItemCanBeRegistered::
	.string "Puoi assegnare uno strumento dello\n"
	.string "ZAINO a SELECT.$"

Text_TrainerSchoolEmail::
	.string "パソÍンà\n"
	.string "ポケモン トレ-ナ- こÂざç\l"
	.string "メ-ルが ÊÛÁñ!\p"
	.string "…… …… ……\p"
	.string "ポケモンが ÈぼÇúºñ わざè 4Ú!\p"
	.string "ど+ß わざ& ÈぼÇÎÓñÉで\n"
	.string "トレ-ナ-ç じÚû;Ëが ÑわºまÒ!\p"
	.string "…… …… ……$"

Text_PlayerBootedUpPC::
	.string "{PLAYER} accende il PC.$"

Text_LinkWasCanceled::
	.byte 0x12, 0x03, 0x0C, 0x2E, 0x1A, 0x00, 0x57, 0x84, 0x7E, 0x5E, 0x79, 0x0B
	.byte 0x2A, 0x1F, 0x0C, 0x10, 0xFF

Text_GiveNicknameToReceivedMon::
	.string "Vuoi dare un soprannome a\n"
	.string "{STR_VAR_2}?$"

gText_PkmnFainted3::
	.string "{STR_VAR_1} è esausto…\p$"

Text_WelcomeWantToHealPkmn::
	.string "Sei in un CENTRO POKéMON.\p"
	.string "Rimettiamo in sesto i POKéMON\n"
	.string "stanchi.\p"
	.string "Vuoi far riposare la tua squadra?$"

Text_TakeYourPkmnForFewSeconds::
	.string "OK, mi prendo la tua squadra di\n"
	.string "POKéMON per qualche secondo.$"

Text_WeHopeToSeeYouAgain::
	.string "Arrivederci!$"

Text_RestoredPkmnToFullHealth::
	.string "Grazie per l'attesa.\n"
	.string "Ora la tua squadra di POKéMON è in\l"
	.string "perfetta forma.$"

Text_DoorOpenedFarAway::
	.string "どこÉ ÑÈËç Ñびúが\n"
	.string "éúÁŒùÂß ÈÑだ……$"

Text_BigHoleInTheWall::
	.string "Éべà\n"
	.string "ÈÈÊß Àßが ÀÁÛÁñ!$"

Text_WirelessClubUndergoingAdjustments::
	.string "Sono spiacente.\n"
	.string "Il CLUB WIRELESS POKéMON\l"
	.string "è chiuso per lavori.$"

Text_AppearsToBeUndergoingAdjustments::
	.string "Sembra che sia chiuso per lavori.$"

Text_HandedOverItem::
	.string "{PLAYER} cede\n"
	.string "{STR_VAR_1}.$"

Text_GiveNicknameToThisMon::
	.string "Vuoi dare un soprannome a\n"
	.string "{STR_VAR_1}?$"

Text_CardKeyOpenedDoor::
	.string "Evviva!\n"
	.string "L'APRIPORTA ha funzionato!$"

Text_ItNeedsCardKey::
	.string "Oh, no!\n"
	.string "Ci vuole l'APRIPORTA!$"

Text_AccessedProfOaksPC::
	.string "Accesso al PC del PROF. OAK.\p"
	.string "Accesso al Sistema Valutazione\n"
	.string "POKéDEX.$"

Text_HavePokedexRated::
	.string "Vuoi far valutare il tuo POKéDEX?$"

Text_ClosedLinkToProfOaksPC::
	.string "Fine collegamento con il PC del\n"
	.string "PROF. OAK.$"

Text_VoiceRangOutDontRunAway::
	.string "Si sente una voce:\n"
	.string "“Non scappare!”.$"

Text_IdLikeToSeeRequest::
	.string "ÇっÑ-\n"
	.string "{STR_VAR_2}が îÛîŒÁß-\p"
	.string "Ôºó {STR_VAR_1}{STR_VAR_3}\n"
	.string "{STR_VAR_2}が îÛîŒÁß-$"

Text_ThankYouForShowingMe::
	.string "わぁ- ÒごÁ!\n"
	.string "{STR_VAR_1}{STR_VAR_3}{STR_VAR_2}だ-!\p"
	.string "ÀûがÑ-\n"
	.string "まŒ ùªÏËね-!$"

Text_ThatsNotRight::
	.string "Ôºっ ÙがÂù-!$"

Text_ISee::
	.string "ÔっÉ…$"

Text_TheDoorIsClosed::
	.string "ド¿è ÏまっÛÁñ…$"

Text_TheDoorIsOpen::
	.string "La porta è aperta…$"

Text_MonFlewAway::
	.string "{STR_VAR_1} è fuggito!$"

Text_TheresBedLetsRest::
	.string "ベッドが Àñ……\n"
	.string "ôÒ+でÁこÂ$"

Text_FoundTMHMContainsMove::
	.string "{PLAYER} trova {STR_VAR_2}.\n"
	.string "Contiene {STR_VAR_1}!$"

Text_Gyaoo::
	.string "Ghiooo!$"

Text_MoveCanOnlyBeLearnedOnce::
	.string "Questa mossa può essere appresa\n"
	.string "soltanto una volta: vuoi\l"
	.string "continuare?$"

