Text_Bookshelf::
	.string "Pieno zeppo di libri POKéMON!$"
Text_NothingButPokemonBooks::
	.string "ì+だßà ßú+でÁñçè\n"
	.string "ポケモンç ì+ ばÉûだ$"
Text_ATownMap::
	.string "Una MAPPA CITTÀ.$"
Text_PokeMartShelf::
	.string "Wow!\n"
	.string "Montagne di oggetti POKéMON!$"
Text_DishesPlatesNeatlyLinedUp::
	.string "Ci sono piatti e vassoi in perfetto\n"
	.string "ordine.$"
Text_Kitchen::
	.string "Che profumino… C'è qualcosa sul\n"
	.string "fuoco…$"
Text_Dresser::
	.string "È una bella credenza. Sembra\n"
	.string "molto capiente.$"
Text_Snacks::
	.string "Ci sono parecchi snack.$"
Text_PokemartSign::
	.string "Abbiamo tutti gli strumenti per te!\n"
	.string "POKéMON-MARKET$"
Text_PokecenterSign::
	.string "Rimetti in sesto i tuoi POKéMON!\n"
	.string "CENTRO POKéMON$"
Text_Indigo_UltimateGoal::
	.string "ALTOPIANO BLU\p"
	.string "La grande meta degli ALLENATORI!\n"
	.string "SEDE CENTRALE LEGA POKéMON.$"
Text_Indigo_HighestAuthority::
	.string "ALTOPIANO BLU\p"
	.string "La massima autorità POKéMON:\n"
	.string "SEDE CENTRALE LEGA POKéMON.$"
Text_Food::
	.string "Dev'essere pieno di cibi\n"
	.string "deliziosi.$"
Text_Blueprints::
	.string "Sembra un progetto. Le pagine sono\n"
	.string "piene di testi e diagrammi.$"
Text_Painting::
	.string "È una bella immagine di un\n"
	.string "POKéMON. Sembra contento.$"
Text_PowerPlantMachine::
	.string "Uno strano macchinario. Meglio\n"
	.string "stargli alla larga…$"
Text_Telephone::
	.string "È un telefono. Meglio non usarlo…$"
Text_Computer::
	.string "È pieno di parole e numeri\n"
	.string "incomprensibili…$"
Text_AdvertisingPoster::
	.string "È un cartellone pubblicitario con\n"
	.string "prodotti di ogni tipo.$"
Text_TastyFood::
	.string "Che profumino!\n"
	.string "Fa venire l'acquolina in bocca!$"
Text_TrashBin::
	.string "Qui dentro…\n"
	.string "……\p"
	.string "…non c'è niente!$"
Text_Cup::
	.string "È una tazza con un POKéMON\n"
	.string "disegnato.$"
Text_PolishedWindow::
	.string "I vetri della finestra sembrano\n"
	.string "appena stati lavati.$"
Text_BeautifulSkyWindow::
	.string "Dalla finestra…\p"
	.string "…si vede un cielo terso,\n"
	.string "magnifico.$"
Text_BlinkingLights::
	.string "Ci sono luci lampeggianti di vario\n"
	.string "colore.$"
Text_NeatlyLinedUpTools::
	.string "Vi sono oggetti di ogni tipo.$"
Text_ImpressiveMachine::
	.string "È uno strano macchinario,\n"
	.string "impressionante.$"
Text_VideoGame::
	.string "È un videogioco appena uscito.\n"
	.string "Dev'essere divertente!$"
Text_Burglary::
	.string "I ladri hanno lasciato chiari segni\n"
	.string "del loro passaggio.$"
Text_PlayerFacingTVScreen::
	.string "C'è un POKéMON in TV! Sembra\n"
	.string "divertirsi un mondo!$"
