Trade_Text_LookingForMonWannaTradeForMon::
	.string "Cerco {STR_VAR_1}!\n"
	.string "Vuoi scambiarlo con {STR_VAR_2}?$"
Trade_Text_AwwOhWell::
	.string "Oh!\n"
	.string "Vabbè!$"
Trade_Text_WhatThatsNoMon::
	.string "Questo non è {STR_VAR_1}!$"
Trade_Text_HeyThanks::
	.string "Grazie mille!$"
Trade_Text_IsntMyOldMonGreat::
	.string "Visto com'è forte il mio vecchio\n"
	.string "{STR_VAR_2}?$"
Trade_Text_DoYouHaveMonWouldYouTradeForMon::
	.string "Ciao! Vuoi scambiare il tuo\n"
	.string "{STR_VAR_1} con {STR_VAR_2}?$"
Trade_Text_WellIfYouDontWantTo::
	.string "Vabbè! Se non vuoi…$"
Trade_Text_ThisIsntMon::
	.string "Questo non è {STR_VAR_1}.\p"
	.string "Quando ne hai uno torna a\n"
	.string "trovarmi!$"
Trade_Text_Thanks::
	.string "Grazie!$"
Trade_Text_HasTradedMonGrownStronger::
	.string "Come sta l'esemplare di\n"
	.string "{STR_VAR_2} che ti ho dato nello\l"
	.string "scambio? Si è rafforzato?$"
Trade_Text_DoYouHaveMonWantToTradeForMon::
	.string "Ciao!\n"
	.string "Hai {STR_VAR_1}?\p"
	.string "Vuoi scambiarlo con {STR_VAR_2}?$"
Trade_Text_ThatsTooBad::
	.string "Che sfortuna!$"
Trade_Text_ThisIsNoMon::
	.string "Questo non è {STR_VAR_1}.\p"
	.string "Quando ne hai uno, scambialo con\n"
	.string "me!$"
Trade_Text_ThanksYoureAPal::
	.string "Grazie mille!$"
Trade_Text_HowIsMyOldMon::
	.string "Come sta il mio vecchio\n"
	.string "{STR_VAR_2}?\p"
	.string "Il mio caro {STR_VAR_1} sta\n"
	.string "divinamente!$"
