Text_ObtainedTheX::
	.string "Hai ottenuto {STR_VAR_2}!$"
Text_BagIsFull::
	.string "Lo ZAINO è pieno…$"
Text_PutItemAway::
	.string "Strumento sistemato nello scomparto\n"
	.string "{STR_VAR_3} dello ZAINO.$"
Text_FoundOneItem::
	.byte 0xFD, 0x01, 0x00, 0xE8, 0xE6, 0xE3, 0xEA, 0xD5, 0x00, 0xFD, 0x03, 0xAB
	.byte 0xFC, 0x08, 0x40, 0xFF
Text_TooBadBagFull::
	.string "Che peccato!\n"
	.string "Hai lo ZAINO troppo pieno…$"
Text_FoundXCoins::
	.string "{PLAYER} trova\n"
	.string "{STR_VAR_1} {STR_VAR_2}!$"
Text_PutCoinsAwayInCoinCase::
	.string "{PLAYER} mette via i GETTONI\n"
	.string "nel SALVADANAIO.$"
Text_CoinCaseIsFull::
	.string "Che peccato!\n"
	.string "Il tuo SALVADANAIO è pieno!$"
Text_NothingToPutThemIn::
	.string "Che peccato!\n"
	.string "Non hai un contenitore in cui\l"
	.string "raccoglierli!$"
Text_FoundXItems::
	.string "{PLAYER} ha trovato {STR_VAR_1} unità\n"
	.string "di {STR_VAR_2}!$"
Text_ObtainedTheDecor::
	.string "Hai ottenuto {STR_VAR_2}!$"
Text_NoRoomForAnotherDecor::
	.string "Non hai spazio per {STR_VAR_2}? \n"
	.string "È un peccato…$"
Text_DecorTransferredToPC::
	.string "{STR_VAR_2} è nel tuo PC.$"
