Text_MonSentToBoxInSomeonesPC::
	.string "{STR_VAR_2} è stato trasferito\n"
	.string "al PC di ???.\p"
	.string "È nel BOX chiamato “{STR_VAR_1}”.$"
Text_MonSentToBoxInBillsPC::
	.string "{STR_VAR_2} è stato inviato al\n"
	.string "PC di BILL.\p"
	.string "È nel BOX chiamato “{STR_VAR_1}”.$"
Text_MonSentToBoxSomeonesBoxFull::
	.string "Il BOX chiamato “{STR_VAR_3}” nel\n"
	.string "PC di ??? è pieno.\p"
	.string "{STR_VAR_2} è stato inviato al\n"
	.string "BOX chiamato “{STR_VAR_1}”.$"
Text_MonSentToBoxBillsBoxFull::
	.string "Il BOX chiamato “{STR_VAR_3}” nel\n"
	.string "PC di BILL è pieno.\p"
	.string "{STR_VAR_2} è stato inviato al\n"
	.string "BOX chiamato “{STR_VAR_1}”.$"
Text_PlayerObtainedTheMon::
	.string "{PLAYER} riceve\n"
	.string "{STR_VAR_1}!$"
Text_MonSentToBoxInPC::
	.byte 0x9F, 0x59, 0x73, 0x7E, 0x2D, 0x00, 0x23, 0x11, 0x07, 0x2A, 0x15, 0x02
	.byte 0x19, 0x44, 0xFE, 0x9B, 0x5F, 0x5A, 0x7E, 0x19, 0x00, 0x9A, 0xA0, 0x58
	.byte 0x5D, 0xB1, 0xFD, 0x02, 0xB2, 0x00, 0x16, 0xFA, 0xFD, 0x03, 0x2D, 0x00
	.byte 0x13, 0x2E, 0x0F, 0x03, 0x0C, 0x10, 0xAB, 0xFF
Text_NoMoreRoomForPokemon::
	.string "Non c'è spazio per altri POKéMON!\n"
	.string "I BOX POKéMON sono pieni!$"
