PokedexRating_Text_HowIsPokedexComingAlong::
	.string "OAK: Che piacere vederti!\n"
	.string "Come va il tuo POKéDEX?\p"
	.string "Fammi vedere!$"
PokedexRating_Text_SeenXOwnedY::
	.string "Il tuo POKéDEX dice:\p"
	.string "POKéMON visti: {STR_VAR_1}\n"
	.string "POKéMON presi: {STR_VAR_2}\p"
	.string "{FONT_NORMAL}Giudizio del PROF. OAK:$"
PokedexRating_Text_LessThan10::
	.string "Hai ancora molto da fare.\n"
	.string "Cerca i POKéMON nell'erba alta!$"
PokedexRating_Text_LessThan20::
	.string "Bene, sei sulla buona strada!\p"
	.string "Se non ce l'hai già, prendi la MN\n"
	.string "FLASH dal mio ASSISTENTE!$"
PokedexRating_Text_LessThan30::
	.string "Hai bisogno di più POKéMON!\n"
	.string "Catturane altre specie!$"
PokedexRating_Text_LessThan40::
	.string "Benissimo!\n"
	.string "Stai lavorando sodo!\p"
	.string "Se non ce l'hai già, prendi un\n"
	.string "DETECTOR dal mio ASSISTENTE!$"
PokedexRating_Text_LessThan50::
	.string "Ehi, ma il tuo POKéDEX sta\n"
	.string "diventando sempre più completo!\p"
	.string "Ho dato MONETAMULETO ad uno\n"
	.string "dei miei ASSISTENTI, per te!\p"
	.string "Non dimenticare di passarlo a\n"
	.string "prendere!$"
PokedexRating_Text_LessThan60::
	.string "Hai raggiunto il traguardo di 50\n"
	.string "specie!\p"
	.string "Ho dato CONDIV. ESP. ad uno dei\n"
	.string "miei ASSISTENTI, per te!\p"
	.string "Non dimenticare di passarlo a\n"
	.string "prendere!$"
PokedexRating_Text_LessThan70::
	.string "Wow!\n"
	.string "Va sempre meglio!$"
PokedexRating_Text_LessThan80::
	.string "Fantastico!\p"
	.string "Va in cerca di qualche POKéMON\n"
	.string "marino!$"
PokedexRating_Text_LessThan90::
	.string "Magnifico!\n"
	.string "Ti piace fare collezioni?$"
PokedexRating_Text_LessThan100::
	.string "Sono soddisfatto!\n"
	.string "Hai proprio lavorato sodo!$"
PokedexRating_Text_LessThan110::
	.string "Complimenti! Hai già 100 esemplari\n"
	.string "diversi! Sei davvero in gamba!$"
PokedexRating_Text_LessThan120::
	.string "Hai persino le forme evolute dei\n"
	.string "POKéMON! Bene!$"
PokedexRating_Text_LessThan130::
	.string "Eccellente! Scambiali con i tuoi\n"
	.string "amici per averne altri!$"
PokedexRating_Text_LessThan140::
	.string "Sensazionale!\n"
	.string "Ormai questa è la tua professione!$"
PokedexRating_Text_LessThan150::
	.string "Sono senza parole!\n"
	.string "Adesso sei tu la persona esperta!$"
PokedexRating_Text_Complete::
	.string "Il tuo POKéDEX è completo!\n"
	.string "Congratulazioni!$"
PokedexRating_Text_NationalDexSeenXOwnedY::
	.string "E nel POKéDEX NAZIONALE hai:\p"
	.string "POKéMON visti: {STR_VAR_1}.\n"
	.string "POKéMON presi: {STR_VAR_2}.$"
PokedexRating_Text_LookForwardToFilledNationalDex::
	.string "Non vedo l'ora che il tuo\n"
	.string "POKéDEX NAZIONALE\l"
	.string "sia completato!$"
PokedexRating_Text_YouveCompletedDex::
	.string "Ce l'hai fatta!\p"
	.string "Finalmente hai completato il\n"
	.string "POKéDEX!\p"
	.string "Sono commosso! Davvero!\n"
	.string "Oggi è un gran giorno!$"
PokedexRating_Text_Wroooaaarrr::
	.string "Wooow!$"
PokedexRating_Text_HaHa::
	.string "èÀ èÀ…$"
PokedexRating_Text_ThankYouMadeDreamReality::
	.string "Grazie, {PLAYER}!\n"
	.string "Grazie di cuore!\l"
	.string "Hai realizzato il mio sogno!$"
PokedexRating_Text_LoveSeeingYourPokedex::
	.string "Ciao, come va?\p"
	.string "E il completamento del POKéDEX?\n"
	.string "Procede bene?\p"
	.string "Lo conosco come le mie tasche,\n"
	.string "ma mi piace comunque vederlo.\p"
	.string "Vediamo…$"
