gText_WouldYouLikeToSaveTheGame::
	.string "Vuoi salvare il gioco?$"
gText_AlreadySaveFile_WouldLikeToOverwrite::
	.string "Sono presenti dati di gioco salvati.\n"
	.string "Vuoi sovrascriverli?$"
gText_SavingDontTurnOffThePower::
	.string "SALVATAGGIO IN CORSO…\n"
	.string "NON SPEGNERE!$"
gText_PlayerSavedTheGame::
	.string "{PLAYER} ha salvato i dati di\n"
	.string "gioco.$"
gText_SaveFailed2::
	.string "セ-ブà ÏっぱÁ ÏまÏŒ…$"
gText_DifferentGameFile::
	.string "ATTENZIONE!\n"
	.string "In memoria è presente il\l"
	.string "salvataggio di un'altra partita.\p"
	.string "Se salvi adesso, i dati dell'altra\n"
	.string "partita, inclusi gli strumenti e\l"
	.string "i POKéMON, andranno perduti.\p"
	.string "Vuoi comunque salvare,\n"
	.string "sovrascrivendo i dati di gioco\l"
	.string "che si trovano in memoria?$"
