PalletTown_Text_HmmIsThatRight::
	.string "Hmmm…\n"
	.string "È quello giusto…$"
PalletTown_Text_OhLookLook::
	.string "Oh!\n"
	.string "Guarda, guarda!$"
PalletTown_Text_ReadItReadIt::
	.string "Leggi, leggi!$"
PalletTown_Text_PressStartToOpenMenu::
	.string "CONSIGLI UTILI\p"
	.string "Premi START per aprire il MENU!$"
PalletTown_Text_SignsAreUsefulArentThey::
	.string "Sono utili i cartelli, vero?$"
PalletTown_Text_LookCopiedTrainerTipsSign::
	.string "Guarda qui!\p"
	.string "Ho copiato una frase scritta su\n"
	.string "un cartello di CONSIGLI UTILI.$"
PalletTown_Text_PressStartToOpenMenuCopy::
	.string "CONSIGLI UTILI\p"
	.string "Premi START per aprire il MENU!$"
