VSSeeker_Text_BatteryNotChargedNeedXSteps::
	.string "Non è sufficientemente caricato.\p"
	.string "Passi necessari per caricarlo\n"
	.string "completamente: {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"
VSSeeker_Text_NoTrainersWithinRange::
	.string "Non ci sono ALLENATORI pronti\n"
	.string "a combattere nell'area…\p"
	.string "Il CERCASFIDE è stato spento.{PAUSE_UNTIL_PRESS}$"
VSSeeker_Text_TrainersNotReady::
	.string "Gli altri ALLENATORI non sono\n"
	.string "pronti per lottare.\p"
	.string "Dovrai aspettare un po'.{PAUSE_UNTIL_PRESS}$"
Route3_Text_ColtonRematchIntro::
	.string "Ci siamo già visti a\n"
	.string "BOSCO SMERALDO!$"
Route3_Text_BenRematchIntro::
	.string "Ciao!\n"
	.string "Mi piacciono i pantaloncini corti!\p"
	.string "Sono molto comodi!$"
Route3_Text_JaniceRematchIntro::
	.string "Mi stavi guardando, vero?$"
Route3_Text_GregRematchIntro::
	.string "Sei un ALLENATORE?\n"
	.string "Lottiamo, forza!$"
Route3_Text_SallyRematchIntro::
	.string "Quel tuo sguardo è così intrigante!$"
Route3_Text_CalvinRematchIntro::
	.string "Ehi! Continui a non indossare\n"
	.string "pantaloncini!$"
Route3_Text_JamesRematchIntro::
	.string "Dai, rilottiamo! Così ti faccio\n"
	.string "vedere quanto sono migliorato!$"
Route3_Text_RobinRematchIntro::
	.string "Ehi, mi hai spinto?!$"
Route4_Text_CrissyRematchIntro::
	.string "Il MONTE LUNA è un buon posto per\n"
	.string "catturare POKéMON simili a funghi.$"
Route6_Text_RickyRematchIntro::
	.string "Ah, sei quella mosca fastidiosa che\n"
	.string "origliava i nostri discorsi!$"
Route6_Text_NancyRematchIntro::
	.string "Scusa, non ti avevo detto che\n"
	.string "questa è una conversazione\l"
	.string "privata?!\p"
	.string "Quindi non dovresti origliare,\n"
	.string "giusto?$"
Route6_Text_KeigoRematchIntro::
	.string "Ho provato ad allenare anche altri\n"
	.string "POKéMON, ma alla fine i POKéMON\l"
	.string "COLEOTTERO sono i migliori!$"
Route6_Text_JeffRematchIntro::
	.string "Vuoi lottare di nuovo?$"
Route6_Text_IsabelleRematchIntro::
	.string "Dici a me?\n"
	.string "Bene! Giochiamo!$"
Route6_Text_ElijahRematchIntro::
	.string "Ehi, è un po' che non ci vediamo!\n"
	.string "Hai migliorato la tua tecnica?$"
Route8_Text_AidanRematchIntro::
	.string "Sembri forte con i POKéMON,\n"
	.string "l'ho già notato, ma come vai\l"
	.string "in chimica?$"
Route8_Text_StanRematchIntro::
	.string "Benissimo!\n"
	.string "Il dado è tratto nuovamente!$"
Route8_Text_GlennRematchIntro::
	.string "Ti serve una tattica migliore!\n"
	.string "Segui i miei consigli?$"
Route8_Text_PaigeRematchIntro::
	.string "Ho catturato parecchi NIDORAN.\n"
	.string "Sto pensando di non farli evolvere.$"
Route8_Text_LeslieRematchIntro::
	.string "Mi piace la scuola, ma anche i\n"
	.string "POKéMON!$"
Route8_Text_AndreaRematchIntro::
	.string "MEOWTH e PERSIAN sono così carini!\n"
	.string "Miao!$"
Route8_Text_MeganRematchIntro::
	.string "Ti sembra stupido che ce ne stiamo\n"
	.string "qui in piedi a non fare niente?\p"
	.string "Perché non rilottiamo, allora?$"
Route8_Text_RichRematchIntro::
	.string "Sono un errante RISCHIATUTTO!$"
Route8_Text_JuliaRematchIntro::
	.string "Qual è il POKéMON tondo e morbido?\n"
	.string "Te l'ho già chiesto, vero?$"
Route8_Text_RicardoRematchIntro::
	.string "La mia moto è sempre eccezionale,\n"
	.string "sai?$"
Route8_Text_JarenRematchIntro::
	.string "E va bene, rilottiamo!\n"
	.string "E questa volta, non avrò pietà!$"
Route8_Text_EliRematchIntro::
	.string "ELI: Siamo diventate ancora più\n"
	.string "forti!$"
Route8_Text_AnneRematchIntro::
	.string "ANNE: Siamo ancora più\n"
	.string "affiatate di prima!$"
Route9_Text_AliciaRematchIntro::
	.string "Sei qui per un'altra sfida?\n"
	.string "Questa volta ti batterò!$"
Route9_Text_ChrisRematchIntro::
	.string "Non vi ho dimenticato, tu e la\n"
	.string "tua potente squadra di POKéMON!$"
Route9_Text_DrewRematchIntro::
	.string "Vado a LAVANDONIA attraverso il\n"
	.string "TUNNEL ROCCIOSO.\p"
	.string "Conto di fermarmi a lottare con\n"
	.string "tutti quelli che incontro!$"
Route9_Text_CaitlinRematchIntro::
	.string "Questa volta non mi batterai!$"
Route9_Text_JeremyRematchIntro::
	.string "Ahaha! Che bello!\n"
	.string "Stavo iniziando ad annoiarmi!$"
Route9_Text_BriceRematchIntro::
	.string "Ahaha!\n"
	.string "Ma chi ti credi di essere?!$"
Route9_Text_BrentRematchIntro::
	.string "Mi sveglio presto ogni mattina per\n"
	.string "allenare i miei POKéMON\l"
	.string "COLEOTTERO!$"
Route9_Text_AlanRematchIntro::
	.string "Questa volta vinco io!$"
Route9_Text_ConnerRematchIntro::
	.string "Forza, miei POKéMON COLEOTTERO!\n"
	.string "Questa volta dovete vincere!$"
Route10_Text_MarkRematchIntro::
	.string "Ehi, guarda chi si rivede!\p"
	.string "Vuoi vedere la mia collezione?$"
Route10_Text_ClarkRematchIntro::
	.string "Eccì! Eccì!\p"
	.string "Non riesco a smettere di\n"
	.string "starnutire!$"
Route10_Text_HermanRematchIntro::
	.string "Ehi!\n"
	.string "Ti mostro i miei POKéMON!$"
Route10_Text_HeidiRematchIntro::
	.string "Sono tornata un'altra volta alla\n"
	.string "PALESTRA POKéMON… e ho perso\l"
	.string "di nuovo!$"
Route10_Text_TrentRematchIntro::
	.string "Ah!\n"
	.string "Quest'aria di montagna!$"
Route10_Text_CarolRematchIntro::
	.string "Inizia a girarmi la testa: oggi\n"
	.string "ho scarpinato troppo!$"
Route11_Text_HugoRematchIntro::
	.string "Scommettiamo sulla tua\n"
	.string "sconfitta?\l"
	.string "Dai, inizia la rivincita!$"
Route11_Text_JasperRematchIntro::
	.string "Sfide!\p"
	.string "Non ne ho mai abbastanza, anche\n"
	.string "se l'ultima volta ho perso contro\l"
	.string "di te!$"
Route11_Text_EddieRematchIntro::
	.string "OK, lottiamo!\n"
	.string "Ma non imbrogliare!$"
Route11_Text_BraxtonRematchIntro::
	.string "Attento!\n"
	.string "Sto posando dei cavi!$"
Route11_Text_DillonRematchIntro::
	.string "Sono ALLENATORE da poco!\n"
	.string "Ma penso di poter vincere!$"
Route11_Text_DirkRematchIntro::
	.string "Ihaha!\n"
	.string "Non ho mai perso!$"
Route11_Text_DarianRematchIntro::
	.string "Non ho ancora mai vinto…$"
Route11_Text_YasuRematchIntro::
	.string "Sono il primo della classe!$"
Route11_Text_BernieRematchIntro::
	.string "Attento ai cavi scoperti!$"
Route11_Text_DaveRematchIntro::
	.string "I miei POKéMON dovrebbero essere\n"
	.string "pronti ormai!$"
Route12_Text_NedRematchIntro::
	.string "Sìì! Ha abboccato!$"
Route12_Text_ChipRematchIntro::
	.string "Ci vuole pazienza!\n"
	.string "La pesca richiede tempo!$"
Route12_Text_JustinRematchIntro::
	.string "Hai trovato la PIETRALUNARE?$"
Route12_Text_LucaRematchIntro::
	.string "L'elettricità è la mia specialità!$"
Route12_Text_HankRematchIntro::
	.string "Il PESCATORE PAZZO contro\n"
	.string "l'ALLENATORE in ERBA!$"
Route12_Text_ElliotRematchIntro::
	.string "Preferirei lavorare!\n"
	.string "Te l'ho già detto, forse?$"
Route12_Text_AndrewRematchIntro::
	.string "Cosa sto pescando?\n"
	.string "Se mi batti, potrei dirtelo.$"
Route12_Text_JesRematchIntro::
	.string "JES: Facciamo così: se ti batto,\n"
	.string "chiedo a GIA di sposarmi!$"
Route12_Text_GiaRematchIntro::
	.string "GIA: JES… ormai usciamo insieme\n"
	.string "da così tanto tempo…\p"
	.string "Che ne dici? Se vinciamo questa\n"
	.string "lotta, ci sposiamo!$"
Route13_Text_SebastianRematchIntro::
	.string "I miei POKéMON uccello vogliono\n"
	.string "divertirsi!$"
Route13_Text_SusieRematchIntro::
	.string "Voglio diventare il miglior\n"
	.string "ALLENATORE mentre sono ancora\l"
	.string "una bambina!$"
Route13_Text_ValerieRematchIntro::
	.string "Che belle MEDAGLIE che hai!$"
Route13_Text_GwenRematchIntro::
	.string "I miei cari POKéMON vogliono\n"
	.string "conoscerti.$"
Route13_Text_AlmaRematchIntro::
	.string "Con i miei risparmi, ho un altro\n"
	.string "po' di CARBURANTE!$"
Route13_Text_PerryRematchIntro::
	.string "Ho il vento a favore!\n"
	.string "Questa volta, per davvero!$"
Route13_Text_LolaRematchIntro::
	.string "Ah, sei di nuovo qui!\n"
	.string "Certo che ho voglia di risfidarti!$"
Route13_Text_SheilaRematchIntro::
	.string "Certo che mi ricordo di te!$"
Route13_Text_JaredRematchIntro::
	.string "Cos'hai da guardare?!$"
Route13_Text_RobertRematchIntro::
	.string "Tengo i POKéMON uccello sempre con\n"
	.string "me! Come vedi, non è cambiato\l"
	.string "niente dall'ultima volta!$"
Route14_Text_CarterRematchIntro::
	.string "Ho usato delle MT per insegnare\n"
	.string "buone mosse ai miei POKéMON.$"
Route14_Text_MitchRematchIntro::
	.string "I miei POKéMON uccello sono pronti\n"
	.string "a lottare.$"
Route14_Text_BeckRematchIntro::
	.string "Stai usando le MT sui tuoi\n"
	.string "POKéMON?\p"
	.string "Averle e non usarle non serve\n"
	.string "a niente!$"
Route14_Text_MarlonRematchIntro::
	.string "Hai insegnato il VOLO ai tuoi\n"
	.string "POKéMON uccello?$"
Route14_Text_DonaldRematchIntro::
	.string "La leggenda dei miraggi alati…\p"
	.string "Non dirmi che non ne hai sentito\n"
	.string "parlare?!$"
Route14_Text_BennyRematchIntro::
	.string "Non sono un grande esperto,\n"
	.string "però lottare continua a piacermi!$"
Route14_Text_LukasRematchIntro::
	.string "Ehi!\n"
	.string "Mi ricordo di te!\p"
	.string "Forza! Forza!\n"
	.string "Avanti, andiamo, sottoooo!$"
Route14_Text_IsaacRematchIntro::
	.string "Devo ingannare il tempo, a volte!$"
Route14_Text_GeraldRematchIntro::
	.string "Veniamo qui con la moto perché c'è\n"
	.string "più spazio!$"
Route14_Text_MalikRematchIntro::
	.string "Lotta POKéMON?\n"
	.string "Eccome no!$"
Route14_Text_KiriRematchIntro::
	.string "KIRI: JAN, oggi dobbiamo vincere!$"
Route14_Text_JanRematchIntro::
	.string "JAN: Dai, KIRI!\n"
	.string "Questa volta si vince di sicuro!$"
Route15_Text_KindraRematchIntro::
	.string "Voglio provare i POKéMON che ho\n"
	.string "appena scambiato!$"
Route15_Text_BeckyRematchIntro::
	.string "Sembri debole!\n"
	.string "Penso di poterti vincere\l"
	.string "questa volta!$"
Route15_Text_EdwinRematchIntro::
	.string "Quando fischio, chiamo a raccolta\n"
	.string "i POKéMON uccello!\p"
	.string "Devi vedere che spettacolo!$"
Route15_Text_ChesterRematchIntro::
	.string "I miei uccellini tremano di paura!\n"
	.string "Sei forte, vero?$"
Route15_Text_GraceRematchIntro::
	.string "Oh!\n"
	.string "Sei un tipo simpatico!\l"
	.string "Mi ricordo di te!$"
Route15_Text_OliviaRematchIntro::
	.string "Allevo POKéMON per non sentirmi\n"
	.string "sola.\p"
	.string "Come vedi non ho ancora trovato\n"
	.string "l'anima gemella!$"
Route15_Text_ErnestRematchIntro::
	.string "Ehi tu! Coraggio!\n"
	.string "Guarda cos'ho!$"
Route15_Text_AlexRematchIntro::
	.string "O la borsa, o la vita!$"
Route15_Text_CeliaRematchIntro::
	.string "Cos'è bello?\n"
	.string "Scambiar POKéMON!$"
Route15_Text_YazminRematchIntro::
	.string "Vuoi giocare con i miei POKéMON\n"
	.string "ancora una volta?$"
Route15_Text_MyaRematchIntro::
	.string "MYA: Ehi, ci si rincontra!\p"
	.string "Vuoi aiutarmi di nuovo ad\n"
	.string "allenare il mio fratellino?$"
Route15_Text_RonRematchIntro::
	.string "RON: Mia sorella è diventata\n"
	.string "ancora più forte!$"
Route16_Text_LaoRematchIntro::
	.string "Che vuoi?$"
Route16_Text_KojiRematchIntro::
	.string "Bella BICICLETTA!\n"
	.string "Da' qua!$"
Route16_Text_LukeRematchIntro::
	.string "Vieni a giocare, pulce!\n"
	.string "Questa volta ti concio per le\l"
	.string "feste!$"
Route16_Text_HideoRematchIntro::
	.string "Ehi!\n"
	.string "Mi hai urtato un'altra volta!$"
Route16_Text_CamronRematchIntro::
	.string "Ho fame e mi sto arrabbiando\n"
	.string "sul serio, questa volta!$"
Route16_Text_RubenRematchIntro::
	.string "Ehi, divertiamoci con un'altra\n"
	.string "bella lotta!$"
Route16_Text_JedRematchIntro::
	.string "JED: Sei qui per contemplare\n"
	.string "la grandezza sconfinata del\l"
	.string "nostro amore?$"
Route16_Text_LeaRematchIntro::
	.string "LEA: A volte sono spaventata\n"
	.string "dall'intensità del nostro amore.$"
Route17_Text_RaulRematchIntro::
	.string "Non vale la pena lottare con i\n"
	.string "bambini!\l"
	.string "Mi sembra di avertelo già detto!$"
Route17_Text_IsaiahRematchIntro::
	.string "Che vuoi, pulce? Di nuovo qui?$"
Route17_Text_VirgilRematchIntro::
	.string "Ti stai facendo un giretto?$"
Route17_Text_BillyRematchIntro::
	.string "Siamo CENTAURI!\n"
	.string "Dei campioni!$"
Route17_Text_NikolasRematchIntro::
	.string "Oggi VOLTORB ti elettrizzerà, sul\n"
	.string "serio!$"
Route17_Text_ZeekRematchIntro::
	.string "I miei POKéMON non si evolvono!\n"
	.string "Perché? Te l'ho già chiesto?$"
Route17_Text_JamalRematchIntro::
	.string "Ho bisogno di un po' d'esercizio!$"
Route17_Text_CoreyRematchIntro::
	.string "Sii ribelle!$"
Route17_Text_JaxonRematchIntro::
	.string "Bella BICICLETTA!\n"
	.string "Come funziona?$"
Route17_Text_WilliamRematchIntro::
	.string "Sparisci, pulce!\n"
	.string "Sono esausto!$"
Route18_Text_WiltonRematchIntro::
	.string "Ho setacciato tutte le zone\n"
	.string "erbose alla ricerca di nuove\l"
	.string "specie di POKéMON!\p"
	.string "Ma non è così facile!$"
Route18_Text_RamiroRematchIntro::
	.string "Cu cu cu!\n"
	.string "Il mio richiamo è un po'\l"
	.string "migliorato?$"
Route18_Text_JacobRematchIntro::
	.string "Questo è il mio territorio!\n"
	.string "Ti avevo già avvertito!\l"
	.string "Via!$"
Route19_Text_RichardRematchIntro::
	.string "Sto finendo il riscaldamento, prima\n"
	.string "di nuotare.$"
Route19_Text_ReeceRematchIntro::
	.string "Aspetta!\n"
	.string "Ti verrà un accidente!$"
Route19_Text_MatthewRematchIntro::
	.string "Mi piace nuotare!\n"
	.string "E a te?$"
Route19_Text_DouglasRematchIntro::
	.string "Che c'è oltre l'orizzonte?$"
Route19_Text_DavidRematchIntro::
	.string "Mi sono tuffato per prendere dei\n"
	.string "POKéMON, ma zero come sempre!$"
Route19_Text_TonyRematchIntro::
	.string "Guardo il mare per dimenticare,\n"
	.string "soprattutto la sconfitta di prima!$"
Route19_Text_AnyaRematchIntro::
	.string "Dev'essere rilassante fare SURF sul\n"
	.string "tuo POKéMON.\l"
	.string "Se vinco, me lo presti?$"
Route19_Text_AliceRematchIntro::
	.string "Nuotare è bello!\n"
	.string "Scottarsi al sole invece no!$"
Route19_Text_AxleRematchIntro::
	.string "Cosa ci fai di nuovo qui?\n"
	.string "Queste acque sono pericolose!$"
Route19_Text_ConnieRematchIntro::
	.string "Ho nuotato fin qui con i miei\n"
	.string "POKéMON e adesso sono stanca!\p"
	.string "Vuoi proprio sfidarmi di nuovo?$"
Route19_Text_LiaRematchIntro::
	.string "LIA: Ti ricordi che mio fratello è\n"
	.string "appena diventato ALLENATORE, vero?\p"
	.string "Lo sto allenando, e ho di nuovo\n"
	.string "bisogno del tuo aiuto!$"
Route19_Text_LucRematchIntro::
	.string "SAM: La mia sorellona mi ha\n"
	.string "insegnato tutto sui POKéMON.\p"
	.string "Forse ora sono persino più forte\n"
	.string "di lei!$"
Route20_Text_BarryRematchIntro::
	.string "Qui l'acqua non è profonda.$"
Route20_Text_ShirleyRematchIntro::
	.string "Sono in vacanza alle ISOLE\n"
	.string "SPUMARINE!$"
Route20_Text_TiffanyRematchIntro::
	.string "Nuotare con i pesci!\n"
	.string "Mi piace sempre di più!$"
Route20_Text_IreneRematchIntro::
	.string "Sei qui in vacanza anche tu?$"
Route20_Text_DeanRematchIntro::
	.string "Guarda che fisico che ho!\p"
	.string "Non ti sembra ancora più\n"
	.string "possente dell'altra volta?$"
Route20_Text_DarrinRematchIntro::
	.string "Perché fai SURF su di un POKéMON?\n"
	.string "Non hai ancora imparato a nuotare?$"
Route20_Text_RogerRematchIntro::
	.string "Sono arrivato a dorso del mio\n"
	.string "POKéMON uccello!$"
Route20_Text_NoraRematchIntro::
	.string "Il mio ragazzo mi ha dato delle\n"
	.string "grandi perle, che sono diventate\l"
	.string "ancora più grosse!$"
Route20_Text_MissyRematchIntro::
	.string "Sono venuta a nuoto dall'ISOLA\n"
	.string "CANNELLA!\p"
	.string "Te l'ho già detto?\n"
	.string "Lo so, sono ripetitiva!$"
Route20_Text_MelissaRematchIntro::
	.string "C'è un LABORATORIO POKéMON a\n"
	.string "ovest, sull'ISOLA CANNELLA.\p"
	.string "Mio papà lavora lì!$"
Route21_North_Text_RonaldRematchIntro::
	.string "Vuoi sapere se i pesci abboccano?$"
Route21_North_Text_WadeRematchIntro::
	.string "Ho pescato dei bei POKéMON!\n"
	.string "Vuoi lottare di nuovo?$"
Route21_North_Text_SpencerRematchIntro::
	.string "Il mare pulisce il corpo e l'anima!$"
Route21_North_Text_CueBallRematchIntro::
	.string "Ê;Âó Èùぎà\n"
	.string "ÊÙまっŒぜ$"
Route21_South_Text_JackRematchIntro::
	.string "Ho catturato i miei POKéMON in\n"
	.string "mare, ed è qui che li alleno.$"
Route21_South_Text_JeromeRematchIntro::
	.string "Sto andando a fare un'altra gara\n"
	.string "di triathlon!$"
Route21_South_Text_RolandRematchIntro::
	.string "Ah!\n"
	.string "Senti il sole e il vento!$"
Route21_South_Text_ClaudeRematchIntro::
	.string "Ehi, ci hai preso proprio gusto a\n"
	.string "spaventarmi i pesci!$"
Route21_South_Text_NolanRematchIntro::
	.string "Fammi compagnia finché non prendo\n"
	.string "qualcosa!$"
Route21_North_Text_LilRematchIntro::
	.string "LIL: Un'altra lotta? IAN, non ce\n"
	.string "la fai a combattere da solo?$"
Route21_North_Text_IanRematchIntro::
	.string "IAN: Mia sorella continua a essere\n"
	.string "una pigrona!\p"
	.string "Aiutami a farla diventare un po'\n"
	.string "più attiva, altrimenti non dimagrirà\l"
	.string "mai!$"
Route25_Text_JoeyRematchIntro::
	.string "Non credere di battermi di nuovo!$"
Route25_Text_DanRematchIntro::
	.string "Papà mi ha portato a una bella\n"
	.string "festa sulla M/N ANNA ad\l"
	.string "ARANCIOPOLI!$"
Route25_Text_FlintRematchIntro::
	.string "Sono un tipo giusto, io!\n"
	.string "Ho la ragazza!\p"
	.string "Sempre la stessa di prima!$"
Route25_Text_KelseyRematchIntro::
	.string "Ciao!\n"
	.string "Il mio ragazzo è forte!\p"
	.string "E oggi anch'io sono al top!$"
Route25_Text_ChadRematchIntro::
	.string "Lo sapevo che ci saremmo\n"
	.string "scontrati ancora una volta!$"
Route25_Text_HaleyRematchIntro::
	.string "Il mio amico ha un POKéMON così\n"
	.string "dolce…\p"
	.string "Crepo dall'invidia!$"
Route25_Text_FranklinRematchIntro::
	.string "Ho appena lottato sul MONTE LUNA,\n"
	.string "ma non mi è certo passata la\l"
	.string "voglia!$"
Route25_Text_NobRematchIntro::
	.string "Vado al capo a trovare un\n"
	.string "collezionista di POKéMON!\p"
	.string "Hai visto la sua collezione?$"
Route25_Text_WayneRematchIntro::
	.string "Stai andando da BILL?\n"
	.string "Prima però in guardia!$"
Route24_Text_ShaneRematchIntro::
	.string "Ti ho visto tra l'erba!\n"
	.string "Di nuovo!$"
Route24_Text_EthanRematchIntro::
	.string "OK!\n"
	.string "Ti polverizzerò!$"
Route24_Text_ReliRematchIntro::
	.string "Hai sempre così tanta energia!\n"
	.string "Non ti stanchi mai?$"
Route24_Text_TimmyRematchIntro::
	.string "Ti piace venire al PONTE PEPITA,\n"
	.string "eh?$"
Route24_Text_AliRematchIntro::
	.string "È vero che ho perso, prima, ma\n"
	.string "sono comunque la vincitrice morale,\l"
	.string "vero?$"
Route24_Text_CaleRematchIntro::
	.string "Questo è il PONTE PEPITA.\p"
	.string "Ci hai già battuto prima, però\n"
	.string "possiamo lottare di nuovo, se\l"
	.string "vuoi!$"
OneIsland_TreasureBeach_Text_AmaraRematchIntro::
	.string "Galleggiando sul dorso, cullata\n"
	.string "dalle onde, non mi accorgo del\l"
	.string "tempo che passa!$"
OneIsland_KindleRoad_Text_MariaRematchIntro::
	.string "Che tempo magnifico!\n"
	.string "Il tempo perfetto per una\l"
	.string "vittoria!$"
OneIsland_KindleRoad_Text_AbigailRematchIntro::
	.string "La mia scottatura inizia a fare\n"
	.string "male!$"
OneIsland_KindleRoad_Text_FinnRematchIntro::
	.string "La montagna dell'uccello di fuoco\n"
	.string "proietta un'ombra mastodontica!$"
OneIsland_KindleRoad_Text_GarrettRematchIntro::
	.string "Questa volta penso proprio di poter\n"
	.string "vincere!$"
OneIsland_KindleRoad_Text_TommyRematchIntro::
	.string "Aspetta! Aspetta un secondo!\n"
	.string "Sono sicuro che ha abboccato\l"
	.string "un pesce enorme!$"
OneIsland_KindleRoad_Text_SharonRematchIntro::
	.string "Sei qui per aiutarmi di nuovo\n"
	.string "ad allenarmi?$"
OneIsland_KindleRoad_Text_TanyaRematchIntro::
	.string "Finora non abbiamo perso un solo\n"
	.string "giorno di allenamento!$"
OneIsland_KindleRoad_Text_SheaRematchIntro::
	.string "Ogni mattina, prima di colazione,\n"
	.string "faccio tre giri intorno all'isola!$"
OneIsland_KindleRoad_Text_HughRematchIntro::
	.string "Non ti ho già detto che devi\n"
	.string "vestirti in modo appropriato\l"
	.string "per lottare?$"
OneIsland_KindleRoad_Text_BryceRematchIntro::
	.string "In mezzo alla natura, il cibo ha\n"
	.string "un sapore più intenso.$"
OneIsland_KindleRoad_Text_ClaireRematchIntro::
	.string "Ho di nuovo mangiato troppo!\n"
	.string "Lottiamo un po', così smaltisco!$"
OneIsland_KindleRoad_Text_KiaRematchIntro::
	.string "KIA: Io e il mio fratellone siamo\n"
	.string "una coppia fantastica!\p"
	.string "Questa volta non perderemo!$"
OneIsland_KindleRoad_Text_MikRematchIntro::
	.string "MIK: Insieme a KIA, niente mi fa\n"
	.string "paura!\p"
	.string "E questa volta, te lo\n"
	.string "dimostreremo!$"
ThreeIsland_BondBridge_Text_NikkiRematchIntro::
	.string "Lottiamo di nuovo?$"
ThreeIsland_BondBridge_Text_VioletRematchIntro::
	.string "Da dove vieni, e dov'è diretto il\n"
	.string "tuo cammino?$"
ThreeIsland_BondBridge_Text_AmiraRematchIntro::
	.string "Presto saprò nuotare senza\n"
	.string "salvagente!$"
ThreeIsland_BondBridge_Text_AlexisRematchIntro::
	.string "Yuppi, yuppi, POKéMON!$"
ThreeIsland_BondBridge_Text_TishaRematchIntro::
	.string "Non ti avevo già detto di stare\n"
	.string "alla larga?$"
ThreeIsland_BondBridge_Text_JoyRematchIntro::
	.string "JOY: Ora siamo più forti, ma di\n"
	.string "molto!$"
ThreeIsland_BondBridge_Text_MegRematchIntro::
	.string "IDA: Oggi non potrai batterci!$"
FiveIsland_WaterLabyrinth_Text_AlizeRematchIntro::
	.string "Stai allenando i tuoi POKéMON\n"
	.string "in un ambiente salutare?$"
FiveIsland_ResortGorgeous_Text_DaisyRematchIntro::
	.string "Oggi costruirò la vittoria con le\n"
	.string "mie stesse mani!$"
FiveIsland_ResortGorgeous_Text_CelinaRematchIntro::
	.string "Non farmi ripetere sempre le stesse\n"
	.string "cose: sto dipingendo e non voglio\l"
	.string "essere disturbata!$"
FiveIsland_ResortGorgeous_Text_RaynaRematchIntro::
	.string "Non ho fatto progressi. Continuo a\n"
	.string "sbagliare la prospettiva.$"
FiveIsland_ResortGorgeous_Text_JackiRematchIntro::
	.string "Hai deciso di concedermi la\n"
	.string "rivincita?$"
FiveIsland_ResortGorgeous_Text_GillianRematchIntro::
	.string "La piscina per i miei POKéMON è\n"
	.string "quasi terminata.\p"
	.string "Appena è pronta ti invito a casa\n"
	.string "mia!$"
FiveIsland_ResortGorgeous_Text_DestinRematchIntro::
	.string "Sono un buon corridore! Ora\n"
	.string "sono ancora più veloce!$"
FiveIsland_ResortGorgeous_Text_TobyRematchIntro::
	.string "Io e te siamo amici, vero?\n"
	.string "E allora, lottiamo!$"
FiveIsland_MemorialPillar_Text_MiloRematchIntro::
	.string "Sono il più vecchio dei FRATELLI\n"
	.string "VOLANTI. Ti ricordi di me?\p"
	.string "Sì, sono quello che dei volatili\n"
	.string "apprezza soprattutto il becco!$"
FiveIsland_MemorialPillar_Text_ChazRematchIntro::
	.string "Dei FRATELLI VOLANTI, sono quello\n"
	.string "di mezzo.\p"
	.string "Sono quello che degli uccelli\n"
	.string "apprezza soprattutto le ali!$"
FiveIsland_MemorialPillar_Text_HaroldRematchIntro::
	.string "Sono il più giovane dei FRATELLI\n"
	.string "VOLANTI.\p"
	.string "Sono quello che ama i volatili\n"
	.string "soprattutto per le piume.\l"
	.string "Non pensavo di rivederti qui!$"
SixIsland_OutcastIsland_Text_TylorRematchIntro::
	.string "Continuo a non avere nessuna\n"
	.string "fortuna.\p"
	.string "Mi ci vorrebbe una vittoria, per\n"
	.string "risollevarmi il morale!$"
SixIsland_OutcastIsland_Text_MymoRematchIntro::
	.string "Gasp… Gasp…\p"
	.string "Ho di nuovo nuotato fin qui da\n"
	.string "SESTISOLA senza mai fermarmi!$"
SixIsland_OutcastIsland_Text_NicoleRematchIntro::
	.string "Arrivi sempre quando sto nuotando!$"
SixIsland_OutcastIsland_Text_AvaRematchIntro::
	.string "AVA: Facciamoci un'altra lotta\n"
	.string "2 contro 2 in mezzo al mare!$"
SixIsland_OutcastIsland_Text_GebRematchIntro::
	.string "GEB: Io e la mia sorellona non\n"
	.string "siamo mai stati così forti!$"
SixIsland_GreenPath_Text_JaclynRematchIntro::
	.string "…Huh?\p"
	.string "Non capisco: mi concentro su casa\n"
	.string "mia, però TELETRASPORTO mi porta\l"
	.string "sempre qui!$"
SixIsland_WaterPath_Text_RoseRematchIntro::
	.string "Ah, ciao!\n"
	.string "Soffia di nuovo una dolce\l"
	.string "brezza, come l'altra volta!$"
SixIsland_WaterPath_Text_EdwardRematchIntro::
	.string "Mi sto di nuovo allenando\n"
	.string "in segreto!$"
SixIsland_WaterPath_Text_SamirRematchIntro::
	.string "Davvero non ce la fai più\n"
	.string "a vedere NUOTATORI come me?\p"
	.string "E dai, non te la prendere!\n"
	.string "Lottiamo un po', su!$"
SixIsland_WaterPath_Text_DeniseRematchIntro::
	.string "Sigh…\n"
	.string "Il mio ragazzo è di nuovo\l"
	.string "occupatissimo…$"
SixIsland_WaterPath_Text_EarlRematchIntro::
	.string "Scusa, sai se ci sono montagne\n"
	.string "da queste parti?$"
SixIsland_WaterPath_Text_MiuRematchIntro::
	.string "MIU: POKéMON, è di nuovo il\n"
	.string "momento di giocare!$"
SixIsland_WaterPath_Text_MiaRematchIntro::
	.string "MIA: POKéMON, è di nuovo il\n"
	.string "momento di lottare!$"
SixIsland_RuinValley_Text_StanlyRematchIntro::
	.string "In questo mondo ci sono ancora\n"
	.string "così tanti segreti da scoprire!$"
SixIsland_RuinValley_Text_FosterRematchIntro::
	.string "Non ci siamo già incontrati?\n"
	.string "Cosa ti ha spinto a ritornare?$"
SixIsland_RuinValley_Text_LarryRematchIntro::
	.string "Pare che ci siano strane pietre su\n"
	.string "quest'isola.\p"
	.string "Hai scoperto qualcosa dall'ultima\n"
	.string "volta che ci siamo visti?$"
SixIsland_RuinValley_Text_DarylRematchIntro::
	.string "Vuoi lottare di nuovo?\n"
	.string "E perché no?$"
SixIsland_RuinValley_Text_HectorRematchIntro::
	.string "Conosco molto bene questi posti.$"
SevenIsland_TrainerTower_Text_DarioRematchIntro::
	.string "Ho presagito il tuo arrivo!$"
SevenIsland_TrainerTower_Text_RodetteRematchIntro::
	.string "Da qualche parte sull'isola, ci\n"
	.string "sono POKéMON che dormono.$"
SevenIsland_SevaultCanyon_Entrance_Text_MiahRematchIntro::
	.string "Non so se hai fatto bene a\n"
	.string "tornare! Sto per distruggerti!$"
SevenIsland_SevaultCanyon_Entrance_Text_MasonRematchIntro::
	.string "Ciao! Hai la tessera del mio\n"
	.string "fan club, vero?$"
SevenIsland_SevaultCanyon_Entrance_Text_NicolasRematchIntro::
	.string "Quest'isola è troppo grande!\n"
	.string "Continuo ad avere problemi\l"
	.string "a pattugliarla!$"
SevenIsland_SevaultCanyon_Entrance_Text_MadelineRematchIntro::
	.string "Non perdono chi fa male ai miei\n"
	.string "POKéMON!$"
SevenIsland_SevaultCanyon_Entrance_Text_EveRematchIntro::
	.string "EVE: Io e JON vogliamo la\n"
	.string "rivincita!$"
SevenIsland_SevaultCanyon_Entrance_Text_JonRematchIntro::
	.string "JON: Con EVE, è come se non\n"
	.string "potessimo mai perdere.$"
SevenIsland_SevaultCanyon_Text_CyndyRematchIntro::
	.string "Dai lottiamo! Ero già in forma,\n"
	.string "ma ora lo sono ancora di più!$"
SevenIsland_SevaultCanyon_Text_EvanRematchIntro::
	.string "Non importa che tu abbia i POKéMON\n"
	.string "migliori.\p"
	.string "Se non sai utilizzarli al meglio,\n"
	.string "perdi comunque.\l"
	.string "Te l'avevo già detto?$"
SevenIsland_SevaultCanyon_Text_JacksonRematchIntro::
	.string "Lavoro per proteggere l'ambiente. E\n"
	.string "l'ambiente mi protegge a sua volta.\p"
	.string "Dico sempre le stesse cose, lo so.$"
SevenIsland_SevaultCanyon_Text_KatelynRematchIntro::
	.string "Ogni volta che ci incontriamo\n"
	.string "indossi sempre quelle scarpe\l"
	.string "stupende!$"
SevenIsland_SevaultCanyon_Text_LeroyRematchIntro::
	.string "Chissà come sei forte ora!\n"
	.string "Dai, lottiamo! Voglio vedere!$"
SevenIsland_SevaultCanyon_Text_MichelleRematchIntro::
	.string "Ho ricevuto i migliori insegnamenti\n"
	.string "per giungere a questi livelli.\p"
	.string "Non perderò un'altra volta!$"
SevenIsland_SevaultCanyon_Text_LexRematchIntro::
	.string "PAUL: YUKI, mia cara, insieme non\n"
	.string "possiamo proprio perdere!$"
SevenIsland_SevaultCanyon_Text_NyaRematchIntro::
	.string "YUKI: Non farò certamente perdere\n"
	.string "il mio maestro, PAUL!$"
SevenIsland_TanobyRuins_Text_BrandonRematchIntro::
	.string "Hai scoperto qualcosa sulla\n"
	.string "sala di pietra?$"
SevenIsland_TanobyRuins_Text_BenjaminRematchIntro::
	.string "Pare che qui dentro dorma un\n"
	.string "POKéMON speciale!$"
SevenIsland_TanobyRuins_Text_EdnaRematchIntro::
	.string "Il mio maestro mi sta dando altre\n"
	.string "lezioni di pittura.$"
SevenIsland_TanobyRuins_Text_CliffordRematchIntro::
	.string "Oggi, oltre alla lezione, torneremo\n"
	.string "a vedere la cripta!$"
