SevenIsland_SevaultCanyon_Text_CyndyIntro::
	.string "Sono in piena forma!$"

SevenIsland_SevaultCanyon_Text_CyndyDefeat::
	.string "Ehi!\n"
	.string "C'è qualcosa che non va!$"

SevenIsland_SevaultCanyon_Text_CyndyPostBattle::
	.string "Alla fine, non credo di essere in\n"
	.string "forma per la TORRE ALLENATORI.$"

SevenIsland_SevaultCanyon_Text_EvanIntro::
	.string "Non importa che tu abbia i POKéMON\n"
	.string "migliori.\p"
	.string "Se non sai utilizzarli al meglio,\n"
	.string "perdi comunque.$"

SevenIsland_SevaultCanyon_Text_EvanDefeat::
	.string "Complimenti, vedo che sai usare al\n"
	.string "meglio la tua squadra.$"

SevenIsland_SevaultCanyon_Text_EvanPostBattle::
	.string "Troppo spesso vedo ALLENATORI che\n"
	.string "hanno POKéMON fortissimi, ma non\l"
	.string "sanno utilizzarli.\p"
	.string "POKéMON potenti hanno bisogno di\n"
	.string "ALLENATORI capaci.$"

SevenIsland_SevaultCanyon_Text_JacksonIntro::
	.string "Lavoro per proteggere l'ambiente. E\n"
	.string "l'ambiente mi protegge a sua volta.$"

SevenIsland_SevaultCanyon_Text_JacksonDefeat::
	.string "Sei forte. Ora mi sento protetto\n"
	.string "anche da te!$"

SevenIsland_SevaultCanyon_Text_JacksonPostBattle::
	.string "La terra non è che una goccia\n"
	.string "d'acqua nel mare dell'universo.\p"
	.string "Ma preservare quella goccia\n"
	.string "d'acqua è il compito di tutti.$"

SevenIsland_SevaultCanyon_Text_KatelynIntro::
	.string "Che belle scarpe! Vedo che vesti\n"
	.string "alla moda!$"

SevenIsland_SevaultCanyon_Text_KatelynDefeat::
	.string "Non solo ti sai vestire, ma sai\n"
	.string "anche combattere!$"

SevenIsland_SevaultCanyon_Text_KatelynPostBattle::
	.string "Tua mamma ti ha comprato quelle\n"
	.string "belle SCARPE da CORSA?\l"
	.string "Che brava!$"

SevenIsland_SevaultCanyon_Text_LeroyIntro::
	.string "Mi sembri forte. Lottiamo?$"

SevenIsland_SevaultCanyon_Text_LeroyDefeat::
	.string "Lo sapevo! Sei proprio forte come\n"
	.string "pensavo!$"

SevenIsland_SevaultCanyon_Text_LeroyPostBattle::
	.string "Ho imparato molto studiando il modo\n"
	.string "in cui combatti!$"

SevenIsland_SevaultCanyon_Text_MichelleIntro::
	.string "Mi sono allenata con i migliori\n"
	.string "ALLENATORI per raggiungere\l"
	.string "questo livello. Non posso perdere.$"

SevenIsland_SevaultCanyon_Text_MichelleDefeat::
	.string "Grazie! Ora so che posso anche\n"
	.string "perdere!$"

SevenIsland_SevaultCanyon_Text_MichellePostBattle::
	.string "Non so perché, ma oggi sono\n"
	.string "tesa come una corda di violino.\p"
	.string "Mi calmerò facendo qualche\n"
	.string "esercizio di respirazione.$"

SevenIsland_SevaultCanyon_Text_LexIntro::
	.string "PAUL: Dai, YUKI! Insieme possiamo\n"
	.string "farcela!$"

SevenIsland_SevaultCanyon_Text_LexDefeat::
	.string "PAUL: Ho affrontato questa lotta\n"
	.string "con troppa sicurezza!$"

SevenIsland_SevaultCanyon_Text_LexPostBattle::
	.string "PAUL: Questa lotta è stata\n"
	.string "un'ottima esperienza per YUKI.\l"
	.string "Grazie!$"

SevenIsland_SevaultCanyon_Text_LexNotEnoughMons::
	.string "PAUL: Io e YUKI vorremmo\n"
	.string "affrontarti insieme.\p"
	.string "Ciò significa che ti servono almeno\n"
	.string "due POKéMON!$"

SevenIsland_SevaultCanyon_Text_NyaIntro::
	.string "YUKI: Farò del mio meglio per non\n"
	.string "deludere PAUL, il mio maestro!$"

SevenIsland_SevaultCanyon_Text_NyaDefeat::
	.string "YUKI: Oh, no! Scusami, PAUL!$"

SevenIsland_SevaultCanyon_Text_NyaPostBattle::
	.string "YUKI: Credo di dover migliorare\n"
	.string "ancora molto, sotto la guida di\l"
	.string "PAUL.\p"
	.string "PAUL, ti prego, posso continuare ad\n"
	.string "allenarmi insieme a te?$"

SevenIsland_SevaultCanyon_Text_NyaNotEnoughMons::
	.string "YUKI: Preferisco le lotte 2 contro\n"
	.string "2.\p"
	.string "Quindi dovresti avere almeno due\n"
	.string "POKéMON in squadra.$"

SevenIsland_SevaultCanyon_Text_RouteSign::
	.string "CANYON SEPTION\n"
	.string "Per le ROVINE FLORABETO$"

SevenIsland_SevaultCanyon_Text_BrunoTrainedWithBrawly::
	.string "Non c'è niente di male\n"
	.string "nell'allenarsi in solitudine.\p"
	.string "Ma c'è chi preferisce cercare di\n"
	.string "raggiungere la perfezione con un\l"
	.string "compagno.\p"
	.string "BRUNO stesso si è allenato per\n"
	.string "parecchio tempo con un amico,\l"
	.string "un certo BRAWLY.$"

