LavenderTown_Text_DoYouBelieveInGhosts::
	.string "Credi agli spettri?$"

LavenderTown_Text_SoThereAreBelievers::
	.string "Davvero?\n"
	.string "Non farmi ridere!$"

LavenderTown_Text_JustImaginingWhiteHand::
	.string "Ahahah!\n"
	.string "Cos'è quella mano bianca sulla tua\l"
	.string "spalla?\p"
	.string "…No, scusa, l'avevo solo\n"
	.string "immaginata.$"

LavenderTown_Text_TownKnownAsMonGraveSite::
	.string "Questa città è nota come il\n"
	.string "cimitero dei POKéMON.\p"
	.string "I funerali si celebrano nella TORRE\n"
	.string "POKéMON.$"

LavenderTown_Text_GhostsAppearedInTower::
	.string "Sono apparsi degli spettri nella\n"
	.string "TORRE POKéMON.\p"
	.string "Sono gli spiriti dei POKéMON\n"
	.string "uccisi dai ROCKET.$"

LavenderTown_Text_TownSign::
	.string "LAVANDONIA\n"
	.string "Nobile città viola$"

LavenderTown_Text_SilphScopeNotice::
	.string "La nuova SPETTROSONDA!\n"
	.string "Rende visibile l'invisibile!\p"
	.string "SILPH SpA$"

LavenderTown_Text_VolunteerPokemonHouse::
	.string "CENTRO POKéMON VOLONTARIO di\n"
	.string "LAVANDONIA$"

LavenderTown_Text_PokemonTowerSign::
	.string "TORRE POKéMON\n"
	.string "Che le anime dei POKéMON riposino \l"
	.string "in pace!$"

