PokemonMansion_Text_PressSecretSwitchJP::
	.string "éîÚç )¡ッチが Àñ!\p"
	.string "ÈÏÛ îまÒÉ?$"

PokemonMansion_Text_LetsTryIt::
	.string "ÈÏÛîùÂ! …ポチッÑß$"

PokemonMansion_Text_GaveUpOnPressingSwitch::
	.string "ÈÒçè ÀÊúòŒ$"

PokemonMansion_1F_Text_SimonIntro::
	.string "Questo posto è gigantesco!$"

PokemonMansion_1F_Text_SimonDefeat::
	.string "Ahi!$"

PokemonMansion_1F_Text_SimonPostBattle::
	.string "Mi domando dove sia il mio amico.$"

PokemonMansion_1F_Text_BraydonIntro::
	.string "Il mio maestro viveva qui.$"

PokemonMansion_1F_Text_BraydonDefeat::
	.string "Wow!\n"
	.string "Impressionante!$"

PokemonMansion_1F_Text_BraydonPostBattle::
	.string "Non riesci a proseguire?\n"
	.string "Prova a saltare da lì!$"

PokemonMansion_1F_Text_MewGaveBirthToMewtwo::
	.string "Diario: 6 febbraio\n"
	.string "MEW ha dato alla luce\l"
	.string "un nuovo POKéMON.\p"
	.string "Abbiamo chiamato MEWTWO\n"
	.string "il piccolo.$"

