LavenderTown_PokemonCenter_1F_Text_RocketsDoAnythingForMoney::
	.string "TEAM ROCKET farebbe ogni cosa per\n"
	.string "l'oro!$"

LavenderTown_PokemonCenter_1F_Text_CubonesMotherKilledByRockets::
	.string "La madre di CUBONE è morta\n"
	.string "cercando di scappare da TEAM\l"
	.string "ROCKET!$"

LavenderTown_PokemonCenter_1F_Text_PeoplePayForCuboneSkulls::
	.string "I CUBONE portano dei teschi, vero?\p"
	.string "C'è chi pagherebbe oro per averli!$"

