Route17_Text_RaulIntro::
	.string "Non vale la pena lottare con i\n"
	.string "bambini!$"

Route17_Text_RaulDefeat::
	.string "Sono fritto!$"

Route17_Text_RaulPostBattle::
	.string "Lungo la PISTA CICLABILE trovi\n"
	.string "cose utili!$"

Route17_Text_IsaiahIntro::
	.string "Che vuoi, pulce?$"

Route17_Text_IsaiahDefeat::
	.string "Ooohhh!$"

Route17_Text_IsaiahPostBattle::
	.string "Potrei scaraventarti via di qui a\n"
	.string "panciate!$"

Route17_Text_VirgilIntro::
	.string "Vai verso FUCSIAPOLI?$"

Route17_Text_VirgilDefeat::
	.string "Impanato e fritto!$"

Route17_Text_VirgilPostBattle::
	.string "Mi piace correre in discesa.$"

Route17_Text_BillyIntro::
	.string "Siamo CENTAURI!\n"
	.string "Veri campioni!$"

Route17_Text_BillyDefeat::
	.string "Affumicato!$"

Route17_Text_BillyPostBattle::
	.string "Sei in cerca del brivido?$"

Route17_Text_NikolasIntro::
	.string "Troverai VOLTORB elettrizzante!$"

Route17_Text_NikolasDefeat::
	.string "Ridotto in poltiglia!$"

Route17_Text_NikolasPostBattle::
	.string "Ho catturato il mio VOLTORB alla\n"
	.string "CENTRALE ELETTRICA\l"
	.string "abbandonata!$"

Route17_Text_ZeekIntro::
	.string "I miei POKéMON non si evolvono!\n"
	.string "Perché?$"

Route17_Text_ZeekDefeat::
	.string "Tu!\n"
	.string "Cosa hai fatto?!$"

Route17_Text_ZeekPostBattle::
	.string "Alcuni POKéMON hanno bisogno di\n"
	.string "PIETRE elemento per evolversi.$"

Route17_Text_JamalIntro::
	.string "Ho bisogno di un po' d'esercizio!$"

Route17_Text_JamalDefeat::
	.string "Uff!\n"
	.string "Questo sì che è esercizio!$"

Route17_Text_JamalPostBattle::
	.string "Sono sicuramente dimagrito!$"

Route17_Text_CoreyIntro::
	.string "Sii ribelle!$"

Route17_Text_CoreyDefeat::
	.string "Grrr!$"

Route17_Text_CoreyPostBattle::
	.string "Non rinunciare mai a lottare per\n"
	.string "le tue idee!$"

Route17_Text_JaxonIntro::
	.string "Bella BICICLETTA!\n"
	.string "Come funziona?$"

Route17_Text_JaxonDefeat::
	.string "Che schianti!$"

Route17_Text_JaxonPostBattle::
	.string "È difficile sterzare in discesa!$"

Route17_Text_WilliamIntro::
	.string "Sparisci, pulce!\n"
	.string "Sono esausto!$"

Route17_Text_WilliamDefeat::
	.string "Sei felice adesso?$"

Route17_Text_WilliamPostBattle::
	.string "Devo recuperare il sonno perduto!$"

Route17_Text_WatchOutForDiscardedItems::
	.string "Un avviso!\p"
	.string "Attenzione agli strumenti\n"
	.string "abbandonati!$"

Route17_Text_SameSpeciesGrowDifferentRates::
	.string "CONSIGLI UTILI\p"
	.string "Tutti i POKéMON sono diversi.\p"
	.string "POKéMON della stessa specie e\n"
	.string "e di uguale livello crescono a\l"
	.string "ritmi diversi.$"

Route17_Text_PressBToStayInPlace::
	.string "CONSIGLI UTILI\p"
	.string "Premi il pulsante B per restare in\n"
	.string "equilibrio in discesa.$"

Route17_Text_RouteSign::
	.string "PERCORSO 17\n"
	.string "AZZURROPOLI - FUCSIAPOLI$"

Route17_Text_DontThrowGameThrowBalls::
	.string "AVVISO:\p"
	.string "Se perdi le staffe, non buttare\n"
	.string "il gioco contro il muro, ma\l"
	.string "lancia un paio di POKé BALL!$"

Route17_Text_CyclingRoadSign::
	.string "PISTA CICLABILE\n"
	.string "Fine discesa!$"

