Route5_PokemonDayCare_Text_WantMeToRaiseMon::
	.string "Questa PENSIONE è mia.\p"
	.string "Vuoi che accudisca uno dei tuoi\n"
	.string "POKéMON?$"

Route5_PokemonDayCare_Text_ComeAgain::
	.string "Torna più tardi!$"

Route5_PokemonDayCare_Text_WhichMonShouldIRaise::
	.string "Che POKéMON devo allevare?$"

Route5_PokemonDayCare_Text_ComeAnytimeYouLike::
	.string "Capisco…\n"
	.string "Torna a farmi visita.$"

Route5_PokemonDayCare_Text_LookAfterMonForAWhile::
	.string "Bene, baderò io a {STR_VAR_1} per\n"
	.string "un po'.$"

Route5_PokemonDayCare_Text_ComeSeeMeInAWhile::
	.string "Torna a trovarmi fra un po'.$"

Route5_PokemonDayCare_Text_MonNeedsToSpendMoreTime::
	.string "Già di ritorno?\p"
	.string "Il tuo {STR_VAR_1} ha ancora\n"
	.string "bisogno delle mie cure.$"

Route5_PokemonDayCare_Text_OweMeXForMonsReturn::
	.string "Devi darmi ¥{STR_VAR_2} per riavere\n"
	.string "questo POKéMON.$"

Route5_PokemonDayCare_Text_ThankYouHeresMon::
	.string "Grazie!\n"
	.string "Ecco il tuo POKéMON!$"

Route5_PokemonDayCare_Text_PlayerGotMonBack::
	.string "{PLAYER} recupera\n"
	.string "il suo {STR_VAR_1}!$"

Route5_PokemonDayCare_Text_OnlyHaveOneMonWithYou::
	.string "Hai un solo POKéMON con te.$"

Route5_PokemonDayCare_Text_WhatWillYouBattleWith::
	.string "Se mi lasci quel POKéMON,\n"
	.string "come farai a lottare?$"

Route5_PokemonDayCare_Text_MonHasGrownByXLevels::
	.string "Il tuo {STR_VAR_1} è cresciuto\n"
	.string "bene!\p"
	.string "Il suo livello è salito di {STR_VAR_2}!\n"
	.string "Fantastico, eh?$"

Route5_PokemonDayCare_Text_YouveGotNoRoomForIt::
	.string "Non hai spazio per questo POKéMON!$"

Route5_PokemonDayCare_Text_DontHaveEnoughMoney::
	.string "Ehi, non hai abbastanza soldi!$"

Route5_PokemonDayCare_Text_WantMeToTakeALookAtYours::
	.string "Êîç\n"
	.string "îÛîñÉね?$"

Route5_PokemonDayCare_Text_CantAcceptMonWithHM::
	.string "わñÁÌど éで+çわざ& óっŒ\n"
	.string "ポケモンè ÀずÉºßÁßぁ$"

