SevenIsland_SevaultCanyon_Entrance_Text_MiahIntro::
	.string "Mi sbarazzerò di te in scioltezza!$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahDefeat::
	.string "Forse ho parlato troppo presto!$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahPostBattle::
	.string "Sembro tanto carina, ma quando\n"
	.string "lotto divento una furia!\p"
	.string "Fa parte della mia tattica,\n"
	.string "capisci?$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonIntro::
	.string "Ehi! Perché non ti iscrivi al\n"
	.string "mio fan club?$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonDefeat::
	.string "Non ti iscriverai mai al mio\n"
	.string "fan club, lo so!$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonPostBattle::
	.string "Quando mando in campo i miei\n"
	.string "POKéMON, tutte le ragazze\l"
	.string "iniziano a gridare estasiate!$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasIntro::
	.string "Quest'isola è troppo grande! Non\n"
	.string "è facile pattugliarla!$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasDefeat::
	.string "Oh oh…$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasPostBattle::
	.string "Gli ALLENATORI di città come te\n"
	.string "sono ossi duri.\p"
	.string "Scommetto che stai andando alla\n"
	.string "TORRE ALLENATORI!$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineIntro::
	.string "Chi offende i POKéMON verrà\n"
	.string "punito! Da me!$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineDefeat::
	.string "Tutto regolare, vai pure.$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelinePostBattle::
	.string "I POKéMON devono essere trattati\n"
	.string "bene, è un loro diritto!$"

SevenIsland_SevaultCanyon_Entrance_Text_EveIntro::
	.string "EVE: Faccio sempre squadra\n"
	.string "con JON.$"

SevenIsland_SevaultCanyon_Entrance_Text_EveDefeat::
	.string "EVE: Ho perso, JON.\n"
	.string "Anzi, abbiamo perso!$"

SevenIsland_SevaultCanyon_Entrance_Text_EvePostBattle::
	.string "EVE: Io e JON dobbiamo impegnarci\n"
	.string "di più per vincere.$"

SevenIsland_SevaultCanyon_Entrance_Text_EveNotEnoughMons::
	.string "EVE: Certo che voglio sfidarti, ma\n"
	.string "solo insieme a JON.\p"
	.string "Quindi, devi avere almeno due\n"
	.string "POKéMON.$"

SevenIsland_SevaultCanyon_Entrance_Text_JonIntro::
	.string "JON: Quando sono con EVE, ho\n"
	.string "l'impressione di non poter perdere!$"

SevenIsland_SevaultCanyon_Entrance_Text_JonDefeat::
	.string "JON: Anche la sconfitta è meno\n"
	.string "amara, se sono con EVE.$"

SevenIsland_SevaultCanyon_Entrance_Text_JonPostBattle::
	.string "JON: Quando sono con EVE, non\n"
	.string "m'importa se vinco o perdo!\p"
	.string "È semplicemente magico!$"

SevenIsland_SevaultCanyon_Entrance_Text_JonNotEnoughMons::
	.string "JON: Certo, lottiamo! Ma insieme a\n"
	.string "EVE, naturalmente!\p"
	.string "Torna con almeno due POKéMON\n"
	.string "in squadra, OK?$"

SevenIsland_SevaultCanyon_Entrance_Text_RouteSign::
	.string "INGRESSO CANYON SEPTION\p"
	.string "Si raccomanda agli ALLENATORI di\n"
	.string "rispettare il verde.$"

