Route12_Text_MonSprawledOutInSlumber::
	.string "Un POKéMON addormentato blocca la\n"
	.string "strada!$"

Text_SnorlaxWokeUp::
	.string "SNORLAX si è svegliato male\n"
	.string "e attacca furioso!$"

Text_SnorlaxReturnedToMountains::
	.string "SNORLAX si calma.\n"
	.string "Sbadiglia e torna sulle montagne!$"

Text_WantToUsePokeFlute::
	.string "Vuoi suonare il POKé FLAUTO?$"

Text_PlayedPokeFlute::
	.string "{PLAYER} suona il POKé FLAUTO.$"

Route12_Text_NedIntro::
	.string "Sì! Ha abboccato!$"

Route12_Text_NedDefeat::
	.string "È solo un pesciolino!$"

Route12_Text_NedPostBattle::
	.string "Un momento!\n"
	.string "Ho preso qualcosa!$"

Route12_Text_ChipIntro::
	.string "Ci vuole pazienza!\n"
	.string "La pesca richiede tempo!$"

Route12_Text_ChipDefeat::
	.string "Mi è scappato!$"

Route12_Text_ChipPostBattle::
	.string "Con un AMO migliore potrei pescare\n"
	.string "POKéMON migliori!$"

Route12_Text_JustinIntro::
	.string "Hai trovato la PIETRALUNARE?$"

Route12_Text_JustinDefeat::
	.string "Ahi ahi!$"

Route12_Text_JustinPostBattle::
	.string "Avrei potuto far evolvere i miei\n"
	.string "POKéMON con la PIETRALUNARE!$"

Route12_Text_LucaIntro::
	.string "L'elettricità è la mia specialità!\p"
	.string "Però non chiedermi niente sui\n"
	.string "POKéMON acquatici!$"

Route12_Text_LucaDefeat::
	.string "Mi hai staccato la spina!$"

Route12_Text_LucaPostBattle::
	.string "L'acqua conduce elettricità!\n"
	.string "Prendi dei POKéMON di mare!$"

Route12_Text_HankIntro::
	.string "Mi chiamano il PESCATORE PAZZO!\n"
	.string "Hai paura?$"

Route12_Text_HankDefeat::
	.string "È troppo per me!$"

Route12_Text_HankPostBattle::
	.string "Mi batti in fatto di POKéMON, ma\n"
	.string "sono un bravo pescatore!$"

Route12_Text_ElliotIntro::
	.string "Preferirei lavorare!$"

Route12_Text_ElliotDefeat::
	.string "Non è facile…$"

Route12_Text_ElliotPostBattle::
	.string "Va bene.\n"
	.string "Non mi importa più di perdere.$"

Route12_Text_AndrewIntro::
	.string "Non si sa mai cosa può abboccare!$"

Route12_Text_AndrewDefeat::
	.string "Ho perso! Perso!$"

Route12_Text_AndrewPostBattle::
	.string "Abboccano un sacco di MAGIKARP,\n"
	.string "ma sono debolissimi!$"

Route12_Text_RouteSign::
	.string "PERCORSO 12\n"
	.string "LAVANDONIA a nord$"

Route12_Text_SportfishingArea::
	.string "PESCA SPORTIVA$"

Route12_Text_JesIntro::
	.string "JES: Se vinco, chiedo a GIA\n"
	.string "di sposarmi.$"

Route12_Text_JesDefeat::
	.string "JES: Vedi, così hai rovinato il\n"
	.string "mio sogno romantico!$"

Route12_Text_JesPostBattle::
	.string "JES: GIA, amore mio, perdonami!$"

Route12_Text_JesNotEnoughMons::
	.string "JES: Io e GIA lottiamo solo in\n"
	.string "squadra.\p"
	.string "Se non hai almeno due POKéMON,\n"
	.string "non possiamo sfidarti.$"

Route12_Text_GiaIntro::
	.string "GIA: JES, se vinciamo, ci sposiamo!\n"
	.string "Pensi che sia troppo precipitosa?$"

Route12_Text_GiaDefeat::
	.string "GIA: Perché?$"

Route12_Text_GiaPostBattle::
	.string "GIA: JES, hai rovinato tutto!\n"
	.string "Non ti sposerò mai!$"

Route12_Text_GiaNotEnoughMons::
	.string "GIA: Non posso lottare senza il\n"
	.string "mio JES!\p"
	.string "Torna con almeno due POKéMON.$"

