SaffronCity_Gym_Text_SabrinaIntro::
	.byte 0xC2, 0xE3, 0x00, 0xD5, 0xEA, 0xE9, 0xE8, 0xE3, 0x00, 0xE0, 0xD5, 0x00
	.byte 0xEA, 0xDD, 0xE7, 0xDD, 0xE3, 0xE2, 0xD9, 0x00, 0xD8, 0xD9, 0xE0, 0x00
	.byte 0xE8, 0xE9, 0xE3, 0x00, 0xD5, 0xE6, 0xE6, 0xDD, 0xEA, 0xE3, 0xAD, 0xFB
	.byte 0xC1, 0xDD, 0x16, 0x00, 0xD8, 0xD5, 0x00, 0xD6, 0xD5, 0xE1, 0xD6, 0xDD
	.byte 0xE2, 0xD5, 0x00, 0xD5, 0xEA, 0xD9, 0xEA, 0xE3, 0x00, 0xE4, 0xE3, 0xE8
	.byte 0xD9, 0xE6, 0xDD, 0xFE, 0xE4, 0xD5, 0xE6, 0xD5, 0xE2, 0xE3, 0xE6, 0xE1
	.byte 0xD5, 0xE0, 0xDD, 0xAB, 0xFB, 0xCE, 0xE9, 0xE8, 0xE8, 0xE3, 0x00, 0x1A
	.byte 0x00, 0xDD, 0xE2, 0xDD, 0xEE, 0xDD, 0xD5, 0xE8, 0xE3, 0x00, 0xE5, 0xE9
	.byte 0xD5, 0xE2, 0xD8, 0xE3, 0x00, 0xDC, 0xE3, 0x00, 0xDD, 0xE1, 0xE4, 0xD5
	.byte 0xE6, 0xD5, 0xE8, 0xE3, 0xFE, 0xD5, 0x00, 0xE4, 0xDD, 0xD9, 0xDB, 0xD5
	.byte 0xE6, 0xD9, 0x00, 0xDD, 0x00, 0xD7, 0xE9, 0xD7, 0xD7, 0xDC, 0xDD, 0xD5
	.byte 0xDD, 0x00, 0xD7, 0xE3, 0xE0, 0x00, 0xE4, 0xD9, 0xE2, 0xE7, 0xDD, 0xD9
	.byte 0xE6, 0xE3, 0xAD, 0xFB, 0xC9, 0xD8, 0xDD, 0xE3, 0x00, 0xE0, 0xE3, 0xE8
	.byte 0xE8, 0xD5, 0xE6, 0xD9, 0x00, 0xE1, 0xD5, 0x00, 0xE7, 0xD9, 0x00, 0xEA
	.byte 0xE9, 0xE3, 0xDD, 0x00, 0xE8, 0xDD, 0x00, 0xE1, 0xE3, 0xE7, 0xE8, 0xE6
	.byte 0xD9, 0xE6, 0x22, 0xFE, 0xDD, 0x00, 0xE1, 0xDD, 0xD9, 0xDD, 0x00, 0xE4
	.byte 0xE3, 0xE8, 0xD9, 0xE6, 0xDD, 0xAB, 0xFC, 0x0B, 0x56, 0x01, 0xFF

SaffronCity_Gym_Text_SabrinaDefeat::
	.string "Non ci credo!\n"
	.string "Ma non nego la disfatta.\p"
	.string "Non mi sono data molto da fare per\n"
	.string "vincere!\p"
	.string "Ti conferisco la MEDAGLIA PALUDE!$"

SaffronCity_Gym_Text_SabrinaPostBattle::
	.string "Tutti hanno poteri paranormali, ma\n"
	.string "non lo sanno!$"

SaffronCity_Gym_Text_ExplainMarshBadgeTakeThis::
	.string "Con la MEDAGLIA PALUDE, tutti i\n"
	.string "POKéMON fino al livello 70 ti\l"
	.string "obbediranno!\p"
	.string "Quelli più forti ignoreranno gli\n"
	.string "ordini in battaglia!\p"
	.string "Non far salire troppo il livello dei\n"
	.string "tuoi POKéMON prima di avere\l"
	.string "le medaglie adeguate!\p"
	.string "Aspetta, prendi questa MT!$"

SaffronCity_Gym_Text_ReceivedTM04FromSabrina::
	.string "{PLAYER} riceve\n"
	.string "la MT04!$"

SaffronCity_Gym_Text_ExplainTM04::
	.string "La MT04 è CALMAMENTE!\p"
	.string "Serve a potenziare la DIF. SPEC. e\n"
	.string "l'ATT. SPEC. dei tuoi POKéMON.$"

SaffronCity_Gym_Text_BagFullOfOtherItems::
	.string "Lo ZAINO è già pieno!$"

SaffronCity_Gym_Text_AmandaIntro::
	.string "SABRINA è più giovane di me, ma la\n"
	.string "rispetto!$"

SaffronCity_Gym_Text_AmandaDefeat::
	.string "Non sono all'altezza!$"

SaffronCity_Gym_Text_AmandaPostBattle::
	.string "In una lotta tra pari vince chi ha\n"
	.string "più volontà!\p"
	.string "Se vuoi battere SABRINA, pensa a\n"
	.string "vincere!$"

SaffronCity_Gym_Text_JohanIntro::
	.string "Temi il nostro potere nascosto?$"

SaffronCity_Gym_Text_JohanDefeat::
	.string "Non l'avevo previsto!$"

SaffronCity_Gym_Text_JohanPostBattle::
	.string "I POKéMON del tipo PSICO temono\n"
	.string "solo i POKéMON di tipo SPETTRO\l"
	.string "e COLEOTTERO.$"

SaffronCity_Gym_Text_StacyIntro::
	.string "I POKéMON tendono ad assomigliare\n"
	.string "ai loro ALLENATORI.\p"
	.string "I tuoi devono essere davvero\n"
	.string "forti!$"

SaffronCity_Gym_Text_StacyDefeat::
	.string "Lo sapevo!$"

SaffronCity_Gym_Text_StacyPostBattle::
	.string "Devo insegnare migliori tecniche\n"
	.string "PSICO ai miei POKéMON!$"

SaffronCity_Gym_Text_TyronIntro::
	.string "Il potere da solo non basta!$"

SaffronCity_Gym_Text_TyronDefeat::
	.string "Non ci credo!$"

SaffronCity_Gym_Text_TyronPostBattle::
	.string "SABRINA ha battuto il MAESTRO di\n"
	.string "KARATE qui accanto!$"

SaffronCity_Gym_Text_TashaIntro::
	.string "Ehi tu, facciamo lottare i nostri\n"
	.string "POKéMON!$"

SaffronCity_Gym_Text_TashaDefeat::
	.string "Ho perso, nonostante i miei sforzi!$"

SaffronCity_Gym_Text_TashaPostBattle::
	.string "Sapevo che sarebbe successo.$"

SaffronCity_Gym_Text_CameronIntro::
	.string "SABRINA è giovane ma è già il\n"
	.string "nostro CAPO!\p"
	.string "Non arriverai a lei facilmente!$"

SaffronCity_Gym_Text_CameronDefeat::
	.string "Mi sono distratto!$"

SaffronCity_Gym_Text_CameronPostBattle::
	.string "A ZAFFERANOPOLI una volta c'erano\n"
	.string "2 PALESTRE.\p"
	.string "Il DOJO KARATE accanto ha perso\n"
	.string "il suo status di PALESTRA dopo che\l"
	.string "li abbiamo sconfitti!$"

SaffronCity_Gym_Text_PrestonIntro::
	.string "La PALESTRA di ZAFFERANOPOLI è\n"
	.string "famosa per il paranormale!\p"
	.string "Vuoi vedere SABRINA! Lo so!$"

SaffronCity_Gym_Text_PrestonDefeat::
	.string "Grrr!$"

SaffronCity_Gym_Text_PrestonPostBattle::
	.string "Ti ho letto il pensiero con la\n"
	.string "telepatia!$"

SaffronCity_Gym_Text_GymGuyAdvice::
	.string "Ehi!\n"
	.string "Aspirante CAMPIONE!\p"
	.string "I POKéMON di SABRINA non usano\n"
	.string "la forza fisica, ma poteri\l"
	.string "paranormali!\p"
	.string "I POKéMON di tipo LOTTA sono\n"
	.string "deboli contro quelli tipo PSICO!\p"
	.string "Il potere psichico li sfianca prima\n"
	.string "ancora che possano sferrare\l"
	.string "un pugno!$"

SaffronCity_Gym_Text_GymGuyPostVictory::
	.string "Poteri psichici, io?\p"
	.string "Se li avessi, sbancherei le slot\n"
	.string "machine!$"

SaffronCity_Gym_Text_GymStatue::
	.string "CAPOPALESTRA di ZAFFERANOPOLI:\n"
	.string "SABRINA\p"
	.string "ALLENATORI VINCENTI:\n"
	.string "{RIVAL}$"

SaffronCity_Gym_Text_GymStatuePlayerWon::
	.string "CAPOPALESTRA di ZAFFERANOPOLI:\n"
	.string "SABRINA\p"
	.string "ALLENATORI VINCENTI:\n"
	.string "{RIVAL}, {PLAYER}$"

