PokemonTower_6F_Text_AngelicaIntro::
	.string "Daaammi… il… saaangue…$"

PokemonTower_6F_Text_AngelicaDefeat::
	.string "Grrrr!$"

PokemonTower_6F_Text_AngelicaPostBattle::
	.string "Mi sento anemica e debole…$"

PokemonTower_6F_Text_EmiliaIntro::
	.string "Uuff… Guaa!$"

PokemonTower_6F_Text_EmiliaDefeat::
	.string "È caduto qualcosa!$"

PokemonTower_6F_Text_EmiliaPostBattle::
	.string "Non ho perso i capelli!\n"
	.string "È stato uno spirito maligno!$"

PokemonTower_6F_Text_JenniferIntro::
	.string "Ki… ki… ki… \n"
	.string "ki… ki… ki!$"

PokemonTower_6F_Text_JenniferDefeat::
	.string "Kiii!$"

PokemonTower_6F_Text_JenniferPostBattle::
	.string "Che succede qui?$"

PokemonTower_6F_Text_BeGoneIntruders::
	.string "Via gli intrusi!$"

PokemonTower_6F_Text_GhostWasCubonesMother::
	.string "Lo spettro era l'anima inquieta\n"
	.string "della madre di CUBONE!$"

PokemonTower_6F_Text_MothersSpiritWasCalmed::
	.string "Adesso l'anima è tranquilla.\p"
	.string "È partita per l'aldilà!$"

