Text_ExplosionTeach::
	.string "Immagina cosa succederebbe se\n"
	.string "questo vulcano eruttasse!\p"
	.string "Salteremmo in aria come\n"
	.string "fuochi d'artificio!\p"
	.string "Già che siamo in argomento,\n"
	.string "vuoi che ti insegni ESPLOSIONE?$"

Text_ExplosionDeclined::
	.string "Hai ragione, è una mossa troppo\n"
	.string "spaventosa.$"

Text_ExplosionWhichMon::
	.string "Ehi, che coraggio!\p"
	.string "A quale POKéMON vuoi che insegni\n"
	.string "ESPLOSIONE?$"

Text_ExplosionTaught::
	.string "Usare ESPLOSIONE su questo\n"
	.string "vulcano…\p"
	.string "Dev'essere terrorizzante!$"

Text_ExplosionTeachJP::
	.string "こ こç Éざ+が\n"
	.string "óÏ だÁばËèÚ ÏŒú\l"
	.string "È Èºú éÑŒまûó\l"
	.string "ßÁßÀ …ブルブル!\p"
	.string "こ こわÁ ÚÁでà\n"
	.string "だÁばËèÚ でó ÈぼÇÛîñ?$"

Text_ExplosionDeclinedJP::
	.string "ô ôっぱ こわÁó+ß\n"
	.string "ブルブル$"

Text_ExplosionWhichMonJP::
	.string "Ú ÚùÊだね!\n"
	.string "じゃÀ どç ポケモンà Òñ?$"

Text_ExplosionTaughtJP::
	.string "Éざ+で だÁばËèÚ&…\n"
	.string "Ò ÒごÁ )リル!$"

MtEmber_Exterior_Text_WellTryDiggingHere::
	.string "Qui va bene.\n"
	.string "Proviamo a scavare qui.\p"
	.string "Quel tesoro di cui parlano i\n"
	.string "TENENTI dovrebbe essere qua\l"
	.string "sotto.$"

MtEmber_Exterior_Text_YoureInTheWayGetLost::
	.string "Ehi, togliti di mezzo!$"

MtEmber_Exterior_Text_PunchedThroughAtLast::
	.string "Dai! Andiamo a cercare il tesoro!$"

MtEmber_Exterior_Text_WhatsPasswordAgain::
	.string "Appena troviamo qualcosa \n"
	.string "torniamo al MAGAZZINO, intesi?\p"
	.string "…Uhm, ma qual è la parola\n"
	.string "d'ordine per il MAGAZZINO ROCKET?$"

MtEmber_Exterior_Text_FirstPasswordGoldeen::
	.string "Cos'hai, un'amnesia?!\n"
	.string "Ce ne sono due.\p"
	.string "La prima è “Un'ORTICA ad\n"
	.string "ARTICUNO”.\p"
	.string "E la seconda è…$"

MtEmber_Exterior_Text_SnoopsBeenListeningIn::
	.string "Ehi, sembra che abbiamo\n"
	.string "compagnia!$"

MtEmber_Exterior_Text_Grunt1Intro::
	.string "Stavi origliando, vero?$"

MtEmber_Exterior_Text_Grunt1Defeat::
	.string "Ehi, ma come?!$"

MtEmber_Exterior_Text_Grunt1PostBattle::
	.string "Come ho potuto farmi battere?!$"

MtEmber_Exterior_Text_Grunt2Intro::
	.string "Vuoi soffiarci il tesoro?\n"
	.string "Scordatelo!$"

MtEmber_Exterior_Text_Grunt2Defeat::
	.string "Ehi, ma come è potuto\n"
	.string "succedere?!$"

MtEmber_Exterior_Text_Grunt2PostBattle::
	.string "Tu non hai sentito niente,\n"
	.string "capito?$"

MtEmber_Exterior_Text_WellRegroupDontStepInsideThere::
	.string "Che sconfitta! Dovremo\n"
	.string "riorganizzarci!\p"
	.string "E tu, non farti venire in mente di\n"
	.string "mettere piede qui dentro!\p"
	.string "Se hai un po' di cervello, stai\n"
	.string "alla larga da qui!$"

MtEmber_Exterior_Text_LoganIntro::
	.string "Un vulcano attivo è un vulcano in\n"
	.string "eruzione, o che potrebbe eruttare.$"

MtEmber_Exterior_Text_LoganDefeat::
	.string "…Che lotta esplosiva!\n"
	.string "Sembrava un'eruzione!$"

MtEmber_Exterior_Text_LoganPostBattle::
	.string "Sai che nel mondo ci sono più di\n"
	.string "1.500 vulcani attivi?\p"
	.string "Mi viene caldo solo a pensarci!$"

MtEmber_Exterior_Text_BethIntro::
	.string "Lo sai come si formano le grotte\n"
	.string "dentro ai vulcani?$"

MtEmber_Exterior_Text_BethDefeat::
	.string "Sei sorprendente!$"

MtEmber_Exterior_Text_BethPostBattle::
	.string "Quando la lava sopra il magma\n"
	.string "si indurisce e il magma stesso\l"
	.string "scorre via, si forma una grotta.$"

MtEmber_Exterior_Text_JocelynIntro::
	.string "Mi alleno per dimenticare le pene\n"
	.string "d'amore…\p"
	.string "Il mio spirito resta a terra, ma\n"
	.string "almeno mi rafforzo nel corpo.$"

MtEmber_Exterior_Text_JocelynDefeat::
	.string "Forse ho voluto strafare…$"

MtEmber_Exterior_Text_JocelynPostBattle::
	.string "Il modo in cui lotti mi ricorda il\n"
	.string "ragazzo che mi ha mollata!$"

