SSAnne_B1F_Room4_Text_LeonardIntro::
	.string "Ci sono marinai che si prendono\n"
	.string "a scazzottate, altri che lottano\l"
	.string "con i POKéMON!$"

SSAnne_B1F_Room4_Text_LeonardDefeat::
	.string "Bella lotta!!!$"

SSAnne_B1F_Room4_Text_LeonardPostBattle::
	.string "Ah!\n"
	.string "Vuoi entrare a far parte\l"
	.string "dell'equipaggio?$"

SSAnne_B1F_Room4_Text_DuncanIntro::
	.string "È in gioco il mio orgoglio di\n"
	.string "marinaio!!!$"

SSAnne_B1F_Room4_Text_DuncanDefeat::
	.string "La tua forza mi ha messo al\n"
	.string "tappeto!$"

SSAnne_B1F_Room4_Text_DuncanPostBattle::
	.string "Hai visto il GURU PESCATORE ad\n"
	.string "ARANCIOPOLI?$"

