SixIsland_Text_IslandSign::
	.string "SESTISOLA\n"
	.string "L'isola della saggezza veneranda$"

SixIsland_Text_ThatWayToWaterPathRuinValley::
	.string "Se prosegui in questa direzione\n"
	.string "arrivi alla VIA MARINA.\p"
	.string "La VIA MARINA conduce alla\n"
	.string "VALLE ANTICA!$"

SixIsland_Text_SkyAtNightIsFantastic::
	.string "Così lontano dalle città, il cielo\n"
	.string "stellato è meraviglioso!$"

