SilphCo_7F_Text_HaveMonForSavingUs::
	.string "Ah! Ciao! Non sei un ROCKET!\n"
	.string "Ci hai salvato la vita!\l"
	.string "Siamo in debito!\p"
	.string "Ti donerò questo POKéMON per\n"
	.string "averci salvato.$"

SilphCo_7F_Text_ObtainedLaprasFromEmployee::
	.string "{PLAYER} ha ottenuto LAPRAS\n"
	.string "dall'impiegato della SILPH!$"

SilphCo_7F_Text_ExplainLapras::
	.string "È LAPRAS.\n"
	.string "È molto intelligente.\p"
	.string "Lo teniamo in laboratorio, ma starà\n"
	.string "molto meglio con te!\p"
	.string "Sarai un ottimo ALLENATORE per\n"
	.string "LAPRAS!\p"
	.string "È un buon nuotatore.\n"
	.string "Potresti servirtene per spostarti\l"
	.string "sull'acqua!$"

SilphCo_7F_Text_RocketBossWentToBoardroom::
	.string "Il CAPO di TEAM ROCKET è in sala\n"
	.string "consiliare!\p"
	.string "Il nostro PRESIDENTE sta bene?$"

SilphCo_7F_Text_OhNo::
	.string "À… óÂ óÛßÁぞ$"

SilphCo_7F_Text_SavedAtLast::
	.string "ŒÒÉっŒù ÀûがÑ!$"

SilphCo_7F_Text_RocketsAfterMasterBall::
	.string "TEAM ROCKET stava cercando la\n"
	.string "MASTER BALL che cattura qualsiasi\l"
	.string "POKéMON!$"

SilphCo_7F_Text_CanceledMasterBallProject::
	.string "Abbiamo annullato i progetti sulla\n"
	.string "MASTER BALL per colpa di TEAM\l"
	.string "ROCKET.$"

SilphCo_7F_Text_BadIfTeamRocketTookOver::
	.string "Sarebbe tremendo se TEAM ROCKET si\n"
	.string "prendesse la SILPH SpA o i nostri\l"
	.string "POKéMON!$"

SilphCo_7F_Text_WowYouChasedOffTeamRocket::
	.string "Wow!\p"
	.string "Hai cacciato TEAM ROCKET senza\n"
	.string "nessun aiuto?$"

SilphCo_7F_Text_ReallyDangerousHere::
	.string "Ehi!\n"
	.string "È pericoloso qui!\p"
	.string "Sei qui per salvarmi?\n"
	.string "Non puoi!$"

SilphCo_7F_Text_ThankYouSoMuch::
	.string "Finalmente salvi!\n"
	.string "Grazie infinite!$"

SilphCo_7F_Text_Grunt3Intro::
	.string "Oh oh!\n"
	.string "Da dove sbuca questo topastro?$"

SilphCo_7F_Text_Grunt3Defeat::
	.string "Fuori uso!$"

SilphCo_7F_Text_Grunt3PostBattle::
	.string "Non incontrerai il CAPO scappando\n"
	.string "qua e là!$"

SilphCo_7F_Text_JoshuaIntro::
	.string "Ehi tu!\p"
	.string "Mi hai scambiato per un dipendente\n"
	.string "della SILPH?$"

SilphCo_7F_Text_JoshuaDefeat::
	.string "Distrutto!$"

SilphCo_7F_Text_JoshuaPostBattle::
	.string "Nonostante la tua età, sei un buon\n"
	.string "ALLENATORE!$"

SilphCo_7F_Text_Grunt1Intro::
	.string "Sono uno dei 4 FRATELLI ROCKET!$"

SilphCo_7F_Text_Grunt1Defeat::
	.string "Fratelli, ho perso!$"

SilphCo_7F_Text_Grunt1PostBattle::
	.string "Non importa. I miei fratelli ti\n"
	.string "renderanno il favore!$"

SilphCo_7F_Text_Grunt2Intro::
	.string "Un intruso?\n"
	.string "Devi essere tu!$"

SilphCo_7F_Text_Grunt2Defeat::
	.string "Bene! Cioè, male!\n"
	.string "Ho perso!$"

SilphCo_7F_Text_Grunt2PostBattle::
	.string "Vattene a casa prima che il CAPO\n"
	.string "si arrabbi!$"

SilphCo_7F_Text_RivalWhatKeptYou::
	.string "{RIVAL}: Perché ci hai messo\n"
	.string "tanto, {PLAYER}?$"

SilphCo_7F_Text_RivalIntro::
	.string "{RIVAL}: Ahah! Sapevo che ti\n"
	.string "avrei incontrato aspettandoti qui!\p"
	.string "Suppongo che TEAM ROCKET ti abbia\n"
	.string "dato del filo da torcere!\l"
	.string "Non che m'importi…\p"
	.string "Ti ho visto a ZAFFERANOPOLI e\n"
	.string "volevo vedere se ora sei più\l"
	.string "forte!$"

SilphCo_7F_Text_RivalDefeat::
	.string "Ahah!\n"
	.string "Sei abbastanza forte per battere\l"
	.string "il CAPO ROCKET!$"

SilphCo_7F_Text_RivalVictory::
	.string "{RIVAL}“ÈまÇßÀ…\p"
	.string "こ+ß ÂでまÇじゃ\n"
	.string "まだまだ…\l"
	.string "ÁÙà+まÇ Ñè ÁÇßÁぜ$"

SilphCo_7F_Text_RivalPostBattle::
	.string "Bene, {PLAYER}!\n"
	.string "Sto migliorando!\p"
	.string "Controllando il mio POKéDEX vedo\n"
	.string "quali sono i più forti e come si\l"
	.string "evolvono!\p"
	.string "Vado alla LEGA POKéMON per\n"
	.string "scalzare i SUPERQUATTRO!\p"
	.string "Sarò l'ALLENATORE nº1 al mondo!\p"
	.string "{PLAYER}, buona fortuna!\n"
	.string "E non ti affaticare tanto!\l"
	.string "Ci becchiamo in giro!$"

SilphCo_7F_Text_FloorSign::
	.string "DIREZIONE della SILPH SpA\n"
	.string "6ºP$"

