ViridianCity_Gym_Text_GiovanniIntro::
	.string "Ehilà!\n"
	.string "Questo è il mio nascondiglio!\p"
	.string "Qui voglio ricostituire TEAM\n"
	.string "ROCKET!\p"
	.string "Ma mi hai scovato di nuovo!\n"
	.string "Va bene allora!\p"
	.string "Non mi tiro senz'altro indietro!\p"
	.string "Ancora una volta dovrai affrontare\n"
	.string "il grande GIOVANNI!{PLAY_BGM}éÀ$"

ViridianCity_Gym_Text_GiovanniDefeat::
	.byte 0x05, 0x00, 0xE7, 0xE8, 0xD5, 0xE8, 0xD5, 0x00, 0xE9, 0xE2, 0xD5, 0x00
	.byte 0xD8, 0xE9, 0xE6, 0xD5, 0x00, 0xE0, 0xE3, 0xE8, 0xE8, 0xD5, 0x00, 0xD9
	.byte 0x00, 0xDC, 0xD5, 0xDD, 0x00, 0xEA, 0xDD, 0xE2, 0xE8, 0xE3, 0xFE, 0xE8
	.byte 0xE9, 0xAB, 0xFB, 0xCE, 0xDD, 0x00, 0xE1, 0xD9, 0xE6, 0xDD, 0xE8, 0xDD
	.byte 0x00, 0xE0, 0xD5, 0x00, 0xC7, 0xBF, 0xBE, 0xBB, 0xC1, 0xC6, 0xC3, 0xBB
	.byte 0x00, 0xCE, 0xBF, 0xCC, 0xCC, 0xBB, 0xAB, 0xFE, 0xFC, 0x17, 0xFC, 0x0B
	.byte 0x04, 0x01, 0xFC, 0x08, 0xFE, 0xFC, 0x08, 0x56, 0xFC, 0x18, 0xFF

ViridianCity_Gym_Text_GiovanniPostBattle::
	.string "Ora che ho perso non potrò più\n"
	.string "presentarmi ai miei scagnozzi!\l"
	.string "TEAM ROCKET è finito ormai!\p"
	.string "D'ora in poi mi dedicherò solo ad\n"
	.string "addestrare i POKéMON!\p"
	.string "Chissà, forse un giorno ci vedremo\n"
	.string "di nuovo! Addio!$"

ViridianCity_Gym_Text_ExplainEarthBadgeTakeThis::
	.string "Con la MEDAGLIA TERRA i POKéMON\n"
	.string "di ogni livello ti obbediranno!\p"
	.string "È la prova della tua abilità come\n"
	.string "ALLENATORE di POKéMON!\p"
	.string "Con questa puoi entrare nella LEGA\n"
	.string "POKéMON!\p"
	.string "È il mio regalo per la sfida con la\n"
	.string "LEGA POKéMON!$"

ViridianCity_Gym_Text_ReceivedTM26FromGiovanni::
	.string "{PLAYER} riceve\n"
	.string "la MT26!$"

ViridianCity_Gym_Text_ExplainTM26::
	.string "La MT26 è TERREMOTO!\p"
	.string "È un attacco potente, che fa\n"
	.string "tremare la terra sotto i piedi!\p"
	.string "L'ho inventata quando dirigevo\n"
	.string "questa PALESTRA molto tempo fa.$"

ViridianCity_Gym_Text_YouDoNotHaveSpace::
	.string "Non hai più spazio per questo!$"

ViridianCity_Gym_Text_YujiIntro::
	.string "Ehi!\n"
	.string "Cosa fai, ti manca il fiato?!$"

ViridianCity_Gym_Text_YujiDefeat::
	.string "Ohi! Sono a secco!!!$"

ViridianCity_Gym_Text_YujiPostBattle::
	.string "Hai bisogno di energia per tener\n"
	.string "testa al nostro CAPOPALESTRA!$"

ViridianCity_Gym_Text_AtsushiIntro::
	.string "Grrr!\n"
	.string "Sto andando su tutte le furie!$"

ViridianCity_Gym_Text_AtsushiDefeat::
	.string "Che brutto colpo!!!$"

ViridianCity_Gym_Text_AtsushiPostBattle::
	.string "Non sono ancora degno!$"

ViridianCity_Gym_Text_JasonIntro::
	.string "Faccio della gran bella musica con\n"
	.string "i miei POKéMON!$"

ViridianCity_Gym_Text_JasonDefeat::
	.string "Siete in perfetta armonia!$"

ViridianCity_Gym_Text_JasonPostBattle::
	.string "Hai mai visto chi è il nostro\n"
	.string "CAPOPALESTRA?$"

ViridianCity_Gym_Text_KiyoIntro::
	.string "La suprema disciplina tra le arti\n"
	.string "marziali è il karate!$"

ViridianCity_Gym_Text_KiyoDefeat::
	.string "Ahiaia!$"

ViridianCity_Gym_Text_KiyoPostBattle::
	.string "Magari anche i miei POKéMON fossero\n"
	.string "bravi come me a karate!$"

ViridianCity_Gym_Text_WarrenIntro::
	.string "Il vero talento sta nello stile!$"

ViridianCity_Gym_Text_WarrenDefeat::
	.string "Ho mancato la presa!$"

ViridianCity_Gym_Text_WarrenPostBattle::
	.string "Il CAPOPALESTRA mi rimprovererà!$"

ViridianCity_Gym_Text_TakashiIntro::
	.string "Sono il RE del KARATE!\n"
	.string "Non hai più scampo!$"

ViridianCity_Gym_Text_TakashiDefeat::
	.string "Ahi! Ahi!$"

ViridianCity_Gym_Text_TakashiPostBattle::
	.string "Vuoi entrare nella LEGA POKéMON?\n"
	.string "Tu? Prima devi crescere, pulce!$"

ViridianCity_Gym_Text_ColeIntro::
	.string "I tuoi POKéMON se la faranno sotto\n"
	.string "allo schiocco della mia frusta!$"

ViridianCity_Gym_Text_ColeDefeat::
	.string "E voilà!\n"
	.string "Che bella frustata!$"

ViridianCity_Gym_Text_ColePostBattle::
	.string "Ehi!\n"
	.string "Ho perso la concentrazione!$"

ViridianCity_Gym_Text_SamuelIntro::
	.string "La PALESTRA di SMERALDOPOLI è\n"
	.string "rimasta chiusa molto tempo ma il\l"
	.string "nostro CAPO è tornato adesso!$"

ViridianCity_Gym_Text_SamuelDefeat::
	.string "Ho perso? Ma come?!$"

ViridianCity_Gym_Text_SamuelPostBattle::
	.string "Puoi affrontare la LEGA POKéMON\n"
	.string "solo se sconfiggi il nostro CAPO!$"

ViridianCity_Gym_Text_GymGuyAdvice::
	.string "Ehi! Tu!\n"
	.string "Aspirante CAMPIONE!\p"
	.string "Neanch'io so chi sia in realtà il\n"
	.string "CAPOPALESTRA di SMERALDOPOLI!\p"
	.string "Sarà sicuramente un osso duro!\p"
	.string "So che qui gli ALLENATORI usano\n"
	.string "POKéMON di TERRA!$"

ViridianCity_Gym_Text_GymGuyPostVictory::
	.string "Ah, davvero?\n"
	.string "GIOVANNI era il CAPOPALESTRA di\l"
	.string "SMERALDOPOLI?$"

ViridianCity_Gym_Text_GymStatue::
	.string "CAPOPALESTRA di SMERALDOPOLI:\n"
	.string "?\p"
	.string "ALLENATORI VINCENTI:\n"
	.string "{RIVAL}$"

ViridianCity_Gym_Text_GymStatuePlayerWon::
	.string "CAPOPALESTRA di SMERALDOPOLI:\n"
	.string "GIOVANNI\p"
	.string "ALLENATORI VINCENTI:\n"
	.string "{RIVAL}, {PLAYER}$"

