RocketHideout_B1F_Text_Grunt1Intro::
	.string "Chi sei?\n"
	.string "Come hai fatto ad\l"
	.string "arrivare fin qui?$"

RocketHideout_B1F_Text_Grunt1Defeat::
	.string "Ahi!\n"
	.string "Colpito!$"

RocketHideout_B1F_Text_Grunt1PostBattle::
	.string "Sfiderai TEAM ROCKET?$"

RocketHideout_B1F_Text_Grunt2Intro::
	.string "Hai rovinato i nostri piani!$"

RocketHideout_B1F_Text_Grunt2Defeat::
	.string "È finita!$"

RocketHideout_B1F_Text_Grunt2PostBattle::
	.string "Non la passerai liscia, pulce!$"

RocketHideout_B1F_Text_Grunt3Intro::
	.string "Allarme! Intrusione!$"

RocketHideout_B1F_Text_Grunt3Defeat::
	.string "Non ce la faccio!!!$"

RocketHideout_B1F_Text_Grunt3PostBattle::
	.string "La SPETTROSONDA?\n"
	.string "Non so dove sia!$"

RocketHideout_B1F_Text_Grunt4Intro::
	.string "Cosa fai qui?$"

RocketHideout_B1F_Text_Grunt4Defeat::
	.string "Niente da fare!$"

RocketHideout_B1F_Text_Grunt4PostBattle::
	.string "Bene, parlerò! Se vuoi vedere il\n"
	.string "CAPO, prendi l'ascensore!$"

RocketHideout_B1F_Text_Grunt5Intro::
	.string "Hai perso la strada, piccola\n"
	.string "peste?$"

RocketHideout_B1F_Text_Grunt5Defeat::
	.string "Perché?$"

RocketHideout_B1F_Text_Grunt5PostBattle::
	.string "Oh! In qualche modo, sembra\n"
	.string "che il trambusto della lotta abbia\l"
	.string "aperto la porta!$"

