RocketHideout_B4F_Text_GiovanniIntro::
	.string "Mhm! Sono davvero sorpreso che tu\n"
	.string "ce l'abbia fatta ad arrivare\l"
	.string "fin qui!\p"
	.string "TEAM ROCKET usa i POKéMON per\n"
	.string "finanziare i suoi loschi piani!\p"
	.string "Sono il CAPO: GIOVANNI!\p"
	.string "Pagherai cara la tua insolenza!$"

RocketHideout_B4F_Text_GiovanniDefeat::
	.string "NO!\n"
	.string "Non può essere!$"

RocketHideout_B4F_Text_GiovanniPostBattle::
	.string "Vedo che allevi i tuoi POKéMON con\n"
	.string "molta passione!\p"
	.string "Non credo, però, che tu sia in\n"
	.string "grado di capire ciò che voglio\l"
	.string "ottenere!\p"
	.string "Questa volta ti farò passare!\p"
	.string "Spero che ci rincontreremo!$"

RocketHideout_B4F_Text_Grunt2Intro::
	.string "Ti conosco! Sei tu che hai rovinato\n"
	.string "i nostri piani sul MONTE LUNA!$"

RocketHideout_B4F_Text_Grunt2Defeat::
	.string "Hai vinto di nuovo!!!$"

RocketHideout_B4F_Text_Grunt2PostBattle::
	.string "Hai qualcosa contro TEAM ROCKET?$"

RocketHideout_B4F_Text_Grunt3Intro::
	.string "Come fai a non vedere la bellezza\n"
	.string "della nostra malvagità?$"

RocketHideout_B4F_Text_Grunt3Defeat::
	.string "Ahiaia!$"

RocketHideout_B4F_Text_Grunt3PostBattle::
	.string "Scusa, CAPO!\n"
	.string "So di averti deluso!$"

RocketHideout_B4F_Text_Grunt1Intro::
	.string "L'ascensore non funziona?\n"
	.string "Chi ha la CHIAVE?$"

RocketHideout_B4F_Text_Grunt1Defeat::
	.string "Oh no!$"

RocketHideout_B4F_Text_Grunt1PostBattle::
	.string "Oh no! Ho perso la CHIAVE\n"
	.string "dell'ASCENSORE!$"

