SixIsland_RuinValley_Text_CantFigureOutHowToGetInside::
	.string "Non riesco a capire come\n"
	.string "si fa ad entrare.$"

SixIsland_RuinValley_Text_IFoundThisPlace::
	.string "Questo posto l'ho scoperto io.\p"
	.string "Ora non farti prendere dall'invidia.$"

SixIsland_RuinValley_Text_CheckDoorMoreThoroughly::
	.string "La porta non vuole proprio aprirsi.\n"
	.string "Vuoi controllarla meglio?$"

SixIsland_RuinValley_Text_LeftDoorAlone::
	.string "{PLAYER} distoglie l'attenzione\n"
	.string "dalla porta.$"

SixIsland_RuinValley_Text_SeveralDotsOnTheDoor::
	.string "Ad un attento esame, scolpiti sulla\n"
	.string "porta si notano diversi punti.$"

SixIsland_RuinValley_Text_DoorIsOpen::
	.string "La porta è aperta…$"

SixIsland_RuinValley_Text_StanlyIntro::
	.string "Ci sono tanti segreti ancora da\n"
	.string "scoprire in questo mondo.$"

SixIsland_RuinValley_Text_StanlyDefeat::
	.string "Hm…$"

SixIsland_RuinValley_Text_StanlyPostBattle::
	.string "Vuoi un consiglio? Almeno una volta\n"
	.string "al giorno, fermati a pensare ai\l"
	.string "misteri del mondo.$"

SixIsland_RuinValley_Text_FosterIntro::
	.string "Dimmi, cosa ti ha spinto fin qui?$"

SixIsland_RuinValley_Text_FosterDefeat::
	.string "È tanto che non combatto,\n"
	.string "non ho più i riflessi pronti.$"

SixIsland_RuinValley_Text_FosterPostBattle::
	.string "Il SETTIPELAGO comprende\n"
	.string "diverse rovine.\p"
	.string "Molte di queste sono antichissime.$"

SixIsland_RuinValley_Text_LarryIntro::
	.string "Si dice che sull'isola vi siano\n"
	.string "pietre misteriose.\p"
	.string "Ci dev'essere un qualche\n"
	.string "collegamento con le rovine.$"

SixIsland_RuinValley_Text_LarryDefeat::
	.string "Ah, interessante.$"

SixIsland_RuinValley_Text_LarryPostBattle::
	.string "Quelle rovine…\p"
	.string "…Non sono ancora riuscito ad\n"
	.string "entrarci.$"

SixIsland_RuinValley_Text_DarylIntro::
	.string "Una lotta contro di te, quassù?\n"
	.string "Ottima idea!$"

SixIsland_RuinValley_Text_DarylDefeat::
	.string "Ho perso troppo facilmente!$"

SixIsland_RuinValley_Text_DarylPostBattle::
	.string "Arrampicarmi su queste montagne\n"
	.string "è una gioia per me!$"

SixIsland_RuinValley_Text_HectorIntro::
	.string "Conosco bene questi posti.$"

SixIsland_RuinValley_Text_HectorDefeat::
	.string "So cosa vuoi sapere!\n"
	.string "Va bene, te lo dico!$"

SixIsland_RuinValley_Text_HectorPostBattle::
	.string "Sulla porta d'ingresso per le\n"
	.string "rovine ci sono strane incisioni. Non\l"
	.string "ho idea di cosa significhino.$"

