SafariZone_North_Text_RestHouse::
	.string "OSTELLO$"

SafariZone_North_Text_SecretHouseStillAhead::
	.string "CONSIGLI UTILI\p"
	.string "La CASA SEGRETA è più avanti!$"

SafariZone_North_Text_Area2::
	.string "ZONA 2$"

SafariZone_North_Text_ZigzagThroughTallGrass::
	.string "CONSIGLI UTILI\p"
	.string "I POKéMON si nascondono nell'erba\n"
	.string "alta!\p"
	.string "Per scovarli, devi aggirarti tra le\n"
	.string "zone erbose!$"

SafariZone_North_Text_WinFreeHMFindSecretHouse::
	.string "CONSIGLI UTILI\p"
	.string "Se trovi la CASA SEGRETA\n"
	.string "vinci una MN!$"

