VictoryRoad_2F_Text_DawsonIntro::
	.string "Se puoi passare da qui, puoi anche\n"
	.string "affrontare i SUPERQUATTRO!$"

VictoryRoad_2F_Text_DawsonDefeat::
	.string "No!\n"
	.string "Incredibile!$"

VictoryRoad_2F_Text_DawsonPostBattle::
	.string "In fatto di POKéMON, ti batto di\n"
	.string "sicuro!$"

VictoryRoad_2F_Text_DaisukeIntro::
	.string "La VIA VITTORIA è la prova finale\n"
	.string "per tutti gli ALLENATORI!$"

VictoryRoad_2F_Text_DaisukeDefeat::
	.string "Ahiaia!$"

VictoryRoad_2F_Text_DaisukePostBattle::
	.string "Se non puoi procedere, prova\n"
	.string "a spostare i massi!$"

VictoryRoad_2F_Text_NelsonIntro::
	.string "Ah!\n"
	.string "Vuoi sfidare i SUPERQUATTRO?$"

VictoryRoad_2F_Text_NelsonDefeat::
	.string "Mi hai sconfitto!$"

VictoryRoad_2F_Text_NelsonPostBattle::
	.string "Anche {RIVAL} è passato da qui!$"

VictoryRoad_2F_Text_VincentIntro::
	.string "Forza!\n"
	.string "Ti darò una bella lezione!$"

VictoryRoad_2F_Text_VincentDefeat::
	.string "La lezione l'ho avuta io!$"

VictoryRoad_2F_Text_VincentPostBattle::
	.string "Ora hai diritto di passare per la\n"
	.string "VIA VITTORIA!$"

VictoryRoad_2F_Text_GregoryIntro::
	.string "È molto dura la VIA VITTORIA?$"

VictoryRoad_2F_Text_GregoryDefeat::
	.string "Bel lavoro!$"

VictoryRoad_2F_Text_GregoryPostBattle::
	.string "Molti ALLENATORI gettano la spugna\n"
	.string "proprio qua!$"

VictoryRoad_2F_Text_Gyaoo::
	.byte 0x88, 0x74, 0xAE, 0x55, 0xAB, 0xFF

