SafariZone_West_Text_KogaPatrolsSafariEverySoOften::
	.string "Visto quanto è grande la ZONA\n"
	.string "SAFARI?\p"
	.string "Ogni tanto passa di qui KOGA,\n"
	.string "CAPOPALESTRA di FUCSIAPOLI.\p"
	.string "Grazie a lui, tutti possono giocare\n"
	.string "senza correre nessun pericolo.$"

SafariZone_West_Text_RocksMakeMonRunButEasierCatch::
	.string "Tirare SASSI ai POKéMON rende\n"
	.string "più facile catturarli, ma aumenta\l"
	.string "il rischio che scappino.$"

SafariZone_West_Text_BaitMakesMonStickAround::
	.string "L'ESCA rende più difficile la\n"
	.string "fuga ai POKéMON.$"

SafariZone_West_Text_HikedLotsDidntSeeMonIWanted::
	.string "Ho camminato molto, ma non ho\n"
	.string "visto i POKéMON che\l"
	.string "m'interessavano.$"

