SSAnne_Deck_Text_ShipDepartingSoon::
	.string "La festa è finita!\n"
	.string "La nave salperà tra poco!$"

SSAnne_Deck_Text_ScrubbingDecksHardWork::
	.string "Uff!\n"
	.string "Pulire in coperta è un lavoraccio!$"

SSAnne_Deck_Text_FeelSeasick::
	.string "Uff, mi sento male…\p"
	.string "Sono uscito a prendere un\n"
	.string "po' d'aria.$"

SSAnne_Deck_Text_EdmondIntro::
	.string "Ehi, tu!\p"
	.string "Balliamo!!! Ti va?$"

SSAnne_Deck_Text_EdmondDefeat::
	.string "Sei impressionante!!!$"

SSAnne_Deck_Text_EdmondPostBattle::
	.string "Quante specie di POKéMON pensi che\n"
	.string "esistano?$"

SSAnne_Deck_Text_TrevorIntro::
	.string "Ehi! Hai il mal di mare?$"

SSAnne_Deck_Text_TrevorDefeat::
	.string "Mi sono distratto!$"

SSAnne_Deck_Text_TrevorPostBattle::
	.string "Mio padre dice che ci sono 100\n"
	.string "specie di POKéMON. Io penso che\l"
	.string "siano di più.$"

