FourIsland_IcefallCave_Back_Text_LoreleiKeepHandsOffMons::
	.string "LORELEI: Giù le manacce dai\n"
	.string "POKéMON della grotta!\p"
	.string "Altrimenti, vedrete!!!$"

FourIsland_IcefallCave_Back_Text_ShutItLadyLeaveUsBe::
	.string "Ragazzina, chiudi il becco e\n"
	.string "togliti di mezzo.\p"
	.string "Sloggia, prima che ci\n"
	.string "innervosiamo!$"

FourIsland_IcefallCave_Back_Text_LoreleiPlayerHelpMeKickPoachersOut::
	.string "LORELEI: {PLAYER}?!\n"
	.string "Cosa ci fai qua?\p"
	.string "Vabbè, ci salutiamo dopo.\n"
	.string "Ora aiutami!\p"
	.string "Dobbiamo cacciare questi cattivoni!\p"
	.string "Stanno cercando POKéMON qui per\n"
	.string "andarli a vendere!\p"
	.string "Tu occupati di quello lì!$"

FourIsland_IcefallCave_Back_Text_GruntIntro::
	.string "Questa è bella!\p"
	.string "Chi ha detto che non possiamo fare\n"
	.string "ciò che ci pare con i POKéMON?$"

FourIsland_IcefallCave_Back_Text_GruntDefeat::
	.string "Questo non ci voleva!$"

FourIsland_IcefallCave_Back_Text_LoreleiWhereHaveYouTakenMons::
	.string "LORELEI: Che ridicoli\n"
	.string "mollaccioni!\p"
	.string "Avanti! Parlate!\p"
	.string "Dove avete portato i POKéMON\n"
	.string "che avete catturato?$"

FourIsland_IcefallCave_Back_Text_NotTellingYouThat::
	.string "Puoi scordartelo!\n"
	.string "Non te lo dirò mai!$"

FourIsland_IcefallCave_Back_Text_LoreleiWellDeepFreezeYou::
	.string "LORELEI: Confessa, o ti congelerò\n"
	.string "come un pacco di spinaci!\p"
	.string "Il mio LAPRAS è furioso per ciò\n"
	.string "che hai fatto ai suoi amici!\p"
	.string "Vai, LAPRAS!\n"
	.string "GELORAGGIO…$"

FourIsland_IcefallCave_Back_Text_OkayRocketWareHouseFiveIsland::
	.string "No!!! Va bene!\n"
	.string "Ti dirò tutto!\p"
	.string "I POKéMON sono nel MAGAZZINO\n"
	.string "ROCKET a QUINTISOLA.\p"
	.string "Ecco qui! Ora che ve l'ho detto\n"
	.string "potete lasciarci andare.\p"
	.string "Intanto, non riuscirete mai ad\n"
	.string "arrivare al MAGAZZINO ROCKET!\p"
	.string "Hehehehehe!$"

FourIsland_IcefallCave_Back_Text_ThankYouThisIsAwful::
	.string "Grazie, {PLAYER}!\n"
	.string "Tutto questo è orribile!\p"
	.string "Sono nata e cresciuta su\n"
	.string "queste isole.\p"
	.string "Non pensavo che potessero\n"
	.string "diventare il covo di questi\l"
	.string "criminali!$"

