SaffronCity_House_Text_DontLookAtMyLetter::
	.string "Grazie per avermi scritto.\n"
	.string "Spero di vederti presto!\p"
	.string "Ehi!\n"
	.string "Non leggere la mia lettera!$"

SaffronCity_House_Text_Pidgey::
	.string "PIDGEY: Grugrù!$"

SaffronCity_House_Text_GettingCopycatPokeDoll::
	.string "COPIONA è forte!\n"
	.string "Le porto una POKé BAMBOLA!$"

SaffronCity_House_Text_ExplainPPUp::
	.string "Mi hanno regalato un PP-SU.\p"
	.string "Aumenta i PP degli attacchi!$"

