SSAnne_2F_Room2_Text_BrooksIntro::
	.string "Lottare contro i giovani mi tiene\n"
	.string "in forma!$"

SSAnne_2F_Room2_Text_BrooksDefeat::
	.string "Bella lotta!\n"
	.string "Sono ringiovanito!!!$"

SSAnne_2F_Room2_Text_BrooksPostBattle::
	.string "15 anni fa avrei vinto!!!$"

SSAnne_2F_Room2_Text_DaleIntro::
	.string "Guarda cosa ho pescato!$"

SSAnne_2F_Room2_Text_DaleDefeat::
	.string "Sono distrutto!!!$"

SSAnne_2F_Room2_Text_DalePostBattle::
	.string "Una festa?\p"
	.string "La festa sulla nave dovrebbe\n"
	.string "essere già finita!$"

