Route4_Text_TrippedOverGeodude::
	.string "Sono inciampata in un roccioso\n"
	.string "GEODUDE!$"

Route4_Text_CrissyIntro::
	.string "Sono qui per cercare POKéMON\n"
	.string "simili a funghi!$"

Route4_Text_CrissyDefeat::
	.string "I miei bei POKéMON simili a\n"
	.string "funghi!$"

Route4_Text_CrissyPostBattle::
	.string "È probabile che non ci siano più\n"
	.string "POKéMON simili a funghi qui!\p"
	.string "Penso di averli presi tutti io.$"

Route4_Text_MtMoonEntrance::
	.string "MONTE LUNA\n"
	.string "Entrata tunnel$"

Route4_Text_RouteSign::
	.string "PERCORSO 4\n"
	.string "MONTE LUNA - CELESTOPOLI$"

Text_MegaPunchTeach::
	.string "Un pugno di inaudita potenza!\p"
	.string "Una concentrazione di ferocia!\p"
	.string "MEGAPUGNO è la\n"
	.string "soluzione ideale. Sei d'accordo?\p"
	.string "Se vuoi, posso insegnare\n"
	.string "MEGAPUGNO a uno dei tuoi\l"
	.string "POKéMON!$"

Text_MegaPunchDeclined::
	.string "Torna quando avrai capito il\n"
	.string "valore di MEGAPUGNO!$"

Text_MegaPunchWhichMon::
	.string "Bene! A quale POKéMON vuoi\n"
	.string "che lo insegni?$"

Text_MegaPunchTaught::
	.string "Ora siamo fratelli di pugno, per\n"
	.string "così dire!\p"
	.string "Ora vai, prima che ti veda quel\n"
	.string "pazzoide che si allena solo\l"
	.string "tirando calci!$"

Text_MegaKickTeach::
	.string "Un calcio di inaudita potenza!\p"
	.string "Una concentrazione di ferocia!\p"
	.string "MEGACALCIO è semplicemente\n"
	.string "perfetto. Sei d'accordo?\p"
	.string "Se vuoi, posso insegnare\n"
	.string "MEGACALCIO a uno dei tuoi\l"
	.string "POKéMON!$"

Text_MegaKickDeclined::
	.string "Tornerai a pregarmi in ginocchio,\n"
	.string "appena avrai capito l'importanza\l"
	.string "di MEGACALCIO!$"

Text_MegaKickWhichMon::
	.string "Va bene! A quale POKéMON vuoi\n"
	.string "che lo insegni?$"

Text_MegaKickTaught::
	.string "Ora siamo fratelli di calci, se\n"
	.string "mi passi il gioco di parole.\p"
	.string "Fila via prima che ti veda quel\n"
	.string "fissato che si allena solo\l"
	.string "tirando pugni!$"

Route4_Text_PeopleLikeAndRespectBrock::
	.string "Ehi, quella è la MEDAGLIA SASSO!\n"
	.string "L'hai ricevuta da BROCK, vero?\p"
	.string "BROCK è un grande. Non solo è\n"
	.string "forte, ma soprattutto ha carisma.\p"
	.string "Vorrei diventare un CAPOPALESTRA\n"
	.string "come lui.$"

