CeladonCity_DepartmentStore_Roof_Text_ImThirstyGiveHerDrink::
	.string "Ho sete!\n"
	.string "Vorrei qualcosa da bere!\p"
	.string "{FONT_NORMAL}Le dai da bere?$"

CeladonCity_DepartmentStore_Roof_Text_GiveWhichDrink::
	.string "Quale bibita le dai?$"

CeladonCity_DepartmentStore_Roof_Text_YayFreshWaterHaveThis::
	.string "Ehi!\p"
	.string "ACQUA FRESCA!\p"
	.string "Grazie!\n"
	.string "Prendila, è per te!$"

Text_ReceivedItemFromLittleGirl::
	.string "{PLAYER} riceve\n"
	.string "{STR_VAR_2}!$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM16::
	.string "MT16 contiene SCHERMOLUCE!\p"
	.string "Indebolisce gli attacchi SPECIALI\n"
	.string "del tuo nemico.$"

CeladonCity_DepartmentStore_Roof_Text_YaySodaPopHaveThis::
	.string "Fantastico!\p"
	.string "GASSOSA!\p"
	.string "Grazie!\n"
	.string "Prendila, è per te!$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM20::
	.string "MT20 contiene SALVAGUARDIA!\p"
	.string "Serve ad evitare ai tuoi POKéMON\n"
	.string "problemi di stato.$"

CeladonCity_DepartmentStore_Roof_Text_YayLemonadeHaveThis::
	.string "Forte!\p"
	.string "LEMONSUCCO!\p"
	.string "Grazie!\n"
	.string "Prendilo, è per te!$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM33::
	.string "MT33 contiene RIFLESSO!\p"
	.string "Indebolisce gli attacchi fisici\n"
	.string "dell'avversario.$"

CeladonCity_DepartmentStore_Roof_Text_DontHaveSpaceForThis::
	.string "Non hai più spazio per questo!$"

CeladonCity_DepartmentStore_Roof_Text_ImNotThirstyAfterAll::
	.string "No, grazie!\n"
	.string "Tanto non ho molta sete!$"

CeladonCity_DepartmentStore_Roof_Text_MySisterIsImmature::
	.string "Mia sorella è un ALLENATORE, che\n"
	.string "tu ci creda o no!\p"
	.string "Ma è così immatura che mi fa\n"
	.string "perdere le staffe!$"

CeladonCity_DepartmentStore_Roof_Text_ImThirstyIWantDrink::
	.string "Ho sete!\n"
	.string "Vorrei qualcosa da bere!$"

CeladonCity_DepartmentStore_Roof_Text_FloorSign::
	.string "TETTO:\n"
	.string "DISTRIBUTORI AUTOMATICI$"

CeladonCity_DepartmentStore_Roof_Text_VendingMachineWhatDoesItHave::
	.string "Un distributore!\n"
	.string "Ecco i prodotti!$"

CeladonCity_DepartmentStore_Roof_Text_NotEnoughMoney::
	.string "Caspita, non ho abbastanza soldi!$"

CeladonCity_DepartmentStore_Roof_Text_DrinkCanPoppedOut::
	.string "È uscita una lattina di\n"
	.string "{STR_VAR_1}!$"

CeladonCity_DepartmentStore_Roof_Text_NoMoreRoomForStuff::
	.string "Non hai più spazio per nient'altro!$"

CeladonCity_DepartmentStore_Roof_Text_NotThirsty::
	.string "Non ho sete!$"

