SSAnne_1F_Room2_Text_TylerIntro::
	.string "Io adoro i POKéMON, e tu?$"

SSAnne_1F_Room2_Text_TylerDefeat::
	.string "Wow!\n"
	.string "Sei una forza!$"

SSAnne_1F_Room2_Text_TylerPostBattle::
	.string "Perché non diventiamo amici?\p"
	.string "Ci scambieremo i POKéMON!$"

SSAnne_1F_Room2_Text_AnnIntro::
	.string "Questi POKéMON provengono da\n"
	.string "tutto il mondo!$"

SSAnne_1F_Room2_Text_AnnDefeat::
	.string "E io avrei fatto il giro del mondo\n"
	.string "per questi?$"

SSAnne_1F_Room2_Text_AnnPostBattle::
	.string "Hai ferito i miei poveri POKéMON!!!\p"
	.string "Portameli al CENTRO POKéMON!!!$"

SSAnne_1F_Room2_Text_CruisingAroundWorld::
	.string "Siamo in crociera attorno al mondo!$"

