Route21_North_Text_RonaldIntro::
	.string "Vuoi sapere se i pesci abboccano?$"

Route21_North_Text_RonaldDefeat::
	.string "Che botta!$"

Route21_North_Text_RonaldPostBattle::
	.string "Non pesco niente di buono!$"

Route21_North_Text_WadeIntro::
	.string "Ho preso un bel po' di POKéMON!\n"
	.string "Guarda!$"

Route21_North_Text_WadeDefeat::
	.string "Che noia, questi MAGIKARP!$"

Route21_North_Text_WadePostBattle::
	.string "Pesco solo MAGIKARP!$"

Route21_North_Text_SpencerIntro::
	.string "Il mare pulisce il corpo e l'anima!$"

Route21_North_Text_SpencerDefeat::
	.string "Ahiahi!$"

Route21_North_Text_SpencerPostBattle::
	.string "Mi piace anche la montagna!$"

Route21_North_Text_CueBallIntro::
	.string "ÈºだっÛ Œまàè\n"
	.string "Èùぎà Ëñぜ!$"

Route21_North_Text_CueBallDefeat::
	.string "ぐわわ!$"

Route21_North_Text_CueBallPostBattle::
	.string "ÂÊôÒÔÂ だÑ?\n"
	.string "ÂñÓ- ÈÈÊß ÈÓわだッ!$"

