CeladonCity_GameCorner_Text_CanExchangeCoinsNextDoor::
	.string "Salve!\p"
	.string "Alla porta accanto puoi cambiare i\n"
	.string "tuoi GETTONI in premi favolosi.$"

CeladonCity_GameCorner_Text_WelcomeBuySomeCoins::
	.string "Prego, questo è il CASINÒ ROCKET!\p"
	.string "Hai bisogno di GETTONI?$"

CeladonCity_GameCorner_Text_ComePlaySometime::
	.string "No?\n"
	.string "Vieni qualche volta a giocare!$"

CeladonCity_GameCorner_Text_SorryDontHaveCoinCase::
	.string "Non hai un SALVADANAIO!$"

CeladonCity_GameCorner_Text_CoinCaseIsFull::
	.string "Oh!\n"
	.string "Il SALVADANAIO è pieno!$"

CeladonCity_GameCorner_Text_CantAffordCoins::
	.string "Non hai abbastanza soldi per\n"
	.string "ottenere lo scambio dei GETTONI!$"

CeladonCity_GameCorner_Text_HereAreYourCoins::
	.string "Grazie!\n"
	.string "Eccoti i tuoi GETTONI!$"

CeladonCity_GameCorner_Text_RumoredTeamRocketRunsThisPlace::
	.string "Non dirlo in giro!\p"
	.string "Ma si dice che qui comandi TEAM\n"
	.string "ROCKET.$"

CeladonCity_GameCorner_Text_ThinkMachinesHaveDifferentOdds::
	.string "Queste macchine sono impostate\n"
	.string "diversamente!$"

CeladonCity_GameCorner_Text_DoYouWantToPlay::
	.string "Ehi! Ti piacerebbe giocare?$"

CeladonCity_GameCorner_Text_Received10CoinsFromMan::
	.string "{PLAYER} riceve\n"
	.string "10 GETTONI!$"

CeladonCity_GameCorner_Text_DontNeedMyCoins::
	.string "Non hai bisogno dei miei GETTONI!$"

CeladonCity_GameCorner_Text_WinsComeAndGo::
	.string "La fortuna va e viene.$"

CeladonCity_GameCorner_Text_WinOrLoseItsOnlyLuck::
	.string "Mi sto divertendo un mondo!$"

CeladonCity_GameCorner_Text_GymGuyAdvice::
	.string "Ehi!\p"
	.string "Non hai di meglio da fare,\n"
	.string "aspirante CAMPIONE?\p"
	.string "ERIKA è il CAPOPALESTRA di\n"
	.string "AZZURROPOLI! Usa POKéMON di\l"
	.string "tipo ERBA!\p"
	.string "Può sembrare molto tranquilla, ma\n"
	.string "non sottovalutarla!$"

CeladonCity_GameCorner_Text_RareMonsForCoins::
	.string "Puoi scambiare i tuoi GETTONI per\n"
	.string "dei POKéMON rari!\p"
	.string "Ma proprio non riesco a vincere!$"

CeladonCity_GameCorner_Text_SoEasyToGetHooked::
	.string "I giochi sono pericolosi, è facile\n"
	.string "cascarci!$"

CeladonCity_GameCorner_Text_WantSomeCoins::
	.string "Che c'è, vuoi dei GETTONI?$"

CeladonCity_GameCorner_Text_Received20CoinsFromNiceGuy::
	.string "{PLAYER} riceve\n"
	.string "20 GETTONI!$"

CeladonCity_GameCorner_Text_YouHaveLotsOfCoins::
	.string "Hai un sacco di GETTONI!$"

CeladonCity_GameCorner_Text_NeedMoreCoinsForMonIWant::
	.string "Uffa! Mi servono più GETTONI per\n"
	.string "i POKéMON che voglio!$"

CeladonCity_GameCorner_Text_HereAreSomeCoinsShoo::
	.string "Cosa? Mi buttate fuori! Ecco qui\n"
	.string "dei GETTONI!$"

CeladonCity_GameCorner_Text_Received20CoinsFromMan::
	.string "{PLAYER} riceve\n"
	.string "20 GETTONI!$"

CeladonCity_GameCorner_Text_YouveGotPlentyCoins::
	.string "Ehi, vedo che ne hai già\n"
	.string "a sufficienza!$"

CeladonCity_GameCorner_Text_WatchReelsClosely::
	.string "Il trucco è osservare bene le\n"
	.string "figure!$"

CeladonCity_GameCorner_Text_GruntIntro::
	.string "Faccio la guardia a questo poster,\n"
	.string "smamma di qua!$"

CeladonCity_GameCorner_Text_GruntDefeat::
	.string "Dang!$"

CeladonCity_GameCorner_Text_GruntPostBattle::
	.string "Il RIFUGIO di TEAM ROCKET\n"
	.string "potrebbe essere scoperto!\p"
	.string "Meglio dirlo al CAPO!$"

CeladonCity_GameCorner_Text_SwitchBehindPosterPushIt::
	.string "Ehi!\p"
	.string "Un pulsante dietro al poster!\n"
	.string "Premiamolo!$"

CeladonCity_GameCorner_Text_CoinCaseIsRequired::
	.string "È necessario un SALVADANAIO!$"

CeladonCity_GameCorner_Text_DontHaveCoinCase::
	.string "Ups!\n"
	.string "Non vedo il SALVADANAIO!$"

CeladonCity_GameCorner_Text_SlotMachineWantToPlay::
	.string "Una slot machine!\n"
	.string "Vuoi giocare?$"

CeladonCity_GameCorner_Text_OutOfOrder::
	.string "NON FUNZIONA\n"
	.string "È guasta.$"

CeladonCity_GameCorner_Text_OutToLunch::
	.string "TORNO SUBITO\n"
	.string "Dev'essere occupata.$"

CeladonCity_GameCorner_Text_SomeonesKeys::
	.string "Una borsa!\n"
	.string "Dev'essere occupata.$"

