SixIsland_WaterPath_Text_RoseIntro::
	.string "Una brezza leggera mi ha\n"
	.string "trasportato fin qui.$"

SixIsland_WaterPath_Text_RoseDefeat::
	.string "Mi piace quel tuo aspetto\n"
	.string "determinato!$"

SixIsland_WaterPath_Text_RosePostBattle::
	.string "Vorrei addentrarmi nei boschi\n"
	.string "qui vicino, ma…\p"
	.string "…ho paura dei\n"
	.string "POKéMON di tipo COLEOTTERO!$"

SixIsland_WaterPath_Text_EdwardIntro::
	.string "Mi alleno in segreto, così non\n"
	.string "mi vede nessuno.$"

SixIsland_WaterPath_Text_EdwardDefeat::
	.string "L'importante è che nessuno\n"
	.string "mi abbia visto perdere!$"

SixIsland_WaterPath_Text_EdwardPostBattle::
	.string "Agli artisti non piace svelare i\n"
	.string "segreti della propria arte!$"

SixIsland_WaterPath_Text_SamirIntro::
	.string "Vorresti dirmi che ci sono troppi\n"
	.string "NUOTATORI da queste parti?\p"
	.string "Ehi, ma io SONO un NUOTATORE!$"

SixIsland_WaterPath_Text_SamirDefeat::
	.string "No no no no no!$"

SixIsland_WaterPath_Text_SamirPostBattle::
	.string "Sono un NUOTATORE e me ne vanto,\n"
	.string "anche se mi hai battuto!$"

SixIsland_WaterPath_Text_DeniseIntro::
	.string "Il mio fidanzato non ha mai tempo\n"
	.string "per me, così nuoto da sola.$"

SixIsland_WaterPath_Text_DeniseDefeat::
	.string "Sapevo che sarebbe andata così!$"

SixIsland_WaterPath_Text_DenisePostBattle::
	.string "Quando non posso stare con il mio\n"
	.string "fidanzato, passo il tempo con i\l"
	.string "POKéMON che mi ha regalato.$"

SixIsland_WaterPath_Text_EarlIntro::
	.string "Dimmi un po', dove sono le\n"
	.string "montagne da queste parti?$"

SixIsland_WaterPath_Text_EarlDefeat::
	.string "Ero tanto intento a lottare che mi\n"
	.string "sono perso!$"

SixIsland_WaterPath_Text_EarlPostBattle::
	.string "Ma non ci sono montagne da queste\n"
	.string "parti?$"

SixIsland_WaterPath_Text_MiuIntro::
	.string "MIU: POKéMON, è il momento di\n"
	.string "giocare!$"

SixIsland_WaterPath_Text_MiuDefeat::
	.string "MIU: Uffa, non gioco più con te!$"

SixIsland_WaterPath_Text_MiuPostBattle::
	.string "MIU: Le sconfitte mi fanno perdere\n"
	.string "la voglia di giocare!$"

SixIsland_WaterPath_Text_MiuNotEnoughMons::
	.string "MIU: Io e MIA siamo GEMELLE.\n"
	.string "Combattiamo sempre insieme.$"

SixIsland_WaterPath_Text_MiaIntro::
	.string "MIA: POKéMON, è il momento\n"
	.string "di lottare!$"

SixIsland_WaterPath_Text_MiaDefeat::
	.string "MIA: Ora non ti vantare tanto\n"
	.string "perché hai vinto!$"

SixIsland_WaterPath_Text_MiaPostBattle::
	.string "MIA: POKéMON, mi dispiace di\n"
	.string "avervi fatto perdere!$"

SixIsland_WaterPath_Text_MiaNotEnoughMons::
	.string "MIA: Hai solo un POKéMON?\p"
	.string "E non soffrite di solitudine?$"

SixIsland_WaterPath_Text_WantedUltimateHorn::
	.string "Si cercano emozioni!!!\n"
	.string "Anche di seconda mano!!!$"

SixIsland_WaterPath_Text_RouteSign::
	.string "VIA MARINA\n"
	.string "Per la VALLE ANTICA$"

