SilphCo_6F_Text_RocketsTookOverBuilding::
	.string "Sono arrivati i ROCKET e hanno\n"
	.string "preso possesso dell'edificio!$"

SilphCo_6F_Text_BetterGetBackToWork::
	.string "OK, meglio tornare al lavoro!$"

SilphCo_6F_Text_HelpMePlease::
	.string "Mamma mia!\n"
	.string "Aiutami!$"

SilphCo_6F_Text_WeGotEngaged::
	.string "Ci siamo fidanzati!\n"
	.string "Ah ah!$"

SilphCo_6F_Text_ThatManIsSuchACoward::
	.string "Vedi quell'uomo vicino a me?\n"
	.string "È un mollaccione!$"

SilphCo_6F_Text_NeedsMeToLookAfterHim::
	.string "Vedi quell'uomo vicino a me?\n"
	.string "È così tenero che…\l"
	.string "…quasi quasi me lo sposo!$"

SilphCo_6F_Text_RocketsTryingToConquerWorld::
	.string "TEAM ROCKET cerca di conquistare\n"
	.string "il mondo con i POKéMON!$"

SilphCo_6F_Text_RocketsRanAwayBecauseOfYou::
	.string "Hai fatto scappare TEAM ROCKET!$"

SilphCo_6F_Text_TargetedSilphForOurMonProducts::
	.string "Devono aver preso di mira la SILPH\n"
	.string "per i nostri prodotti POKéMON.$"

SilphCo_6F_Text_ComeWorkForSilphWhenYoureOlder::
	.string "Vieni a lavorare per la SILPH,\n"
	.string "quando sarai grande!$"

SilphCo_6F_Text_Grunt1Intro::
	.string "Sono uno dei 4 FRATELLI ROCKET!$"

SilphCo_6F_Text_Grunt1Defeat::
	.string "Mi hai fatto fuori!$"

SilphCo_6F_Text_Grunt1PostBattle::
	.string "Non importa!\n"
	.string "I miei fratelli mi vendicheranno!$"

SilphCo_6F_Text_TaylorIntro::
	.string "Quel maledetto PRESIDENTE!\p"
	.string "Non avrebbe dovuto mandarmi alla\n"
	.string "SUCCURSALE TIKSI!\p"
	.string "Sono sicuro che è per questo che\n"
	.string "TEAM ROCKET ci ha preso di\l"
	.string "mira!$"

SilphCo_6F_Text_TaylorDefeat::
	.string "Sono finito!$"

SilphCo_6F_Text_TaylorPostBattle::
	.string "La SUCCURSALE TIKSI? È in un\n"
	.string "paesino sperduto della steppa!$"

SilphCo_6F_Text_Grunt2Intro::
	.string "Osi tradire TEAM ROCKET?$"

SilphCo_6F_Text_Grunt2Defeat::
	.string "Ci hai traditi!$"

SilphCo_6F_Text_Grunt2PostBattle::
	.string "Non capisci? Difendendo la giustizia\n"
	.string "tradisci il male!$"

SilphCo_6F_Text_FloorSign::
	.string "DIREZIONE della SILPH SpA\n"
	.string "5ºP$"

