JPText_BodySlamTeach::
	.string "Ô-º ぼù-+!\n"
	.string "どっÙが ÎÊà ëŒばñÉ?\l"
	.string "çÏÉÉû Ï;Âぶ ÏÛñ+だ\p"
	.string "Êîè ßÉまà èÁっŒú\n"
	.string "ÚぶºÔÂだß…\l"
	.string "Éわûà Êîç ポケモンà\l"
	.string "çÏÉÉû ÈÏÇÛ ôªっÉ?$"

JPText_BodySlamDeclined::
	.string "まŒ ÈÁで ぼù-+!$"

JPText_BodySlamWhichMon::
	.string "どç ポケモンà\n"
	.string "ÈÏÇŒÁ ÉÁ?$"

JPText_BodySlamTaught::
	.string "ぼùù-+!$"

FourIsland_House1_Text_YoureAwfullyHeavy::
	.string "Boioing!\n"
	.string "Ehi, sei proprio pesante!$"

