Route6_NorthEntrance_Text_ThirstyOnGuardDuty::
	.string "Sono di guardia.\n"
	.string "Uha! Ho una sete!\p"
	.string "Non puoi passare! La strada è\n"
	.string "chiusa.$"

Route6_NorthEntrance_Text_ThatTeaLooksTasty::
	.string "Oh, quel TÈ sembra delizioso!\n"
	.string "Ho una sete spaventosa!$"

Route6_NorthEntrance_Text_ThanksIllShareTeaWithGuards::
	.string "Huh? È per me?\n"
	.string "Davvero? Grazie!\p"
	.string "… …\n"
	.string "Glug, glug…\p"
	.string "… …\n"
	.string "Gulp…\p"
	.string "Se vuoi andare a ZAFFERANOPOLI…\n"
	.string "… …\l"
	.string "Puoi passare!\p"
	.string "Condividerò questo TÈ delizioso con\n"
	.string "le altre guardie.$"

Route6_NorthEntrance_Text_HiHowsItGoing::
	.string "Ehi! Grazie per la bibita fresca!$"

