SaffronCity_Text_WhatDoYouWantGetLost::
	.string "Che vuoi?\n"
	.string "Sparisci!$"

SaffronCity_Text_BossTakeTownForTeamRocket::
	.string "Il CAPO vuole conquistare questa\n"
	.string "città!$"

SaffronCity_Text_DontGetDefiantOrIllHurtYou::
	.string "Smamma!$"

SaffronCity_Text_SaffronBelongsToTeamRocket::
	.string "ZAFFERANOPOLI è occupata da TEAM\n"
	.string "ROCKET!$"

SaffronCity_Text_CriminalLifeMakesMeFeelAlive::
	.string "Essere malvagio mi fa sentire così\n"
	.string "vivo!$"

SaffronCity_Text_WatchWhereYoureWalking::
	.string "Ahi!\n"
	.string "Guarda dove metti i piedi!$"

SaffronCity_Text_WeCanExploitMonsAroundWorld::
	.string "Con il controllo della SILPH\n"
	.string "sfrutteremo i POKéMON di tutto il\l"
	.string "mondo!$"

SaffronCity_Text_YouBeatTeamRocket::
	.string "Hai sconfitto TEAM ROCKET?\n"
	.string "Incredibile!$"

SaffronCity_Text_SafeToGoOutAgain::
	.string "Sììì! TEAM ROCKET è fuggito!\n"
	.string "Si può nuovamente uscire sicuri!\l"
	.string "Evviva!$"

SaffronCity_Text_PeopleComingBackToSaffron::
	.string "Ora la gente tornerà a\n"
	.string "ZAFFERANOPOLI.$"

SaffronCity_Text_FlewHereOnPidgeot::
	.string "Sono volato qui su PIDGEOT quando\n"
	.string "ho letto della SILPH.\p"
	.string "Già tutto finito?\n"
	.string "Mi sono perso un po' di movimento!$"

SaffronCity_Text_Pidgeot::
	.string "PIDGEOT: Pigigiù!$"

SaffronCity_Text_SawRocketBossEscaping::
	.string "Ho visto il CAPO dei ROCKET\n"
	.string "fuggire dalla sede della SILPH.$"

SaffronCity_Text_ImASecurityGuard::
	.string "Sono un agente di sicurezza.\p"
	.string "Non ammetto mocciosi sospetti qui\n"
	.string "dentro!$"

SaffronCity_Text_HesTakingASnooze::
	.string "…\n"
	.string "Ronf… ronf…\p"
	.string "Sta schiacciando un pisolino!$"

SaffronCity_Text_CitySign::
	.string "ZAFFERANOPOLI\n"
	.string "Dorata terra del commercio$"

SaffronCity_Text_FightingDojo::
	.string "DOJO KARATE$"

SaffronCity_Text_GymSign::
	.string "CAPOPALESTRA di ZAFFERANOPOLI:\n"
	.string "SABRINA\l"
	.string "Regina dei POKéMON di tipo PSICO!$"

SaffronCity_Text_FullHealCuresStatus::
	.string "CONSIGLI UTILI\p"
	.string "CURA TOTALE risolve tutti i\n"
	.string "problemi come il sonno, la\l"
	.string "scottatura, l'avvelenamento…\p"
	.string "…la paralisi e il congelamento.\p"
	.string "Costa un po' di più, ma conviene!$"

SaffronCity_Text_GreatBallImprovedCatchRate::
	.string "CONSIGLI UTILI\p"
	.string "La nuova MEGA BALL offre maggiori\n"
	.string "possibilità di cattura.\p"
	.string "Provala sui POKéMON difficili da\n"
	.string "catturare.$"

SaffronCity_Text_SilphCoSign::
	.string "SILPH SpA\n"
	.string "UFFICI$"

SaffronCity_Text_MrPsychicsHouse::
	.string "CASA DEL SIG. PSICHE$"

SaffronCity_Text_SilphsLatestProduct::
	.string "Il nuovo prodotto della SILPH!\n"
	.string "Lancio sul mercato da stabilirsi…$"

SaffronCity_Text_TrainerFanClubSign::
	.string "FAN CLUB ALLENATORI di POKéMON\p"
	.string "Gli ALLENATORI hanno scritto i loro\n"
	.string "nomi sul cartello…$"

SaffronCity_Text_HowCanClubNotRecognizeLance::
	.string "In questo FAN CLUB…\n"
	.string "…sembrano tutti avere gli\l"
	.string "occhi foderati di prosciutto!\p"
	.string "Com'è possibile che la grandezza\n"
	.string "di LANCE non venga riconosciuta?\p"
	.string "È un paladino della giustizia!\n"
	.string "È allo stesso tempo un uomo\l"
	.string "duro e romantico.\p"
	.string "LANCE è semplicemente il più\n"
	.string "grande!$"

