TwoIsland_PokemonCenter_1F_Text_HaveYouVisitedGameCorner::
	.string "Hai già visto l'ARENA GIOCHI?\p"
	.string "Non ci si può andare da soli:\n"
	.string "devi portarti un amico.$"

TwoIsland_PokemonCenter_1F_Text_OldLadyLivesOutOnCape::
	.string "Non sono tanti gli abitanti di\n"
	.string "SECONDISOLA.\p"
	.string "Hai già conosciuto la vecchietta\n"
	.string "che vive al capo?\p"
	.string "È lì da tempo immemorabile.$"

