Text_CutTreeDown::
	.string "Ô Ç♀éËÌÂヒÁâヒÁL'albero si può abbattere con\n"
	.string "TAGLIO.\p"
	.string "Vuoi usare TAGLIO?$"

Text_MonUsedMove::
	.string "{STR_VAR_1} usa {STR_VAR_2}.$"

Text_TreeCanBeCutDown::
	.string "L'albero si può abbattere con\n"
	.string "TAGLIO.$"

Text_UseRockSmash::
	.string "Questa roccia si può frantumare.\n"
	.string "Vuoi usare SPACCAROCCIA?$"

Text_MonMaySmashRock::
	.string "È una roccia dura, ma un POKéMON\n"
	.string "dovrebbe poterla frantumare.$"

Text_UseStrength::
	.string "È un masso enorme, ma un POKéMON\n"
	.string "dovrebbe poterlo spostare.\p"
	.string "Vuoi usare FORZA?$"

Text_MonUsedStrengthCanMoveBoulders::
	.string "{STR_VAR_1} usa FORZA.\p"
	.string "La FORZA di {STR_VAR_1} riesce a\n"
	.string "spostare i massi.$"

Text_MonMayPushBoulder::
	.string "È un masso enorme, ma un POKéMON\n"
	.string "dovrebbe poterlo spostare.$"

Text_StrengthMadeMovingBouldersPossible::
	.string "FORZA ha reso possibile spostare\n"
	.string "i massi.$"

Text_WallOfWaterCrashingDown::
	.string "Una parete d'acqua che si schianta\n"
	.string "con un potente fragore…$"

Text_UseWaterfall::
	.string "C'è un'enorme cascata.\n"
	.string "Vuoi usare CASCATA?$"

Text_MonUsedWaterfall::
	.string "{STR_VAR_1} usa CASCATA.$"

Text_MonMayGoUnderwater::
	.string "Il mare è profondo qui. Ci si\n"
	.string "potrebbe immergere anche un\l"
	.string "POKéMON.$"

Text_SeaIsDeepUseDive::
	.string "Il mare è profondo qui.\n"
	.string "Vuoi usare SUB?$"

Text_MonUsedDive::
	.string "{STR_VAR_1} usa SUB.$"

Text_MonMaySurface::
	.string "Una luce illumina l'acqua dall'alto.\n"
	.string "Da qui un POKéMON potrebbe\l"
	.string "riemergere.$"

Text_LightFilteringUseDive::
	.string "Una luce illumina l'acqua dall'alto.\n"
	.string "Vuoi usare SUB?$"

Text_DiveCantBeUsedHere::
	.string "C'è qualcosa che blocca in\n"
	.string "superficie. Non puoi usare SUB qui.$"

Text_LooksLikeNothingHere::
	.string "Pare non ci sia nulla qui…$"

