FiveIsland_ResortGorgeous_House_Text_PleaseHearMyWish::
	.string "NOIANNA: Ehi!\n"
	.string "Non ci siamo già visti?\p"
	.string "Beh, non importa.\n"
	.string "Sono annoiat… cioè, scusa…\l"
	.string "…onorata di conoscerti.\p"
	.string "Ascolta, ho un desiderio, forse\n"
	.string "puoi soddisfarlo…$"

FiveIsland_ResortGorgeous_House_Text_WishToSeeMonPlease::
	.string "Mentre mi annoiavo a morte…\n"
	.string "…mi è venuto in mente che…\p"
	.string "…mi piacerebbe vedere un\n"
	.string "esemplare di {STR_VAR_1}.\p"
	.string "Me ne porti uno? Ti prego!\n"
	.string "Ooouuuh… Scusa lo sbadiglio!$"

FiveIsland_ResortGorgeous_House_Text_OhImTiredOfWaiting::
	.string "NOIANNA: Cosa aspetti a mostrarmi\n"
	.string "un POKéMON?!\p"
	.string "Mi hai fatto venire il latte alle\n"
	.string "ginocchia, e l'hai fatto pure\l"
	.string "scadere!\p"
	.string "Sbrigati, su!$"

FiveIsland_ResortGorgeous_House_Text_MonYouCaughtForMeThankYou::
	.string "NOIANNA: Oh, ciaooouuuh…\n"
	.string "Scusa lo sbadiglio!\p"
	.string "Ah, ma questo è l'esemplare\n"
	.string "di {STR_VAR_1} che cercavo!\p"
	.string "Sai che…\n"
	.string "…ti somiglia un po'?\p"
	.string "Grazie mille!\p"
	.string "… …  … …  … …\n"
	.string "Ora però sparisci. La tua vista\l"
	.string "inizia ad annoiarmi.\p"
	.string "… …  … …  … …\n"
	.string "Ah, ho capito!\p"
	.string "SEBASTIANO!\n"
	.string "Ho bisogno di te.$"

FiveIsland_ResortGorgeous_House_Text_ButlerYesMyLady::
	.string "Maggiordomo: Eccomi, signorina!$"

FiveIsland_ResortGorgeous_House_Text_SelphyGiveTokenOfAppreciation::
	.string "NOIANNA: Fai in modo che questa\n"
	.string "persona riceva un segno del mio\l"
	.string "apprezzamento.$"

FiveIsland_ResortGorgeous_House_Text_ButlerIShallDoAsYouBid::
	.string "Maggiordomo: Sì, signorina!\n"
	.string "Provvederò immediatamente!$"

FiveIsland_ResortGorgeous_House_Text_ButlerPleaseAcceptThisAsHerThanks::
	.string "Maggiordomo: Grazie di cuore per\n"
	.string "aver aiutato la signorina NOIANNA.\p"
	.string "Accetta questo, in segno della\n"
	.string "nostra gratitudine…$"

FiveIsland_ResortGorgeous_House_Text_ButlerBagAppearsToBeFull::
	.string "Maggiordomo: Ops! Il tuo ZAINO\n"
	.string "è pieno! Che deprecabile\l"
	.string "situazione!$"

FiveIsland_ResortGorgeous_House_Text_OhHowDisappointing::
	.string "Oh…\n"
	.string "Che delusione.$"

FiveIsland_ResortGorgeous_House_Text_SelphyWishYouBestOfLuck::
	.string "NOIANNA: Ti auguro buona fortuna \n"
	.string "e soprattutto… di annoiarti\l"
	.string "meno di me!$"

FiveIsland_ResortGorgeous_House_Text_LadySelphySmileHasBrillianceOfSun::
	.string "Maggiordomo: Il sorriso della\n"
	.string "signorina NOIANNA è raggiante\l"
	.string "come il sole d'estate.\p"
	.string "Oh, se solo potesse sorridere\n"
	.string "un po' più spesso…$"

