Route16_Text_LaoIntro::
	.string "Che vuoi?$"

Route16_Text_LaoDefeat::
	.string "Non osare ridere!$"

Route16_Text_LaoPostBattle::
	.string "Ci piace stare qui!\n"
	.string "E a te, che t'importa?$"

Route16_Text_KojiIntro::
	.string "Bella BICICLETTA!\n"
	.string "Dà qua!$"

Route16_Text_KojiDefeat::
	.string "Sono KO!$"

Route16_Text_KojiPostBattle::
	.string "Lascia stare.\n"
	.string "Non mi serve la BICICLETTA!$"

Route16_Text_LukeIntro::
	.string "Vieni a giocare, pulce!$"

Route16_Text_LukeDefeat::
	.string "Sei una pulce vincente!$"

Route16_Text_LukePostBattle::
	.string "Odio perdere!\n"
	.string "Sparisci da qui!$"

Route16_Text_HideoIntro::
	.string "Ehi!\n"
	.string "Mi hai urtato!$"

Route16_Text_HideoDefeat::
	.string "Tombola!$"

Route16_Text_HideoPostBattle::
	.string "Seguendo la costa da ARANCIOPOLI\n"
	.string "puoi raggiungere FUCSIAPOLI.$"

Route16_Text_CamronIntro::
	.string "Ho fame e mi sto arrabbiando!$"

Route16_Text_CamronDefeat::
	.string "Male, molto molto male!$"

Route16_Text_CamronPostBattle::
	.string "Mi piacciono i POKéMON feroci!\n"
	.string "Sbranano i nemici, anche se solo\l"
	.string "in senso figurato.$"

Route16_Text_RubenIntro::
	.string "Ehi, divertiamoci con una bella\n"
	.string "lotta!$"

Route16_Text_RubenDefeat::
	.string "Non farmi arrabbiare!$"

Route16_Text_RubenPostBattle::
	.string "Mi piace molestare la gente con il\n"
	.string "fetore dei miei POKéMON!$"

Route16_Text_MonSprawledOutInSlumber::
	.string "Un POKéMON addormentato blocca la\n"
	.string "strada!$"

Route16_Text_CyclingRoadSign::
	.string "Buona discesa!\n"
	.string "PISTA CICLABILE$"

Route16_Text_RouteSign::
	.string "PERCORSO 16\n"
	.string "AZZURROPOLI - FUCSIAPOLI$"

Route16_Text_JedIntro::
	.string "JED: Il nostro amore è senza\n"
	.string "confini, e senza rivali!$"

Route16_Text_JedDefeat::
	.string "JED: Oh, no! Ora LEA crederà che\n"
	.string "sono un perdente!$"

Route16_Text_JedPostBattle::
	.string "JED: A volte credo che LEA si\n"
	.string "aspetti un po' troppo da me.$"

Route16_Text_JedNotEnoughMons::
	.string "JED: Hai solo un POKéMON?\n"
	.string "Ma non hai proprio cuore!$"

Route16_Text_LeaIntro::
	.string "LEA: A volte ho paura di amare\n"
	.string "troppo JED.$"

Route16_Text_LeaDefeat::
	.string "LEA: Ho perso, ma il mio amore per\n"
	.string "JED è imbattibile.$"

Route16_Text_LeaPostBattle::
	.string "LEA: Non credi anche tu che il\n"
	.string "mio ragazzo sia meraviglioso?$"

Route16_Text_LeaNotEnoughMons::
	.string "LEA: Ah, non hai con te due\n"
	.string "POKéMON?\p"
	.string "Non vi sentite soli tu e il tuo\n"
	.string "POKéMON?$"

