Route6_Text_RickyIntro::
	.string "Chi va là?\n"
	.string "Smetti di origliare!$"

Route6_Text_RickyDefeat::
	.string "Elementare, non riesco a vincere!$"

Route6_Text_RickyPostBattle::
	.string "Bla bla bla…\n"
	.string "Bla bla bla…$"

Route6_Text_NancyIntro::
	.string "Scusa, ma è una conversazione\n"
	.string "privata!$"

Route6_Text_NancyDefeat::
	.string "Grr!\n"
	.string "Odio perdere!$"

Route6_Text_NancyPostBattle::
	.string "Bla bla bla…\n"
	.string "Bla bla bla…$"

Route6_Text_KeigoIntro::
	.string "Non ci sono molti insetti qui.$"

Route6_Text_KeigoDefeat::
	.string "No!\n"
	.string "Scherzi?!$"

Route6_Text_KeigoPostBattle::
	.string "Mi piacciono gli insetti! Tornerò\n"
	.string "al BOSCO SMERALDO a cercare\l"
	.string "POKéMON di tipo COLEOTTERO!$"

Route6_Text_JeffIntro::
	.string "Eh?\n"
	.string "Volevi parlarmi?$"

Route6_Text_JeffDefeat::
	.string "Non ho cominciato io!$"

Route6_Text_JeffPostBattle::
	.string "Per sicurezza dovrei portare più\n"
	.string "POKéMON con me.$"

Route6_Text_IsabelleIntro::
	.string "Dici a me?\n"
	.string "Bene! Giochiamo!$"

Route6_Text_IsabelleDefeat::
	.string "Non ha funzionato!$"

Route6_Text_IsabellePostBattle::
	.string "Devo rafforzarmi!\n"
	.string "Qual è il tuo segreto?$"

Route6_Text_ElijahIntro::
	.string "Non ti ho mai visto in giro!\n"
	.string "Sei in gamba?$"

Route6_Text_ElijahDefeat::
	.string "Sei troppo in gamba!$"

Route6_Text_ElijahPostBattle::
	.string "Il mio POKéMON è debole, o sono\n"
	.string "un disastro io?$"

Route6_Text_UndergroundPathSign::
	.string "VIA SOTTERRANEA\n"
	.string "CELESTOPOLI - ARANCIOPOLI$"

