CeruleanCity_House1_Text_BadgesHaveAmazingSecrets::
	.string "Le MEDAGLIE le hanno solo gli\n"
	.string "ALLENATORI più abili.\p"
	.string "Vedo che ne hai almeno una.\p"
	.string "Queste MEDAGLIE custodiscono\n"
	.string "grandi segreti!$"

CeruleanCity_House1_Text_DescribeWhichBadge::
	.string "Dimmi…\p"
	.string "Quale delle 8 MEDAGLIE vuoi che\n"
	.string "ti descriva?$"

CeruleanCity_House1_Text_ComeVisitAnytime::
	.string "Vieni a trovarmi quando vuoi.$"

CeruleanCity_House1_Text_AttackStatFlash::
	.string "L'ATTACCO di tutti i POKéMON\n"
	.string "aumenta un po'.\p"
	.string "Inoltre, potrai usare FLASH\n"
	.string "anche fuori dalla lotta.$"

CeruleanCity_House1_Text_ObeyLv30Cut::
	.string "I POKéMON fino al livello 30 ti\n"
	.string "obbediranno.\p"
	.string "Oltre quel livello potrebbero\n"
	.string "essere incontrollabili!\p"
	.string "Inoltre, potrai usare TAGLIO\n"
	.string "anche fuori dalla lotta.$"

CeruleanCity_House1_Text_SpeedStatFly::
	.string "La VELOCITÀ di tutti i POKéMON\n"
	.string "aumenta un po'.\p"
	.string "Inoltre, potrai usare VOLO\n"
	.string "anche fuori dalla lotta.$"

CeruleanCity_House1_Text_ObeyLv50Strength::
	.string "I POKéMON fino al livello 50 ti\n"
	.string "obbediranno.\p"
	.string "Oltre quel livello potrebbero\n"
	.string "essere incontrollabili!\p"
	.string "Inoltre, potrai usare FORZA\n"
	.string "anche fuori dalla lotta.$"

CeruleanCity_House1_Text_DefenseStatSurf::
	.string "La DIFESA di tutti i POKéMON\n"
	.string "aumenta un po'.\p"
	.string "Inoltre, potrai usare SURF\n"
	.string "anche fuori dalla lotta.$"

CeruleanCity_House1_Text_ObeyLv70RockSmash::
	.string "I POKéMON fino al livello 70 ti\n"
	.string "obbediranno.\p"
	.string "Oltre tale livello potrebbero\n"
	.string "essere incontrollabili!\p"
	.string "Inoltre, potrai usare SPACCAROCCIA\n"
	.string "anche fuori dalla lotta.$"

CeruleanCity_House1_Text_SpStatsWaterfall::
	.string "Le statistiche ATT. SPEC. e DIF.\n"
	.string "SPEC. dei tuoi POKéMON aumentano\l"
	.string "un po'.\p"
	.string "Inoltre, puoi usare CASCATA anche\n"
	.string "fuori dalla lotta.$"

CeruleanCity_House1_Text_AllMonsWillObeyYou::
	.string "Tutti i POKéMON ti obbediranno!$"

