Route3_Text_TunnelFromCeruleanTiring::
	.string "Uffa… Meglio riposarsi un po'!\n"
	.string "Che stanchezza!!!\p"
	.string "Questo tunnel per CELESTOPOLI è\n"
	.string "impegnativo!$"

Route3_Text_ColtonIntro::
	.string "Ci siamo già visti al\n"
	.string "BOSCO SMERALDO!$"

Route3_Text_ColtonDefeat::
	.string "Battuto ancora!$"

Route3_Text_ColtonPostBattle::
	.string "Ci sono altre specie di POKéMON\n"
	.string "oltre a quelle che si trovano nel\l"
	.string "bosco!$"

Route3_Text_BenIntro::
	.string "Ciao!\n"
	.string "Mi piacciono i pantaloncini corti!\p"
	.string "Sono molto comodi!$"

Route3_Text_BenDefeat::
	.string "Non ci posso credere!$"

Route3_Text_BenPostBattle::
	.string "Stai depositando i tuoi POKéMON nel\n"
	.string "PC?\p"
	.string "Ogni BOX può contenere 30\n"
	.string "POKéMON!$"

Route3_Text_JaniceIntro::
	.string "Mi stavi guardando, vero?$"

Route3_Text_JaniceDefeat::
	.string "Non brilli certo per la statura!$"

Route3_Text_JanicePostBattle::
	.string "Smetti di fissarmi, se non vuoi\n"
	.string "guai!$"

Route3_Text_GregIntro::
	.string "Sei un ALLENATORE?\n"
	.string "Lottiamo, forza!$"

Route3_Text_GregDefeat::
	.string "Con altri POKéMON ti avrei\n"
	.string "battuto!$"

Route3_Text_GregPostBattle::
	.string "Se un POKéMON BOX del PC è pieno,\n"
	.string "passa a un altro!$"

Route3_Text_SallyIntro::
	.string "Quel tuo sguardo è così intrigante!$"

Route3_Text_SallyDefeat::
	.string "Sii gentile!$"

Route3_Text_SallyPostBattle::
	.string "Evita le lotte nascondendoti da\n"
	.string "certa gente!$"

Route3_Text_CalvinIntro::
	.string "Ehi!\n"
	.string "Non indossi pantaloncini!$"

Route3_Text_CalvinDefeat::
	.string "Ho perso!\n"
	.string "Perso! Perso!$"

Route3_Text_CalvinPostBattle::
	.string "Porto sempre i pantaloncini, anche\n"
	.string "d'inverno!$"

Route3_Text_JamesIntro::
	.string "Puoi lottare contro i miei nuovi\n"
	.string "POKéMON!$"

Route3_Text_JamesDefeat::
	.string "Sono distrutto!$"

Route3_Text_JamesPostBattle::
	.string "I POKéMON allenati sono più forti\n"
	.string "di quelli selvatici!$"

Route3_Text_RobinIntro::
	.string "Ehi!\n"
	.string "Mi hai urtato?$"

Route3_Text_RobinDefeat::
	.string "Tutto qui?$"

Route3_Text_RobinPostBattle::
	.string "Il PERCORSO 4 è ai piedi del\n"
	.string "MONTE LUNA.$"

Route3_Text_RouteSign::
	.string "PERCORSO 3 - Per il MONTE LUNA$"

