Text_DoubleEdgeTeach::
	.string "Ottimo! Non è da tutti giungere\n"
	.string "fin qui lungo la VIA VITTORIA!\p"
	.string "Per festeggiare, ti regalo\n"
	.string "SDOPPIATORE!\p"
	.string "Vuoi che lo insegni ad uno dei\n"
	.string "tuoi POKéMON?$"

Text_DoubleEdgeDeclined::
	.string "Come preferisci. Se cambi idea,\n"
	.string "mi trovi sempre qui.$"

Text_DoubleEdgeWhichMon::
	.string "A quale POKéMON vuoi che insegni\n"
	.string "SDOPPIATORE?$"

Text_DoubleEdgeTaught::
	.string "Continua così fino alla\n"
	.string "LEGA POKéMON!\p"
	.string "Stendili, mi raccomando!$"

VictoryRoad_3F_Text_GeorgeIntro::
	.string "Ci sono voci che narrano di un\n"
	.string "giovane ALLENATORE\l"
	.string "prodigioso!$"

VictoryRoad_3F_Text_GeorgeDefeat::
	.string "Le voci erano vere!$"

VictoryRoad_3F_Text_GeorgePostBattle::
	.string "Hai battuto GIOVANNI di TEAM\n"
	.string "ROCKET?$"

VictoryRoad_3F_Text_AlexaIntro::
	.string "Gli ALLENATORI vivono per trovare\n"
	.string "sfidanti sempre più forti!$"

VictoryRoad_3F_Text_AlexaDefeat::
	.string "Oh!\n"
	.string "Sei un portento!$"

VictoryRoad_3F_Text_AlexaPostBattle::
	.string "Affrontando lotte sempre più dure,\n"
	.string "diventerai sempre più forte!$"

VictoryRoad_3F_Text_CarolineIntro::
	.string "Ti mostrerò quanto poco\n"
	.string "vali!$"

VictoryRoad_3F_Text_CarolineDefeat::
	.string "Sono furiosa!!!$"

VictoryRoad_3F_Text_CarolinePostBattle::
	.string "Sei tu che mi hai mostrato quanto\n"
	.string "poco valgo!$"

VictoryRoad_3F_Text_ColbyIntro::
	.string "Solo i prescelti possono passare!$"

VictoryRoad_3F_Text_ColbyDefeat::
	.string "Non ci posso credere!$"

VictoryRoad_3F_Text_ColbyPostBattle::
	.string "Tutti gli ALLENATORI che vedi qui\n"
	.string "sono diretti alla LEGA POKéMON!\p"
	.string "Sono forti! Fai attenzione!$"

VictoryRoad_3F_Text_RayIntro::
	.string "RAY: Insieme, siamo destinati a\n"
	.string "fare grandi cose!$"

VictoryRoad_3F_Text_RayDefeat::
	.string "RAY: Ma questo è ridicolo!$"

VictoryRoad_3F_Text_RayPostBattle::
	.string "RAY: Ci hai battuti! Com'è\n"
	.string "difficile misurare la grandezza…$"

VictoryRoad_3F_Text_RayNotEnoughMons::
	.string "RAY: Insieme, siamo destinati a\n"
	.string "fare grandi cose!\p"
	.string "Per lottare con noi devi avere\n"
	.string "almeno due POKéMON da\l"
	.string "mandare in campo!$"

VictoryRoad_3F_Text_TyraIntro::
	.string "IVA: Io e il mio amico, insieme,\n"
	.string "diventeremo grandi campioni!$"

VictoryRoad_3F_Text_TyraDefeat::
	.string "IVA: Ehi, ma…$"

VictoryRoad_3F_Text_TyraPostBattle::
	.string "IVA: Tu mi hai insegnato che la\n"
	.string "potenza può avere infinite forme!$"

VictoryRoad_3F_Text_TyraNotEnoughMons::
	.string "IVA: Se hai solo un POKéMON\n"
	.string "non puoi lottare con noi!$"

