ViridianForest_Text_FriendsItchingToBattle::
	.string "Sono qui con alcuni amici!\p"
	.string "Stiamo catturando POKéMON di\n"
	.string "tipo COLEOTTERO, per lottare!$"

ViridianForest_Text_RickIntro::
	.string "Ehi! Anche tu hai dei POKéMON!\n"
	.string "Dai!\l"
	.string "Lottiamo!$"

ViridianForest_Text_RickDefeat::
	.string "Noo!\n"
	.string "CATERPIE non può perdere!$"

ViridianForest_Text_RickPostBattle::
	.string "Ssh! Piano, o fai scappare tutti\n"
	.string "gli insetti!$"

ViridianForest_Text_DougIntro::
	.string "Ehi!\n"
	.string "Un ALLENATORE di POKéMON non può\l"
	.string "svignarsela!$"

ViridianForest_Text_DougDefeat::
	.string "Non ho più POKéMON per lottare!$"

ViridianForest_Text_DougPostBattle::
	.string "Maledizione!\n"
	.string "Devo catturarne di più forti!$"

ViridianForest_Text_SammyIntro::
	.string "Ehi, aspetta!\n"
	.string "Cos'è questa fretta?$"

ViridianForest_Text_SammyDefeat::
	.string "Mi arrendo!\n"
	.string "Sei proprio forte!$"

ViridianForest_Text_SammyPostBattle::
	.string "Qualche volta si trovano delle\n"
	.string "cose per terra!\p"
	.string "Sto cercando ciò che ho perso!\n"
	.string "Mi aiuti?$"

ViridianForest_Text_AnthonyIntro::
	.string "Sono piccolino, ma ti consiglio di\n"
	.string "non sottovalutarmi.$"

ViridianForest_Text_AnthonyDefeat::
	.string "Oh no! Mi sono andate tutte storte!$"

ViridianForest_Text_AnthonyPostBattle::
	.string "Ho anche perso un po' di soldi…$"

ViridianForest_Text_CharlieIntro::
	.string "Lo sapevi che i POKéMON si\n"
	.string "evolvono?$"

ViridianForest_Text_CharlieDefeat::
	.string "Oh!\n"
	.string "Ho perso!$"

ViridianForest_Text_CharliePostBattle::
	.string "I POKéMON di tipo COLEOTTERO si\n"
	.string "evolvono facilmente. Comodo, no?$"

ViridianForest_Text_RanOutOfPokeBalls::
	.string "Accidenti! Non ho più POKé BALL\n"
	.string "per prendere POKéMON!\p"
	.string "Dovresti averne sempre alcune di\n"
	.string "scorta!$"

ViridianForest_Text_AvoidGrassyAreasWhenWeak::
	.string "CONSIGLI UTILI\p"
	.string "Se non vuoi lottare, evita\n"
	.string "l'erba alta!$"

ViridianForest_Text_UseAntidoteForPoison::
	.string "Usa l'ANTIDOTO contro il veleno!\n"
	.string "Lo troverai ai POKéMON-MARKET!$"

ViridianForest_Text_ContactOakViaPCToRatePokedex::
	.string "CONSIGLI UTILI\p"
	.string "Contatta il PROF. OAK via PC per\n"
	.string "avere la valutazione del tuo\l"
	.string "POKéDEX!$"

ViridianForest_Text_CantCatchOwnedMons::
	.string "CONSIGLI UTILI\p"
	.string "Non puoi rubare i POKéMON di\n"
	.string "altri ALLENATORI.\p"
	.string "Solo i POKéMON selvatici possono\n"
	.string "essere catturati!$"

ViridianForest_Text_WeakenMonsBeforeCapture::
	.string "CONSIGLI UTILI\p"
	.string "Indebolisci i POKéMON prima di\n"
	.string "tentare di catturarli!\p"
	.string "Se ancora forti, scappano!$"

ViridianForest_Text_LeavingViridianForest::
	.string "ARRIVEDERCI NEL BOSCO SMERALDO\n"
	.string "PROSSIMA CITTÀ PLUMBEOPOLI$"

