FiveIsland_House1_JPText_HusbandWentOffFishing::
	.string "こ+ば+ç ÈÉずè\n"
	.string "ùÂÁ ÏßËÛ ÁÁぞ!\p"
	.string "っÛ だ+ßが\n"
	.string "Úûà ÁっŒ+ だÌど…\l"
	.string "Ï+じÛ ÁÁçÉねÇ$"

FiveIsland_House1_Text_HusbandWentOffFishing::
	.string "Sai cosa mi ha detto mio marito\n"
	.string "stamattina prima di andare a\l"
	.string "pescare?\p"
	.string "Non comprare niente per cena!\p"
	.string "Adesso, stiamo a vedere se\n"
	.string "porta qualche pesce!$"

