MtMoon_B2F_Text_MiguelIntro::
	.string "Ehi! Giù le zampe!\p"
	.string "Questi due fossili li ho trovati io!\n"
	.string "Sono miei!$"

MtMoon_B2F_Text_MiguelDefeat::
	.string "Bene!\n"
	.string "Ce li divideremo!$"

MtMoon_B2F_Text_WellEachTakeAFossil::
	.string "Uno a testa!\n"
	.string "Non bisogna essere avidi!$"

MtMoon_B2F_Text_ThenThisFossilIsMine::
	.string "OK!\n"
	.string "Allora questo è mio!!!$"

MtMoon_B2F_Text_LabOnCinnabarRegeneratesFossils::
	.string "Sull'ISOLA CANNELLA c'è un\n"
	.string "LABORATORIO POKéMON.\p"
	.string "Si studia come rigenerare i\n"
	.string "POKéMON dai fossili!$"

MtMoon_B2F_Text_Grunt1Intro::
	.string "TEAM ROCKET troverà i fossili, li\n"
	.string "rivitalizzerà e li venderà a caro\l"
	.string "prezzo!$"

MtMoon_B2F_Text_Grunt1Defeat::
	.string "Grrr!\n"
	.string "Sono furioso!$"

MtMoon_B2F_Text_Grunt1PostBattle::
	.string "Mi fai infuriare! TEAM ROCKET ti\n"
	.string "metterà nella lista nera!$"

MtMoon_B2F_Text_Grunt2Intro::
	.string "Noi, TEAM ROCKET, siamo i gangster\n"
	.string "dei POKéMON!$"

MtMoon_B2F_Text_Grunt2Defeat::
	.string "No!\n"
	.string "Che duro colpo!$"

MtMoon_B2F_Text_Grunt2PostBattle::
	.string "Maledizione!\n"
	.string "Ai miei compagni non piacerà!!!$"

MtMoon_B2F_Text_Grunt3Intro::
	.string "Stiamo lavorando!\n"
	.string "Roba che scotta! Vattene, pulce!$"

MtMoon_B2F_Text_Grunt3Defeat::
	.string "Allora sei forte!$"

MtMoon_B2F_Text_Grunt3PostBattle::
	.string "Se trovi un fossile, dammelo e\n"
	.string "smamma!$"

MtMoon_B2F_Text_Grunt4Intro::
	.string "I mocciosi devono lasciare in pace\n"
	.string "gli adulti!$"

MtMoon_B2F_Text_Grunt4Defeat::
	.string "Sono completamente KO!$"

MtMoon_B2F_Text_Grunt4PostBattle::
	.string "I POKéMON vivevano qui molto prima\n"
	.string "dell'uomo.$"

MtMoon_B2F_Text_YouWantDomeFossil::
	.string "Vuoi il DOMOFOSSILE?$"

MtMoon_B2F_Text_YouWantHelixFossil::
	.string "Vuoi l'HELIXFOSSILE?$"

MtMoon_B2F_Text_ObtainedHelixFossil::
	.string "Hai ottenuto l'HELIXFOSSILE.$"

MtMoon_B2F_Text_ObtainedDomeFossil::
	.string "Hai ottenuto il DOMOFOSSILE.$"

