TwoIsland_JoyfulGameCorner_Text_WhereHasLostelleGottenTo::
	.string "Che fine ha fatto LISETTA?\n"
	.string "Perché tarda tanto?\p"
	.string "Ogni giorno, a quest'ora, mi\n"
	.string "porta il pranzo.$"

TwoIsland_JoyfulGameCorner_Text_PleaseHelpFindLostelle::
	.string "Ehi, tu!\n"
	.string "Conosci LISETTA?\p"
	.string "L'hai per caso vista in giro?\n"
	.string "Dovrebbe già essere qui da molto\l"
	.string "tempo, chissà dove s'è cacciata.\p"
	.string "LISETTA ha un aspetto così\n"
	.string "indifeso…\p"
	.string "Non vorrei che le fosse successo\n"
	.string "qualcosa!\p"
	.string "Aiutami a trovarla, ti prego!\n"
	.string "Vai a cercarla a TERZISOLA!$"

TwoIsland_JoyfulGameCorner_Text_IsThisOnlyThreeIsland::
	.string "Quest'ARENA GIOCHI è davvero\n"
	.string "deprimente!\p"
	.string "E dove sono finiti gli altri?\n"
	.string "Dovevamo vederci qui a\l"
	.string "TERZISOLA!\p"
	.string "Ehi, sai se per caso c'è un'altra\n"
	.string "TERZISOLA, da queste parti?$"

TwoIsland_JoyfulGameCorner_Text_ThisIsTwoIslandMoveIt::
	.string "Svegliati, stordito!\p"
	.string "Questa è SECONDISOLA,\n"
	.string "non TERZISOLA!\p"
	.string "Accendi questo catorcio di\n"
	.string "moto e sparisci!$"

TwoIsland_JoyfulGameCorner_Text_TheseIslandsAreConfusing::
	.string "Ah…\n"
	.string "Allora ho sbagliato isola!?\p"
	.string "Con tutti questi numeri…\n"
	.string "…non ci capisco niente!\p"
	.string "Non potevate chiamarle in modo\n"
	.string "un po' più fantasioso?$"

TwoIsland_JoyfulGameCorner_Text_PunkScuffedUpMyFloor::
	.string "Hai visto? Con la moto mi ha\n"
	.string "rovinato tutto il tappeto!$"

TwoIsland_JoyfulGameCorner_Text_PleaseGoToThreeIsland::
	.string "Allora, non vai a TERZISOLA?\p"
	.string "Ti prego, vai a cercare LISETTA!\p"
	.string "Se dovesse succederle qualcosa…\p"
	.string "Casa mia è quella col tetto rosso\n"
	.string "a TERZISOLA.\p"
	.string "Io non posso andare, perché se si\n"
	.string "fa viva qui, dev'esserci qualcuno\l"
	.string "ad attenderla.\p"
	.string "Per questo l'ho chiesto a te!$"

TwoIsland_JoyfulGameCorner_Text_NotRunningAnyGamesToday::
	.string "Scusa ma oggi è chiuso.$"

TwoIsland_JoyfulGameCorner_Text_GetGamesGoingSoon::
	.string "Mi spiace ma oggi tutti i giochi\n"
	.string "sono chiusi.$"

TwoIsland_JoyfulGameCorner_Text_YouRescuedLostelle::
	.string "Hai salvato LISETTA!\n"
	.string "Come posso ringraziarti?!\p"
	.string "LISETTA, mia cara, scusami!\n"
	.string "Papà non sapeva che fossi\l"
	.string "in pericolo!$"

TwoIsland_JoyfulGameCorner_Text_LostelleItsOkayDaddy::
	.string "LISETTA: Non ti preoccupare,\n"
	.string "papino! Almeno, ho fatto amicizia\l"
	.string "con {PLAYER}!$"

TwoIsland_JoyfulGameCorner_Text_ThisIsForMe::
	.string "Ah, è per me?\p"
	.string "Come facevi a sapere che sono un\n"
	.string "appassionato di gemme e rocce\l"
	.string "rare?$"

TwoIsland_JoyfulGameCorner_Text_HandedMeteoriteToLostellesDaddy::
	.string "{PLAYER} dà il METEORITE\n"
	.string "al padre di LISETTA.$"

TwoIsland_JoyfulGameCorner_Text_OhThisIsFromBill::
	.string "Ah, me lo manda BILL!\n"
	.string "Ringrazialo tanto da parte mia!\p"
	.string "E per sdebitarmi per la tua\n"
	.string "immensa gentilezza…\p"
	.string "…voglio darti questo!$"

TwoIsland_JoyfulGameCorner_Text_ReceivedMoonStoneFromLostellesDaddy::
	.string "{PLAYER} riceve PIETRALUNARE\n"
	.string "dal padre di LISETTA.$"

TwoIsland_JoyfulGameCorner_Text_NotGoingToFitInBag::
	.string "Non puoi metterla nello ZAINO, è\n"
	.string "pieno…$"

TwoIsland_JoyfulGameCorner_Text_IllGetGameCornerRunning::
	.string "Bene, ora metterò in funzione\n"
	.string "l'ARENA GIOCHI!\p"
	.string "Mi raccomando, vienimi a\n"
	.string "trovare con un amico!$"

TwoIsland_JoyfulGameCorner_Text_PleaseShowMeYouBeingCool::
	.string "Ascolta, ascolta!\p"
	.string "Dammi un'altra dimostrazione\n"
	.string "della tua classe!$"

