Route22_Text_EarlyRivalIntro::
	.string "{RIVAL}: Ehi! {PLAYER}!\p"
	.string "Stai andando alla LEGA POKéMON?\n"
	.string "Figuriamoci!\p"
	.string "Scommetto che non hai neanche una\n"
	.string "MEDAGLIA!\p"
	.string "Se non hai tutte le MEDAGLIE, la\n"
	.string "guardia non ti farà mai passare!\p"
	.string "A proposito, sono più forti i tuoi\n"
	.string "POKéMON, ora?$"

Route22_Text_EarlyRivalDefeat::
	.string "Ah!\n"
	.string "Solo un colpo di fortuna!$"

Route22_Text_EarlyRivalPostBattle::
	.string "Si dice che gli ALLENATORI della\n"
	.string "LEGA POKéMON siano fortissimi!\p"
	.string "Devo escogitare un modo per\n"
	.string "batterli!\p"
	.string "E tu, cosa aspetti a collezionare\n"
	.string "tutte le MEDAGLIE? Altrimenti, la\l"
	.string "LEGA POKéMON te la puoi scordare!$"

Route22_Text_RivalShouldCatchSomeMons::
	.string "{RIVAL}“ß+だ?\n"
	.string "ポケモン 2éÊó\l"
	.string "óっÛñç ßぜÉ だっÛ?\p"
	.string "ÈまÇó\n"
	.string "ÚÉまÇºば ÁÁ じゃ+!$"

Route22_Text_LateRivalIntro::
	.string "{RIVAL}: Cosa? {PLAYER}!\n"
	.string "Che sorpresa vederti qui!\p"
	.string "E così vai alla LEGA POKéMON?!\p"
	.string "E hai anche tutte le MEDAGLIE?!\n"
	.string "Fantastico!\p"
	.string "Allora ti sfido, {PLAYER}, in\n"
	.string "preparazione alla LEGA POKéMON!\p"
	.string "Cominciamo!$"

Route22_Text_LateRivalDefeat::
	.string "Cosa?!\p"
	.string "Mi sono solo distratto!$"

Route22_Text_LateRivalPostBattle::
	.string "Perdere mi ha fatto bene!\n"
	.string "Ora sono pronto per la LEGA\l"
	.string "POKéMON!\p"
	.string "{PLAYER}, devi fare più\n"
	.string "allenamento!\p"
	.string "Ma questo lo sai!\n"
	.string "Me ne vado ora!\l"
	.string "Ci becchiamo in giro!$"

Route22_Text_LateRivalVictory::
	.string "{RIVAL}“éゃèèッ {PLAYER}-!\n"
	.string "Ôºで が+ばっÛñçÉù!\l"
	.string "Èºç ÎÁçÂà Ëúべûゃ\l"
	.string "{PLAYER}è まだまだ だß!\p"
	.string "óっÑ º+Ï=Â こÁù!\n"
	.string "Àèè-ッ!$"

Route22_Text_LeagueGateSign::
	.string "LEGA POKéMON\n"
	.string "Ingresso principale$"

