OneIsland_TreasureBeach_Text_AmaraIntro::
	.string "Per riposarmi mi giro sul dorso e\n"
	.string "mi faccio cullare dalle onde.$"

OneIsland_TreasureBeach_Text_AmaraDefeat::
	.string "Perdere mi lascia\n"
	.string "l'amaro in bocca.$"

OneIsland_TreasureBeach_Text_AmaraPostBattle::
	.string "L'acqua del mare è particolarmente\n"
	.string "tiepida da queste parti.$"

OneIsland_TreasureBeach_Text_GoodThingsWashUpOnBeach::
	.string "A volte le onde del mare lasciano\n"
	.string "oggetti interessanti sulla riva.\p"
	.string "Per questo, di tanto in tanto,\n"
	.string "mi metto a rastrellare la spiaggia.$"

