SilphCo_11F_Text_ThanksForSavingMeDearBoy::
	.string "PRESIDENTE: Ragazzo mio!\n"
	.string "Grazie per aver salvato la SILPH!\p"
	.string "Non dimenticherò mai ciò\n"
	.string "che hai fatto!\p"
	.string "Devo sdebitarmi in qualche modo!\p"
	.string "I soldi non mi mancano, credo\n"
	.string "di poterti fare un bel regalo!\p"
	.string "Ecco, questo fa al caso tuo!$"

SilphCo_11F_Text_ThanksForSavingMeDearGirl::
	.string "PRESIDENTE: Ragazza mia!\n"
	.string "Grazie per aver salvato la SILPH!\p"
	.string "Non dimenticherò mai ciò\n"
	.string "che hai fatto!\p"
	.string "Devo sdebitarmi in qualche modo!\p"
	.string "I soldi non mi mancano, credo\n"
	.string "di poterti fare un bel regalo!\p"
	.string "Ecco, questo fa al caso tuo!$"

SilphCo_11F_Text_ObtainedMasterBallFromPresident::
	.string "{PLAYER} riceve\n"
	.string "la MASTER BALL!$"

SilphCo_11F_Text_ThatsOurSecretPrototype::
	.string "PRESIDENTE: Questa non si compra\n"
	.string "da nessuna parte!\p"
	.string "È la MASTER BALL, una POKé BALL\n"
	.string "infallibile!\p"
	.string "Può catturare qualsiasi POKéMON!\p"
	.string "Ti raccomando di usarla con\n"
	.string "prudenza.$"

SilphCo_11F_Text_YouHaveNoRoomForThis::
	.string "Non hai più spazio per questo.$"

SilphCo_11F_Text_ThanksForRescuingUs::
	.string "SEGRETARIA: Grazie per averci\n"
	.string "salvati!\p"
	.string "Ammiriamo il tuo coraggio.$"

SilphCo_11F_Text_GiovanniIntro::
	.string "Ah, {PLAYER}!\n"
	.string "Ci rincontriamo!\p"
	.string "Il PRESIDENTE e io stiamo\n"
	.string "valutando un affare molto\l"
	.string "importante!\p"
	.string "Non t'immischiare negli affari dei\n"
	.string "grandi…\p"
	.string "…o patirai le pene dell'inferno!$"

SilphCo_11F_Text_GiovanniDefeat::
	.string "Grrr!!!\n"
	.string "Perso di nuovo!$"

SilphCo_11F_Text_GiovanniPostBattle::
	.string "Maledizione! Hai mandato a monte i\n"
	.string "nostri piani per la SILPH!\p"
	.string "Ma TEAM ROCKET non cederà mai!\p"
	.string "{PLAYER}! Un giorno TEAM ROCKET\n"
	.string "avrà tutti i POKéMON! Ricordatelo!\p"
	.string "Devo andare, ma ritornerò!$"

SilphCo_11F_Text_Grunt2Intro::
	.string "Altolà!\n"
	.string "Non osare muoverti!$"

SilphCo_11F_Text_Grunt2Defeat::
	.string "No…\n"
	.string "Ti prego!$"

SilphCo_11F_Text_Grunt2PostBattle::
	.string "Allora!\n"
	.string "Vuoi vedere il CAPO?$"

SilphCo_11F_Text_Grunt1Intro::
	.string "Fermati!\n"
	.string "Hai un appuntamento con il CAPO?$"

SilphCo_11F_Text_Grunt1Defeat::
	.string "Ahi!\n"
	.string "Mi hai annientato!$"

SilphCo_11F_Text_Grunt1PostBattle::
	.string "Tieni gli occhi aperti!\n"
	.string "Il CAPO usa POKéMON potenti!$"

SilphCo_11F_Text_MonitorHasMonsOnIt::
	.string "Sul video ci sono dei POKéMON!$"

SilphCo_11F_Text_FloorSign::
	.string "DIREZIONE della SILPH SpA\n"
	.string "10ºP$"

