PokemonMansion_Text_PressSecretSwitch::
	.string "Un pulsante segreto!\p"
	.string "Devo premerlo?$"

PokemonMansion_Text_WhoWouldnt::
	.string "Chi non lo farebbe?$"

PokemonMansion_Text_NotQuiteYet::
	.string "Non ancora!$"

PokemonMansion_1F_Text_ArnieIntro::
	.string "Non riesco ad uscire! Questo posto\n"
	.string "è come un enorme labirinto!$"

PokemonMansion_1F_Text_ArnieDefeat::
	.string "No!\n"
	.string "Il mio bottino!$"

PokemonMansion_1F_Text_ArniePostBattle::
	.string "I pulsanti aprono e chiudono\n"
	.string "alternativamente gruppi di porte!$"

PokemonMansion_1F_Text_NewMonDiscoveredInGuyanaJungle::
	.string "Diario: 5 luglio\n"
	.string "Guyana, Sudamerica.\p"
	.string "È stato scoperto un nuovo POKéMON\n"
	.string "nel cuore della giungla.$"

PokemonMansion_1F_Text_ChristenedDiscoveredMonMew::
	.string "Diario: 10 luglio\n"
	.string "Abbiamo chiamato MEW il\l"
	.string "POKéMON appena scoperto.$"

