CinnabarIsland_Gym_Text_BlaineIntro::
	.byte 0xBF, 0xDC, 0xDD, 0xAB, 0xFB, 0xCD, 0xE3, 0xE2, 0xE3, 0x00, 0xBC, 0xC6
	.byte 0xBB, 0xC3, 0xC8, 0xBF, 0xB8, 0x00, 0xDD, 0xE0, 0x00, 0xBD, 0xBB, 0xCA
	.byte 0xC9, 0xCA, 0xBB, 0xC6, 0xBF, 0xCD, 0xCE, 0xCC, 0xBB, 0xFE, 0xD8, 0xD9
	.byte 0xE0, 0xE0, 0xB4, 0xC3, 0xCD, 0xC9, 0xC6, 0xBB, 0x00, 0xBD, 0xBB, 0xC8
	.byte 0xC8, 0xBF, 0xC6, 0xC6, 0xBB, 0xAB, 0xFB, 0xC3, 0x00, 0xE1, 0xDD, 0xD9
	.byte 0xDD, 0x00, 0xCA, 0xC9, 0xC5, 0x1B, 0xC7, 0xC9, 0xC8, 0x00, 0xDD, 0xE2
	.byte 0xD7, 0xD9, 0xE2, 0xD9, 0xE6, 0xDD, 0xE6, 0xD5, 0xE2, 0xE2, 0xE3, 0x00
	.byte 0xE3, 0xDB, 0xE2, 0xDD, 0xFE, 0xE7, 0xDA, 0xDD, 0xD8, 0xD5, 0xE2, 0xE8
	.byte 0xD9, 0xAB, 0xFB, 0xCA, 0xE6, 0xE3, 0xD7, 0xE9, 0xE6, 0xD5, 0xE8, 0xDD
	.byte 0x00, 0xE0, 0xB4, 0xBB, 0xC8, 0xCE, 0xC3, 0xCD, 0xBD, 0xC9, 0xCE, 0xCE
	.byte 0xBB, 0xCE, 0xCF, 0xCC, 0xBB, 0xAB, 0xFC, 0x0B, 0x56, 0x01, 0xFF

CinnabarIsland_Gym_Text_BlaineDefeat::
	.string "Mi hai incenerito!\p"
	.string "Hai meritato la MEDAGLIA\n"
	.string "VULCANO!$"

CinnabarIsland_Gym_Text_FireBlastIsUltimateFireMove::
	.string "FUOCOBOMBA è la massima tecnica\n"
	.string "del fuoco!\p"
	.string "Non sprecarla sui POKéMON di\n"
	.string "tipo ACQUA.$"

CinnabarIsland_Gym_Text_ExplainVolcanoBadge::
	.string "Ehi!\p"
	.string "La MEDAGLIA VULCANO migliora le\n"
	.string "statistiche SPECIALI dei tuoi\l"
	.string "POKéMON!\p"
	.string "Prendi anche questo!$"

CinnabarIsland_Gym_Text_ReceivedTM38FromBlaine::
	.string "{PLAYER} riceve\n"
	.string "la MT38!$"

CinnabarIsland_Gym_Text_BlainePostBattle::
	.string "La MT38 contiene FUOCOBOMBA!\p"
	.string "Insegnala ai POKéMON di tipo\n"
	.string "FUOCO!\p"
	.string "CHARMELEON e VULPIX sono i più\n"
	.string "adatti!$"

CinnabarIsland_Gym_Text_MakeSpaceForThis::
	.string "Non hai abbastanza spazio!$"

CinnabarIsland_Gym_Text_ErikIntro::
	.string "Sai quanto caldo può diventare il\n"
	.string "fiato dei POKéMON di tipo FUOCO?$"

CinnabarIsland_Gym_Text_ErikDefeat::
	.string "Caldo!\n"
	.string "Caldissimo!$"

CinnabarIsland_Gym_Text_ErikPostBattle::
	.string "Fuoco, o per la precisione,\n"
	.string "combustione…\p"
	.string "Bla, bla, bla, bla…$"

CinnabarIsland_Gym_Text_QuinnIntro::
	.string "Ero un ladro ma sono diventato un\n"
	.string "bravo ALLENATORE!$"

CinnabarIsland_Gym_Text_QuinnDefeat::
	.string "Mi arrendo!$"

CinnabarIsland_Gym_Text_QuinnPostBattle::
	.string "Non posso fare a meno di rubare i\n"
	.string "POKéMON altrui!$"

CinnabarIsland_Gym_Text_AveryIntro::
	.string "Non puoi vincere!\n"
	.string "Ho studiato molto i POKéMON!$"

CinnabarIsland_Gym_Text_AveryDefeat::
	.string "Bleeh!\n"
	.string "I miei studi…$"

CinnabarIsland_Gym_Text_AveryPostBattle::
	.string "Le mie teorie sono troppo\n"
	.string "complicate per te!$"

CinnabarIsland_Gym_Text_RamonIntro::
	.string "Mi piace usare i POKéMON di tipo\n"
	.string "FUOCO!$"

CinnabarIsland_Gym_Text_RamonDefeat::
	.string "Che patata bollente!$"

CinnabarIsland_Gym_Text_RamonPostBattle::
	.string "Userei volentieri un POKéMON ladro\n"
	.string "se ce ne fossero!$"

CinnabarIsland_Gym_Text_DerekIntro::
	.string "So perché BLAINE è diventato un\n"
	.string "ALLENATORE!$"

CinnabarIsland_Gym_Text_DerekDefeat::
	.string "Ahia!$"

CinnabarIsland_Gym_Text_DerekPostBattle::
	.string "BLAINE si era perso in montagna\n"
	.string "quando apparve uno spaventoso\l"
	.string "POKéMON uccello!\p"
	.string "Grazie alla sua luce, BLAINE poté\n"
	.string "ritrovare la via.$"

CinnabarIsland_Gym_Text_DustyIntro::
	.string "Conosco molte PALESTRE, ma la mia\n"
	.string "preferita è questa!$"

CinnabarIsland_Gym_Text_DustyDefeat::
	.string "È troppo caldo!$"

CinnabarIsland_Gym_Text_DustyPostBattle::
	.string "A noi fan dei POKéMON di tipo\n"
	.string "FUOCO piacciono PONYTA e\l"
	.string "NINETALES!$"

CinnabarIsland_Gym_Text_ZacIntro::
	.string "Il fuoco è debole contro l'acqua!$"

CinnabarIsland_Gym_Text_ZacDefeat::
	.string "Perso miseramente!$"

CinnabarIsland_Gym_Text_ZacPostBattle::
	.string "L'acqua batte il fuoco!\p"
	.string "Il fuoco però scioglie i POKéMON\n"
	.string "di tipo GHIACCIO!$"

CinnabarIsland_Gym_Text_GymGuyAdvice::
	.string "Ehi!\n"
	.string "Aspirante CAMPIONE!\p"
	.string "Quella testa calda di BLAINE è un\n"
	.string "maestro con i POKéMON di tipo\l"
	.string "FUOCO! \p"
	.string "Usa l'acqua per calmare i suoi\n"
	.string "bollenti spiriti!\p"
	.string "Ti consiglio degli ANTISCOTTATURA!$"

CinnabarIsland_Gym_Text_GymGuyPostVictory::
	.string "{PLAYER}!\n"
	.string "Hai spento quel braciere!$"

CinnabarIsland_Gym_Text_GymStatue::
	.string "CAPOPALESTRA dell'ISOLA CANNELLA:\n"
	.string "BLAINE\p"
	.string "ALLENATORI VINCENTI:\n"
	.string "{RIVAL}$"

CinnabarIsland_Gym_Text_GymStatuePlayerWon::
	.string "CAPOPALESTRA dell'ISOLA CANNELLA:\n"
	.string "BLAINE\p"
	.string "ALLENATORI VINCENTI:\n"
	.string "{RIVAL}, {PLAYER}$"

CinnabarIsland_Gym_Text_PokemonQuizRules::
	.string "Quiz POKéMON!\p"
	.string "Rispondi giusto e si aprirà la porta\n"
	.string "della prossima stanza!\p"
	.string "Ma se la risposta è sbagliata,\n"
	.string "dovrai vedertela con l'ALLENATORE!\p"
	.string "Se vuoi tenerti i POKéMON per il\n"
	.string "CAPOPALESTRA…\p"
	.string "…allora rispondi bene!\n"
	.string "Su, forza!$"

CinnabarIsland_Gym_Text_QuizQuestion1::
	.string "CATERPIE diventa METAPOD?$"

CinnabarIsland_Gym_Text_QuizQuestion2::
	.string "Sono 9 le MEDAGLIE ufficiali della\n"
	.string "LEGA POKéMON?$"

CinnabarIsland_Gym_Text_QuizQuestion3::
	.string "POLIWAG si evolve tre volte?$"

CinnabarIsland_Gym_Text_QuizQuestion4::
	.string "Le mosse elettriche sono efficaci\n"
	.string "contro i POKéMON tipo TERRA?$"

CinnabarIsland_Gym_Text_QuizQuestion5::
	.string "È vero che POKéMON dello stesso\n"
	.string "livello non sono comunque identici?$"

CinnabarIsland_Gym_Text_QuizQuestion6::
	.string "La MT28 contiene PIETRA TOMBALE?$"

CinnabarIsland_Gym_Text_CorrectGoOnThrough::
	.string "Risposta esatta!\p"
	.string "Avanti!$"

CinnabarIsland_Gym_Text_SorryBadCall::
	.string "Peccato!\n"
	.string "Hai toppato!$"

