SSAnne_B1F_Room1_Text_PhillipIntro::
	.string "Ti farò gettare a mare dai pirati,\n"
	.string "se perdi!!!$"

SSAnne_B1F_Room1_Text_PhillipDefeat::
	.string "Battuto da una pulce!!!$"

SSAnne_B1F_Room1_Text_PhillipPostBattle::
	.string "A volte POKéMON simili a meduse\n"
	.string "entrano nella nave.$"

SSAnne_B1F_Room1_Text_BarnyIntro::
	.string "Ciao!\n"
	.string "Parliamo un po'!\p"
	.string "Tutti i miei POKéMON vengono dal\n"
	.string "mare, sai?$"

SSAnne_B1F_Room1_Text_BarnyDefeat::
	.string "Acc…\n"
	.string "Non ce l'ho fatta!$"

SSAnne_B1F_Room1_Text_BarnyPostBattle::
	.string "Se ti avessi battuto, ti avrei\n"
	.string "chiesto di farmi da assistente!$"

