Route12_NorthEntrance_2F_Text_TakeTMDontNeedAnymoreMale::
	.string "Le ceneri dei miei POKéMON sono\n"
	.string "conservate nella TORRE POKéMON.\p"
	.string "Puoi avere questa mia MT.\n"
	.string "Non mi serve più ormai!$"

Route12_NorthEntrance_2F_Text_TakeTMDontNeedAnymoreFemale::
	.string "Le ceneri dei miei POKéMON sono\n"
	.string "conservate nella TORRE POKéMON.\p"
	.string "Puoi avere questa mia MT.\n"
	.string "Non mi serve più ormai!$"

Route12_NorthEntrance_2F_Text_ReceivedTM27FromLittleGirl::
	.string "{PLAYER} riceve\n"
	.string "la MT27!$"

Route12_NorthEntrance_2F_Text_ExplainTM27::
	.string "La MT27 è RITORNO!\p"
	.string "Se tratti con amore i tuoi POKéMON,\n"
	.string "loro si impegneranno al massimo\l"
	.string "nella lotta.$"

Route12_NorthEntrance_2F_Text_DontHaveRoomForThis::
	.string "Non hai più spazio per questo!$"

Route12_NorthEntrance_2F_Text_TheresManFishing::
	.string "Guardo con il binocolo…\p"
	.string "C'è un uomo che pesca!$"

Route12_NorthEntrance_2F_Text_ItsPokemonTower::
	.string "Guardo con il binocolo…\p"
	.string "È la TORRE POKéMON!$"

