PokemonTower_2F_Text_RivalIntro::
	.string "{RIVAL}: Ehi che fai qui, {PLAYER}!\n"
	.string "I tuoi POKéMON non sono morti!\p"
	.string "Però li posso sconfiggere!\n"
	.string "In guardia!$"

PokemonTower_2F_Text_RivalDefeat::
	.string "Cosa?\n"
	.string "Brutta puzzola!\p"
	.string "Ti ho sottovalutato!$"

PokemonTower_2F_Text_RivalVictory::
	.string "{RIVAL}“À-À…!\n"
	.string "ì+Ñà ËŒばっÙまっŒぞ!\l"
	.string "ùわÁß-!\l"
	.string "óっÑ Ùゃ+Ñ ÔだÛÛ ôºù$"

PokemonTower_2F_Text_RivalPostBattle::
	.string "Com'è messo il tuo POKéDEX?\n"
	.string "Io ho un CUBONE!\p"
	.string "Ma non ho ancora trovato un\n"
	.string "MAROWAK!\p"
	.string "Credo non ce ne siano più! Beh,\n"
	.string "meglio che vada, ho un sacco di\l"
	.string "cose da fare!\p"
	.string "Ci becchiamo in giro!$"

PokemonTower_2F_Text_SilphScopeCouldUnmaskGhosts::
	.string "Non siamo riusciti a identificare\n"
	.string "gli spettri!\p"
	.string "Ci vorrebbe una SPETTROSONDA!\n"
	.string "Le producono alla SILPH.$"

