FuchsiaCity_House3_Text_WouldYouLikeToForgetMove::
	.string "Uh…\n"
	.string "Oh, ciao, sono l'ELIMINAMOSSE.\p"
	.string "Posso far scordare le mosse ai\n"
	.string "POKéMON.\p"
	.string "Vuoi usufruire del servizio?$"

FuchsiaCity_House3_Text_WhichMonShouldForgetMove::
	.string "A quale POKéMON vuoi far scordare\n"
	.string "una mossa?$"

FuchsiaCity_House3_Text_WhichMoveShouldBeForgotten::
	.string "Quale mossa deve essere scordata?$"

FuchsiaCity_House3_Text_MonOnlyKnowsOneMove::
	.string "{STR_VAR_1} sembra conoscere solo\n"
	.string "una mossa…$"

FuchsiaCity_House3_Text_MonsMoveShouldBeForgotten::
	.string "Uh! {STR_VAR_2} di {STR_VAR_1}?\n"
	.string "Vuoi che scordi questa mossa?$"

FuchsiaCity_House3_Text_MonHasForgottenMoveCompletely::
	.string "Tutto ha funzionato a meraviglia!\p"
	.string "{STR_VAR_1} ha scordato\n"
	.string "{STR_VAR_2} completamente.$"

FuchsiaCity_House3_Text_ComeAgainToForgetOtherMoves::
	.string "Ritorna se ci ripensi.$"

FuchsiaCity_House3_Text_NoEggShouldKnowMoves::
	.string "Che cosa?\n"
	.string "L'UOVO non conosce mosse.$"

