Text_DreamEaterTeach::
	.string "Ahou!\n"
	.string "Devo essermi addormentato al sole.\p"
	.string "Ho sognato che un DROWZEE si\n"
	.string "mangiava i miei sogni.\p"
	.string "E… ho imparato anch'io a\n"
	.string "mangiare i sogni!\p"
	.string "Mi faccio paura da solo!\p"
	.string "Vuoi che insegni questa capacità\n"
	.string "ad uno dei tuoi POKéMON?$"

Text_DreamEaterDeclined::
	.string "…Ronf ronf…$"

Text_DreamEaterWhichMon::
	.string "A quale POKéMON vuoi che insegni\n"
	.string "MANGIASOGNI?$"

Text_DreamEaterTaught::
	.string "…ZZZ…\n"
	.string "…Sono… sazio…$"

PewterCity_Text_ClefairyCameFromMoon::
	.string "Pare che CLEFAIRY venga dalla\n"
	.string "luna!\p"
	.string "È apparso quando la PIETRALUNARE\n"
	.string "è caduta sul MONTE LUNA!$"

PewterCity_Text_BrockOnlySeriousTrainerHere::
	.string "Non ci sono tanti ALLENATORI di\n"
	.string "POKéMON seri qui!\p"
	.string "Sono tutti dei PIGLIAMOSCHE!\p"
	.string "Si salva solo BROCK della PALESTRA\n"
	.string "di PLUMBEOPOLI!$"

PewterCity_Text_DidYouCheckOutMuseum::
	.string "Hai già visitato il MUSEO?$"

PewterCity_Text_WerentThoseFossilsAmazing::
	.string "Interessanti i fossili trovati sul\n"
	.string "MONTE LUNA, no?$"

PewterCity_Text_ReallyYouHaveToGo::
	.string "No?\n"
	.string "Devi andarci assolutamente!$"

PewterCity_Text_ThisIsTheMuseum::
	.string "Questo è il MUSEO!\p"
	.string "Si paga per entrare, ma ne vale la\n"
	.string "pena! Ciao!$"

PewterCity_Text_DoYouKnowWhatImDoing::
	.string "Pssss!\n"
	.string "Sai cosa faccio?$"

PewterCity_Text_ThatsRightItsHardWork::
	.string "Esatto!\n"
	.string "È un lavoro duro!$"

PewterCity_Text_SprayingRepelToKeepWildMonsOut::
	.string "Spruzzo il REPELLENTE per tenere\n"
	.string "lontano i POKéMON dal mio giardino!$"

PewterCity_Text_BrocksLookingForChallengersFollowMe::
	.string "Sei un ALLENATORE, vero?\p"
	.string "BROCK sta cercando nuovi sfidanti.\n"
	.string "Vieni!$"

PewterCity_Text_GoTakeOnBrock::
	.string "Se hai stoffa, allora vai a\n"
	.string "sfidare BROCK!$"

PewterCity_Text_TrainerTipsEarningEXP::
	.string "CONSIGLI UTILI\p"
	.string "Tutti i POKéMON impegnati in una\n"
	.string "lotta, seppure breve, crescono in\l"
	.string "ESPERIENZA!$"

PewterCity_Text_CallPoliceIfInfoOnThieves::
	.string "AVVISO:\p"
	.string "Sono stati rubati i fossili POKéMON\n"
	.string "dal MONTE LUNA!\p"
	.string "Chiunque abbia informazioni chiami\n"
	.string "la POLIZIA di PLUMBEOPOLI!$"

PewterCity_Text_MuseumOfScience::
	.string "MUSEO della SCIENZA di\n"
	.string "PLUMBEOPOLI$"

PewterCity_Text_GymSign::
	.string "CAPOPALESTRA di PLUMBEOPOLI:\n"
	.string "BROCK\p"
	.string "L'ALLENATORE di POKéMON più forte\n"
	.string "di una roccia!$"

PewterCity_Text_CitySign::
	.string "PLUMBEOPOLI\n"
	.string "Città grigia come il piombo$"

PewterCity_Text_DefeatedBrockYouCanHaveTreasure::
	.string "Àッº-!\n"
	.string "Ôç ジムバッジ……\l"
	.string "ÒげÇß タケ(à ÉっŒçÉù!\p"
	.string "É+どÂ ÏŒÉú\n"
	.string "Èºç ŒÉúóç ôñù!$"

PewterCity_Text_BerriesInsideUseCarefully::
	.string "ßÉàè Êçîが èÁっÛñぜ\p"
	.string "ôËà ŒÚ Êçîó\n"
	.string "èÁっÛ ÁñÉú\l"
	.string "だÁじà ÚÉっÛ Ëºù!$"

PewterCity_Text_MonsWillUseHeldBerriesOnTheirOwn::
	.byte 0x9F, 0x59, 0x73, 0x7E, 0x16, 0x00, 0x07, 0x19, 0x20, 0x2D, 0xFE, 0x23
	.byte 0x10, 0x0E, 0x13, 0x00, 0x05, 0x09, 0x46, 0xFA, 0x10, 0x10, 0x06, 0x50
	.byte 0x13, 0x02, 0x29, 0x00, 0x14, 0x07, 0x16, 0xFA, 0x06, 0x50, 0x13, 0x16
	.byte 0x00, 0x12, 0x06, 0x50, 0x13, 0x00, 0x08, 0x2A, 0x29, 0x2E, 0x41, 0xFB
	.byte 0x57, 0x8E, 0x39, 0x0D, 0x28, 0x00, 0x14, 0x06, 0x00, 0x45, 0x08, 0x09
	.byte 0x0C, 0x00, 0x26, 0x28, 0xFE, 0x13, 0x37, 0x29, 0x44, 0x00, 0x49, 0x2E
	.byte 0x28, 0x00, 0x41, 0x2B, 0xAC, 0xFF

PewterCity_Text_OhPlayer::
	.string "Oh, {PLAYER}{KUN}!$"

PewterCity_Text_AskedToDeliverThis::
	.string "Finalmente ti ho trovato!\n"
	.string "Sono l'ASSISTENTE del PROF. OAK.\p"
	.string "Ho qualcosa da consegnarti. Tieni!$"

PewterCity_Text_ReceivedRunningShoesFromAide::
	.string "{PLAYER} riceve\n"
	.string "le SCARPE da CORSA.$"

PewterCity_Text_SwitchedShoesWithRunningShoes::
	.string "{PLAYER} si cambia le scarpe e\n"
	.string "mette le SCARPE da CORSA.$"

PewterCity_Text_ExplainRunningShoes::
	.string "Dove c'è abbastanza spazio, puoi\n"
	.string "correre premendo il pulsante B!$"

PewterCity_Text_MustBeGoingBackToLab::
	.string "Beh, ora devo tornare al\n"
	.string "LABORATORIO.\p"
	.string "Ci vediamo!$"

PewterCity_Text_RunningShoesLetterFromMom::
	.string "C'è un biglietto…\p"
	.string "{PLAYER}, pulcino mio!\p"
	.string "Ti ho mandato un paio di SCARPE\n"
	.string "da CORSA.\p"
	.string "Sono lontana, ma ti penso sempre.\n"
	.string "E non smetto un minuto di fare il\l"
	.string "tifo per te!\p"
	.string "Baci,\n"
	.string "la tua mamma$"

