PokemonTower_3F_Text_HopeIntro::
	.string "Urrg… Aaa…\n"
	.string "Uuuu… graa…$"

PokemonTower_3F_Text_HopeDefeat::
	.string "Ah!\n"
	.string "Sono in salvo!$"

PokemonTower_3F_Text_HopePostBattle::
	.string "Gli spettri si identificano con la\n"
	.string "SPETTROSONDA.$"

PokemonTower_3F_Text_CarlyIntro::
	.string "Kikiki…\n"
	.string "Gaaah!$"

PokemonTower_3F_Text_CarlyDefeat::
	.string "Mmm?\n"
	.string "Che sto facendo?$"

PokemonTower_3F_Text_CarlyPostBattle::
	.string "Scusa!\n"
	.string "Ero posseduta!$"

PokemonTower_3F_Text_PatriciaIntro::
	.string "Vattene, spirito maligno!$"

PokemonTower_3F_Text_PatriciaDefeat::
	.string "Lo spirito se n'è andato!$"

PokemonTower_3F_Text_PatriciaPostBattle::
	.string "Anche le altre persone\n"
	.string "erano possedute!$"

