SilphCo_9F_Text_YouShouldTakeQuickNap::
	.string "Sembri a terra!\n"
	.string "Dovresti fare un pisolino!$"

SilphCo_9F_Text_DontGiveUp::
	.string "Non arrenderti!$"

SilphCo_9F_Text_ThankYouSoMuch::
	.string "Grazie infinite!$"

SilphCo_9F_Text_Grunt1Intro::
	.string "I tuoi POKéMON ti adorano!$"

SilphCo_9F_Text_Grunt1Defeat::
	.string "Bleeeh!$"

SilphCo_9F_Text_Grunt1PostBattle::
	.string "Se solo avessi iniziato la carriera\n"
	.string "di ALLENATORE alla tua età…$"

SilphCo_9F_Text_EdIntro::
	.string "I tuoi POKéMON hanno dei punti\n"
	.string "deboli! Li vedo!$"

SilphCo_9F_Text_EdDefeat::
	.string "Mi hai abbattuto!$"

SilphCo_9F_Text_EdPostBattle::
	.string "Sfruttare i punti deboli funziona!\n"
	.string "Cerca sempre di usare i POKéMON\l"
	.string "avvantaggiati contro i vari tipi!$"

SilphCo_9F_Text_Grunt2Intro::
	.string "Sono uno dei 4 FRATELLI ROCKET!$"

SilphCo_9F_Text_Grunt2Defeat::
	.string "Fratelli!\n"
	.string "Ho perso!$"

SilphCo_9F_Text_Grunt2PostBattle::
	.string "I miei fratelli mi vendicheranno!$"

SilphCo_9F_Text_FloorSign::
	.string "DIREZIONE della SILPH SpA\n"
	.string "8ºP$"

