Route25_Text_JoeyIntro::
	.string "Gli ALLENATORI del luogo vengono\n"
	.string "qui a fare pratica!$"

Route25_Text_JoeyDefeat::
	.string "Fantastico!\n"
	.string "Sei in gamba!$"

Route25_Text_JoeyPostBattle::
	.string "Ogni POKéMON ha dei punti deboli.\n"
	.string "Devi addestrarne vari tipi.$"

Route25_Text_DanIntro::
	.string "Papà mi ha portato a una bella\n"
	.string "festa sulla M/N ANNA ad\l"
	.string "ARANCIOPOLI!$"

Route25_Text_DanDefeat::
	.string "Non ho perso la calma!$"

Route25_Text_DanPostBattle::
	.string "Sulla M/N ANNA ho incontrato\n"
	.string "ALLENATORI di tutto il mondo!$"

Route25_Text_FlintIntro::
	.string "Sono un tipo giusto, io!\n"
	.string "Ho la ragazza!$"

Route25_Text_FlintDefeat::
	.string "Ah, accidenti…$"

Route25_Text_FlintPostBattle::
	.string "Pazienza, la mia ragazza mi\n"
	.string "consolerà!$"

Route25_Text_KelseyIntro::
	.string "Ciao!\n"
	.string "Il mio ragazzo è forte!$"

Route25_Text_KelseyDefeat::
	.string "Non ero proprio in forma!$"

Route25_Text_KelseyPostBattle::
	.string "Ah, vorrei che anche il mio\n"
	.string "ragazzo fosse come te!$"

Route25_Text_ChadIntro::
	.string "Lo sapevo che ci saremmo\n"
	.string "scontrati!$"

Route25_Text_ChadDefeat::
	.string "Sapevo pure che avrei perso!$"

Route25_Text_ChadPostBattle::
	.string "Se il tuo POKéMON è confuso,\n"
	.string "sostituiscilo!$"

Route25_Text_HaleyIntro::
	.string "Il mio amico ha un POKéMON così\n"
	.string "dolce… Che invidia!$"

Route25_Text_HaleyDefeat::
	.string "Non ti invidio mica!$"

Route25_Text_HaleyPostBattle::
	.string "Vieni dal MONTE LUNA?\n"
	.string "Mi dai un CLEFAIRY?$"

Route25_Text_FranklinIntro::
	.string "Torno adesso dal MONTE LUNA ma\n"
	.string "posso farcela!$"

Route25_Text_FranklinDefeat::
	.string "Ottimo lavoro!$"

Route25_Text_FranklinPostBattle::
	.string "Accidentaccio!\n"
	.string "Un forte ZUBAT ha aggredito i miei\l"
	.string "POKéMON!$"

Route25_Text_NobIntro::
	.string "Vado al capo a trovare un\n"
	.string "collezionista di POKéMON!$"

Route25_Text_NobDefeat::
	.string "Hai vinto tu!$"

Route25_Text_NobPostBattle::
	.string "Il collezionista ha molti POKéMON\n"
	.string "rari.$"

Route25_Text_WayneIntro::
	.string "Stai andando da BILL?\n"
	.string "Prima però in guardia!$"

Route25_Text_WayneDefeat::
	.string "Mi arrendo!$"

Route25_Text_WaynePostBattle::
	.string "Il percorso là in basso è una\n"
	.string "scorciatoia per CELESTOPOLI.$"

Route25_Text_SeaCottageSign::
	.string "MIRAMARE\n"
	.string "Qui vive BILL!$"

Route25_Text_MistyHighHopesAboutThisPlace::
	.string "Questo capo è famoso per gli\n"
	.string "appuntamenti fra innamorati.\p"
	.string "MISTY, la nostra CAPOPALESTRA, è\n"
	.string "molto legata a questo luogo.$"

Route25_Text_AreYouHereAlone::
	.string "Stai andando al capo di\n"
	.string "CELESTOPOLI?\p"
	.string "Sai che è un posto per coppiette,\n"
	.string "vero?$"

