ThreeIsland_Port_Text_WereKantoRiderFederation::
	.string "Siamo della FEDERAZIONE\n"
	.string "CENTAURI di KANTO.\p"
	.string "Vrum vrum! Vrum vrum! Mi piace\n"
	.string "imitare il rumore della mia moto!$"

ThreeIsland_Port_Text_ForkOverMoney::
	.string "Ehi, nonnetta! Scucimi qualche\n"
	.string "spicciolo!$"

ThreeIsland_Port_Text_IllCallThePolice::
	.string "Eh?!?!\p"
	.string "E tu chi sei?!\n"
	.string "Ora chiamo la polizia!$"

ThreeIsland_Port_Text_ThankGoodnessBikersGone::
	.string "Quei CENTAURI, se ne sono andati?\p"
	.string "Grazie al cielo!\n"
	.string "Mi avevano terrorizzato!$"

ThreeIsland_Port_Text_EverythingTurnedOutForBest::
	.string "Quei CENTAURI se ne sono andati e\n"
	.string "LISETTA è stata ritrovata.\p"
	.string "Insomma, va tutto per il meglio!$"

