Route11_EastEntrance_1F_Text_BagIsFull::
	.string "{PLAYER}{KUN}ç バッグ\n"
	.string "ÁっぱÁ îŒÁ だね$"

Route11_EastEntrance_1F_Text_ManInLavenderRatesNames::
	.string "Quando catturi molti POKéMON, è\n"
	.string "duro inventare nomi per tutti!\p"
	.string "A LAVANDONIA c'è un uomo che\n"
	.string "giudica i nomi dei POKéMON.\p"
	.string "Ti aiuterà anche a dare nuovi\n"
	.string "nomi ai tuoi POKéMON!$"

Route11_EastEntrance_1F_Text_RockTunnelToReachLavender::
	.string "Per LAVANDONIA, procedi\n"
	.string "lungo il TUNNEL ROCCIOSO.\p"
	.string "Come si arriva al TUNNEL ROCCIOSO?\n"
	.string "Da CELESTOPOLI, naturalmente!$"

