Route9_Text_AliciaIntro::
	.string "Hai dei POKéMON?!\n"
	.string "In guardia!$"

Route9_Text_AliciaDefeat::
	.string "Hai giocato sporco!$"

Route9_Text_AliciaPostBattle::
	.string "Ti serve la luce di un FLASH per\n"
	.string "attraversare quel tunnel buio.$"

Route9_Text_ChrisIntro::
	.string "Chi è quella persona con quella\n"
	.string "bella squadra di POKéMON?$"

Route9_Text_ChrisDefeat::
	.string "Fuori combattimento!$"

Route9_Text_ChrisPostBattle::
	.string "Continua per la tua strada!$"

Route9_Text_DrewIntro::
	.string "Prendo il TUNNEL ROCCIOSO per\n"
	.string "LAVANDONIA!$"

Route9_Text_DrewDefeat::
	.string "Puah!\n"
	.string "Non sono all'altezza!$"

Route9_Text_DrewPostBattle::
	.string "Vai verso il TUNNEL ROCCIOSO?$"

Route9_Text_CaitlinIntro::
	.string "Non fare l'arrogante!$"

Route9_Text_CaitlinDefeat::
	.string "No!\n"
	.string "Sei troppo forte!?$"

Route9_Text_CaitlinPostBattle::
	.string "È palese che hai talento!\n"
	.string "In bocca al lupo!$"

Route9_Text_JeremyIntro::
	.string "Ahaha! Che bello!\n"
	.string "Stavo iniziando ad annoiarmi!$"

Route9_Text_JeremyDefeat::
	.string "Non sarò io a fermarti! Va'!\p"
	.string "Hai fortuna!\n"
	.string "Ho finito i POKéMON!$"

Route9_Text_JeremyPostBattle::
	.string "Hai avuto fegato per sfidarmi\n"
	.string "così!$"

Route9_Text_BriceIntro::
	.string "Ahaha!\n"
	.string "Ma chi ti credi di essere?!$"

Route9_Text_BriceDefeat::
	.string "Cosa è stato?$"

Route9_Text_BricePostBattle::
	.string "Ahaha!\n"
	.string "E così tu saresti forte!$"

Route9_Text_BrentIntro::
	.string "Mi alzo presto ogni giorno per\n"
	.string "allenare i miei POKéMON\l"
	.string "COLEOTTERO!$"

Route9_Text_BrentDefeat::
	.string "Che gran perdita di tempo!$"

Route9_Text_BrentPostBattle::
	.string "Forse dovrei indirizzarmi su\n"
	.string "altri POKéMON…$"

Route9_Text_AlanIntro::
	.string "Ahaha!\n"
	.string "Andiamo, pulce!$"

Route9_Text_AlanDefeat::
	.string "Ah!\n"
	.string "Mi hai battuto onestamente!$"

Route9_Text_AlanPostBattle::
	.string "Ahaha!\n"
	.string "I tipi vivaci come noi ridono\l"
	.string "sempre!$"

Route9_Text_ConnerIntro::
	.string "Forza, miei POKéMON COLEOTTERO!$"

Route9_Text_ConnerDefeat::
	.string "Oh, miei cari POKéMON di tipo\n"
	.string "COLEOTTERO!$"

Route9_Text_ConnerPostBattle::
	.string "Adoro i POKéMON COLEOTTERO!\n"
	.string "Tu no? Vattene!$"

Route9_Text_RouteSign::
	.string "PERCORSO 9\n"
	.string "CELESTOPOLI - TUNNEL ROCCIOSO$"

