ThreeIsland_Mart_Text_TrueThatCeldadonDeptStoreBigger::
	.string "È vero?\p"
	.string "È vero che il CENTRO COMMERCIALE\n"
	.string "di AZZURROPOLI è incredibilmente\l"
	.string "più grande di questo negozio?$"

ThreeIsland_Mart_Text_PeopleHealWithBerriesFromForest::
	.string "A volte compro dei medicamenti in\n"
	.string "questo negozio.\p"
	.string "La maggior parte delle persone,\n"
	.string "però, cura i POKéMON con le\l"
	.string "BACCHE del BOSCO BACCOSO.\p"
	.string "D'altronde, le BACCHE sono gratuite\n"
	.string "e sempre disponibili!$"

ThreeIsland_Mart_Text_BikersWereAboutToTrashMart::
	.string "Quei CENTAURI screanzati stavano\n"
	.string "per distruggere il POKéMON-MARKET!\p"
	.string "Meno male che se ne sono andati!$"

