ThreeIsland_BondBridge_Text_NikkiIntro::
	.string "Mi piace il profumo dell'acqua\n"
	.string "marina.$"

ThreeIsland_BondBridge_Text_NikkiDefeat::
	.string "…Sniff, sniff…\n"
	.string "Ehi, che strano odore!$"

ThreeIsland_BondBridge_Text_NikkiPostBattle::
	.string "Non sarai mica tu che hai addosso\n"
	.string "quel profumo dolciastro?!$"

ThreeIsland_BondBridge_Text_VioletIntro::
	.string "Dove vai così di corsa?$"

ThreeIsland_BondBridge_Text_VioletDefeat::
	.string "La tua squadra è davvero\n"
	.string "notevole.$"

ThreeIsland_BondBridge_Text_VioletPostBattle::
	.string "Per questa strada si raggiunge\n"
	.string "il BOSCO BACCOSO.$"

ThreeIsland_BondBridge_Text_AmiraIntro::
	.string "Mia mamma non vuole che nuoti\n"
	.string "senza salvagente.$"

ThreeIsland_BondBridge_Text_AmiraDefeat::
	.string "Oh, nooo!!!$"

ThreeIsland_BondBridge_Text_AmiraPostBattle::
	.string "Quest'anno voglio finalmente\n"
	.string "imparare a nuotare!$"

ThreeIsland_BondBridge_Text_AlexisIntro::
	.string "Vai così!\n"
	.string "POKéMON, POKéMON!$"

ThreeIsland_BondBridge_Text_AlexisDefeat::
	.string "Vai così! Hai vinto tu?$"

ThreeIsland_BondBridge_Text_AlexisPostBattle::
	.string "Vai così! Hai vinto tu,\n"
	.string "oppure ho perso io?$"

ThreeIsland_BondBridge_Text_TishaIntro::
	.string "Oh, no! Stai alla larga da\n"
	.string "me!$"

ThreeIsland_BondBridge_Text_TishaDefeat::
	.string "Ora che hai vinto, vattene,\n"
	.string "ti prego!$"

ThreeIsland_BondBridge_Text_TishaPostBattle::
	.string "Che tragedia! Ho perso il costume\n"
	.string "e non posso uscire dall'acqua!$"

ThreeIsland_BondBridge_Text_JoyIntro::
	.string "JOY: Vuoi vedere qual è il nostro\n"
	.string "POKéMON preferito?$"

ThreeIsland_BondBridge_Text_JoyDefeat::
	.string "JOY: Oooh…\n"
	.string "IDA!$"

ThreeIsland_BondBridge_Text_JoyPostBattle::
	.string "JOY: Che divertimento! Spero di\n"
	.string "lottare ancora con te!$"

ThreeIsland_BondBridge_Text_JoyNotEnoughMons::
	.string "JOY: Io e IDA siamo una squadra\n"
	.string "fissa.\p"
	.string "Se non hai due POKéMON, non\n"
	.string "puoi lottare con noi.$"

ThreeIsland_BondBridge_Text_MegIntro::
	.string "IDA: Vuoi vedere qual è il nostro\n"
	.string "POKéMON preferito?$"

ThreeIsland_BondBridge_Text_MegDefeat::
	.string "IDA: Oooh…\n"
	.string "JOY!$"

ThreeIsland_BondBridge_Text_MegPostBattle::
	.string "IDA: È stato divertente. Vero,\n"
	.string "JOY?$"

ThreeIsland_BondBridge_Text_MegNotEnoughMons::
	.string "IDA: Io e JOY siamo una squadra\n"
	.string "fissa.\p"
	.string "Se non hai due POKéMON, non\n"
	.string "puoi lottare con noi.$"

ThreeIsland_BondBridge_Text_BerryForestAhead::
	.string "Per BOSCO BACCOSO$"

ThreeIsland_BondBridge_Text_BondBridgeSign::
	.string "PONTE ABBRACCIO\n"
	.string "Si prega di fare silenzio.\p"
	.string "Per BOSCO BACCOSO$"

