FiveIsland_ResortGorgeous_Text_DaisyIntro::
	.string "Sto dipingendo un quadro per\n"
	.string "celebrare la mia prossima vittoria.$"

FiveIsland_ResortGorgeous_Text_DaisyDefeat::
	.string "Ecco, ora sono diventata tutta\n"
	.string "rossa per la vergogna!$"

FiveIsland_ResortGorgeous_Text_DaisyPostBattle::
	.string "Tutti i miei pennelli, e i colori,\n"
	.string "spazzati via!$"

FiveIsland_ResortGorgeous_Text_CelinaIntro::
	.string "Come vedi, sto provando a\n"
	.string "dipingere, e tu non sei di certo un\l"
	.string "buon soggetto. Smamma, su!$"

FiveIsland_ResortGorgeous_Text_CelinaDefeat::
	.string "Invece di lottare, era meglio se ti\n"
	.string "facevo un ritratto…$"

FiveIsland_ResortGorgeous_Text_CelinaPostBattle::
	.string "GIANNA, gira un po' la testa!\n"
	.string "Così, perfetto! Che ritratto!$"

FiveIsland_ResortGorgeous_Text_RaynaIntro::
	.string "Forse è un problema di\n"
	.string "prospettiva…$"

FiveIsland_ResortGorgeous_Text_RaynaDefeat::
	.string "Mi sento spenta, come i colori\n"
	.string "dei miei quadri!$"

FiveIsland_ResortGorgeous_Text_RaynaPostBattle::
	.string "Il cielo e il mare hanno colori\n"
	.string "così cangianti!\p"
	.string "Per questo è difficile catturarne\n"
	.string "lo splendore.$"

FiveIsland_ResortGorgeous_Text_JackiIntro::
	.string "Sono venuta a trovare una mia\n"
	.string "amica che è qui per riposarsi.$"

FiveIsland_ResortGorgeous_Text_JackiDefeat::
	.string "Ehi, sei proprio forte!$"

FiveIsland_ResortGorgeous_Text_JackiPostBattle::
	.string "È bello lottare con questa fresca\n"
	.string "brezza che ci accarezza!$"

FiveIsland_ResortGorgeous_Text_GillianIntro::
	.string "Pensavo di farmi costruire una\n"
	.string "piscina speciale per i POKéMON.$"

FiveIsland_ResortGorgeous_Text_GillianDefeat::
	.string "Ho perso? Devo essermi distratta!$"

FiveIsland_ResortGorgeous_Text_GillianPostBattle::
	.string "Una piscina sarebbe fantastica,\n"
	.string "ma forse è meglio un solarium.$"

FiveIsland_ResortGorgeous_Text_DestinIntro::
	.string "Corro veloce, sai? Sono una\n"
	.string "scheggia.$"

FiveIsland_ResortGorgeous_Text_DestinDefeat::
	.string "Forse ho corso troppo!$"

FiveIsland_ResortGorgeous_Text_DestinPostBattle::
	.string "Quando corro sospinto dal vento,\n"
	.string "mi sembra di volare!$"

FiveIsland_ResortGorgeous_Text_TobyIntro::
	.string "Mi piace l'atmosfera rilassata che\n"
	.string "regna su quest'isola.$"

FiveIsland_ResortGorgeous_Text_TobyDefeat::
	.string "Ecco, ora mi hai fatto tornare\n"
	.string "l'ansia!$"

FiveIsland_ResortGorgeous_Text_TobyPostBattle::
	.string "Rilassati! Tu prendi tutto troppo\n"
	.string "sul serio!$"

FiveIsland_ResortGorgeous_Text_SelphyThanksYouMayGoNow::
	.string "NOIANNA: Grazie, puoi andare ora.$"

FiveIsland_ResortGorgeous_Text_SelphysHouse::
	.string "CASA di NOIANNA$"

