CeruleanCity_Mart_Text_RepelWorksOnWeakMons::
	.string "Usa il REPELLENTE per allontanare\n"
	.string "i POKéMON deboli.\p"
	.string "Metti il POKéMON più forte al primo\n"
	.string "posto in squadra, così il\l"
	.string "REPELLENTE avrà più efficacia!$"

CeruleanCity_Mart_Text_DoYouKnowAboutRareCandy::
	.string "Hai provato la CARAMELLA RARA?\n"
	.string "Fa salire di un livello i POKéMON!\p"
	.string "Non la vendono nei negozi però.$"

