Route11_Text_HugoIntro::
	.string "Scommettiamo sulla tua\n"
	.string "sconfitta?$"

Route11_Text_HugoDefeat::
	.string "Accidenti!\n"
	.string "Mi è andata male!$"

Route11_Text_HugoPostBattle::
	.string "I POKéMON sono vita!\n"
	.string "E vivere è giocare!$"

Route11_Text_JasperIntro::
	.string "Sfide?!\n"
	.string "Non ne ho mai abbastanza!$"

Route11_Text_JasperDefeat::
	.string "Ho avuto la mia occasione!$"

Route11_Text_JasperPostBattle::
	.string "Non puoi essere un codardo nel\n"
	.string "mondo dei POKéMON!$"

Route11_Text_EddieIntro::
	.string "OK, lottiamo!\n"
	.string "Ma non imbrogliare!$"

Route11_Text_EddieDefeat::
	.string "Cosa?\n"
	.string "Non può essere!$"

Route11_Text_EddiePostBattle::
	.string "Ho fatto tutto il possibile!\n"
	.string "Non ho rimpianti!$"

Route11_Text_BraxtonIntro::
	.string "Attenzione!\n"
	.string "Sto posando dei cavi!$"

Route11_Text_BraxtonDefeat::
	.string "La tua è elettricità pura!$"

Route11_Text_BraxtonPostBattle::
	.string "Bisogna risparmiare elettricità!\n"
	.string "Mi raccomando, spargi la voce!$"

Route11_Text_DillonIntro::
	.string "Sono ALLENATORE da poco!\n"
	.string "Ma penso di poter vincere!$"

Route11_Text_DillonDefeat::
	.string "I miei POKéMON hanno perso!$"

Route11_Text_DillonPostBattle::
	.string "Che vuoi?\n"
	.string "Lasciami in pace!$"

Route11_Text_DirkIntro::
	.string "Ihaha!\n"
	.string "Non ho mai perso!$"

Route11_Text_DirkDefeat::
	.string "C'è sempre una prima volta!$"

Route11_Text_DirkPostBattle::
	.string "La fortuna del principiante!$"

Route11_Text_DarianIntro::
	.string "Non ho ancora mai vinto…$"

Route11_Text_DarianDefeat::
	.string "Me l'immaginavo…$"

Route11_Text_DarianPostBattle::
	.string "Chissà quando riuscirò a vincere\n"
	.string "una lotta!$"

Route11_Text_YasuIntro::
	.string "Sono il primo della classe!$"

Route11_Text_YasuDefeat::
	.string "Accidenti!\n"
	.string "Devo rinforzare i miei POKéMON!$"

Route11_Text_YasuPostBattle::
	.string "C'è un POKéMON grasso che è sceso\n"
	.string "dai monti!\p"
	.string "È forte!\n"
	.string "Catturalo!$"

Route11_Text_BernieIntro::
	.string "Attenzione ai cavi scoperti!$"

Route11_Text_BernieDefeat::
	.string "Wow!\n"
	.string "Sei una scheggia!$"

Route11_Text_BerniePostBattle::
	.string "Meglio tornare al lavoro!$"

Route11_Text_DaveIntro::
	.string "I miei POKéMON dovrebbero essere\n"
	.string "pronti ormai!$"

Route11_Text_DaveDefeat::
	.string "No, i miei POKéMON non sono\n"
	.string "ancora all'altezza.$"

Route11_Text_DavePostBattle::
	.string "Meglio cercarne di più forti!$"

Route11_Text_DiglettsCave::
	.string "GROTTA DIGLETT$"

