CeladonCity_House1_Text_SlotsReelInTheDough::
	.string "Wow!\p"
	.string "Ho vinto della grana alle slot!\n"
	.string "Bel colpo!$"

CeladonCity_House1_Text_ShippedMonsAsSlotPrizes::
	.string "CAPO!\p"
	.string "Abbiamo spedito 2.000 POKéMON\n"
	.string "come premi!$"

CeladonCity_House1_Text_DontTouchGameCornerPoster::
	.string "Non toccare il poster al CASINÒ!\p"
	.string "Non c'è nessun pulsante segreto\n"
	.string "dietro!$"

Text_ItsABuddhistAltar::
	.string "ぶÚだ+ だ…$"

