SixIsland_OutcastIsland_Text_RocketIntro::
	.string "Non ci sono POKéMON rari da queste\n"
	.string "parti! Che noia!\p"
	.string "Dai, lottiamo così passo il tempo.$"

SixIsland_OutcastIsland_Text_RocketDefeat::
	.string "Huh?!$"

SixIsland_OutcastIsland_Text_RocketPostBattle::
	.string "Neanche tu hai visto POKéMON rari\n"
	.string "da queste parti, vero?$"

SixIsland_OutcastIsland_Text_TylorIntro::
	.string "Oggi non ho proprio fortuna.\n"
	.string "Lottiamo, magari cambia qualcosa.$"

SixIsland_OutcastIsland_Text_TylorDefeat::
	.string "No, la fortuna oggi non mi assiste.$"

SixIsland_OutcastIsland_Text_TylorPostBattle::
	.string "Non posso andarmene senza aver\n"
	.string "catturato qualcosa!$"

SixIsland_OutcastIsland_Text_MymoIntro::
	.string "Gasp… Gasp…\p"
	.string "Ho nuotato dal PORTO di\n"
	.string "SESTISOLA senza mai fermarmi.$"

SixIsland_OutcastIsland_Text_MymoDefeat::
	.string "Gasp…\n"
	.string "Gasp…$"

SixIsland_OutcastIsland_Text_MymoPostBattle::
	.string "Sono solo a metà strada e\n"
	.string "non ce la faccio già più!$"

SixIsland_OutcastIsland_Text_NicoleIntro::
	.string "Non è facile lottare mentre\n"
	.string "si nuota, sai?$"

SixIsland_OutcastIsland_Text_NicoleDefeat::
	.string "Nel nuoto, non ho perso.\n"
	.string "E questo è ciò che importa.$"

SixIsland_OutcastIsland_Text_NicolePostBattle::
	.string "Stai andando verso l'isola qui\n"
	.string "avanti?\p"
	.string "Non ho visto nulla di interessante\n"
	.string "da quelle parti.$"

SixIsland_OutcastIsland_Text_AvaIntro::
	.string "AVA: Facciamo una lotta acquatica\n"
	.string "2 contro 2!$"

SixIsland_OutcastIsland_Text_AvaDefeat::
	.string "AVA: Sei eccezionale! Anzi, di più:\n"
	.string "sei una categoria a parte!$"

SixIsland_OutcastIsland_Text_AvaPostBattle::
	.string "AVA: Per me, il mare batte\n"
	.string "qualsiasi piscina.$"

SixIsland_OutcastIsland_Text_AvaNotEnoughMons::
	.string "AVA: Vuoi sfidarci?\p"
	.string "Beh, allora devi avere in squadra\n"
	.string "due POKéMON, almeno.$"

SixIsland_OutcastIsland_Text_GebIntro::
	.string "GEB: Sorellona, aiuto!\n"
	.string "Dammi una mano!$"

SixIsland_OutcastIsland_Text_GebDefeat::
	.string "GEB: Wow! Sorellona, abbiamo\n"
	.string "trovato un grande avversario!$"

SixIsland_OutcastIsland_Text_GebPostBattle::
	.string "GEB: Mi tengo a mia sorella perché\n"
	.string "qui il mare è troppo profondo.$"

SixIsland_OutcastIsland_Text_GebNotEnoughMons::
	.string "GEB: Vuoi lottare contro mia\n"
	.string "sorella e me?\p"
	.string "Ah, ma non hai due POKéMON?!$"

