Route14_Text_CarterIntro::
	.string "Usa le MT per insegnare buone\n"
	.string "mosse ai POKéMON!$"

Route14_Text_CarterDefeat::
	.string "Ancora non va!$"

Route14_Text_CarterPostBattle::
	.string "Hai delle MN, eh? I POKéMON non\n"
	.string "dimenticheranno mai quelle mosse.$"

Route14_Text_MitchIntro::
	.string "I miei POKéMON uccello sono pronti\n"
	.string "a lottare.$"

Route14_Text_MitchDefeat::
	.string "No! Non lo erano!$"

Route14_Text_MitchPostBattle::
	.string "Devono imparare mosse migliori.$"

Route14_Text_BeckIntro::
	.string "Si vendono MT ad AZZURROPOLI!\n"
	.string "Le MN invece sono rare!$"

Route14_Text_BeckDefeat::
	.string "Ahi! Che dolore!$"

Route14_Text_BeckPostBattle::
	.string "Insegna ai POKéMON mosse del\n"
	.string "loro stesso tipo perché siano più\l"
	.string "potenti.$"

Route14_Text_MarlonIntro::
	.string "Hai insegnato il VOLO ai tuoi\n"
	.string "POKéMON uccello?$"

Route14_Text_MarlonDefeat::
	.string "Mi hai bruciato!$"

Route14_Text_MarlonPostBattle::
	.string "Adoro i POKéMON uccello!$"

Route14_Text_DonaldIntro::
	.string "Hai mai sentito parlare della\n"
	.string "leggenda dei miraggi alati?$"

Route14_Text_DonaldDefeat::
	.string "Ho perso?\n"
	.string "Perché? Perché?$"

Route14_Text_DonaldPostBattle::
	.string "I miraggi alati non sono altro che\n"
	.string "i POKéMON uccelli leggendari.\p"
	.string "Sono tre: ZAPDOS, ARTICUNO\n"
	.string "e MOLTRES.$"

Route14_Text_BennyIntro::
	.string "Non sono un grande esperto,\n"
	.string "però lottare mi piace!$"

Route14_Text_BennyDefeat::
	.string "Lo sapevo!$"

Route14_Text_BennyPostBattle::
	.string "Vincere o perdere che importanza\n"
	.string "ha, in fondo?!$"

Route14_Text_LukasIntro::
	.string "Forza! Forza!\n"
	.string "Avanti, andiamo, sottoooo!$"

Route14_Text_LukasDefeat::
	.string "Grr!\n"
	.string "Ho perso! Smamma!$"

Route14_Text_LukasPostBattle::
	.string "Che? Che? Che?\n"
	.string "Che vuoi?$"

Route14_Text_IsaacIntro::
	.string "Devo ingannare il tempo, a volte!$"

Route14_Text_IsaacDefeat::
	.string "Cosa?\n"
	.string "Tu?!$"

Route14_Text_IsaacPostBattle::
	.string "Allenare i POKéMON è una\n"
	.string "faticaccia!$"

Route14_Text_GeraldIntro::
	.string "Veniamo qui con la moto perché c'è\n"
	.string "più spazio!$"

Route14_Text_GeraldDefeat::
	.string "Smamma!$"

Route14_Text_GeraldPostBattle::
	.string "Fooorte!\n"
	.string "I tuoi POKéMON sono potentissimi!\p"
	.string "La forza è tutto!\n"
	.string "E tu lo sai!$"

Route14_Text_MalikIntro::
	.string "Lotta POKéMON?\n"
	.string "Come no!$"

Route14_Text_MalikDefeat::
	.string "Spazzato via!$"

Route14_Text_MalikPostBattle::
	.string "Sapevi chi avrebbe vinto!\n"
	.string "Che sfida!$"

Route14_Text_RouteSign::
	.string "PERCORSO 14\n"
	.string "FUCSIAPOLI a ovest$"

Route14_Text_KiriIntro::
	.string "KIRI: Dai, JAN!\n"
	.string "Non possiamo perdere!$"

Route14_Text_KiriDefeat::
	.string "KIRI: Abbiamo perso, vero?$"

Route14_Text_KiriPostBattle::
	.string "KIRI: Abbiamo perso a\n"
	.string "causa mia?$"

Route14_Text_KiriNotEnoughMons::
	.string "KIRI: Quando avrai due POKéMON,\n"
	.string "potrai tornare qui a sfidarci.$"

Route14_Text_JanIntro::
	.string "JAN: Dai, KIRI! Possiamo\n"
	.string "farcela!$"

Route14_Text_JanDefeat::
	.string "JAN: Eh, no! Non ce l'abbiamo\n"
	.string "fatta!$"

Route14_Text_JanPostBattle::
	.string "JAN: Non piangere, KIRI!\n"
	.string "La prossima volta andrà meglio!$"

Route14_Text_JanNotEnoughMons::
	.string "JAN: Vuoi combattere? Ti manca\n"
	.string "un POKéMON. Te ne servono due.$"

