Route10_Text_MarkIntro::
	.string "Sai che sono un POKéFANATICO?\n"
	.string "Vuoi vedere la mia collezione?$"

Route10_Text_MarkDefeat::
	.string "Puh!\n"
	.string "Non sono arrabbiato!$"

Route10_Text_MarkPostBattle::
	.string "A casa ho altri POKéMON rari!$"

Route10_Text_ClarkIntro::
	.string "Ah-ahah-ah-ah!$"

Route10_Text_ClarkDefeat::
	.string "Ah-ahah!\n"
	.string "Non sto ridendo!\l"
	.string "È ah-al-lergia! Ahah-ac-ciù!$"

Route10_Text_ClarkPostBattle::
	.string "Ahah-ac-ciù!\n"
	.string "Ac-ciù!\l"
	.string "Snif, snif! Sigh, sigh!$"

Route10_Text_HermanIntro::
	.string "Ehi!\n"
	.string "Ti mostro i miei POKéMON!$"

Route10_Text_HermanDefeat::
	.string "Oh no!\n"
	.string "I miei poveri POKéMON!$"

Route10_Text_HermanPostBattle::
	.string "Non mi piace essere battuto!$"

Route10_Text_HeidiIntro::
	.string "Vado spesso alla PALESTRA\n"
	.string "POKéMON, ma perdo sempre!$"

Route10_Text_HeidiDefeat::
	.string "Uff!\n"
	.string "Ho perso ancora!$"

Route10_Text_HeidiPostBattle::
	.string "Ho visto dei POKéFANATICI da\n"
	.string "queste parti.$"

Route10_Text_TrentIntro::
	.string "Ah!\n"
	.string "Quest'aria di montagna!$"

Route10_Text_TrentDefeat::
	.string "Ora ho le idee più chiare!$"

Route10_Text_TrentPostBattle::
	.string "L'aria di montagna mi confonde!$"

Route10_Text_CarolIntro::
	.string "Questa gita mi ha stancato!$"

Route10_Text_CarolDefeat::
	.string "Non ero allenata!$"

Route10_Text_CarolPostBattle::
	.string "I POKéMON qui sono così grossi!\n"
	.string "Ce ne dev'essere uno rosa a fiori!$"

Route10_Text_RockTunnelDetourToLavender::
	.string "TUNNEL ROCCIOSO\n"
	.string "Deviazione per LAVANDONIA$"

Route10_Text_RockTunnel::
	.string "TUNNEL ROCCIOSO$"

Route10_Text_PowerPlant::
	.string "CENTRALE ELETT.$"

