RockTunnel_1F_Text_LennyIntro::
	.string "Questo cunicolo è molto\n"
	.string "lungo, sai?!$"

RockTunnel_1F_Text_LennyDefeat::
	.string "No!\n"
	.string "Hai vinto!$"

RockTunnel_1F_Text_LennyPostBattle::
	.string "Attento a ONIX.\n"
	.string "Ogni tanto ne appaiono di molto\l"
	.string "forti e pericolosi!$"

RockTunnel_1F_Text_OliverIntro::
	.string "Mhm.\n"
	.string "Forse mi sono perso…$"

RockTunnel_1F_Text_OliverDefeat::
	.string "Stiamo calmi!\n"
	.string "Che sto facendo?\l"
	.string "Da dove si esce?$"

RockTunnel_1F_Text_OliverPostBattle::
	.string "Quel POKéMON addormentato sul\n"
	.string "PERCORSO 12 mi ha fatto deviare.$"

RockTunnel_1F_Text_LucasIntro::
	.string "I forestieri come te mi devono\n"
	.string "rispetto!$"

RockTunnel_1F_Text_LucasDefeat::
	.string "Mi arrendo!$"

RockTunnel_1F_Text_LucasPostBattle::
	.string "Dovresti venire a fare qualche\n"
	.string "escursione con me!$"

RockTunnel_1F_Text_AshtonIntro::
	.string "Lotta POKéMON!\n"
	.string "Pronti… via!$"

RockTunnel_1F_Text_AshtonDefeat::
	.string "Fine del gioco!$"

RockTunnel_1F_Text_AshtonPostBattle::
	.string "Bene, catturerò uno ZUBAT durante\n"
	.string "il viaggio!$"

RockTunnel_1F_Text_LeahIntro::
	.string "Ehi!\n"
	.string "Non fare scherzi stupidi al buio!$"

RockTunnel_1F_Text_LeahDefeat::
	.string "Era troppo buio!$"

RockTunnel_1F_Text_LeahPostBattle::
	.string "Ho visto un MACHOP in questo\n"
	.string "tunnel!$"

RockTunnel_1F_Text_DanaIntro::
	.string "Sono giunta fin qui per i POKéMON!$"

RockTunnel_1F_Text_DanaDefeat::
	.string "Non ho più POKéMON!$"

RockTunnel_1F_Text_DanaPostBattle::
	.string "Parevi un piccolo essere indifeso!$"

RockTunnel_1F_Text_ArianaIntro::
	.string "Hai dei POKéMON?!\n"
	.string "Cominciamo!$"

RockTunnel_1F_Text_ArianaDefeat::
	.string "Giochi duro!$"

RockTunnel_1F_Text_ArianaPostBattle::
	.string "Uffa!\n"
	.string "Sono tutta sudata!$"

RockTunnel_1F_Text_RouteSign::
	.string "TUNNEL ROCCIOSO\n"
	.string "CELESTOPOLI - LAVANDONIA$"

