Route1_Text_WorkAtPokeMartTakeSample::
	.string "Ciao!\n"
	.string "Lavoro in un POKéMON-MARKET.\p"
	.string "Abbiamo prezzi buoni! Vieni a\n"
	.string "trovarci a SMERALDOPOLI.\p"
	.string "Tieni! Ti do un campioncino!\n"
	.string "Ecco qua!$"

Route1_Text_ComeSeeUsIfYouNeedPokeBalls::
	.string "Abbiamo anche le POKé BALL per\n"
	.string "catturare i POKéMON!$"

Route1_Text_PutPotionAway::
	.string "{PLAYER} ripone la POZIONE nella \n"
	.string "TASCA STRUMENTI dello ZAINO.$"

Route1_Text_CanJumpFromLedges::
	.string "Vedi quei dislivelli lungo la\n"
	.string "strada?\p"
	.string "Fa un po' paura, ma li puoi\n"
	.string "saltare.\p"
	.string "Così puoi tornare a BIANCAVILLA\n"
	.string "più rapidamente!$"

Route1_Text_RouteSign::
	.string "PERCORSO 1\n"
	.string "BIANCAVILLA - SMERALDOPOLI$"

