PokemonTower_5F_Text_RestHereInPurifiedSpace::
	.string "Vieni! Ho protetto questo luogo\n"
	.string "con la magia bianca!\p"
	.string "Riposati un po'!$"

PokemonTower_5F_Text_TammyIntro::
	.string "Daaammi… la tuuua…\n"
	.string "aaanima…$"

PokemonTower_5F_Text_TammyDefeat::
	.string "Gasp!$"

PokemonTower_5F_Text_TammyPostBattle::
	.string "Ero posseduta!$"

PokemonTower_5F_Text_RuthIntro::
	.string "Vieeeni… con…\n"
	.string "noooi…$"

PokemonTower_5F_Text_RuthDefeat::
	.string "Che incubo!$"

PokemonTower_5F_Text_RuthPostBattle::
	.string "Ero posseduta!$"

PokemonTower_5F_Text_KarinaIntro::
	.string "Zombie!$"

PokemonTower_5F_Text_KarinaDefeat::
	.string "Ah?$"

PokemonTower_5F_Text_KarinaPostBattle::
	.string "Ho ripreso i sensi!$"

PokemonTower_5F_Text_JanaeIntro::
	.string "Oooo…\n"
	.string "Uuuu…$"

PokemonTower_5F_Text_JanaeDefeat::
	.string "Uhuuu!$"

PokemonTower_5F_Text_JanaePostBattle::
	.string "Nonostante il mio allenamento gli\n"
	.string "spiriti maligni mi hanno preso!$"

PokemonTower_5F_Text_PurifiedZoneMonsFullyHealed::
	.string "Zona disinfestata e protetta!\p"
	.string "I POKéMON di {PLAYER} sono\n"
	.string "ricaricati!$"

