Route16_NorthEntrance_1F_Text_NoPedestriansOnCyclingRoad::
	.string "I pedoni non possono usare la\n"
	.string "PISTA CICLABILE!$"

Route16_NorthEntrance_1F_Text_CyclingRoadIsDownhillCourse::
	.string "La PISTA CICLABILE si sviluppa in\n"
	.string "discesa lungo il mare. È stupendo!$"

Route16_NorthEntrance_1F_Text_ExcuseMeWaitUp::
	.string "Ehi, senti!\n"
	.string "Aspetta!$"

Route16_NorthEntrance_1F_Text_HowdYouGetInGoodEffort::
	.string "Come hai fatto ad entrare?\n"
	.string "Ben fatto!$"

