CeladonCity_Condominiums_RoofRoom_Text_TheresNothingIDontKnow::
	.string "So tutto sul mondo dei POKéMON nel\n"
	.string "tuo GAME BOY ADVANCE!\p"
	.string "Incontra i tuoi amici e scambia i\n"
	.string "POKéMON!$"

CeladonCity_Condominiums_RoofRoom_Text_ObtainedAnEevee::
	.string "{PLAYER} ha ottenuto EEVEE!$"

CeladonCity_Condominiums_RoofRoom_Text_BoxIsFull::
	.byte 0x9F, 0x59, 0x73, 0x7E, 0x37, 0x00, 0x02, 0x50, 0x4B, 0x02, 0x41, 0xFE
	.byte 0x9A, 0xA0, 0x58, 0x5D, 0x2D, 0x00, 0x06, 0x04, 0x13, 0x00, 0x07, 0x15
	.byte 0x0B, 0x02, 0xFF

CeladonCity_Condominiums_RoofRoom_Text_WirelessAdapterLecture::
	.string "Lezione POKéMON\p"
	.string "Giocare con il GBA Wireless Adapter\n"
	.string "(adattatore wireless per GBA).$"

CeladonCity_Condominiums_RoofRoom_Text_ReadWhichHeading::
	.string "Che capitolo vuoi leggere?$"

CeladonCity_Condominiums_RoofRoom_Text_ExplainWirelessClub::
	.string "Il CLUB WIRELESS POKéMON è al\n"
	.string "piano superiore di ogni CENTRO\l"
	.string "POKéMON.\p"
	.string "Da lì, puoi collegarti con gli\n"
	.string "amici usando l'adattatore wireless\l"
	.string "per GBA.$"

CeladonCity_Condominiums_RoofRoom_Text_ExplainDirectCorner::
	.string "Per collegarti direttamente con un\n"
	.string "amico, vai alla SALA DIRETTA\l"
	.string "del CLUB WIRELESS POKéMON.\p"
	.string "Vi si accede dal primo piano dei\n"
	.string "CENTRI POKéMON, sulla destra.\p"
	.string "La SALA DIRETTA comprende il\n"
	.string "COLOSSEO e il BANCO SCAMBI.$"

CeladonCity_Condominiums_RoofRoom_Text_ExplainUnionRoom::
	.string "Per collegarti con qualsiasi\n"
	.string "ALLENATORE, vai alla\l"
	.string "SALA CONTATTO.\p"
	.string "Si trova nel CLUB WIRELESS\n"
	.string "POKéMON.\p"
	.string "Vi si accede dal primo piano dei\n"
	.string "CENTRI POKéMON, a sinistra\l"
	.string "della SALA DIRETTA.\p"
	.string "Nella SALA DIRETTA potrai\n"
	.string "anche incontrare ALLENATORI\l"
	.string "che ancora non conosci!$"

CeladonCity_Condominiums_RoofRoom_Text_PamphletOnTMs::
	.string "È un opuscolo sulle MT.\p"
	.string "…\p"
	.string "In totale le MT sono 50…\p"
	.string "Inoltre esistono sette MN che\n"
	.string "si possono usare senza alcun\l"
	.string "limite.\p"
	.string "SILPH SpA$"

