CeladonCity_GameCorner_PrizeRoom_Text_FancyThatPorygon::
	.string "Mi piace quel PORYGON!\n"
	.string "Ma è difficile vincere con le slot\l"
	.string "machine!$"

CeladonCity_GameCorner_PrizeRoom_Text_RakedItInToday::
	.string "Ho vinto molto oggi!$"

CeladonCity_GameCorner_PrizeRoom_Text_CoinCaseRequired::
	.string "È necessario un SALVADANAIO!$"

CeladonCity_GameCorner_PrizeRoom_Text_WeExchangeCoinsForPrizes::
	.string "Cambiamo i tuoi GETTONI in premi.$"

CeladonCity_GameCorner_PrizeRoom_Text_WhichPrize::
	.string "Che premio vuoi?$"

CeladonCity_GameCorner_PrizeRoom_Text_HereYouGo::
	.string "èÁ どÂぞ$"

CeladonCity_GameCorner_PrizeRoom_Text_YouWantPrize::
	.string "Allora, vuoi {STR_VAR_1}?$"

CeladonCity_GameCorner_PrizeRoom_Text_YouWantTM::
	.string "OK, allora vuoi una MT\n"
	.string "contenente {STR_VAR_2}?$"

CeladonCity_GameCorner_PrizeRoom_Text_NeedMoreCoins::
	.string "Ci vogliono altri GETTONI!$"

CeladonCity_GameCorner_PrizeRoom_Text_OopsNotEnoughRoom::
	.string "ÈÊゃËÎ+ óÂ óÛßÁù$"

CeladonCity_GameCorner_PrizeRoom_Text_OhFineThen::
	.string "Àっ ÔÂ$"

