SixIsland_PatternBush_Text_BethanyIntro::
	.string "Dimmi un po', tu come\n"
	.string "allevi i POKéMON?$"

SixIsland_PatternBush_Text_BethanyDefeat::
	.string "Tu allevi con amore i tuoi\n"
	.string "POKéMON, si vede!$"

SixIsland_PatternBush_Text_BethanyPostBattle::
	.string "Allevi i POKéMON con lo stesso\n"
	.string "amore con cui tua mamma ha\l"
	.string "cresciuto te, vero?$"

SixIsland_PatternBush_Text_AllisonIntro::
	.string "Lavoro per preservare l'habitat\n"
	.string "naturale dei POKéMON.$"

SixIsland_PatternBush_Text_AllisonDefeat::
	.string "Per essere così giovane,\n"
	.string "la tua forza è impressionante!$"

SixIsland_PatternBush_Text_AllisonPostBattle::
	.string "Non voglio certo impedirti di\n"
	.string "catturare i POKéMON.\p"
	.string "Voglio soltanto che vengano\n"
	.string "trattati in modo responsabile.$"

SixIsland_PatternBush_Text_GarretIntro::
	.string "Ho catturato un POKéMON di tipo\n"
	.string "COLEOTTERO che vive solo qui.$"

SixIsland_PatternBush_Text_GarretDefeat::
	.string "Comunque è forte il mio POKéMON,\n"
	.string "vero?$"

SixIsland_PatternBush_Text_GarretPostBattle::
	.string "Vicino al BOSCO DISEGNATO c'è\n"
	.string "una ragazza che misura gli\l"
	.string "HERACROSS degli ALLENATORI.$"

SixIsland_PatternBush_Text_JonahIntro::
	.string "Per me usare POKéMON di tipo\n"
	.string "COLEOTTERO è fondamentale.$"

SixIsland_PatternBush_Text_JonahDefeat::
	.string "Ho perso, nonostante la buona\n"
	.string "prestazione.$"

SixIsland_PatternBush_Text_JonahPostBattle::
	.string "“Prestazione” è una parola strana,\n"
	.string "se ci pensi.\p"
	.string "Un po' come “elargizione”, o\n"
	.string "“posticipazione”.$"

SixIsland_PatternBush_Text_VanceIntro::
	.string "Ehi! Dai un'occhiata ai miei\n"
	.string "POKéMON di tipo COLEOTTERO!$"

SixIsland_PatternBush_Text_VanceDefeat::
	.string "Ho cantato troppo presto vittoria.$"

SixIsland_PatternBush_Text_VancePostBattle::
	.string "La prossima settimana porto qui\n"
	.string "il mio fratellino.$"

SixIsland_PatternBush_Text_NashIntro::
	.string "Hai visto che strane linee sul\n"
	.string "terreno?$"

SixIsland_PatternBush_Text_NashDefeat::
	.string "Incredibile.$"

SixIsland_PatternBush_Text_NashPostBattle::
	.string "Le linee sul terreno sembrano\n"
	.string "quelle sui pantaloni di mio nonno.$"

SixIsland_PatternBush_Text_CordellIntro::
	.string "Pensi che sia soltanto uno\n"
	.string "qualunque, vero?$"

SixIsland_PatternBush_Text_CordellDefeat::
	.string "Ora pensi che sia soltanto un\n"
	.string "perdente, vero?$"

SixIsland_PatternBush_Text_CordellPostBattle::
	.string "Con quel berretto, si vede proprio\n"
	.string "che vieni dalla città.\p"
	.string "Perché non lo dai a me?$"

SixIsland_PatternBush_Text_DaliaIntro::
	.string "Fai un bel respiro!\n"
	.string "Che aria pulita, eh?$"

SixIsland_PatternBush_Text_DaliaDefeat::
	.string "Se vuoi, posso insegnarti a\n"
	.string "respirare correttamente.$"

SixIsland_PatternBush_Text_DaliaPostBattle::
	.string "Prima inspira profondamente.\n"
	.string "Poi, espira con tutta la tua forza.\p"
	.string "Quando non hai più aria nei\n"
	.string "polmoni, inspira di nuovo.\p"
	.string "Senti l'aria pulita che ti\n"
	.string "riempie i polmoni? Bello, eh?$"

SixIsland_PatternBush_Text_JoanaIntro::
	.string "I POKéMON di tipo COLEOTTERO\n"
	.string "sono i miei preferiti.\p"
	.string "Per questo sono sempre qui.\n"
	.string "Ci saranno altre ragazze come me?!$"

SixIsland_PatternBush_Text_JoanaDefeat::
	.string "Ho perso, ma continuo a ridere!\n"
	.string "Ci saranno altre ragazze come me?!$"

SixIsland_PatternBush_Text_JoanaPostBattle::
	.string "Voglio catturare tutti i POKéMON\n"
	.string "di tipo COLEOTTERO!\p"
	.string "Ci saranno altre ragazze come me?!$"

SixIsland_PatternBush_Text_RileyIntro::
	.string "Questo è un bel posto. Credo\n"
	.string "che monterò qui la mia tenda.$"

SixIsland_PatternBush_Text_RileyDefeat::
	.string "Ho perso, ma ho sempre la mia\n"
	.string "tenda…$"

SixIsland_PatternBush_Text_RileyPostBattle::
	.string "Passerò la notte ad osservare le\n"
	.string "stelle!$"

SixIsland_PatternBush_Text_MarcyIntro::
	.string "Ahi! Mi sa che m'ha punto un\n"
	.string "insetto!$"

SixIsland_PatternBush_Text_MarcyDefeat::
	.string "Non è stato un insetto, ma un\n"
	.string "filo d'erba!$"

SixIsland_PatternBush_Text_MarcyPostBattle::
	.string "Per un taglio così piccolo,\n"
	.string "basta un po' di saliva.$"

SixIsland_PatternBush_Text_LaytonIntro::
	.string "Hai notato qualcosa di strano\n"
	.string "da queste parti?$"

SixIsland_PatternBush_Text_LaytonDefeat::
	.string "Hai guardato bene per terra?$"

SixIsland_PatternBush_Text_LaytonPostBattle::
	.string "Qui nel BOSCO DISEGNATO ci sono\n"
	.string "punti in cui non cresce l'erba.\p"
	.string "Chissà qual è la causa di questo\n"
	.string "fenomeno!$"

