SilphCo_10F_Text_GruntIntro::
	.string "Ti do il benvenuto al 9º piano!\n"
	.string "Felice di vederti!$"

SilphCo_10F_Text_GruntDefeat::
	.string "Resto di stucco!$"

SilphCo_10F_Text_GruntPostBattle::
	.string "Bel colpo, ma la sala consiliare è\n"
	.string "al piano superiore!$"

SilphCo_10F_Text_TravisIntro::
	.string "Ora basta con i giochetti!$"

SilphCo_10F_Text_TravisDefeat::
	.string "Non c'è più speranza!$"

SilphCo_10F_Text_TravisPostBattle::
	.string "Ecco, mi hai battuto!\n"
	.string "Tornatene a casa!$"

SilphCo_10F_Text_WaaaImScared::
	.string "Wow!\n"
	.string "Che paura!$"

SilphCo_10F_Text_KeepMeCryingASecret::
	.string "Per favore, non dire a nessuno che\n"
	.string "ho pianto!$"

SilphCo_10F_Text_FloorSign::
	.string "DIREZIONE della SILPH SpA\n"
	.string "9ºP$"

