SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyMale::
	.string "{PLAYER}: Ciao!\n"
	.string "Ti piacciono i POKéMON?\p"
	.string "{PLAYER}: Eh?\n"
	.string "Te l'ho appena chiesto io.\p"
	.string "{PLAYER}: Eh?\n"
	.string "Sei molto strana!\p"
	.string "COPIONA: Smettere di imitare?\n"
	.string "Ma è il mio hobby preferito!$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyFemale::
	.string "{PLAYER}: Ciao!\n"
	.string "Ti piacciono i POKéMON?\p"
	.string "{PLAYER}: Eh?\n"
	.string "Te l'ho appena chiesto io.\p"
	.string "{PLAYER}: Eh?\n"
	.string "Sei molto strana!\p"
	.string "COPIONA: Smettere di imitare?\n"
	.string "Ma è il mio hobby preferito!$"

Text_MimicTeach::
	.string "Wow!\n"
	.string "Una POKé BAMBOLA!\p"
	.string "Per me?\n"
	.string "Grazie!\p"
	.string "Sai cosa ti dico? Se vuoi posso\n"
	.string "insegnare MIMICA ad uno dei\l"
	.string "tuoi POKéMON.$"

Text_MimicDeclined::
	.string "Non ti piace MIMICA?$"

Text_MimicWhichMon::
	.string "Adoro MIMICA.\n"
	.string "A quale POKéMON vuoi che la\l"
	.string "insegni?$"

Text_MimicTaughtMale::
	.string "{PLAYER}: Grazie ancora per prima!\p"
	.string "{PLAYER}: Come?\p"
	.string "{PLAYER}: È così bello imitare ogni\n"
	.string "mia mossa?\p"
	.string "COPIONA: Bello?\n"
	.string "È favoloso!$"

Text_MimicTaughtFemale::
	.string "{PLAYER}:Grazie per quello che\n"
	.string "hai fatto per noi!\p"
	.string "{PLAYER}: Come?\p"
	.string "{PLAYER}: È così bello imitare ogni\n"
	.string "mia mossa?\p"
	.string "COPIONA: Bello?\n"
	.string "È favoloso!$"

SaffronCity_CopycatsHouse_2F_Text_TooMuchInBag::
	.string "àóÚが ÁっぱÁね!$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyMaleJP::
	.string "{PLAYER}“ôÀ! こ+àÙè!\n"
	.string "Êî ポケモン ÒÊÉÁ?\p"
	.string "{PLAYER}“ぼË じゃßËっÛ\n"
	.string "Êîà ÊÁÛñ+だ Ìど\p"
	.string "{PLAYER}“…… Ç- ß+だù!\n"
	.string "ヘンß ôÚ だßÀ!\p"
	.string "モノíâïÒò“…… ßà?\n"
	.string "éÑç íâ Ò+ßっÛ?\p"
	.string "だっÛ ÀŒÏ \n"
	.string "óçまね Ï=î ß+だ ó+!”$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyFemaleJP::
	.string "{PLAYER}“こ+àÙè!\n"
	.string "ポケモン ÒÊßçね?\p"
	.string "{PLAYER}“わŒÏ じゃßËっÛ\n"
	.string "ÀßŒà ÊÁÛñ+だ Ìど\p"
	.string "{PLAYER}“… Ç- ß+ßç!\n"
	.string "ÈÉÏßこ ね-!\p"
	.string "モノíâïÒò“… ßà?\n"
	.string "éÑç íâ Ò+ßっÛ?\p"
	.string "だっÛ ÀŒÏ\n"
	.string "óçまね Ï=î ß+だ ó+!$"

SaffronCity_CopycatsHouse_2F_Text_Doduo::
	.string "DODUO: Dododù!\p"
	.string "SPECCHIO DELLE MIE BRAME CHI È\n"
	.string "LA PIÙ BELLA DEL REAME?$"

SaffronCity_CopycatsHouse_2F_Text_RareMonOnlyDoll::
	.string "Un POKéMON raro!\n"
	.string "No, è solo una bambola!$"

SaffronCity_CopycatsHouse_2F_Text_MarioWearingABucket::
	.string "Un gioco in cui MARIO ha un secchio\n"
	.string "sulla testa!$"

SaffronCity_CopycatsHouse_2F_Text_MySecrets::
	.string "…\p"
	.string "I miei segreti!\p"
	.string "Capacità: Imitazione.\n"
	.string "Hobby: Collezioni di bambole.\l"
	.string "POKéMON favorito: CLEFAIRY!$"

SaffronCity_CopycatsHouse_2F_Text_HuhCantSee::
	.string "? îÇßÁぞ…$"

