RocketHideout_B3F_Text_Grunt1Intro::
	.string "Non immischiarti negli affari di\n"
	.string "TEAM ROCKET!$"

RocketHideout_B3F_Text_Grunt1Defeat::
	.string "Uff!\n"
	.string "Sono al tappeto!$"

RocketHideout_B3F_Text_Grunt1PostBattle::
	.string "La SPETTROSONDA? Ah,\n"
	.string "la macchina rubata dal CAPO!\p"
	.string "Dev'essere qui da qualche parte…$"

RocketHideout_B3F_Text_Grunt2Intro::
	.string "Abbiamo già avuto notizia del tuo\n"
	.string "arrivo!$"

RocketHideout_B3F_Text_Grunt2Defeat::
	.string "Ho perso?\n"
	.string "Impossibile!!!$"

RocketHideout_B3F_Text_Grunt2PostBattle::
	.string "Vai avanti, dai!\p"
	.string "Ma ti serve la CHIAVE\n"
	.string "dell'ASCENSORE!$"

