SaffronCity_PokemonCenter_1F_Text_GrowthRatesDifferBySpecies::
	.string "Il ritmo di crescita dei POKéMON\n"
	.string "varia da specie a specie.$"

SaffronCity_PokemonCenter_1F_Text_SilphCoVictimOfFame::
	.string "SILPH SpA è molto famosa, perciò\n"
	.string "TEAM ROCKET ha deciso di\l"
	.string "impadronirsene!$"

SaffronCity_PokemonCenter_1F_Text_GreatIfEliteFourCameBeatRockets::
	.string "Non sarebbe fantastico se\n"
	.string "arrivassero i SUPERQUATTRO e\l"
	.string "annientassero TEAM ROCKET?!$"

SaffronCity_PokemonCenter_1F_Text_TeamRocketTookOff::
	.string "TEAM ROCKET se n'è andato!\n"
	.string "Ora si può uscire senza pericolo!\l"
	.string "Ottimo!$"

