Route16_House_Text_FoundMySecretRetreat::
	.string "Hai scovato il mio rifugio segreto!\p"
	.string "Ti prego, non dire a nessuno che\n"
	.string "sono qui e ti ricambierò!$"

Route16_House_Text_ReceivedHM02FromGirl::
	.string "{PLAYER} riceve\n"
	.string "la MN02!$"

Route16_House_Text_ExplainHM02::
	.string "La MN02 è VOLO.\n"
	.string "Ti riporterà in qualsiasi città.\p"
	.string "Fanne buon uso!$"

Route16_House_Text_DontHaveAnyRoomForThis::
	.string "Non hai più spazio per questo.$"

Route16_House_Text_Fearow::
	.string "FEAROW: Row Row!$"

