PokemonTower_1F_Text_ErectedInMemoryOfDeadMons::
	.string "La TORRE POKéMON fu eretta in\n"
	.string "memoria dei POKéMON scomparsi.$"

PokemonTower_1F_Text_ComeToPayRespectsSon::
	.string "Sei qui per rendere omaggio?\n"
	.string "Che bel gesto, figliolo!$"

PokemonTower_1F_Text_ComeToPayRespectsGirl::
	.string "Sei qui per rendere omaggio?\n"
	.string "Che bel gesto, figliola!$"

PokemonTower_1F_Text_CameToPrayForDepartedClefairy::
	.string "Prego per il mio CLEFAIRY.\p"
	.string "Sigh!\n"
	.string "Non faccio che piangere…$"

PokemonTower_1F_Text_GrowlitheWhyDidYouDie::
	.string "Il mio GROWLITHE…\n"
	.string "Perché sei morto?$"

PokemonTower_1F_Text_SenseSpiritsUpToMischief::
	.string "Sono una MEDIUM!\n"
	.string "Ci sono spiriti molto inquieti\l"
	.string "in questo posto!$"

