SixIsland_Mart_Text_AgathaOldestEverEliteFourMember::
	.string "Chi ama i POKéMON campa cent'anni!\p"
	.string "Prendi AGATHA, per esempio!\p"
	.string "È la più anziana SUPERQUATTRO\n"
	.string "della storia!\p"
	.string "Il suo esempio mi sprona a fare\n"
	.string "sempre meglio!$"

SixIsland_Mart_Text_ShouldBuyMailAndWriteLetter::
	.string "Dovrei comprare un MESSAGGIO e\n"
	.string "scrivergli.$"

