CeruleanCity_BikeShop_Text_WelcomeToBikeShop::
	.string "Salve, questo è il NEGOZIO di\n"
	.string "BICI!\p"
	.string "Abbiamo la BICICLETTA che\n"
	.string "fa per te!$"

CeruleanCity_BikeShop_Text_SorryYouCantAffordIt::
	.string "Mi dispiace, è cara per te!$"

CeruleanCity_BikeShop_Text_OhBikeVoucherHereYouGo::
	.string "Oh! È un…\p"
	.string "BUONO BICI!\p"
	.string "Bene, è tua!$"

CeruleanCity_BikeShop_Text_ExchangedVoucherForBicycle::
	.string "{PLAYER} scambia il BUONO per una\n"
	.string "BICICLETTA.$"

CeruleanCity_BikeShop_Text_ThankYouComeAgain::
	.string "Torna a servirti qui!$"

CeruleanCity_BikeShop_Text_HowDoYouLikeNewBicycle::
	.string "Ti piace la tua nuova BICICLETTA?\p"
	.string "La puoi usare su PISTE CICLABILI\n"
	.string "e nelle grotte!$"

CeruleanCity_BikeShop_Text_MakeRoomForBicycle::
	.string "Fai spazio per questo!$"

CeruleanCity_BikeShop_Text_CityBikeGoodEnoughForMe::
	.string "Per me, una normale BICICLETTA\n"
	.string "basta e avanza!\p"
	.string "Le mountain bike non mi piacciono:\n"
	.string "non ci si può mettere il cestino!$"

CeruleanCity_BikeShop_Text_BikesCoolButExpensive::
	.string "Queste BICICLETTE sono belle\n"
	.string "ma care!$"

CeruleanCity_BikeShop_Text_WowYourBikeIsCool::
	.string "Wow!\n"
	.string "La tua BICICLETTA è un mito!$"

CeruleanCity_BikeShop_Text_GermanFoldableBicyleFinallyOnMarket::
	.string "ÚÁà èÚばÁ!\p"
	.string "ド¡ツ ÓÁ ÎÁこÂÊ=Â\n"
	.string "ÈûŒŒî じÛ+Ïゃ!$"

CeruleanCity_BikeShop_Text_ShinyNewBicycle::
	.string "Una BICICLETTA nuova di zecca!$"

