FiveIsland_RocketWarehouse_Text_ManyMonsLockedInPen::
	.string "Ci sono molti POKéMON rinchiusi\n"
	.string "nel recinto.$"

FiveIsland_RocketWarehouse_Text_PenUnlockedMonsFled::
	.string "La porta del recinto è aperta.\n"
	.string "Pare che i POKéMON siano fuggiti.$"

FiveIsland_RocketWarehouse_Text_Grunt2Intro::
	.string "Sapevi che questo è il MAGAZZINO\n"
	.string "di TEAM ROCKET?\p"
	.string "Sei qui per questo?$"

FiveIsland_RocketWarehouse_Text_Grunt2Defeat::
	.string "Cosa credi di fare?$"

FiveIsland_RocketWarehouse_Text_Grunt2PostBattle::
	.string "TEAM ROCKET s'è sciolto?\n"
	.string "Ma non dire fesserie!$"

FiveIsland_RocketWarehouse_Text_Grunt1Intro::
	.string "La tua squadra sembra davvero\n"
	.string "forte! Vuoi vendermi un POKéMON?\p"
	.string "Ah, vuoi lottare?$"

FiveIsland_RocketWarehouse_Text_Grunt1Defeat::
	.string "Ehi, questo è troppo!$"

FiveIsland_RocketWarehouse_Text_Grunt1PostBattle::
	.string "Ci vendi un POKéMON?\n"
	.string "Guarda che paghiamo bene!$"

FiveIsland_RocketWarehouse_Text_Grunt3Intro::
	.string "Ho sentito parlare di te dai\n"
	.string "miei compagni.\p"
	.string "Ma escludo che tu conosca\n"
	.string "GIOVANNI, il nostro CAPO.$"

FiveIsland_RocketWarehouse_Text_Grunt3Defeat::
	.string "Non osare metterti a ridere!$"

FiveIsland_RocketWarehouse_Text_Grunt3PostBattle::
	.string "Queste sono cose da adulti, non\n"
	.string "dovresti immischiarti!$"

FiveIsland_RocketWarehouse_Text_Admin1Intro::
	.string "Non mi chiedo mai se ciò che\n"
	.string "faccio sia giusto o sbagliato.\p"
	.string "Tutto ciò che faccio è credere in\n"
	.string "GIOVANNI e obbedirgli.$"

FiveIsland_RocketWarehouse_Text_Admin1Defeat::
	.string "Mi hai distrutto!$"

FiveIsland_RocketWarehouse_Text_Admin1PostBattle::
	.string "Tu obbedisci soltanto ai tuoi\n"
	.string "principi e alla tua coscienza.\p"
	.string "Ora capisco la differenza…$"

FiveIsland_RocketWarehouse_Text_MadeItSoYouCanComeBackThrough::
	.string "Da questo passaggio puoi rientrare\n"
	.string "e riprendere la lotta.\p"
	.string "Perché non vai a fare un riposino\n"
	.string "prima di continuare?\p"
	.string "Il TENENTE qui avanti è molto più\n"
	.string "forte di me.\p"
	.string "Per affrontarlo, i tuoi POKéMON\n"
	.string "devono essere in piena forma.$"

FiveIsland_RocketWarehouse_Text_Admin2Intro::
	.string "Ehi, moscerino! La smetti di\n"
	.string "impicciarti?\p"
	.string "Ti diverti a raccontare che TEAM\n"
	.string "ROCKET s'è sciolto, vero?\p"
	.string "Pensavi così di scoraggiare\n"
	.string "le nostre truppe?\p"
	.string "Per fortuna, non siamo così\n"
	.string "ingenui da credere ad un lattante!\p"
	.string "Ora vedrai quanto è spaventoso un\n"
	.string "adulto, quando si arrabbia!$"

FiveIsland_RocketWarehouse_Text_Admin2Defeat::
	.string "Sei troppo forte!\p"
	.string "Ehi, ma quella è la\n"
	.string "MEDAGLIA di GIOVANNI!\p"
	.string "Ma allora, TEAM ROCKET\n"
	.string "si è sciolto davvero!$"

FiveIsland_RocketWarehouse_Text_Admin2PostBattle::
	.string "Abbandoneremo questo MAGAZZINO.\p"
	.string "Ma non credere che sia finita qui.\p"
	.string "Troverò GIOVANNI e, insieme a lui,\n"
	.string "rifonderò TEAM ROCKET!\p"
	.string "Ci rivedremo!$"

FiveIsland_RocketWarehouse_Text_ReportWithGraphsAndText::
	.string "Sullo schermo del PC c'è un\n"
	.string "rapporto pieno di grafici.\p"
	.string "…L'influenza delle onde magnetiche\n"
	.string "sull'evoluzione dei POKéMON… \p"
	.string "… … … … … …\p"
	.string "Non ci si capisce niente.$"

FiveIsland_RocketWarehouse_Text_GideonIntro::
	.string "Ero quasi riuscito a vendere lo\n"
	.string "ZAFFIRO per un pacco di soldi…\p"
	.string "Prima che arrivassi tu a rovinare\n"
	.string "tutto!\p"
	.string "Non avrò alcuna pietà!$"

FiveIsland_RocketWarehouse_Text_GideonDefeat::
	.string "No! Nooo!!! NOOO!!!!!!$"

FiveIsland_RocketWarehouse_Text_GideonPostBattle::
	.string "Se non lo posso vendere, cosa me\n"
	.string "ne faccio? Tieni, te lo lascio.$"

FiveIsland_RocketWarehouse_Text_GetLostLeaveMeBe::
	.string "Cosa vuoi ancora?\n"
	.string "Smamma, prima che mi penta.$"

FiveIsland_RocketWarehouse_Text_GiovannisKidHasRedHair::
	.string "Sei di nuovo qui?!\p"
	.string "Sai che assomigli al figlio\n"
	.string "di GIOVANNI?\p"
	.string "Però il figlio di GIOVANNI\n"
	.string "ha i capelli rossi.\p"
	.string "Ora però lasciami in pace!\n"
	.string "Sciò! Sciò!$"

