FiveIsland_Meadow_Text_DoorNeedsTwoPasswords::
	.string "Ñびú& ÀÌñàè\n"
	.string "パ)ワ-ドが 2Ú ÁñùÂだ$"

FiveIsland_Meadow_Text_EnteredPasswordAnotherNeeded::
	.string "{PLAYER} inserisce la parola\n"
	.string "d'ordine.\p"
	.string " “Un'ORTICA ad ARTICUNO”.\p"
	.string "… … …  … … …\p"
	.string "Manca la seconda parola d'ordine\n"
	.string "per aprire la porta…$"

FiveIsland_Meadow_Text_EnteredPasswordDoorOpened::
	.string "{PLAYER} inserisce le due parole\n"
	.string "d'ordine.\p"
	.string "“Un'ORTICA ad ARTICUNO”.\n"
	.string "“Le SCARPATE di PARASECT”.\p"
	.string "La porta del magazzino s'è aperta!$"

FiveIsland_Meadow_Text_WarehouseDoorAlreadyOpen::
	.string "La porta del magazzino è già\n"
	.string "aperta.$"

FiveIsland_Meadow_Text_Rocket1Intro::
	.string "L'accesso a quest'area è\n"
	.string "assolutamente vietato! Via! Via!$"

FiveIsland_Meadow_Text_Rocket1Defeat::
	.string "Dimmi che sto sognando!$"

FiveIsland_Meadow_Text_Rocket1PostBattle::
	.string "Qui non c'è niente!\n"
	.string "Torna a casa!$"

FiveIsland_Meadow_Text_Rocket2Intro::
	.string "Qui avanti c'è solo il nostro\n"
	.string "MAGAZZINO.\p"
	.string "Si può sapere cosa stai\n"
	.string "cercando?$"

FiveIsland_Meadow_Text_Rocket2Defeat::
	.string "Questo non era nei miei piani…$"

FiveIsland_Meadow_Text_Rocket2PostBattle::
	.string "Vuoi sapere cosa c'è dentro al\n"
	.string "MAGAZZINO?\p"
	.string "È meglio che tu non lo sappia.\n"
	.string "Lo dico per te.$"

FiveIsland_Meadow_Text_Rocket3Intro::
	.string "Anche se riuscissi a battermi,\n"
	.string "sarebbe comunque tempo sprecato.$"

FiveIsland_Meadow_Text_Rocket3Defeat::
	.string "Che rabbia!$"

FiveIsland_Meadow_Text_Rocket3PostBattle::
	.string "Senza le parole d'ordine non\n"
	.string "puoi comunque entrare.$"

