CeladonCity_DepartmentStore_3F_Text_OTStandsForOriginalTrainer::
	.string "Tutti i POKéMON catturati sono\n"
	.string "registrati con un NºID.\p"
	.string "Inoltre per ciascuno è indicato\n"
	.string "l'AO, cioè il nome del primo\l"
	.string "ALLENATORE che l'ha avuto.$"

CeladonCity_DepartmentStore_3F_Text_BuddyTradingKangaskhanForHaunter::
	.string "Benissimo!\p"
	.string "Il mio amico mi dà un KANGASKHAN\n"
	.string "in cambio di un HAUNTER!$"

CeladonCity_DepartmentStore_3F_Text_HaunterEvolvedOnTrade::
	.string "Avanti HAUNTER!\p"
	.string "Mi piacciono gli HAUNTER, li\n"
	.string "colleziono!\p"
	.string "Cosa succede?\p"
	.string "HAUNTER si è evoluto in un\n"
	.string "altro POKéMON!$"

CeladonCity_DepartmentStore_3F_Text_CanIdentifyTradeMonsByID::
	.string "Puoi identificare\n"
	.string "i POKéMON che hai\l"
	.string "scambiato grazie\l"
	.string "al nº d'identità!$"

CeladonCity_DepartmentStore_3F_Text_ItsSuperNES::
	.string "È un SUPER NINTENDO!$"

CeladonCity_DepartmentStore_3F_Text_AnRPG::
	.string "Un gioco di ruolo.\n"
	.string "Ma non ho tempo!$"

CeladonCity_DepartmentStore_3F_Text_SportsGame::
	.string "Un gioco sportivo!\n"
	.string "Piacciono molto a papà!$"

CeladonCity_DepartmentStore_3F_Text_PuzzleGame::
	.string "Un puzzle!\n"
	.string "Sembra irresistibile!$"

CeladonCity_DepartmentStore_3F_Text_FightingGame::
	.string "Un gioco di lotta!\n"
	.string "Sembra difficile!$"

CeladonCity_DepartmentStore_3F_Text_TVGameShop::
	.string "2ºP: VIDEOGIOCHI$"

CeladonCity_DepartmentStore_3F_Text_RedGreenBothArePokemon::
	.string "Rosso Fuoco e Verde Foglia!\n"
	.string "Sono due giochi POKéMON!$"

Text_CounterTeach::
	.string "Wow!\n"
	.string "Ho finito il gioco!\p"
	.string "Tu ancora no?\p"
	.string "Vuoi che ti insegni una buona\n"
	.string "mossa? Si chiama CONTATORE.$"

Text_CounterDeclined::
	.string "No? Beh, se cambi idea, sai dove\n"
	.string "trovarmi.$"

Text_CounterWhichMon::
	.string "A che POKéMON vuoi che la insegni?$"

Text_CounterTaught::
	.string "Stai usando CONTATORE che ho\n"
	.string "insegnato al tuo POKéMON?$"

