PewterCity_House1_Text_Nidoran::
	.string "NIDORAN♂: Nidoor!$"

PewterCity_House1_Text_NidoranSit::
	.string "NIDORAN, cuccia!$"

PewterCity_House1_Text_TradeMonsAreFinicky::
	.string "Questo è un POKéMON acquisito ed\n"
	.string "è difficile da trattare.\p"
	.string "Acquisito è un POKéMON scambiato\n"
	.string "con un altro giocatore.\p"
	.string "Cresce in fretta, ma a volte ignora\n"
	.string "gli ALLENATORI inesperti!\p"
	.string "Se solo avessimo delle MEDAGLIE!$"

