Route13_Text_SebastianIntro::
	.string "I miei POKéMON uccello vogliono\n"
	.string "divertirsi!$"

Route13_Text_SebastianDefeat::
	.string "I miei prodi hanno perso?$"

Route13_Text_SebastianPostBattle::
	.string "I miei POKéMON sono felici anche se\n"
	.string "hanno perso.$"

Route13_Text_SusieIntro::
	.string "Dicono che sono brava anche se\n"
	.string "sono una bambina!$"

Route13_Text_SusieDefeat::
	.string "Oh!\n"
	.string "Ho perso!$"

Route13_Text_SusiePostBattle::
	.string "Lavorerò sodo per diventare un\n"
	.string "buon ALLENATORE.$"

Route13_Text_ValerieIntro::
	.string "Che belle MEDAGLIE che hai!$"

Route13_Text_ValerieDefeat::
	.string "Non mi sono impegnata abbastanza!$"

Route13_Text_ValeriePostBattle::
	.string "Te le hanno date i CAPOPALESTRA\n"
	.string "quelle MEDAGLIE, lo so!$"

Route13_Text_GwenIntro::
	.string "I miei cari POKéMON vogliono\n"
	.string "rivederti.$"

Route13_Text_GwenDefeat::
	.string "Mi hai annientato!$"

Route13_Text_GwenPostBattle::
	.string "Bisogna fare lottare i POKéMON per\n"
	.string "rafforzarli!$"

Route13_Text_AlmaIntro::
	.string "Ho trovato del CARBURANTE in una\n"
	.string "grotta!$"

Route13_Text_AlmaDefeat::
	.string "Ho fatto confusione!$"

Route13_Text_AlmaPostBattle::
	.string "Il CARBURANTE ha aumentato la\n"
	.string "VELOCITÀ dei miei POKéMON.$"

Route13_Text_PerryIntro::
	.string "Ho il vento a favore!$"

Route13_Text_PerryDefeat::
	.string "È cambiato il vento!$"

Route13_Text_PerryPostBattle::
	.string "Ho perso.\n"
	.string "Me ne VOLO a casa.$"

Route13_Text_LolaIntro::
	.string "Certo che giocherò con te!$"

Route13_Text_LolaDefeat::
	.string "Essere spregevole!$"

Route13_Text_LolaPostBattle::
	.string "Sono più forti i POKéMON maschio o\n"
	.string "femmina?$"

Route13_Text_SheilaIntro::
	.string "Vuoi giocare a POKéMON con me?$"

Route13_Text_SheilaDefeat::
	.string "È già finito?$"

Route13_Text_SheilaPostBattle::
	.string "Non so nulla dei POKéMON!\p"
	.string "Li scelgo solo in base alla\n"
	.string "bellezza!$"

Route13_Text_JaredIntro::
	.string "Cosa stai guardando?$"

Route13_Text_JaredDefeat::
	.string "Ho sbagliato tutto!$"

Route13_Text_JaredPostBattle::
	.string "Sparisci!$"

Route13_Text_RobertIntro::
	.string "Tengo i POKéMON uccello sempre con\n"
	.string "me!$"

Route13_Text_RobertDefeat::
	.string "Ho le pile scariche!$"

Route13_Text_RobertPostBattle::
	.string "Oh! Se solo potessi volare\n"
	.string "come PIDGEY e PIDGEOTTO…$"

Route13_Text_LookToLeftOfThatPost::
	.string "CONSIGLI UTILI\p"
	.string "Guarda a sinistra del cartello!$"

Route13_Text_SelectToSwitchItems::
	.string "CONSIGLI UTILI\p"
	.string "Usa SELECT per spostare\n"
	.string "gli strumenti nelle liste.$"

Route13_Text_RouteSign::
	.string "PERCORSO 13\n"
	.string "PONTE SILENZIO a nord$"

