CeruleanCity_House4_Text_NothingEntertaining::
	.string "Che noia…\n"
	.string "Ho tanto di quel tempo, e così\l"
	.string "poco da fare…\p"
	.string "È mai possibile che non succeda\n"
	.string "mai nulla di divertente da queste\l"
	.string "parti?$"

CeruleanCity_House4_Text_NewNewsInformativeHaveThis::
	.string "Ah, ecco qualcuno che mi può\n"
	.string "aggiornare sulle ultime notizie!\p"
	.string "Ah, davvero?! Interessante!\p"
	.string "Per ringraziarti, voglio darti\n"
	.string "questo!$"

CeruleanCity_House4_Text_IncredibleNewsHaveBerries::
	.string "Ah, ecco qui qualcuno che può\n"
	.string "raccontarmi cosa succede nel\l"
	.string "mondo!\p"
	.string "Puoi darmi le ultime notizie? \p"
	.string "Davvero? Grazie per le\n"
	.string "informazioni!\p"
	.string "Ecco, prendi queste BACCHE\n"
	.string "come ringraziamento!$"

CeruleanCity_House4_Text_WishCouldShareNewsWithOthers::
	.string "Come vorrei condividere\n"
	.string "queste notizie con tutte\l"
	.string "le persone che conosco!\p"
	.string "Fallo tu per me, va bene?\p"
	.string "Diffondi queste notizie\n"
	.string "il più possibile!$"

CeruleanCity_House4_Text_ThanksForSpreadingNewsTakeThis::
	.string "Hai diffuso le notizie?\p"
	.string "Le informazioni utili sono fatte\n"
	.string "per essere condivise, non credi?\p"
	.string "Per ringraziarti, voglio farti\n"
	.string "un regalo!$"

CeruleanCity_House4_Text_MagnificentNewsSpreadHaveBerries::
	.string "Hai diffuso le notizie?\n"
	.string "Grazie, grazie di cuore!\p"
	.string "Le informazioni utili sono fatte\n"
	.string "per essere condivise, non credi?\p"
	.string "Per ringraziarti, voglio farti\n"
	.string "un regalo!\p"
	.string "Ti donerò più BACCHE del\n"
	.string "solito!$"

CeruleanCity_House4_Text_EnjoyingMyselfWithAllSortsOfNews::
	.string "Con tutte queste notizie, non mi\n"
	.string "annoierò per un bel po'!\p"
	.string "Grazie mille!\n"
	.string "Sono proprio soddisfatto!$"

CeruleanCity_House4_Text_YourBerryPouchIsFull::
	.string "Ah, il tuo PORTABACCHE è pieno.\n"
	.string "Non posso darti il regalo, allora.$"

