ViridianCity_Mart_Text_YouCameFromPallet::
	.string "Ehi!\n"
	.string "Arrivi da BIANCAVILLA, vero?$"

ViridianCity_Mart_Text_TakeThisToProfOak::
	.string "E conosci il PROF. OAK, vero?\p"
	.string "È arrivato quello che aspettava!\n"
	.string "Glielo puoi portare tu?$"

ViridianCity_Mart_Text_ReceivedOaksParcelFromClerk::
	.string "{PLAYER} riceve\n"
	.string "il PACCO di OAK!$"

ViridianCity_Mart_Text_SayHiToOakForMe::
	.string "OK!\n"
	.string "Saluta il PROF. OAK da parte mia!$"

ViridianCity_Mart_Text_ShopDoesGoodBusinessInAntidotes::
	.string "Qui si vendono molti ANTIDOTI.$"

ViridianCity_Mart_Text_GotToBuySomePotions::
	.string "Devo comprare delle POZIONI.\p"
	.string "Non si sa mai, i POKéMON\n"
	.string "potrebbero sempre averne\l"
	.string "bisogno.$"

