VermilionCity_Gym_Text_LtSurgeIntro::
	.byte 0xBF, 0xDC, 0xDD, 0xB8, 0x00, 0xE8, 0xE9, 0xAB, 0xFE, 0xBD, 0xE3, 0xE7
	.byte 0xD5, 0x00, 0xDA, 0xD5, 0xDD, 0x00, 0xE5, 0xE9, 0xDD, 0xAC, 0xFB, 0xC8
	.byte 0xE3, 0xE2, 0x00, 0xD7, 0xD9, 0x00, 0xE0, 0xD5, 0x00, 0xDA, 0xD5, 0xE6
	.byte 0xD5, 0xDD, 0x00, 0xD5, 0x00, 0xEA, 0xDD, 0xE2, 0xD7, 0xD9, 0xE6, 0xD9
	.byte 0xB8, 0x00, 0xE4, 0xE9, 0xE3, 0xDD, 0xFE, 0xD7, 0xE3, 0xE2, 0xE8, 0xD5
	.byte 0xE6, 0xD7, 0xDD, 0xAB, 0xFB, 0xBE, 0xD9, 0xEA, 0xDD, 0x00, 0xE7, 0xD5
	.byte 0xE4, 0xD9, 0xE6, 0xD9, 0x00, 0xD7, 0xDC, 0xD9, 0x00, 0xDD, 0x00, 0xCA
	.byte 0xC9, 0xC5, 0x1B, 0xC7, 0xC9, 0xC8, 0x00, 0xD9, 0xE0, 0xD9, 0xE8, 0xE8
	.byte 0xE6, 0xDD, 0xD7, 0xDD, 0xFE, 0xE1, 0xDD, 0x00, 0xDC, 0xD5, 0xE2, 0xE2
	.byte 0xE3, 0x00, 0xE7, 0xD5, 0xE0, 0xEA, 0xD5, 0xE8, 0xE3, 0x00, 0xDD, 0xE2
	.byte 0x00, 0xDB, 0xE9, 0xD9, 0xE6, 0xE6, 0xD5, 0xAB, 0xFB, 0xC2, 0xD5, 0xE2
	.byte 0xE2, 0xE3, 0x00, 0xE4, 0xD5, 0xE6, 0xD5, 0xE0, 0xDD, 0xEE, 0xEE, 0xD5
	.byte 0xE8, 0xE3, 0x00, 0xDD, 0x00, 0xE1, 0xDD, 0xD9, 0xDD, 0x00, 0xE2, 0xD9
	.byte 0xE1, 0xDD, 0xD7, 0xDD, 0xAB, 0xFB, 0xCA, 0xE6, 0xE3, 0xE4, 0xE6, 0xDD
	.byte 0xE3, 0x00, 0xE5, 0xE9, 0xD9, 0xE0, 0xE0, 0xE3, 0x00, 0xD7, 0xDC, 0xD9
	.byte 0x00, 0xE7, 0xE9, 0xD7, 0xD7, 0xD9, 0xD8, 0xD9, 0xE6, 0x16, 0x00, 0xD5
	.byte 0x00, 0xE8, 0xD9, 0xAB, 0xFC, 0x0B, 0x56, 0x01, 0xFF

VermilionCity_Gym_Text_LtSurgePostBattle::
	.string "Voglio darti un consiglio!\p"
	.string "L'elettricità è potentissima!\p"
	.string "Ma non ha effetto sui POKéMON di\n"
	.string "tipo TERRA!$"

VermilionCity_Gym_Text_ExplainThunderBadgeTakeThis::
	.string "La MEDAGLIA TUONO aumenta la\n"
	.string "VELOCITÀ dei tuoi POKéMON!\p"
	.string "E i tuoi POKéMON potranno volare\n"
	.string "in ogni momento!\p"
	.string "Sei speciale!\n"
	.string "Prendi questo!$"

VermilionCity_Gym_Text_ReceivedTM34FromLtSurge::
	.string "{PLAYER} riceve\n"
	.string "la MT34!$"

VermilionCity_Gym_Text_ExplainTM34::
	.string "La MT34 contiene ONDASHOCK!\p"
	.string "Insegnala a un POKéMON elettrico!$"

VermilionCity_Gym_Text_MakeRoomInYourBag::
	.string "Fai spazio per questo!$"

VermilionCity_Gym_Text_LtSurgeDefeat::
	.string "Wow!\p"
	.string "Tu sì che sei forte, caspita!\p"
	.string "Bene, prendi la MEDAGLIA TUONO!$"

VermilionCity_Gym_Text_TuckerIntro::
	.string "Quando ero nell'esercito, LT. SURGE\n"
	.string "era molto severo!$"

VermilionCity_Gym_Text_TuckerDefeat::
	.string "Stop!\n"
	.string "Abbi pietà!$"

VermilionCity_Gym_Text_TuckerPostBattle::
	.string "Non riesci a oltrepassare la\n"
	.string "barriera?\p"
	.string "LT. SURGE è sempre stato prudente!$"

VermilionCity_Gym_Text_BailyIntro::
	.string "Sono un peso piuma, ma sono forte\n"
	.string "con l'elettricità!$"

VermilionCity_Gym_Text_BailyDefeat::
	.string "Sono fritto!$"

VermilionCity_Gym_Text_BailyPostBattle::
	.string "Va bene, parlerò!\p"
	.string "LT. SURGE ha nascosto gli\n"
	.string "apriporta dentro qualcosa!$"

VermilionCity_Gym_Text_DwayneIntro::
	.string "Non è posto per bambini questo!$"

VermilionCity_Gym_Text_DwayneDefeat::
	.string "Wow!\n"
	.string "Sei un portento!$"

VermilionCity_Gym_Text_DwaynePostBattle::
	.string "LT. SURGE ha messo doppi\n"
	.string "lucchetti nella PALESTRA.\l"
	.string "Un consiglio…!\p"
	.string "Una volta aperto il 1º, il secondo\n"
	.string "è subito accanto!$"

VermilionCity_Gym_Text_GymGuyAdvice::
	.string "Ehi!\n"
	.string "Aspirante CAMPIONE!\p"
	.string "LT. SURGE ha un soprannome.\p"
	.string "La gente lo chiama l'americano\n"
	.string "illuminato!\p"
	.string "È un esperto di POKéMON elettrici!\p"
	.string "I POKéMON di tipo VOLANTE e\n"
	.string "ACQUA sono a rischio.\p"
	.string "Fai attenzione alle paralisi!\p"
	.string "LT. SURGE è molto prudente!\p"
	.string "Dovrai decifrare un codice per\n"
	.string "arrivare a lui!$"

VermilionCity_Gym_Text_GymGuyPostVictory::
	.string "Wow!\n"
	.string "Una lotta elettrizzante!$"

VermilionCity_Gym_Text_GymStatue::
	.string "CAPOPALESTRA di ARANCIOPOLI:\n"
	.string "LT. SURGE\p"
	.string "ALLENATORI VINCENTI:\n"
	.string "{RIVAL}$"

VermilionCity_Gym_Text_GymStatuePlayerWon::
	.string "CAPOPALESTRA di ARANCIOPOLI:\n"
	.string "LT. SURGE\p"
	.string "ALLENATORI VINCENTI:\n"
	.string "{RIVAL}, {PLAYER}$"

VermilionCity_Gym_Text_NopeOnlyTrashHere::
	.string "Acqua!\n"
	.string "C'è solo spazzatura qui!$"

VermilionCity_Gym_Text_SwitchUnderTrashFirstLockOpened::
	.string "Fuoco! C'è un pulsante sotto il\n"
	.string "bidone! Premilo!\p"
	.string "Primo lucchetto elettrico aperto!$"

VermilionCity_Gym_Text_AnotherSwitchInTrash::
	.string "ガ%ゴソ…!\n"
	.string "ÈっÑ! ゴミばこç Ôこà\l"
	.string "まŒ )¡ッチが ÀっŒ!\l"
	.string "ÈÏÛ îùÂ! … ポチッÑß$"

VermilionCity_Gym_Text_SecondLockOpened::
	.string "Secondo lucchetto elettrico\n"
	.string "aperto. Si apre la porta\l"
	.string "automatica!$"

VermilionCity_Gym_Text_OnlyTrashLocksWereReset::
	.string "Acqua!\n"
	.string "Qui c'è solo spazzatura.\p"
	.string "Ehi!\n"
	.string "I lucchetti sono stati richiusi!$"

