FuchsiaCity_SafariZone_Entrance_Text_WelcomeToSafariZone::
	.string "Benvenuti alla ZONA SAFARI!$"

FuchsiaCity_SafariZone_Entrance_Text_PlaySafariGameFor500::
	.string "Per soli ¥500, potrai catturare\n"
	.string "tutti i POKéMON del parco!\p"
	.string "Vuoi unirti alla caccia?$"

FuchsiaCity_SafariZone_Entrance_Text_ThatllBe500WeOnlyUseSpecialBalls::
	.string "Fanno ¥500, prego!\p"
	.string "Qui si usa solo un tipo speciale di\n"
	.string "POKé BALL.$"

FuchsiaCity_SafariZone_Entrance_Text_PlayerReceived30SafariBalls::
	.string "{PLAYER} riceve 30 SAFARI BALL!$"

FuchsiaCity_SafariZone_Entrance_Text_CallYouOnPAWhenYouRunOut::
	.string "Ti avvertiremo quando stai per\n"
	.string "finire il tempo o le SAFARI BALL!$"

FuchsiaCity_SafariZone_Entrance_Text_OkayPleaseComeAgain::
	.string "OK!\n"
	.string "Torna pure quando vuoi!$"

FuchsiaCity_SafariZone_Entrance_Text_OopsNotEnoughMoney::
	.string "Ohi!\n"
	.string "Non hai abbastanza soldi!$"

FuchsiaCity_SafariZone_Entrance_Text_GoingToLeaveSafariZoneEarly::
	.string "Vuoi rinunciare alla caccia ed\n"
	.string "uscire dalla ZONA SAFARI ora?$"

FuchsiaCity_SafariZone_Entrance_Text_PleaseReturnSafariBalls::
	.string "Restituisci le SAFARI BALL che\n"
	.string "ti rimangono.$"

FuchsiaCity_SafariZone_Entrance_Text_GoodLuck::
	.string "Buona fortuna!$"

FuchsiaCity_SafariZone_Entrance_Text_CatchFairShareComeAgain::
	.string "È stato un buon bottino?\n"
	.string "Torna!$"

FuchsiaCity_SafariZone_Entrance_Text_FirstTimeAtSafariZone::
	.string "Ciao!\n"
	.string "È la prima volta che vieni?$"

FuchsiaCity_SafariZone_Entrance_Text_ExplainSafariZone::
	.string "La ZONA SAFARI è divisa in quattro\n"
	.string "zone.\p"
	.string "In ogni zona ci sono diverse specie\n"
	.string "di POKéMON. Usa le SAFARI BALL\l"
	.string "per prenderne il più possibile!\p"
	.string "La prova termina quando scade il\n"
	.string "tempo o hai esaurito le BALL.\p"
	.string "Se usi l'ESCA i POKéMON fuggono\n"
	.string "meno facilmente, ma sono più \l"
	.string "difficili da catturare.\p"
	.string "Se lanci i SASSI, i POKéMON sono\n"
	.string "più facili da catturare, ma fuggono\l"
	.string "con maggiore facilità.\p"
	.string "Quando hai finito le SAFARI BALL,\n"
	.string "termina il gioco.$"

FuchsiaCity_SafariZone_Entrance_Text_SorryYoureARegularHere::
	.string "Appunto! Mi sembrava di averti già\n"
	.string "visto!$"

