FiveIsland_LostCave_Room10_Text_SelphyIntro::
	.string "Ehi, non farmi paura!$"

FiveIsland_LostCave_Room10_Text_SelphyDefeat::
	.string "Ah, avevo paura che\n"
	.string "volessi farmi male!$"

FiveIsland_LostCave_Room10_Text_MayIAskYouToTakeMeHome::
	.string "Sono contenta di averti\n"
	.string "incontrato.\p"
	.string "Sono stanca di camminare,\n"
	.string "sai? Non ce la faccio più.\p"
	.string "Mi porteresti a casa?$"

