CeladonCity_DepartmentStore_4F_Text_GettingPokeDollAsPresent::
	.string "Comprerò una POKé BAMBOLA per la\n"
	.string "mia amica!$"

CeladonCity_DepartmentStore_4F_Text_CanRunAwayWithPokeDoll::
	.string "Mi hanno detto una cosa molto\n"
	.string "utile!\p"
	.string "Puoi fuggire dai POKéMON selvatici\n"
	.string "distraendoli con una POKé BAMBOLA!$"

CeladonCity_DepartmentStore_4F_Text_FloorSign::
	.string "Dillo con un regalo!\p"
	.string "3ºP: REGALI\p"
	.string "Evoluzione speciale!\n"
	.string "PIETRE elemento in vendita qui!$"

