ViridianCity_House_Text_NicknamingIsFun::
	.string "Inventare nuovi soprannomi è\n"
	.string "divertente ma anche difficile.\p"
	.string "I nomi semplici sono i più facili da\n"
	.string "ricordare.$"

ViridianCity_House_Text_MyDaddyLovesMonsToo::
	.string "Anche a mio papà piacciono molto i\n"
	.string "POKéMON!$"

ViridianCity_House_Text_Speary::
	.string "SPEARY: spir spir!$"

ViridianCity_House_Text_SpearowNameSpeary::
	.string "SPEAROW\n"
	.string "Nome: SPEARY$"

