PalletTown_Text_OakDontGoOut::
	.string "OAK: Ehi! Aspetta!\n"
	.string "Non andare!$"

PalletTown_Text_OakGrassUnsafeNeedMon::
	.string "OAK: È pericoloso! Nell'erba alta\n"
	.string "vivono POKéMON selvatici!\p"
	.string "Hai bisogno di POKéMON tuoi che ti\n"
	.string "proteggano!\p"
	.string "Fidati di me!\n"
	.string "Seguimi!$"

PalletTown_Text_RaisingMonsToo::
	.string "Anch'io alleno i POKéMON!\p"
	.string "Così, quando saranno forti, mi\n"
	.string "proteggeranno!$"

PalletTown_Text_CanStoreItemsAndMonsInPC::
	.string "La tecnologia è incredibile!\p"
	.string "Ora col PC puoi depositare e\n"
	.string "prelevare POKéMON e strumenti come\l"
	.string "fossero dei dati!$"

PalletTown_Text_OakPokemonResearchLab::
	.string "LABORATORIO del PROFESSOR OAK$"

PalletTown_Text_PlayersHouse::
	.string "Casa di {PLAYER}$"

PalletTown_Text_RivalsHouse::
	.string "Casa di {RIVAL}$"

PalletTown_Text_TownSign::
	.string "BIANCAVILLA\n"
	.string "Un viaggio dalle mille sfumature ti\l"
	.string "aspetta!$"

PalletTown_Text_OakLetMeSeePokedex::
	.string "OAK: Ciao, {PLAYER}!\n"
	.string "Sei di ritorno?\p"
	.string "Come va con il POKéDEX?\n"
	.string "Lo stai completando?\p"
	.string "Dai, fammi vedere!$"

PalletTown_Text_CaughtXPuttingInHonestEffort::
	.string "Hai dati su {STR_VAR_2} specie…\p"
	.string "Sei ancora agli inizi, ma so che\n"
	.string "ti stai impegnando!\p"
	.string "Torna quando ne avrai catturato\n"
	.string "qualcun altro, va bene?$"

PalletTown_Text_CaughtXImpressiveFollowMe::
	.string "Hai dati su {STR_VAR_2} specie!\n"
	.string "Davvero notevole!\p"
	.string "Ascolta, {PLAYER}, ho un piacere da\n"
	.string "chiederti.\p"
	.string "Seguimi.$"

PalletTown_Text_OakYouEnjoyingTraveling::
	.string "OAK: Ah, {PLAYER}!\n"
	.string "Vedo che ti piace viaggiare.\p"
	.string "Conoscendoti, so che ti spingerai\n"
	.string "in terre ancora più lontane ed\l"
	.string "esotiche.\p"
	.string "Buon per te!$"

