CeladonCity_Hotel_Text_ThisHotelIsForPeople::
	.string "POKéMON?\n"
	.string "No, questo è un hotel per persone.\p"
	.string "Siamo al completo!$"

CeladonCity_Hotel_Text_OnVacationWithBrotherAndBoyfriend::
	.string "Sono in vacanza con mio fratello e\n"
	.string "il mio ragazzo.\p"
	.string "AZZURROPOLI è una bella città!$"

CeladonCity_Hotel_Text_WhyDidSheBringBrother::
	.string "Perché ha portato suo fratello?$"

CeladonCity_Hotel_Text_SisBroughtMeOnVacation::
	.string "Mia sorella mi accompagna in questo\n"
	.string "viaggio!$"

